### ISSUE TITLE
video display window small on MAC retina lcd

### ISSUE THREAD

**Issue by aonicode** [wang-bin/QtAV#1009]
### QtAV, Qt version and platform
![image](https://user-images.githubusercontent.com/17423597/33464082-8bf0e60c-d67b-11e7-88c8-a973d0a0c802.png)

or commit id if not using release version

### Reproduction steps
I use sdk from following url:
https://sourceforge.net/projects/qtav/files/release/1.11.0/QtAV1.11.0-Player.dmg

1. run example simpleplayer on mac
2. just small video window show on my retina lcd
3. it is ok if I connect pc to 1080P lcd using hdmi, display is ok

### Actual behavior
on retina:
![image](https://user-images.githubusercontent.com/17423597/33464254-508462aa-d67c-11e7-8237-e032189c0da5.png)
on hdmi:
![image](https://user-images.githubusercontent.com/17423597/33464302-84ccc17e-d67c-11e7-922b-09524d4f2815.png)

### Log file

set environment var `QTAV_LOG=all` or C++ api `QtAV::setLogLevel(All)` to enable log.

For Player and QMLPlayer example app, choose log level `all` in config page.

**Comment by wang-bin** [comment]
Build the latest code yourself. It was fixed

**Comment by aonicode** [comment]
It is fixed I build the latest code.
