### ISSUE TITLE
使用Qt5.9.1和Mingw5.3.0编译QtAV1.12.0编译失败

### ISSUE THREAD

**Issue by XChy** [wang-bin/QtAV#1014]
编译错误:
在FilterContext.cpp中

> error: no matching function for call to 'QPainter::drawImage(const QPointF&, const QImage&, QRectF, Qt::ImageConversionFlags&)'
>          painter->drawImage(pos, image, QRectF(0, 0, image.width(), image.height()), flags);

> error: no matching function for call to 'QPainter::drawImage(const QRectF&, const QImage&, QRectF, Qt::ImageConversionFlags&)'
>          painter->drawImage(target, image, QRectF(0, 0, image.width(), image.height()), flags);

**Comment by xxschy** [comment]
注:是在Windows下

**Comment by xxschy** [comment]
在Qt5.9.3下没问题了...
