### ISSUE TITLE
Windows build Error: 'rotation' was not declared in this scope

### ISSUE THREAD

**Issue by shbobur** [wang-bin/QtAV#1022]
Qt 5.9.1, Win7.

Building the latest source following wiki [Build QtAV](https://github.com/wang-bin/QtAV/wiki/Build-QtAV).
Getting error:
```
GraphicsItemRenderer.cpp:55: error: 'rotation' was not declared in this scope
         if (rotation())
                      ^
```
I tried to find `rotation()` function declaration in the [class ](https://github.com/wang-bin/QtAV/blob/master/widgets/GraphicsItemRenderer.cpp) and in all its parent classes but could not find it. Any ideas?

**Comment by shbobur** [comment]
[Solved by running **sdk_uninstall.bat**.](https://github.com/wang-bin/QtAV/issues/911)

**Comment by sravssatyanarayanaReddy** [comment]
Dear friend,

I have run sdk_unistall.bat after running that i compile again but problem was not solved.Can u tell the solution.

Regards,
Satyanarayana.T

**Comment by shbobur** [comment]
I don't exactly remember. Sorry (:
