### ISSUE TITLE
mapToFrame() is not very accurate

### ISSUE THREAD

**Issue by shbobur** [wang-bin/QtAV#1026]
### QtAV, Qt version and platform
latest commit id 65483f5300b4f98ef0561a3e240ed82e252ec357, Qt 5.9.1, Windows 7.

### Reproduction steps
On mouse click, I want to crop an area of size `cropAreaSize` (given in pixels) from actual frame. Mouse is clicked in the center of crop area.
```
void PlayerWindow::mousePressEvent(QMouseEvent *event)
{
    QPointF coordWidget((qreal)event.pos.x(), (qreal)event.pos.y());
    QPointF coordFrame = m_player->renderer()->mapToFrame(coordWidget);
    int x = coordFrame.x() - cropAreaSize.width() / 2;
    int y = coordFrame.y() - cropAreaSize.height() / 2;
    QImage img = lastFrame.copy(x, y, cropAreaSize.width(), cropAresSize.height());
    emit getTemp(img);
}
```
Example frame:
![untitled](https://user-images.githubusercontent.com/20049655/34403919-8924d7f2-ebee-11e7-81ca-8945ae835a69.jpg)

### Expected behavior
On paused state, when I click on the point shown with a blue arrow (center of the bowl with heart) I want to get this:
![wertttttttty11](https://user-images.githubusercontent.com/20049655/34403990-e2dbd2dc-ebee-11e7-8f84-bcf7e9ccc2bb.jpeg)

### Actual behavior
![wertttttttty3](https://user-images.githubusercontent.com/20049655/34404009-fc395d12-ebee-11e7-99e6-354f1ae3ec37.jpeg)

Results vary by resizing the player:
![wertttttttty16](https://user-images.githubusercontent.com/20049655/34404058-43a60fb0-ebef-11e7-945e-851d4f9288cc.jpeg)
![wertttttttty17](https://user-images.githubusercontent.com/20049655/34404059-43d3bc94-ebef-11e7-888d-9b6c2e580c57.jpeg)

Any thoughts?

**Comment by wang-bin** [comment]
`event.pos()` is in PlayerWindow's coordinates. What you need is the position in renderer's coordinates. If the renderer's parent is PlayerWindow, you can try

    auto pos_in_renderer = m_player->renderer()->mapFrom(this, event->pos());
    auto pos_in_frame = m_player->renderer()->mapToFrame(pos_in_renderer);

Of cause you can always map to global coordinates first

    auto pos_in_global =  mapToGlobal(event->pos());
    auto pos_in_renderer = m_player->renderer()->mapFromGlobal(pos_in_global);

**Comment by shbobur** [comment]
```
->  auto pos_in_renderer = m_player->renderer()->mapFrom(this, event->pos());
    auto pos_in_frame = m_player->renderer()->mapToFrame(pos_in_renderer);
```

Error message:

`error C2039: 'mapFrom': is not a member of 'QtAV::VideoRenderer'`

**Comment by shbobur** [comment]
Solved!

```
 auto globPos = mapToGlobal(pos);
 auto rendPos = m_vo->widget()->mapFromGlobal(globPos);   //  m_vo is object of QtAV:VideoOutput;
 auto framePos = m_player->renderer()->mapToFrame(rendPos);
```
