### ISSUE TITLE
调用QtAV库编译程序失败

### ISSUE THREAD

**Issue by magicdmer** [wang-bin/QtAV#1027]
之前在windows上调用QtAV 1.2.0 库编写了一个简单的播放器，测试通过。
后来去ubuntu下，git下master （1.2.0）分支，然后用 
qt 5.3.2 静态库 + ffmpeg-3.4.1-linux-gcc-lite.tar.xz + QtCreator 3.0.1
编译通过，得到
/home/QtAV/out/lib_linux_/libQtAV.a                    4.8M
/home/QtAV/out/lib_linux_/libQtAVWidgets.a       247K
接着拷贝播放器代码到ubuntu上，然后在pro文件加入了
LIBS += -lQtAV -lQtAVWidgets 
结果编译的时候出现了各种未定义符号
/usr/local/Qt-5.3.2-static/lib/libQtAV.a(AVError.o): In function `QtAV::AVError::ffmpegErrorString() const':
AVError.cpp:(.text+0x243): undefined reference to `av_strerror'
/usr/local/Qt-5.3.2-static/lib/libQtAV.a(AVPlayer.o): In function `QtAV::AVPlayer::seekChapter(int)':
AVPlayer.cpp:(.text+0x29b7): undefined reference to `av_compare_ts'
AVPlayer.cpp:(.text+0x2bcc): undefined reference to `av_rescale_q'
/usr/local/Qt-5.3.2-static/lib/libQtAV.a(AVPlayerPrivate.o): In function `QtAV::correct_audio_channels(AVCodecContext*) [clone .isra.3]':
AVPlayerPrivate.cpp:(.text+0x36): undefined reference to `av_get_default_channel_layout'
AVPlayerPrivate.cpp:(.text+0x5e): undefined reference to `av_get_channel_layout_nb_channels'
/usr/local/Qt-5.3.2-static/lib/libQtAV.a(AVPlayerPrivate.o): In function `QtAV::AVPlayer::Private::applySubtitleStream(int, QtAV::AVPlayer*)':
AVPlayerPrivate.cpp:(.text+0x57c): undefined reference to `avcodec_descriptor_get'
/usr/local/Qt-5.3.2-static/lib/libQtAV.a(AVPlayerPrivate.o): In function `QtAV::AVPlayer::Private::initCommonStatistics(int, QtAV::Statistics::Common*, AVCodecContext*)':
AVPlayerPrivate.cpp:(.text+0x8f6): undefined reference to `avcodec_get_name'
AVPlayerPrivate.cpp:(.text+0xbfc): undefined reference to `av_dict_get'
/usr/local/Qt-5.3.2-static/lib/libQtAV.a(AVPlayerPrivate.o): In function `QtAV::AVPlayer::Private::initAudioStatistics(int)':
这些看着都是ffmpeg的符号，难道编译的时候还要再加上-lavcodec -lavformat -lswscale -lavutil 这些？我看到QtAV编译的时候好像是静态编译

**Comment by wang-bin** [comment]
链接静态库需要同时链接静态库的依赖
