### ISSUE TITLE
AVPlayer::stepForward does not update position and causes playback speed issues [bounty]

### ISSUE THREAD

**Issue by ThatOdieGuy** [wang-bin/QtAV#1029]
### QtAV, Qt version and platform
Windows 10
Qt 5.9.3
QtAV 507e6d1

### Reproduction steps
1. Open a video with AVPlayer
2. Call AVPlayer::stepForward
3. Call AVPlayer::play

### Expected behavior
AVPlayer::position should be updated to the new position.
AVPlayer::play should play back at normal speed.

### Actual behavior
Call AVPlayer::stepForward steps forward, but then the position value shows the original position before calling stepForward. Also, after calling stepForward, AVPlayer::play causes the video to play extremely slow or extremely fast.

If I hit my stepForward button a bunch of times in a row, I can see the position value update to something that looks right. But then it immediately jumps back to the original value.

### Log file
Here is after pressing the stepForward button 4 times. I'm logging the position which does not change.
```
Position changed:  50401
"wake up paused thread"
"AVCodecContext.wmav2 options:"
"(repeat 1)wake up paused thread\nskip_frame=>0"
"set QtAV::AudioDecoderFFmpeg() meta properties:"
"AVCodecContext.wmv3 options:"
"set QtAV::VideoDecoderFFmpeg() meta properties:"
Position changed:  50401
Position changed:  50401
Position changed:  50401
"(repeat 1)skip_frame=>0\nwake up paused thread"
"AVCodecContext.wmv3 options:"
"(repeat 1)wake up paused thread\nskip_frame=>0"
"set QtAV::VideoDecoderFFmpeg() meta properties:"
Position changed:  50401
Position changed:  50401
Position changed:  50401
"wake up paused thread"
"AVCodecContext.wmv3 options:"
"(repeat 1)wake up paused thread\nskip_frame=>0"
"set QtAV::VideoDecoderFFmpeg() meta properties:"
Position changed:  50401
Position changed:  50401
Position changed:  50401
"wake up paused thread"
"AVCodecContext.wmv3 options:"
"(repeat 1)wake up paused thread\nskip_frame=>0"
"set QtAV::VideoDecoderFFmpeg() meta properties:"
Position changed:  50401
```

Here's a full log. I loaded a video, then called stepForward three times. The video frames skipped forward in the player. But the position retains the value of 7908. Then I hit play and the video fast forwarded through a few seconds.
[QtAVStepForward.log](https://github.com/wang-bin/QtAV/files/1607249/QtAVStepForward.log)

After stepping forward and then hitting play, and the video is playing either too fast or too slow, I often see these in the logs:
```
Warning: "video too fast!!! sleep 0.15 s, nb fast: 30, v_a: 1.1574"
```
or
```
Debug: "frame slow count: 4. v-a: -0.881"
Debug: "delay -0.880986s @122.862s pts:122.990" 
```

### Sample files
Here's my test using the simple player. I've added a display for the position and Back/Forward buttons for stepping, along with a skip button which uses seek.
[simpleplayer.zip](https://github.com/wang-bin/QtAV/files/1607256/simpleplayer.zip)

**Comment by ThatOdieGuy** [comment]
I'm going to attempt to debug this myself. But I don't know if I will succeed! Any pointers would be appreciated.

**Comment by ThatOdieGuy** [comment]
@wang-bin Do you have any advice for how I can debug this? I've been messing around with `AVDemuxThread::stepForward` & `AVDemuxThread::frameDeliveredOnStepForward`. And I think I can get around the issue of the position not being updated (with a hack). But I don't know how to fix the video speed playback issue.

**Comment by tve** [comment]
I'm seeing the same problem.

**Comment by atvKumar** [comment]
Me too on mac

**Comment by ThatOdieGuy** [comment]
@wang-bin Your help would be appreciated! I've also posted a [bounty](https://www.bountysource.com/issues/53431735-avplayer-stepforward-does-not-update-position-and-causes-playback-speed-issues) for this. 👍

**Comment by atvKumar** [comment]
> 
> 
> @wang-bin Your help would be appreciated! I've also posted a [bounty](https://www.bountysource.com/issues/53431735-avplayer-stepforward-does-not-update-position-and-causes-playback-speed-issues) for this. 👍

Thanks for the bounty, but i think i have a workaround, Try using seek() with repaint() the mainwindow. Should be a nice workaround, but not possible for frame accurate stuff. But close enough.

**Comment by pplxlee** [comment]
@ThatOdieGuy You can try to force the AVPlayer use ExternalClock as below. This can avoid playback speed issues.
    connect(mPlayerCore, &AVPlayer::started,
            [this](){
        mPlayerCore->masterClock()->setClockAuto(false);
        mPlayerCore->masterClock()->setClockType(QtAV::AVClock::ExternalClock);
    });

**Comment by ThatOdieGuy** [comment]
Thanks @pplxlee - I ended up using this trick and I think it's working out pretty well.

**Comment by zhounan354** [comment]
I met the similar issues that after I hit stepForward several times(about 5~10),and then call pause(false),the frame play very slow(1 frame per second),and I found the delay(AudioClock) increase slowly.Setting ExternalClock do not work(it turns out the audio plays strange)

**Comment by ThatOdieGuy** [comment]
I've attempted to address this in the PR I just submitted, #1248. There were a number of issues related to stepping forward & backward. It seems to have worked well for my project.

**Comment by ThatOdieGuy** [comment]
My PR got accepted. Thanks @wang-bin ! If you're having this issue, try it out. This works in conjunction with using the external clock.
```
connect(m_player, &AVPlayer::started, [this](){
  m_player->masterClock()->setClockAuto(false); 
  m_player->masterClock()->setClockType(QtAV::AVClock::ExternalClock);
});
```

I also added a `displayPosition()` to `AVPlayer` because skipping/stepping would often change the `position()` too often, or it wouldn't be correct.  I didn't want to go about changing the logic behind `position()`, so `displayPosition()` attempts to be a more stable position for display.
