### ISSUE TITLE
Cannot open include file: 'QtAV': No such file or directory

### ISSUE THREAD

**Issue by NikkyAI** [wang-bin/QtAV#1034]
### QtAV, Qt version and platform

QtAV-Qt5.9-VS2017x64-release-143da6a
qt-everywhere-opensource-src-5.9.0

### Reproduction steps

compile qt5 and install QtAV with sdk_deploy

### Expected behavior

compiling example code snippets without problems

```cpp
#include <QtAV>
#include <QtAVWidgets>

int main(int argc, char *argv[])
{
    GLWidgetRenderer2 renderer;
    renderer.show();
    AVPlayer player;
    player.setRenderer(&renderer);
    player.play("test.avi");
}
```

### Actual behavior

does not compile successfully
Cannot open include file: 'QtAV': No such file or directory

**Comment by ThatOdieGuy** [comment]
Did you add `QT += avwidgets` to your .pro file and run qmake? I don't know the equivalent for Visual Studio. But you'll need to edit your project somehow.

**Comment by NikkyAI** [comment]
i did add those lines, otherwise it would complain about unknown modules or the like

**Comment by ThatOdieGuy** [comment]
Nope, if you don't add that line and then run qmake you will get `Cannot open include file: 'QtAV': No such file or directory`. Did you run qmake?

Also, check to see if the include files got installed to the correct version of Qt. Mine got installed to `C:\Qt\5.9.3\msvc2015\include\QtAV` & `C:\Qt\5.9.3\msvc2015\include\QtAVWidgets`

**Comment by NikkyAI** [comment]
i installed it into a self compiled version of qt (with openssl, boost and librorrent linked in)

in the meantime i scrapped the old buildprocess though.. will try qtAV again once i am at the point of having clean buildscripts and understanding what they do

at the moment there is too mayn things that could break it, so i will close this for now

i will reopen the issue or create a new issue when i can show our buildscripts as wll to have a reproducible case
