### ISSUE TITLE
can not package my QtAV app

### ISSUE THREAD

**Issue by lbj9527** [wang-bin/QtAV#1042]
I use windeployqt.exe to package my QtAV app, it is successful. But can not play video.(in QtCreator it can play video).please tell how to resolve?
(environment: VS2015 x64 Qt5.7)

**Comment by wang-bin** [comment]
windeployqt is shit(in fact all qt official deployment tools are shit). you have to manually copy dlls

**Comment by lbj9527** [comment]
thanks your reply!
I have another question that how to determine if an unopened video is H264 encoded.
