### ISSUE TITLE
qtav null dereferance and opengl issue

### ISSUE THREAD

**Issue by eagleFromHeaven** [wang-bin/QtAV#1049]
### QtAV, Qt version and platform
latest QtAV commit f3ad0a57ad2d0b4c1caef78a90b37fadcd1a234c

### Reproduction steps
1. static compile qt
2. static compile qtav to msvc 2015 x86
3. try to run Player.exe from example on fresh windows os install (i checked on windows 10 out of the box)

### Expected behavior
we expect the program to open and allow us to play movies

### Actual behavior
all the crashes are widget related , we crash before we see the video black screen opened.

1. we got a crash because null dereferance at `OpenGLHelper.cpp` line 139 (`vs` can be null)
+ after fix of this issue you will still have a problem
2. we got a crash - i don't know why exactly but it's related to widget  or opengl.

### Log file

`Debug: vo: gl

Debug: QtAV 1.12.0(Feb 23 2018, 14:07:30)

Multimedia framework base on Qt and FFmpeg.

Distributed under the terms of LGPLv2.1 or later.

Shanghai University->S3 Graphics->Deepin->PPTV, Shanghai, China Copyright (C) 2012-2017 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com

Donate: http://qtav.org/donate.html

Source: https://github.com/wang-bin/QtAV

Home page: http://qtav.org

Debug: "Build with Qt-5.10.1"

Debug: "FFmpeg/Libav configuration: --extra-version=QtAV --disable-doc --disable-debug --enable-small --enable-shared --disable-static --enable-runtime-cpudetect --enable-hwaccels --enable-avresample --disable-postproc --disable-iconv --enable-pic --extra-ldflags=' -static-libgcc -Wl,-Bstatic'"

Debug: "Build with avutil-55.58.100"

Warning: "Warning: avutil runtime version 55.17.103 mismatch!"

Debug: "Build with avcodec-57.89.100"

Warning: "Warning: avcodec runtime version 57.24.102 mismatch!"

Debug: "Build with avformat-57.71.100"

Warning: "Warning: avformat runtime version 57.25.100 mismatch!"

Debug: "Build with avfilter-6.82.100"

Warning: "Warning: avfilter runtime version 6.31.100 mismatch!"

Debug: "Build with avdevice-57.6.100"

Warning: "Warning: avdevice runtime version 57.0.101 mismatch!"

Debug: "Build with avresample-3.5.0"

Warning: "Warning: avresample runtime version 3.0.0 mismatch!"

Debug: "Build with swresample-2.7.100"

Warning: "Warning: swresample runtime version 2.0.101 mismatch!"

Debug: "Build with swscale-4.6.100"

Warning: "Warning: swscale runtime version 4.0.100 mismatch!"

Debug: engine: "LibASS"

Debug: engine: "FFmpeg"

Debug: engine: "FFmpeg"

Warning: "can not load cuda!"

Debug: Registered audio backends:  ("XAudio2", "OpenAL", "DirectSound", "null")

Debug: "XAudio2_9"

Debug: "Build with XAudio2 from Win8 or later SDK"

Debug: "Try symbol 'XAudio2Create' from WinSDK dll"

Debug: "xaudio2: 0x64d0560"

Debug: "OpenGL version: 1.1  hasGLSL: 0"

Debug: "GL_VERSION: 1.1.0"

Debug: "GL_VENDOR: Microsoft Corporation"

Debug: "GL_RENDERER: GDI Generic"

Debug: "GL_SHADING_LANGUAGE_VERSION: "

Debug: "Is OpenGLES: 0"

Debug: "Is EGL: 0"`

### Sample files (optional)
an example can be download from this link:
[https://ufile.io/ra2z3](url)

**Comment by eagleFromHeaven** [comment]
added log file

**Comment by wang-bin** [comment]
OpenGL 2.0 is the mininal supported version. Your driver is 1.1, ms software implementation. You have to install gpu driver
