### ISSUE TITLE
Playing multiple videos on top of each other

### ISSUE THREAD

**Issue by Janjanus** [wang-bin/QtAV#1050]
Is it possible to play multiple video's (with alpha channel) on top of each other? Are there examples of this?

**Comment by wang-bin** [comment]
Mix multiple images together?

**Comment by Janjanus** [comment]
Yes, so you have different layers of video and you can see through the top video. I tried creating two GLWidget2 renderers and placed them on top of each other but I cannot make the background of a renderer transparant so you only see the top renderer.

**Comment by Janjanus** [comment]
Thanks, I will try that!
