### ISSUE TITLE
Source code of QtAV1.11.0-VS2013x86

### ISSUE THREAD

**Issue by eagleFromHeaven** [wang-bin/QtAV#1052]
I found that despite problems with OpenGL after I installed `QtAV1.11.0-VS2013x86` the problems were resolved.

Can you please publish the code snippet of `QtAV1.11.0-VS2013x86`? Or elaborate all the installation processes so I can understand what was wrong with the portable player version I tried to run?

Thanks!

**Comment by wang-bin** [comment]
git tags. Any log for the latest player?

**Comment by eagleFromHeaven** [comment]
There is no log, everything just worked.
Can you specify more about `git tags` regard to QtAV1.11.0-VS2013x86 full source?
(Where I can get it / download it / see it?)

**Comment by wang-bin** [comment]
Why didn't you follow the issue template? If you read that, you know how to enable log.
BTW, you have to study how to use git
