### ISSUE TITLE
When playing many video files one by one, at some point app crashes.

### ISSUE THREAD

**Issue by quarcko** [wang-bin/QtAV#1064]
### QtAV, Qt version and platform
QtAV 1.12.0
Qt 5.5.1
Developing on Windows 10, compiling for Android-19

### Reproduction steps
Create simple Video element in QML,
and do this in a loop:
videoFrame.onStopped: {
            m_fileFinder.refreshFileList()
            videoFrame.source = m_fileFinder.getNext()
            videoFrame.play()
        }

### Expected behavior
Play files one-by-one indefinetely

### Actual behavior
App crashes after some ~80 videos played.

### Log file

I/OMXClient( 6251): Using client-side OMX mux.
I/OMXClient( 6251): Using client-side OMX mux.
E/dalvikvm( 6251): JNI ERROR (app bug): local reference table overflow (max=512)
W/dalvikvm( 6251): JNI local reference table (0x656e3cf8) dump:
W/dalvikvm( 6251):   Last 10 entries (of 512):
W/dalvikvm( 6251):       511: 0x422022c8 java.lang.String "video/avc"
W/dalvikvm( 6251):       510: 0x42202288 java.lang.String "mime"
W/dalvikvm( 6251):       509: 0x421dee00 java.lang.Integer
W/dalvikvm( 6251):       508: 0x422023b8 java.lang.String "height"
W/dalvikvm( 6251):       507: 0x42203b60 java.nio.DirectByteBuffer
W/dalvikvm( 6251):       506: 0x42203b20 java.lang.String "csd-1"
W/dalvikvm( 6251):       505: 0x41efd8c0 java.lang.Class<java.nio.ByteBuffer>
W/dalvikvm( 6251):       504: 0x41efe8d0 java.lang.Class<java.lang.Float>
W/dalvikvm( 6251):       503: 0x41effae8 java.lang.Class<java.lang.Long>
W/dalvikvm( 6251):       502: 0x41eff998 java.lang.Class<java.lang.Integer>
W/dalvikvm( 6251):   Summary:
W/dalvikvm( 6251):       254 of java.lang.Class (8 unique instances)
W/dalvikvm( 6251):         1 of java.lang.Object[] (5 elements)
W/dalvikvm( 6251):        87 of java.lang.String (87 unique instances)
W/dalvikvm( 6251):         1 of java.nio.DirectByteBuffer
W/dalvikvm( 6251):         1 of java.lang.Integer
W/dalvikvm( 6251):         1 of java.lang.String[] (5 elements)
W/dalvikvm( 6251):        84 of android.media.MediaCodec (83 unique instances)
W/dalvikvm( 6251):        83 of android.media.MediaFormat (83 unique instances)
E/dalvikvm( 6251): Failed adding to JNI local ref table (has 512 entries)
I/dalvikvm( 6251): "QtThread" prio=9 tid=16 RUNNABLE
I/dalvikvm( 6251):   | group="main" sCount=0 dsCount=0 obj=0x421e88e0 self=0x5dba6238
I/dalvikvm( 6251):   | sysTid=6286 nice=-6 sched=0/0 cgrp=apps handle=1572323848
I/dalvikvm( 6251):   | state=R schedstat=( 211293555769 310720641027 951901 ) utm=11849 stm=9280 core=1
I/dalvikvm( 6251):   at android.media.MediaCodec.native_configure(Native Method)
I/dalvikvm( 6251):   at android.media.MediaCodec.configure(MediaCodec.java:262)
I/dalvikvm( 6251):   at dalvik.system.NativeStart.run(Native Method)
I/dalvikvm( 6251):
E/dalvikvm( 6251): VM aborting
F/libc    ( 6251): Fatal signal 6 (SIGABRT) at 0x0000186b (code=-6), thread 6286 (lkotesteris.ADB)
I/DEBUG   (  110): pid: 6251, tid: 6286, name: lkotesteris.ADB  >>> com.alkotesteris.ADB <<<
I/ActivityManager(  443): Process com.alkotesteris.ADB (pid 6251) has died.

**Comment by wang-bin** [comment]
I need backtrace starting with `*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***` in the log

**Comment by quarcko** [comment]
Ok, i found in issues of QtAV, taht this issue was solved some time ago.
This is bug in FFMPEG older version (was using 3.1)
updates FFMPEG to 3.4.2 -> and this bug is gone,

but new gubs are present, probably will open new issue-report. Thanks!
