### ISSUE TITLE
hello a question about http header

### ISSUE THREAD

**Issue by zeecrowddev** [wang-bin/QtAV#1067]
windows, Qt 5.9
just a little quiestion
ther is a way to put additional http header to the video url source ?

Thanks

**Comment by wang-bin** [comment]
https://github.com/wang-bin/QtAV/wiki/FFmpeg-dict-opt-in-QtAV

**Comment by zeecrowddev** [comment]
Thanks a lot, i ll test today 😀

Envoyé de mon iPad

**Comment by zeecrowddev** [comment]
After read the avformat ffmpeg documentation i dont see the tag for "authorization" header ...

I saw is it possible to add on ffmpeg.exe this parameter : -headers 'User-Agent: "FMLE/3.0 (compatible; FMSc/1.0)"'

Then i think it's possible to do this : - headers 'authorization : "<<< my key >>"'

then i have to do that in the code ? : 

`QVariantHash avfmt_opt;
avfmt_opt["probesize"] = 4096;
avfmt_opt["authorization"] = "my key";
QVariantHash opt;
opt["headers"] = avfmt_opt;
player->setOptionsForFormat(opt);`

thx for your reply
