### ISSUE TITLE
QtAv 播放摄像头RTSP视频流延时较大

### ISSUE THREAD

**Issue by hhlcbl** [wang-bin/QtAV#1079]
### QtAV, Qt version and platform
Qt MSVC 5.8.0 
or commit id if not using release version

### Log file

set environment var `QTAV_LOG=all` or C++ api `QtAV::setLogLevel(All)` to enable log.

For Player and QMLPlayer example app, choose log level `all` in config page.

**Comment by HelloTodayWolrd** [comment]
同问
