### ISSUE TITLE
ffmpeg直播DirectShow设备问题？( 100$ awarded )

### ISSUE THREAD

**Issue by manymany2009** [wang-bin/QtAV#1088]
Play Raw Video Streams，first to get a raw yuv stream, then play the yuv stream with ffplay.
https://github.com/wang-bin/QtAV/wiki/Play-Raw-Video-Streams
but, if only want to play camera not get stream.
ffplay可以直接播放摄像头的数据，命令如下：
ffplay -f rawvideo -pixel_format yuv420p -video_size 1280x720 -f dshow -i video="Logitech HD Webcam C270" 

it is ok.
then i use qtav c++ setting, it is failed. why ? If not, how ？

QVariantHash fmt_opt;
fmt_opt["format_whitelist"] = "rawvideo";
fmt_opt["video_size"] = "1280x720";
fmt_opt["pixel_format"] = "yuv420p";
fmt_opt["framerate"] = 25;
player->setOptionsForFormat(fmt_opt);
player->setFile("avdevice:dshow:video=Logitech HD Webcam C270");
player->play();

### Log file ###

Loading  QVariant(QString, "avdevice:dshow:video=Logitech HD Webcam C270")  ...
"all closed and reseted"
"dict: format_whitelist=>rawvideo"
"dict: pixel_format=>yuv420p"
"dict: framerate=>25"
"dict: video_size=>1280x720"
force format:  "rawvideo"
"avformat_open_input: d->format_ctx:'0x1bdcf6c0ca0', url:'video=Logitech HD Webcam C270'..."
"avformat_open_input: url:'video=Logitech HD Webcam C270' ret:-2"
Can't open media:  "failed to open media"
"Load failed!"

**Comment by wang-bin** [comment]
setFFmpegLogLevel("verbose") 或"debug"、"trace"看看更详细的日志

**Comment by manymany2009** [comment]
dear wang-bin
setFFmpegLogLevel("verbose") 或"debug"、"trace" 后，没有看到更详细的日志。是我调用函数的地方不对，还是什么？ 我在 qml/plugin.cpp 的 QtAVQmlPlugin 里面调用setFFmpegLogLevel("verbose")等;

我自己追踪看到：AVDemuxer::load() 里面的 d->input = null

**Comment by wang-bin** [comment]
main.cpp
