### ISSUE TITLE
android capture is failed.  ( 100$ awarded )

### ISSUE THREAD

**Issue by manymany2009** [wang-bin/QtAV#1090]
### QtAV, Qt version and platform

QtAV version - latest, Qt5.10.1, Android armv7 
使用的ffmpeg depends 为 ffmpeg-git-android-gcc-lite.tar.xz

use qtav videoCapture.capture()  in qml, for windows videoCapture.capture() is ok. 
but on android is failed. why?  and how ?

    function live_capture() {
        console.info("videoCapture CaptureDir ", live_player.videoCapture.captureDir)
        console.info("videoCapture originalFormat ", live_player.videoCapture.originalFormat)
        console.info("videoCapture saveFormat ", live_player.videoCapture.saveFormat)
        live_player.videoCapture.capture()
    }

### Log file

W libxpic_client.so: E:\ms_client\qtav\qtav-1.12.0\QtAV-master\src\VideoThread.cpp:517 (virtual void QtAV::VideoThread::run()): "invalid video frame from decoder. undecoded data size: 0"
I libxpic_client.so: qrc:/live/LiveController.qml:277 (live_capture): qml: videoCapture CaptureDir  /storage/emulated/0/Pictures
I libxpic_client.so: qrc:/live/LiveController.qml:278 (live_capture): qml: videoCapture originalFormat  false
I libxpic_client.so: qrc:/live/LiveController.qml:279 (live_capture): qml: videoCapture saveFormat  PNG
W libxpic_client.so: E:\ms_client\qtav\qtav-1.12.0\QtAV-master\src\QtAV_Global.cpp:267 (void QtAV::qtav_ffmpeg_log_callback(void*, int, const char*, va_list)): [FFmpeg:swscaler] deprecated pixel format used, make sure you did set range correctly
W libxpic_client.so: E:\ms_client\qtav\qtav-1.12.0\QtAV-master\src\QtAV_Global.cpp:267 (void QtAV::qtav_ffmpeg_log_callback(void*, int, const char*, va_list)): [FFmpeg:swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
W libxpic_client.so: E:\ms_client\qtav\qtav-1.12.0\QtAV-master\src\VideoFrame.cpp:396 (QtAV::VideoFrame QtAV::VideoFrame::to(const QtAV::VideoFormat&, const QSize&, const QRectF&) const): VideoFrame::to error:  QtAV::VideoFormat(pixelFormat: 15 "yuvj420p" alpha: false, channels: 3, planes: 3, bpc: 8, bpp: 12/12 -8-8-8) => QtAV::VideoFormat(pixelFormat: 1 "bgra" alpha: true, channels: 4, planes: 1, bpc: 8, bpp: 32/32 -32)
W libxpic_client.so: E:\ms_client\qtav\qtav-1.12.0\QtAV-master\src\VideoCapture.cpp:58 (virtual void QtAV::CaptureTask::run()): "Failed to convert to QImage"

**Comment by nejatafshar** [comment]
@wang-bin @manymany2009 I have the same issue using the latest QtAV on Android. Any idea how to fix this?
