### ISSUE TITLE
error: avutil is required, but compiler can not find it

### ISSUE THREAD

**Issue by liuxuan5220** [wang-bin/QtAV#1114]
hello, i get the error;avutil is required, but compiler can not find it.how to deal it??

this is the config.log

bin/arm-linux-androideabi-g++ --sysroot=/usr/local/android/android-ndk-r17/platforms/android-16/arch-arm/ -Wl,--enable-new-dtags -Wl,--no-undefined -Wl,-z,noexecstack -shared -Wl,-soname,libavutil.so -o libavutil.so main.o  -L/usr/local/android/android-ndk-r17/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -L/usr/local/android/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x -lavutil -L/home/xuan/Qt5.11.1/5.11.1/android_armv7/lib -lgnustl_shared -lgcc -llog -lz -lm -ldl -lc 
> /usr/local/android/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lavutil
> collect2: error: ld returned 1 exit status
> Makefile:68: recipe for target 'libavutil.so' failed
> make: *** [libavutil.so] Error 1
test avutil FAILED
executing config test avutil
+ cd /home/xuan/build-QtAV-Android_for_armeabi_v7a_GCC_4_9_Qt_5_11_1_for_Android_armv7-Release/config.tests/avutil && MAKEFLAGS= make distclean
> rm -f main.o
> rm -f *~ core *.core
> rm -f libavutil.so 
> rm -f libavutil.a
> rm -f Makefile
+ cd /home/xuan/build-QtAV-Android_for_armeabi_v7a_GCC_4_9_Qt_5_11_1_for_Android_armv7-Release/config.tests/avutil && /home/xuan/Qt5.11.1/5.11.1/android_armv7/bin/qmake  -spec /home/xuan/Qt5.11.1/5.11.1/android_armv7/mkspecs/android-g++ "CONFIG -= qt debug_and_release app_bundle lib_bundle" /home/xuan/QtAV/config.tests/avutil
+ cd /home/xuan/build-QtAV-Android_for_armeabi_v7a_GCC_4_9_Qt_5_11_1_for_Android_armv7-Release/config.tests/avutil && MAKEFLAGS= make
> /usr/local/android/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -c -D__ANDROID_API__=16 --sysroot=/usr/local/android/android-ndk-r17/sysroot -isystem /usr/local/android/android-ndk-r17/sysroot/usr/include/arm-linux-androideabi -isystem /usr/local/android/android-ndk-r17/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /usr/local/android/android-ndk-r17/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove -mthumb -Os -std=gnu++11 -Wall -W -fPIC -D__STDC_CONSTANT_MACROS -I/home/xuan/QtAV/config.tests/avutil -I. -I/home/xuan/Qt5.11.1/5.11.1/android_armv7/include -I/home/xuan/QtAV/contrib/dxsdk -I/home/xuan/Qt5.11.1/5.11.1/android_armv7/mkspecs/android-g++ -o main.o /home/xuan/QtAV/config.tests/avutil/main.cpp
> rm -f libavutil.so
> /usr/local/android/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ --sysroot=/usr/local/android/android-ndk-r17/platforms/android-16/arch-arm/ -Wl,--enable-new-dtags -Wl,--no-undefined -Wl,-z,noexecstack -shared -Wl,-soname,libavutil.so -o libavutil.so main.o  -L/usr/local/android/android-ndk-r17/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -L/usr/local/android/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x -lavutil -L/home/xuan/Qt5.11.1/5.11.1/android_armv7/lib -lgnustl_shared -lgcc -llog -lz -lm -ldl -lc 
> /usr/local/android/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lavutil
> collect2: error: ld returned 1 exit status
> Makefile:68: recipe for target 'libavutil.so' failed
> make: *** [libavutil.so] Error 1
test avutil FAILED
executing config test avutil
+ cd /home/xuan/build-QtAV-Android_for_armeabi_v7a_GCC_4_9_Qt_5_11_1_for_Android_armv7-Release/config.tests/avutil && MAKEFLAGS= make distclean
> rm -f main.o
> rm -f *~ core *.core
> rm -f libavutil.so 
> rm -f libavutil.a
> rm -f Makefile
+ cd /home/xuan/build-QtAV-Android_for_armeabi_v7a_GCC_4_9_Qt_5_11_1_for_Android_armv7-Release/config.tests/avutil && /home/xuan/Qt5.11.1/5.11.1/android_armv7/bin/qmake  -spec /home/xuan/Qt5.11.1/5.11.1/android_armv7/mkspecs/android-g++ "CONFIG -= qt debug_and_release app_bundle lib_bundle" /home/xuan/QtAV/config.tests/avutil
+ cd /home/xuan/build-QtAV-Android_for_armeabi_v7a_GCC_4_9_Qt_5_11_1_for_Android_armv7-Release/config.tests/avutil && MAKEFLAGS= make
> /usr/local/android/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -c -D__ANDROID_API__=16 --sysroot=/usr/local/android/android-ndk-r17/sysroot -isystem /usr/local/android/android-ndk-r17/sysroot/usr/include/arm-linux-androideabi -isystem /usr/local/android/android-ndk-r17/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /usr/local/android/android-ndk-r17/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove -mthumb -Os -std=gnu++11 -Wall -W -fPIC -D__STDC_CONSTANT_MACROS -I/home/xuan/QtAV/config.tests/avutil -I. -I/home/xuan/Qt5.11.1/5.11.1/android_armv7/include -I/home/xuan/QtAV/contrib/dxsdk -I/home/xuan/Qt5.11.1/5.11.1/android_armv7/mkspecs/android-g++ -o main.o /home/xuan/QtAV/config.tests/avutil/main.cpp
> rm -f libavutil.so
> /usr/local/android/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ --sysroot=/usr/local/android/android-ndk-r17/platforms/android-16/arch-arm/ -Wl,--enable-new-dtags -Wl,--no-undefined -Wl,-z,noexecstack -shared -Wl,-soname,libavutil.so -o libavutil.so main.o  -L/usr/local/android/android-ndk-r17/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -L/usr/local/android/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x -lavutil -L/home/xuan/Qt5.11.1/5.11.1/android_armv7/lib -lgnustl_shared -lgcc -llog -lz -lm -ldl -lc 
> /usr/local/android/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lavutil
> collect2: error: ld returned 1 exit status
> Makefile:68: recipe for target 'libavutil.so' failed
> make: *** [libavutil.so] Error 1
test avutil FAILED

**Comment by wang-bin** [comment]
https://github.com/wang-bin/QtAV/wiki/Build-QtAV
