### ISSUE TITLE
概率性的视频前几秒黑屏

### ISSUE THREAD

**Issue by zhouxl6** [wang-bin/QtAV#1129]
视频：
http://v.yinyuetai.com/video/3261432
下载这个地址的音乐MP4文件

现象：
将视频拖放到Player.exe中，会出现概率性的视频前几秒黑屏现象

分析
利用videoeye软件对视频进行了分析，发现视频的第一帧是 I 帧，然后大概在视频的10S左右的位置出现第二个 I 帧，到视频的第二个 I 帧以后就可以正常播放的了。

开发环境：
VS2015 + QT5.6.3

**Comment by zhouxl6** [comment]
我这边对代码方面进行了调试分析，发现 AVDemuxThread --> run() 方法中不断的向 视频queue里写数据，然后突然，视频queue中的数据被 clear了，结果就导致前面几帧丢失，特别是第一帧 I 帧，这样直到第二个 I 帧出现前，视频都会解码不正常，现象就是显示的是黑屏。

以下是调试输出信息：
Debug: 1
Debug: 2
Debug: 3
以 以上三个开始的是在queue clear 方法中添加的调试信息，输出的是调用 clear() 的方法，文件 ，以至具体行

put a new video frame 是向 queue中添加一视频pkg
take decode video frame 是从queue中取出一视频pkg


Debug: 1 AVDemuxThread.cpp QtAV::AVDemuxThread::run 541
Debug: 2 AVDemuxThread.cpp QtAV::AVDemuxThread::run 541
Debug: 3 AVDemuxThread.cpp QtAV::AVDemuxThread::run 541
Debug: 1 AVDemuxThread.cpp QtAV::AVDemuxThread::run 545
Debug: 2 AVDemuxThread.cpp QtAV::AVDemuxThread::run 545
Debug: 3 AVDemuxThread.cpp QtAV::AVDemuxThread::run 545
Debug: 1 AVDemuxThread.cpp QtAV::AVDemuxThread::run 550
Debug: 2 AVDemuxThread.cpp QtAV::AVDemuxThread::run 550
Debug: 3 AVDemuxThread.cpp QtAV::AVDemuxThread::run 550
Debug: 1 AVThread.cpp QtAV::AVThread::resetState 316
Debug: put a new video frame : PTS  0  first frame PTS :  0  video queue size :  1
Debug: 2 AVThread.cpp QtAV::AVThread::resetState 316
Debug: 3 AVThread.cpp QtAV::AVThread::resetState 316
Debug: put a new video frame : PTS  0.173913  first frame PTS :  0  video queue size :  2
Debug: 1 AVThread.cpp QtAV::AVThread::resetState 320
Debug: 2 AVThread.cpp QtAV::AVThread::resetState 320
Debug: put a new video frame : PTS  0.0869565  first frame PTS :  0  video queue size :  3
Debug: 3 AVThread.cpp QtAV::AVThread::resetState 320
Debug: put a new video frame : PTS  0.0434783  first frame PTS :  0.0434783  video queue size :  1
Debug: take decode video frame :  0.0434783
Debug: put a new video frame : PTS  0.130435  first frame PTS :  0.130435  video queue size :  1
Debug: put a new video frame : PTS  0.26087  first frame PTS :  0.130435  video queue size :  2
Debug: put a new video frame : PTS  0.217391  first frame PTS :  0.130435  video queue size :  3
Debug: put a new video frame : PTS  0.304348  first frame PTS :  0.130435  video queue size :  4
Debug: put a new video frame : PTS  0.391304  first frame PTS :  0.130435  video queue size :  5
Debug: put a new video frame : PTS  0.347826  first frame PTS :  0.130435  video queue size :  6
Debug: put a new video frame : PTS  0.478261  first frame PTS :  0.130435  video queue size :  7
Debug: put a new video frame : PTS  0.434783  first frame PTS :  0.130435  video queue size :  8

**Comment by zhouxl6** [comment]
以下是个人解决的方法，如有不合适或者不对的地方，请见谅：
AudioThread 中重写 start方法，实现如下：
void AudioThread::start(Priority priority) {
    resetState();
    __super::start(priority);
}
同时注释掉AudioThread ::run()中对 resetState(); 的调用

VideoThread 中重写 start方法，实现如下：
void VideoThread::start(Priority priority) {
    resetState();
    __super::start(priority);
}
同时注释掉VideoThread::run()中对 resetState(); 的调用

思路是，在 AVDemuxThread::run() --> while() 运行前，完成对 audio 以及 video 的 resetState() 操作，以确保缓存 audio 和 video pkg 到 queue中后，不会被概率性的 clear()

原因分析：
多线程运行时，有可能 VideoThread::run()--> resetState()在执行前或者过程中，被切换到 AVDemuxThread::run() --> while() 运行。结果就是video pkg queue中缓存了部分数据，当再次切换到 VideoThread::run()--> resetState()执行完时，就有可能会出现video queue被 clear() 现象

**Comment by wang-bin** [comment]
Fixed
