### ISSUE TITLE
upload app with lib QtAV to AppStore, Non-public API usage 

### ISSUE THREAD

**Issue by KolyanVM** [wang-bin/QtAV#1139]
My application contains the QtAV library 1.12. It works fine, but when you send the release to the AppStore store, an error comes ...
  _Non-public API usage:
     **The app references non-public selectors in "MyApp": redo :, texImageIOSurface: target: internalFormat: width: height: format: type: plane: invert :, undo:**
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. 
_

This line refers to the OpenGL ES library.
Most likely this is due to the update of Xcode and Ios v11+. 
How can you solve this problem?

**Comment by KolyanVM** [comment]
Easily solved this problem by changing the name of the method ...
_texImageIOSurface_
to
_xxtexImageIOSurface_

**Comment by pierrexn** [comment]
@KolyanVM are you able to create a correct signed package for MacOSX? As soon as i add QtAV frameworks, my signed app can't be executed.

**Comment by KolyanVM** [comment]
The application was successfully compiled and published for iOS. For makos did not try to publish, but also should work.
