### ISSUE TITLE
[Regression] unable to seek while paused

### ISSUE THREAD

**Issue by mrgreywater** [wang-bin/QtAV#1149]
### QtAV, Qt version and platform
since https://github.com/wang-bin/QtAV/pull/1119
Tested with Windows 10 x64

### Reproduction steps
start QMLPlayer.exe
open any video file
pause
seek to random position with seek bar

### Expected behavior
seekbar updates position, shows image at position

### Actual behavior
nothing happens, video only seeks after resuming playback

**Comment by ThatOdieGuy** [comment]
I believe I've resolved this with #1173

**Comment by mrgreywater** [comment]
Thanks for looking into it! The PR that broke it is quite a bit smaller than your fix, and the "right" solution to fix it would be probably to figure out why that original timing PR broke it in the first place, and fix it there, instead of adding another decoding step.

Sidenote: Your PR seems to use tabs instead of spaces which are used for the rest of the file.

**Comment by ThatOdieGuy** [comment]
Thanks for your notes. 👍  I was able to put back from code from that original PR and I'm much happier with this fix. And good call on the spaces, whoops, new computer and I hadn't setup Visual Studio just yet.
