### ISSUE TITLE
Embed ffmpeg in player.exe

### ISSUE THREAD

**Issue by rahbari** [wang-bin/QtAV#1158]
How can I add ffmpeg to player.exe to get rid of ffmpeg dll files?
I already tried static_ffmpeg but if has no effect.
Thank you

**Comment by wangwenx190** [comment]
You should use the prebuilt static ffmpeg libs provided by the author: https://sourceforge.net/projects/avbuild/files/windows-desktop/ffmpeg-git-windows-desktop-clang-static-lite.tar.xz/download

I succeeded last year, but this year, QtAV programs(such as Player.exe) will crash and I don't know why.
