### ISSUE TITLE
Simpleplayer example on MacOS: dyld: Symbol not found: _av_get_dict

### ISSUE THREAD

**Issue by NickD2039** [wang-bin/QtAV#1161]
I can successfully build and initially run the simpleplayer_sdk.pro example but it crashes as soon as I choose any video file to play back, complaining that _av_dict_get was not found by dyld (more details below). 

I'm using the latest commit 7ddf6db  of QtAV (28 Sep) and have built from sources on MacOS using Qt 5.11.2, QtCreator 4.7.1 and MacOS SDK 10.14.

I grabbed the FFmpeg binaries from https://sourceforge.net/projects/avbuild/files/macOS/ffmpeg-4.0.3-macOS-lite.tar.xz/download and copied the headers and libs to the Qt installation as instructed.

I built QtAV in release mode successfully, and executed sdk_install.sh to install to Qt.

I then built the simpleplayer-sdk.pro example successfully and it initially runs. However, when I load any video file it immediately crashes out. (Also crashes with the alternate simpleplayer.pro example).

The following can be seen in QtCreator's Application Output:

```
15:02:24: Starting /Users/nick/project/QtAV-full-new/examples/build-simpleplayer_sdk-Desktop_Qt_5_11_2_clang_64bit-Release/simpleplayer_sdk.app/Contents/MacOS/simpleplayer_sdk...
objc[13413]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff95d3cc90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x114651cd8). One of the two will be used. Which one is undefined.
dyld: lazy symbol binding failed: Symbol not found: _av_dict_get
  Referenced from: /Users/nick/Qt/5.11.2/clang_64/lib/QtAV.framework/Versions/1/QtAV
  Expected in: /Users/nick/Qt/5.11.2/clang_64/lib/libavdevice.58.dylib

dyld: Symbol not found: _av_dict_get
  Referenced from: /Users/nick/Qt/5.11.2/clang_64/lib/QtAV.framework/Versions/1/QtAV
  Expected in: /Users/nick/Qt/5.11.2/clang_64/lib/libavdevice.58.dylib

15:02:36: The program has unexpectedly finished.
15:02:36: The process was ended forcefully.
15:02:37: /Users/nick/project/QtAV-full-new/examples/build-simpleplayer_sdk-Desktop_Qt_5_11_2_clang_64bit-Release/simpleplayer_sdk.app/Contents/MacOS/simpleplayer_sdk crashed.

```
If it helps, here's the corresponding info in the MacOS problem report:

```
Process:               simpleplayer [13734]
Path:                  /Users/USER/*/simpleplayer
Identifier:            simpleplayer
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        Qt Creator [5130]
Responsible:           simpleplayer [13734]
User ID:               501

Date/Time:             2018-11-07 16:16:02.295 +1100
OS Version:            Mac OS X 10.13.6 (17G2307)
Report Version:        12
Bridge OS Version:     2.4.1 (15P6805)
Anonymous UUID:        F8610A10-7D05-3C5B-C887-E6D5B24855A1

Sleep/Wake UUID:       1CE734F2-360E-4661-BEE5-CFC9046F04D4

Time Awake Since Boot: 55000 seconds
Time Since Wake:       10000 seconds

System Integrity Protection: enabled

Crashed Thread:        8  Thread (pooled)

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: _av_dict_get
  Referenced from: /Users/USER/*/QtAV.framework/Versions/1/QtAV
  Expected in: /Users/USER/*/libavdevice.58.dylib

```

I also installed the later https://sourceforge.net/projects/avbuild/files/macOS/ffmpeg-4.1-macOS-lite.tar.xz/download and repeated all the above steps from clean but had the same result. The expected location mentioned in the error does exist (though it is an alias to libavdevice.58.5.100.dylib, which also exists).

FWIW the exact same procedure on Windows 10/VS2015-64bit and on Ubuntu 16.04 worked just fine.

Any help would be greatly appreciated.

**Comment by NickD2039** [comment]
If it helps, here's the output of objdump -t for the expected dylib:

/Users/nick/Qt/5.11.2/clang_64/lib/libavdevice.dylib:	file format Mach-O 64-bit x86-64

SYMBOL TABLE:
0000000005614542 l    d  *UND*	radr://5614542
0000000000000015 g       *UND*	_av_bprint_chars
000000000000003a g       *UND*	_av_bprint_finalize
000000000000005e g       *UND*	_av_bprint_init
000000000000007a g       *UND*	_av_bprintf
00000000000000a8 g       *UND*	_av_buffersink_get_channel_layout
00000000000000e6 g       *UND*	_av_buffersink_get_channels
000000000000011c g       *UND*	_av_buffersink_get_format
0000000000000155 g       *UND*	_av_buffersink_get_frame_flags
0000000000000189 g       *UND*	_av_buffersink_get_h
00000000000001c5 g       *UND*	_av_buffersink_get_sample_aspect_ratio
000000000000020b g       *UND*	_av_buffersink_get_sample_rate
0000000000000247 g       *UND*	_av_buffersink_get_time_base
000000000000027c g       *UND*	_av_buffersink_get_type
00000000000002a9 g       *UND*	_av_buffersink_get_w
00000000000002d4 g       *UND*	_av_default_item_name
0000000000008460 g       __DATA,__const	_av_device_capabilities
0000000000006010 g       __TEXT,__const	_av_device_ffversion
0000000000000325 g       *UND*	_av_dict_copy
0000000000000341 g       *UND*	_av_dict_free
000000000000035c g       *UND*	_av_dict_get
0000000000000376 g       *UND*	_av_dict_set
0000000000000399 g       *UND*	_av_find_input_format
00000000000003bf g       *UND*	_av_frame_alloc
00000000000003de g       *UND*	_av_frame_free
00000000000003fd g       *UND*	_av_frame_unref
0000000000000416 g       *UND*	_av_free
0000000000000429 g       *UND*	_av_freep
000000000000044c g       *UND*	_av_get_bytes_per_sample
0000000000000484 g       *UND*	_av_get_default_channel_layout
00000000000004c1 g       *UND*	_av_get_padded_bits_per_pixel
00000000000004f1 g       *UND*	_av_get_pcm_codec
0000000000000518 g       *UND*	_av_get_pix_fmt_name
0000000000000545 g       *UND*	_av_get_sample_fmt_name
0000000000000569 g       *UND*	_av_gettime
0000000000000586 g       *UND*	_av_iformat_next
00000000000005b0 g       *UND*	_av_image_copy_to_buffer
00000000000005e3 g       *UND*	_av_image_get_buffer_size
000000000000060d g       *UND*	_av_init_packet
0000000000001bcd g     F __TEXT,__text	_av_input_audio_device_next
0000000000001c3d g     F __TEXT,__text	_av_input_video_device_next
0000000000000672 g       *UND*	_av_int_list_length_for_size
0000000000000697 g       *UND*	_av_log
00000000000006aa g       *UND*	_av_malloc
00000000000006c6 g       *UND*	_av_malloc_array
00000000000006e3 g       *UND*	_av_mallocz
00000000000006fe g       *UND*	_av_new_packet
000000000000071e g       *UND*	_av_oformat_next
000000000000073f g       *UND*	_av_opt_set_bin
0000000000000764 g       *UND*	_av_opt_set_defaults
000000000000078a g       *UND*	_av_opt_set_dict
00000000000007ad g       *UND*	_av_opt_set_dict2
00000000000007cf g       *UND*	_av_opt_set_int
0000000000001c4a g     F __TEXT,__text	_av_output_audio_device_next
0000000000001c58 g     F __TEXT,__text	_av_output_video_device_next
0000000000000832 g       *UND*	_av_packet_new_side_data
000000000000085c g       *UND*	_av_packet_unref
0000000000000882 g       *UND*	_av_pix_fmt_desc_get
00000000000008a5 g       *UND*	_av_rescale_q
00000000000008c5 g       *UND*	_av_rescale_q_rnd
00000000000008e2 g       *UND*	_av_strdup
00000000000008f8 g       *UND*	_av_strtok
0000000000001c66 g     F __TEXT,__text	_avdevice_app_to_dev_control_message
0000000000001c93 g     F __TEXT,__text	_avdevice_capabilities_create
0000000000001da7 g     F __TEXT,__text	_avdevice_capabilities_free
0000000000001bbd g     F __TEXT,__text	_avdevice_configuration
0000000000001c81 g     F __TEXT,__text	_avdevice_dev_to_app_control_message
0000000000001f2a g     F __TEXT,__text	_avdevice_free_list_devices
0000000000001bc5 g     F __TEXT,__text	_avdevice_license
0000000000001e19 g     F __TEXT,__text	_avdevice_list_devices
0000000000001fca g     F __TEXT,__text	_avdevice_list_input_sources
0000000000002067 g     F __TEXT,__text	_avdevice_list_output_sinks
0000000000001ba4 g     F __TEXT,__text	_avdevice_register_all
0000000000001bb7 g     F __TEXT,__text	_avdevice_version
0000000000000000         *UND*	_AVMediaTypeAudio
0000000000000000         *UND*	_AVMediaTypeVideo
0000000000000000         *UND*	_CFRelease
0000000000000000         *UND*	_CFRetain
0000000000000000         *UND*	_CFRunLoopRunInMode
0000000000000000         *UND*	_CGGetActiveDisplayList
0000000000000000         *UND*	_CMAudioFormatDescriptionGetStreamBasicDescription
0000000000000000         *UND*	_CMBlockBufferCopyDataBytes
0000000000000000         *UND*	_CMBlockBufferGetDataLength
0000000000000000         *UND*	_CMSampleBufferGetDataBuffer
0000000000000000         *UND*	_CMSampleBufferGetFormatDescription
0000000000000000         *UND*	_CMSampleBufferGetImageBuffer
0000000000000000         *UND*	_CMSampleBufferGetOutputSampleTimingInfoArray
0000000000000000         *UND*	_CMTimeMake
0000000000000000         *UND*	_CMVideoFormatDescriptionGetDimensions
0000000000000000         *UND*	_CVImageBufferGetEncodedSize
0000000000000000         *UND*	_CVPixelBufferGetBaseAddress
0000000000000000         *UND*	_CVPixelBufferGetBaseAddressOfPlane
0000000000000000         *UND*	_CVPixelBufferGetBytesPerRow
0000000000000000         *UND*	_CVPixelBufferGetBytesPerRowOfPlane
0000000000000000         *UND*	_CVPixelBufferGetDataSize
0000000000000000         *UND*	_CVPixelBufferGetHeight
0000000000000000         *UND*	_CVPixelBufferGetPlaneCount
0000000000000000         *UND*	_CVPixelBufferGetWidth
0000000000000000         *UND*	_CVPixelBufferIsPlanar
0000000000000000         *UND*	_CVPixelBufferLockBaseAddress
0000000000000000         *UND*	_CVPixelBufferUnlockBaseAddress
0000000000000000         *UND*	_NSUndefinedKeyException
0000000000000000         *UND*	_OBJC_CLASS_$_AVCaptureAudioDataOutput
0000000000000000         *UND*	_OBJC_CLASS_$_AVCaptureDevice
0000000000000000         *UND*	_OBJC_CLASS_$_AVCaptureDeviceInput
0000000000000000         *UND*	_OBJC_CLASS_$_AVCaptureScreenInput
0000000000000000         *UND*	_OBJC_CLASS_$_AVCaptureSession
0000000000000000         *UND*	_OBJC_CLASS_$_AVCaptureVideoDataOutput
0000000000000000         *UND*	_OBJC_CLASS_$_NSAutoreleasePool
0000000000000000         *UND*	_OBJC_CLASS_$_NSDictionary
0000000000000000         *UND*	_OBJC_CLASS_$_NSNumber
0000000000000000         *UND*	_OBJC_CLASS_$_NSObject
0000000000000000         *UND*	_OBJC_EHTYPE_$_NSException
0000000000000000         *UND*	_OBJC_METACLASS_$_NSObject
0000000000000000         *UND*	__Unwind_Resume
0000000000000000         *UND*	___CFConstantStringClassReference
0000000000000000         *UND*	___objc_personality_v0
0000000000000000         *UND*	___stack_chk_fail
0000000000000000         *UND*	___stack_chk_guard
0000000000000000         *UND*	___stderrp
0000000000000000         *UND*	__objc_empty_cache
0000000000000000         *UND*	__objc_empty_vtable
0000000000000000         *UND*	_abort
0000000000000000         *UND*	_av_bprint_chars
0000000000000000         *UND*	_av_bprint_finalize
0000000000000000         *UND*	_av_bprint_init
0000000000000000         *UND*	_av_bprintf
0000000000000000         *UND*	_av_buffersink_get_channel_layout
0000000000000000         *UND*	_av_buffersink_get_channels
0000000000000000         *UND*	_av_buffersink_get_format
0000000000000000         *UND*	_av_buffersink_get_frame_flags
0000000000000000         *UND*	_av_buffersink_get_h
0000000000000000         *UND*	_av_buffersink_get_sample_aspect_ratio
0000000000000000         *UND*	_av_buffersink_get_sample_rate
0000000000000000         *UND*	_av_buffersink_get_time_base
0000000000000000         *UND*	_av_buffersink_get_type
0000000000000000         *UND*	_av_buffersink_get_w
0000000000000000         *UND*	_av_default_item_name
0000000000000000         *UND*	_av_dict_copy
0000000000000000         *UND*	_av_dict_free
0000000000000000         *UND*	_av_dict_get
0000000000000000         *UND*	_av_dict_set
0000000000000000         *UND*	_av_find_input_format
0000000000000000         *UND*	_av_frame_alloc
0000000000000000         *UND*	_av_frame_free
0000000000000000         *UND*	_av_frame_unref
0000000000000000         *UND*	_av_free
0000000000000000         *UND*	_av_freep
0000000000000000         *UND*	_av_get_bytes_per_sample
0000000000000000         *UND*	_av_get_default_channel_layout
0000000000000000         *UND*	_av_get_padded_bits_per_pixel
0000000000000000         *UND*	_av_get_pcm_codec
0000000000000000         *UND*	_av_get_pix_fmt_name
0000000000000000         *UND*	_av_get_sample_fmt_name
0000000000000000         *UND*	_av_gettime
0000000000000000         *UND*	_av_iformat_next
0000000000000000         *UND*	_av_image_copy_to_buffer
0000000000000000         *UND*	_av_image_get_buffer_size
0000000000000000         *UND*	_av_init_packet
0000000000000000         *UND*	_av_int_list_length_for_size
0000000000000000         *UND*	_av_log
0000000000000000         *UND*	_av_malloc
0000000000000000         *UND*	_av_malloc_array
0000000000000000         *UND*	_av_mallocz
0000000000000000         *UND*	_av_new_packet
0000000000000000         *UND*	_av_oformat_next
0000000000000000         *UND*	_av_opt_set_bin
0000000000000000         *UND*	_av_opt_set_defaults
0000000000000000         *UND*	_av_opt_set_dict
0000000000000000         *UND*	_av_opt_set_dict2
0000000000000000         *UND*	_av_opt_set_int
0000000000000000         *UND*	_av_packet_new_side_data
0000000000000000         *UND*	_av_packet_unref
0000000000000000         *UND*	_av_pix_fmt_desc_get
0000000000000000         *UND*	_av_rescale_q
0000000000000000         *UND*	_av_rescale_q_rnd
0000000000000000         *UND*	_av_strdup
0000000000000000         *UND*	_av_strtok
0000000000000000         *UND*	_avfilter_get_by_name
0000000000000000         *UND*	_avfilter_graph_alloc
0000000000000000         *UND*	_avfilter_graph_config
0000000000000000         *UND*	_avfilter_graph_create_filter
0000000000000000         *UND*	_avfilter_graph_dump
0000000000000000         *UND*	_avfilter_graph_free
0000000000000000         *UND*	_avfilter_graph_parse_ptr
0000000000000000         *UND*	_avfilter_inout_free
0000000000000000         *UND*	_avfilter_link
0000000000000000         *UND*	_avfilter_pad_get_type
0000000000000000         *UND*	_avformat_alloc_context
0000000000000000         *UND*	_avformat_alloc_output_context2
0000000000000000         *UND*	_avformat_free_context
0000000000000000         *UND*	_avformat_new_stream
0000000000000000         *UND*	_avio_closep
0000000000000000         *UND*	_avio_open2
0000000000000000         *UND*	_avio_read_to_bprint
0000000000000000         *UND*	_avpriv_register_devices
0000000000000000         *UND*	_avpriv_set_pts_info
0000000000000000         *UND*	_dispatch_queue_create
0000000000000000         *UND*	_dispatch_release
0000000000000000         *UND*	_fflush
0000000000000000         *UND*	_fputs
0000000000000000         *UND*	_kCFRunLoopDefaultMode
0000000000000000         *UND*	_kCVPixelBufferPixelFormatTypeKey
0000000000000000         *UND*	_memcpy
0000000000000000         *UND*	_objc_begin_catch
0000000000000000         *UND*	_objc_end_catch
0000000000000000         *UND*	_objc_enumerationMutation
0000000000000000         *UND*	_objc_msgSend
0000000000000000         *UND*	_objc_msgSendSuper2
0000000000000000         *UND*	_pthread_cond_destroy
0000000000000000         *UND*	_pthread_cond_init
0000000000000000         *UND*	_pthread_cond_signal
0000000000000000         *UND*	_pthread_cond_wait
0000000000000000         *UND*	_pthread_mutex_destroy
0000000000000000         *UND*	_pthread_mutex_init
0000000000000000         *UND*	_pthread_mutex_lock
0000000000000000         *UND*	_pthread_mutex_unlock
0000000000000000         *UND*	_sscanf
0000000000000000         *UND*	_strcmp
0000000000000000         *UND*	_strlen
0000000000000000         *UND*	_strncmp
0000000000000000         *UND*	dyld_stub_binder

**Comment by wang-bin** [comment]
use the lastest avbuild https://sourceforge.net/projects/avbuild/files/macOS/
