### ISSUE TITLE
播放不了speex（.spx）格式的音频文件

### ISSUE THREAD

**Issue by redstoneleo** [wang-bin/QtAV#1168]
ffmpeg本身是支持speex（.spx）格式的，但是qtavplayer播放不了该格式的音频文件，能否支持这个格式呢？谢谢！

**Comment by wang-bin** [comment]
qtav使用的ffmpeg支持么

**Comment by redstoneleo** [comment]
1.我不太清楚哦，可能和ffmpeg的编译有关系吧，我用ffmpeg官网提供的static builds of ffmpeg是可以识别并转换speex（.spx）格式的；
2.这个项目也是居于ffmpeg，
https://github.com/matham/ffpyplayer
可以播放speex（.spx）格式

**Comment by wang-bin** [comment]
我提供的ffmpeg不支持，你要自己编译qtav
