### ISSUE TITLE
Last pull request was not merged in

### ISSUE THREAD

**Issue by andre-phan** [wang-bin/QtAV#1204]
### QtAV, Qt version and platform

or commit id if not using release version
6ca0626d635062e2eb53fcf43f64cd16e9298c18

### Reproduction steps
If you git log -p you'll see that there were no code changes even though it was merged.

### Log file

set environment var `QTAV_LOG=all` or C++ api `QtAV::setLogLevel(All)` to enable log.

For Player and QMLPlayer example app, choose log level `all` in config page.

**Comment by wang-bin** [comment]
a new commit id is created for a merge, it's parent id b0dcf9b  contains changes
