### ISSUE TITLE
QTAV Build

### ISSUE THREAD

**Issue by sravssatyanarayanaReddy** [wang-bin/QtAV#1217]
I am using Qt5.13 to build QtAv for andriod with clang when i am trying to build i am getting this below error how to solve

:-1: error: No rule to make target `jmi/jmi.cpp', needed by `C:/Users/SYS/Downloads/QtAV_Andriod_Qt5.12.3/.obj/QtAV_android_arm_llvm/jmi.obj'.  Stop.

can you give me solution how to build wit hQt5.13 for andriod

**Comment by wang-bin** [comment]
run `git submodule update —init`
