### ISSUE TITLE
libOpenSLES: Leaving Object::GetInterface (SL_RESULT_FEATURE_UNSUPPORTED)

### ISSUE THREAD

**Issue by Kambiz-Asadzadeh** [wang-bin/QtAV#1240]
I'm trying to run an Application based on QtAv for Android armeabi-v7 using Qt 5.13.1 and NDK R20 on Windows.

But video does not play and screen is black only!
It gives me runtime error message in Qt Creator Application output is:

`E linker  : normalize_path - invalid input: "C", the input path should be absolute
W linker  : Warning: unable to normalize "C"
E linker  : normalize_path - invalid input: "C", the input path should be absolute
W linker  : Warning: unable to normalize "C"
W libOpenSLES: Leaving Object::GetInterface (SL_RESULT_FEATURE_UNSUPPORTED)
W libOpenSLES: Leaving Object::GetInterface (SL_RESULT_FEATURE_UNSUPPORTED)`

How can I fix this problem?

My Qt library is version 5.13.1 and  ffmpeg is master.
Android version is 7.1.
Minimum api is : 21
Target api is : 28

**Comment by meichuanneiku** [comment]
@KambizAsadzadeh 
Hello, now I also encounter this problem, how did you solve it? Thank you
