### ISSUE TITLE
VideoRenderer display error image while setting ROI(region of interest) for several times 

### ISSUE THREAD

**Issue by zhounan354** [wang-bin/QtAV#1249]
### QtAV, Qt version and platform

latest version and win7 x64

### Reproduction steps

To make animation while the video is zoom in/out，I set ROI several times to approach the target ROI, and change the size of display area at the same time to ensure it looks like the video is zoomed.

(why not set viewport? Because it still deal slowly when zoom in about 1000%)

### Expected behavior and Actual behavior

At most time it works well. But at some moment, quick as flash, the video display abnormal. It seems the ROI is not successfully set, just like the size of ROI is (0,0) or(1,1),and the size of render is normal. I catch one abnormal display image like this. It's vertical stripes and sometimes it may be horizontal. It only appears while I active zoom in/out.

![image](https://user-images.githubusercontent.com/28867408/66362315-d2b56880-e9b4-11e9-8908-0ad74dba2389.png)

I am confused. And I found nothing wrong through debug. And I will go on.

### Nearest discover
When I move the display Area,the position cross (*,0)(according to parent),vertical stripes appears and cross (0,*) ,horizontal stripes.That is good!

### problem solved
look at the code

```
QRectF VideoMaterial::mapToTexture(int plane, const QRectF &roi, int normalize) const
{
    DPTR_D(const VideoMaterial);
...
    float x = roi.x();
    float w = roi.width(); //TODO: texturewidth
    float y = roi.y();
    float h = roi.height();
    if (normalize) {
        if (qAbs(x) > 1) {
            x /= tex0W;
            x *= s;
        }
        if (qAbs(y) > 1)
            y /= (float)d.height;
        if (qAbs(w) > 1) {
            w /= tex0W;
            w *= s;
        }
        if (qAbs(h) > 1)
            h /= (float)d.height;
    }
...
```
I have found that the image is abnormal when the position of ROI is (*,1) or (1,*). That's why I found something strange while the position change across (*,0) or (0,*). roi.x() returns 1.000,qAbs(1.000)>1 return false,which leads x is not correct.The Correct x should be a  ratio to width,here it is 1.000/1280.000 .

I modify the ">” to ">=" .And guess what? It works! 
Goooooooood !

This should be a bug, I think.

**Comment by wang-bin** [comment]
0<=x<=1 assumes x is normalized. You can try `1.0f+FLT_EPSILON`

**Comment by zhounan354** [comment]
谢谢大神回复！我好激动啊，原来大神一直有在关注这个工程的！
I have found that there is another roi value system to set roi by ratio. But I have only used the pixel number of frame to set roi. It means I can also set roi by ratio, without other modifies？
Besides, 0<=x<=1 assumes x is normalized,and in fact, x==1 means the image displayed is meaningless. It will be difficult to tell whether the purpose is to take the whole picture or a single pixel while width is 1.0.
It's enough to solve the problem in my situation(I can handle the width and height not be 1.0). And avoiding the compare 1.0==1, ```1.0f+FLT_EPSILON ```is greater and safer than simplify adding “=”.
So the final code may be...
```
    float x = roi.x();
    float w = roi.width(); //TODO: texturewidth
    float y = roi.y();
    float h = roi.height();
    if (normalize) {
        if (qAbs(x) + FLT_EPSILON> 1) {
            x /= tex0W;
            x *= s;
        }
        if (qAbs(y)+ FLT_EPSILON > 1)
            y /= (float)d.height;
        if (qAbs(w) + FLT_EPSILON> 1) {
            w /= tex0W;
            w *= s;
        }
        if (qAbs(h) + FLT_EPSILON> 1)
            h /= (float)d.height;
    }
```
Thank you again! And, Respect!
