### ISSUE TITLE
Can AVPlayer handle sequential input?

### ISSUE THREAD

**Issue by cwilcox-mersive** [wang-bin/QtAV#1257]
### QtAV, Qt version and platform

Qt 5.12.4
QtAV 1.13.0, built from source, commit b51fee7

### Reproduction steps

Create a custom QBuffer to feed raw H.264 encoded data from USB device. When I make it random access, it works, when sequential, it does not work.

### Expected behavior

Play encoded video.

### Actual behavior

Tries to read all sequential data, then fails, apparently because:

"Can not seek. MediaIO[QtAV::MediaIO] is not a seekable IO"

### Log file

16:18:37: Debugging starts
registerRenderers...........
QtAV 1.13.0(Nov  5 2019, 15:21:39)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai, China Copyright (C) 2012-2019 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
"Build with Qt-5.12.4"
"FFmpeg/Libav configuration: --enable-shared --enable-small --disable-encoders --toolchain=msvc"
"Build with avutil-56.22.100"
"Build with avcodec-58.35.100"
"Build with avformat-58.20.100"
"Build with avfilter-7.40.101"
"Build with avdevice-58.5.100"
"Build with swresample-3.3.100"
"Build with swscale-5.3.100"
Registered audio backends:  ("XAudio2", "DirectSound", "null")

... (removed OpenGL and other irrelevant output)

CustomQBuffer::open()
CustomQBuffer::open, file size: 23620220
CustomQBuffer::open, array size: 23620220
Loading  QVariant(QIODevice*, CustomQBuffer(0xbd78478))  ...
"all closed and reseted"
"network: 0"
"seekable: 1"
CustomQBuffer::isSequential()
"avformat_open_input: d->format_ctx:'0xbb5b400'..., MediaIO('QIODevice'): 0xbdc2988"
CustomQBuffer::isSequential()
CustomQBuffer::readData(): pos 0, length 32768
CustomQBuffer::readData(): pos 32768, length 32768
CustomQBuffer::readData(): pos 65536, length 32768
CustomQBuffer::readData(): pos 98304, length 32768
... (reads everything in between)
CustomQBuffer::readData(): pos 23527424, length 32768
CustomQBuffer::readData(): pos 23560192, length 32768
CustomQBuffer::readData(): pos 23592960, length 32768
CustomQBuffer::readData(): reduced length to 27260
"avformat_open_input: (with MediaIO) ret:0"
CustomQBuffer::isSequential()
"Can not seek. MediaIO[QtAV::MediaIO] is not a seekable IO"
[FFmpeg:mov,mp4,m4a,3gp,3g2,mj2] stream 0, offset 0x30: partial file
CustomQBuffer::isSequential()
"Can not seek. MediaIO[QtAV::MediaIO] is not a seekable IO"
[FFmpeg:mov,mp4,m4a,3gp,3g2,mj2] stream 0, offset 0x30: partial file
"[AVDemuxer] error: Invalid data found when processing input"
... (lots more of the errors above)
"[AVDemuxer] error: Invalid data found when processing input"
...
16:18:55: Debugging has finished

**Comment by cwilcox-mersive** [comment]
The only difference between working and not working is the value I return from QIODevice::IsSequential(). Do I need to use a network protocol if my video stream is sequential?

**Comment by wang-bin** [comment]
ffmpeg may need to seek in the input stream to detect format, but a sequential device is not seekable

**Comment by cwilcox-mersive** [comment]
Thanks for answering so promptly. Do I need to move over to a network protocol if the video stream is not seekable? In our case the video stream is sent over USB, but it's very similar to the network case.

**Comment by cwilcox-mersive** [comment]
Never mind, I think we've made sufficient progress that we don't need any more questions answered. Thanks for QtAV!
