### ISSUE TITLE
Recent install instruction for Windows 10

### ISSUE THREAD

**Issue by ewoudwijma** [wang-bin/QtAV#1271]
I am looking for recent install instructions for Windows 10 as I cannot get it working and I am not sure if I got the right sources and instructions (some are outdated).
See below what I did, it is confusing that some is on github and some is on sourceforge.

So can you point me to clear instructions or maybe give high level instructions, especially where to find what source and what scripts to run.

For platform independence I would like to have a MinGW version, not a VS201x version.

Thx in advance!

### QtAV, Qt version and platform
QtAV: Found latest version [here ](https://sourceforge.net/projects/qtav/files/ci/) dated 2020-01-13:  QtAV-Qt5.9-VS2017x64-release-df5bf45.7z. I guess this is QtAV 1.13.

I would like to have a MinGW version as VS2017 is less platform independent then MinGW but cannot find a recent MinGW version. 

Qt: Using C:\Qt\5.13.2\mingw73_64

QtAV examples. Latest version above do not contain examples so I took the examples from [github ](https://github.com/wang-bin/QtAV/tree/master/examples)

### Reproduction steps
Open examples.pro in QT Creator, choose 5,13,2 MinGW 64 resulting in creating the folder: build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug.

Run the examples project

### Expected behavior
Successful build

### Actual behavior (Issues tab)
:-1: error: No rule to make target 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/audiopipeline/../out/lib_win_/QtAVd1.dll', needed by '../out/bin/audiopipeline.exe'.  Stop.

See also [this issue](https://github.com/wang-bin/QtAV/issues/711). It talks about  sdk_install.bat but I have only  sdk_deploy.bat (which I run into C:\Qt\5.13.2\mingw73_64) .

### Log file (Compile output tab)
13:19:31: Starting: "C:\Qt\Tools\mingw730_64\bin\mingw32-make.exe" -j4
cd common\ && ( if not exist Makefile C:\Qt\5.13.2\mingw73_64\bin\qmake.exe -o Makefile C:\Users\ewoud\Downloads\QtAV-master\examples\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && C:/Qt/Tools/mingw730_64/bin/mingw32-make -f Makefile 
cd audiopipeline\ && ( if not exist Makefile C:\Qt\5.13.2\mingw73_64\bin\qmake.exe -o Makefile C:\Users\ewoud\Downloads\QtAV-master\examples\audiopipeline\audiopipeline.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && C:/Qt/Tools/mingw730_64/bin/mingw32-make -f Makefile 
cd sharedoutput\ && ( if not exist Makefile C:\Qt\5.13.2\mingw73_64\bin\qmake.exe -o Makefile C:\Users\ewoud\Downloads\QtAV-master\examples\sharedoutput\sharedoutput.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && C:/Qt/Tools/mingw730_64/bin/mingw32-make -f Makefile 
cd simpletranscode\ && ( if not exist Makefile C:\Qt\5.13.2\mingw73_64\bin\qmake.exe -o Makefile C:\Users\ewoud\Downloads\QtAV-master\examples\simpletranscode\simpletranscode.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && C:/Qt/Tools/mingw730_64/bin/mingw32-make -f Makefile 
mingw32-make[1]: Entering directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/common'
C:/Qt/Tools/mingw730_64/bin/mingw32-make -f Makefile.Debug
mingw32-make[1]: Entering directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/audiopipeline'
C:/Qt/Tools/mingw730_64/bin/mingw32-make -f Makefile.Debug
mingw32-make[1]: Entering directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/sharedoutput'
C:/Qt/Tools/mingw730_64/bin/mingw32-make -f Makefile.Debug
mingw32-make[2]: Entering directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/audiopipeline'
mingw32-make[2]: Leaving directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/audiopipeline'
mingw32-make[2]: *** No rule to make target 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/audiopipeline/../out/lib_win_/QtAVd1.dll', needed by '../out/bin/audiopipeline.exe'.  Stop.
mingw32-make[1]: Entering directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/simpletranscode'
C:/Qt/Tools/mingw730_64/bin/mingw32-make -f Makefile.Debug
mingw32-make[1]: *** [Makefile:38: debug] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/audiopipeline'
mingw32-make: *** [Makefile:83: sub-audiopipeline-make_first] Error 2
mingw32-make: *** Waiting for unfinished jobs....
mingw32-make[2]: Entering directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/sharedoutput'
mingw32-make[2]: Leaving directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/sharedoutput'
mingw32-make[2]: *** No rule to make target 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/sharedoutput/../out/lib_win_/QtAVd1.dll', needed by '../out/bin/sharedoutput.exe'.  Stop.
mingw32-make[1]: *** [Makefile:38: debug] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/sharedoutput'
mingw32-make[2]: Entering directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/simpletranscode'
mingw32-make[2]: Leaving directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/simpletranscode'
mingw32-make[1]: Leaving directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/simpletranscode'
mingw32-make[2]: *** No rule to make target 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/simpletranscode/../out/lib_win_/QtAVd1.dll', needed by '../out/bin/simpletranscode.exe'.  Stop.
mingw32-make[1]: *** [Makefile:38: debug] Error 2
mingw32-make: *** [Makefile:108: sub-sharedoutput-make_first] Error 2
mingw32-make: *** [Makefile:133: sub-simpletranscode-make_first] Error 2
mingw32-make[2]: Entering directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/common'
mingw32-make[2]: Nothing to be done for 'first'.
mingw32-make[2]: Leaving directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/common'
mingw32-make[1]: Leaving directory 'C:/Users/ewoud/Downloads/QtAV-master/build-examples-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/common'
13:19:33: The process "C:\Qt\Tools\mingw730_64\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project examples (kit: Desktop Qt 5.13.2 MinGW 64-bit)
When executing step "Make"

**Comment by javlada** [comment]
I think it might be [this issue](https://github.com/wang-bin/QtAV/issues/1231).
