### ISSUE TITLE
控制音轨

### ISSUE THREAD

**Issue by zhd785576549** [wang-bin/QtAV#1282]
有没有控制音轨的接口和例子

**Comment by wang-bin** [comment]
外挂音轨：`setAudioStream(const QString& file, int n = 0)`，内置音轨 `setAudioStream(int n)`

**Comment by zhd785576549** [comment]
> 外挂音轨：`setAudioStream(const QString& file, int n = 0)`，内置音轨 `setAudioStream(int n)`

多谢
