### ISSUE TITLE
play a video with encrypting 

### ISSUE THREAD

**Issue by Husseinbeygi** [wang-bin/QtAV#1295]
### QtAV, Qt version and platform
kubuntu 18.04
Qt 5.14
QtAV 1.6

### Question
i have video that i encrypt that with command line below :
```
ffmpeg -i SampleVideo_1280x720_1mb.mp4 -vcodec copy -acodec copy -encryption_scheme cenc-aes-ctr -encryption_key 76a6c65c5ea762046bd749a2e632ccbb -encryption_kid a7e61c373e219033c21091fa607bf3b8 SampleVideo_1280x720_1mb_encrypted.mp4
```
and this is the command line code for for play the video:
```
mpv --demuxer-lavf-o=decryption_key=76a6c65c5ea762046bd749a2e632ccbb SampleVideo_1280x720_1mb_encrypted.mp4

```
so how can i play the video with QtAV?
thank you

**Comment by wang-bin** [comment]
https://github.com/wang-bin/QtAV/wiki/FFmpeg-dict-opt-in-QtAV
