### ISSUE TITLE
Playback speed 

### ISSUE THREAD

**Issue by quocson95** [wang-bin/QtAV#1297]
### QtAV, Qt version and platform
commit id : 11a13bf0717dff5273c6abf2d42d5fee13796f8e

### Reproduction steps
Open hls link
set speed: 32
### Expected behavior
Play and render to end of file
### Actual behavior
Only first segment render, another segment loading but not render
### Log file
https://gist.github.com/quocson95/467a752226667e5f22b4703bd0c7312a
### Sample files (optional)
https://gist.github.com/quocson95/1f6d0482a8ca1e4b8dfae56cff8a12e9
This link using in sample will be expire at GMT: Saturday, April 11, 2020 9:24:43 AM

**Comment by wang-bin** [comment]
https://github.com/wang-bin/avbuild/commit/9342cf14537cd633582bc622e06945c7b56ad6bd
