### ISSUE TITLE
Play video from qrc doesn't work in qrc project for test(qrc工程测试通过qrc播放文件失败)

### ISSUE THREAD

**Issue by ffzzc7** [wang-bin/QtAV#1300]
Put “test.mp4” video file into the same directory of media.qrc,still not work，with the output
"Loading  QVariant(QString, "qrc:/test.mp4")  ...
Failed to open [ ":/test.mp4" ]:  "No such file or directory""

Is there any other steps I forgot?
把test.mp4 文件放到media.qrc同一目录下，仍然无法播放。

**Comment by xbesung** [comment]
我试了一下，qrc文件大小应该是有限制的，你是不是放的mp4文件太大了？你看看你生成的qrc.exe有多大？我放了很大的mp4，编译的exe只有几百k，那肯定是打不开的，放10几M的mp4就可以打开。

**Comment by wangwenx190** [comment]
@ffzzc7 @xbesung 过大的资源无法打包进二进制文件中，你在测试这个功能之前应该先看看资源有没有成功打包进去。QMake使用`CONFIG += resources_big`启用大资源的支持。

**Comment by ffzzc7** [comment]
感谢两位@xbesung @wangwenx190 解答。
我测试了下，qrc添加小于1M的文件，可以正常播放；
使用CONFIG += resources_big后，可以播放之前无法播放的test文件，大概32M左右
