### ISSUE TITLE
avfilter parameter

### ISSUE THREAD

**Issue by itman2200** [wang-bin/QtAV#1303]

**Comment by itman2200** [comment]
I want to use ffmpeg filter in qt av.
eg. -af pan="stereo|c0=c0|c1=-1*c1" 
I use FFmpeg dict opt. ([link](https://github.com/wang-bin/QtAV/wiki/FFmpeg-dict-opt-in-QtAV))
But I did not work.

`QVariantHash avfmt_opt;
    mpPlayer->setOptionsForFormat(avfmt_opt);
    avfmt_opt["pan"]="'stereo|c0=c0|c1=-1*c1' -ac 1";
    QVariantHash opt;
    opt["avformat"] = avfmt_opt;
    mpPlayer->setOptionsForAudioCodec(opt);`
How can I solve it.

**Comment by itman2200** [comment]
I solved it.

**Comment by Fransferdy** [comment]
How did you solve it ?
