### ISSUE TITLE
编译不过，提示无法解析的外部符号 QLinkedListData

### ISSUE THREAD

**Issue by gimhol** [wang-bin/QtAV#1368]
各位好，在构建QtAV的过程中，提示有无法解析的外部符号 QLinkedListData，然后我发现其实只有src/subtitle/Subtitle.cpp中用到了QLinkedList。
　　然后我将其中的QLinkedList全部换成了QList，就可以顺利构建了。
　　但我不明白为什么会提示无法解析的外部符号。请问我就这么替换会不会有问题？或者我应该修改点其他什么地方，让QtAV顺利编译通过呢？
　　先在此谢谢各位阅读和解答。

----

### QtAV, Qt version and platform

- QtAV 1.13.0
- Qt 5.13.2 MSVC2017 32bit / Qt 5.13.0 MSVC2017 32bit 

### Reproduction steps

使用QtCreator构建QtAV项目。

### Expected behavior

应该编译通过并成功构建。

### Actual behavior

无法顺利编译，提示问题：
```
Subtitle.obj:-1: error: LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: __thiscall QLinkedListData::QLinkedListData(void)" (__imp_??0QLinkedListData@@QAE@XZ)，函数 "private: class QLinkedList<class QtAV::SubtitleFrame>::iterator __thiscall QLinkedList<class QtAV::SubtitleFrame>::detach_helper2(class QLinkedList<class QtAV::SubtitleFrame>::iterator)" (?detach_helper2@?$QLinkedList@VSubtitleFrame@QtAV@@@@AAE?
AViterator@1@V21@@Z) 中引用了该符号
```

**Comment by wangwenx190** [comment]
QLinkedList和QList都是Qt提供的容器，这两个东西的功能很相似，你这样替换是没有问题的。但是QLinkedList已经废弃很久了，不建议继续用了。Qt6都已经把这个类移除了。没法编译就不知道为什么了，按理说链接了QtCore就没问题。

**Comment by gimhol** [comment]
> QLinkedList和QList都是Qt提供的容器，这两个东西的功能很相似，你这样替换是没有问题的。但是QLinkedList已经废弃很久了，不建议继续用了。Qt6都已经把这个类移除了。没法编译就不知道为什么了，按理说链接了QtCore就没问题。

多谢解答，那这个项目的里面QLinkedList改成QList是不是更合适？

**Comment by wangwenx190** [comment]
> > QLinkedList和QList都是Qt提供的容器，这两个东西的功能很相似，你这样替换是没有问题的。但是QLinkedList已经废弃很久了，不建议继续用了。Qt6都已经把这个类移除了。没法编译就不知道为什么了，按理说链接了QtCore就没问题。
> 
> 多谢解答，那这个项目的里面QLinkedList改成QList是不是更合适？

QtAV的原作者已经不怎么维护这个仓库了，如果你想改进它，可以尝试自己提个pr

**Comment by litxiaoyao** [comment]
感谢，看来是新版本QLinkedList已经不能使用了
