### ISSUE TITLE
ZeroCopy断言

### ISSUE THREAD

**Issue by iGwkang** [wang-bin/QtAV#1380]
QtAV version: 1.13.0

系统：Windows 10
显卡：AMD 5700xt
CPU：i7-3770K@3.5GHz

代码路径：QtAV-1.13.0/examples/simpleplayer

增加了两行代码，设置0拷贝，使用DXVA解码器
![image](https://user-images.githubusercontent.com/35400668/126487710-26d87e03-475e-425f-81a8-c7e4509891cb.png)

结果：打开视频，导致断言
![image](https://user-images.githubusercontent.com/35400668/126487898-7e3995de-91cb-4a63-8811-03d663683ffa.png)

有什么解决办法？

我希望能够使用0拷贝降低CPU占用，并且使用DXVA提高解码性能，但是目前无法跑通

期待回复。

**Comment by wang-bin** [comment]
驱动不支持，没办法

**Comment by iGwkang** [comment]
> 驱动不支持，没办法

有什么办法能检测是否支持ZeroCopy吗？或者 如果不支持 选择OptimizedCopy模式

**Comment by wang-bin** [comment]
不支持的话你估计得改代码退回到其他方式

**Comment by iGwkang** [comment]
编译QTAV的时候没有拉取子模块，capi没有编译进去，导致egl_api没有使用，才导致的zerocopy失效。
