### ISSUE TITLE
QTAV不支持H265是FFmpeg库的问题吗？

### ISSUE THREAD

**Issue by liquanguo** [wang-bin/QtAV#1419]
我下载的最新版QTAV，发现播放H265无法开启硬解码，FFmpeg的版本为4.3.1
请问一下，这个问题怎么解决啊？

**Comment by wang-bin** [comment]
建议用新的项目 https://github.com/wang-bin/mdk-sdk

**Comment by liquanguo** [comment]
> 建议用新的项目 https://github.com/wang-bin/mdk-sdk

新项目这个怎么集成到QGraphicsView框架中的，有这个功能吗？

**Comment by wang-bin** [comment]
> > 建议用新的项目 https://github.com/wang-bin/mdk-sdk
> 
> 新项目这个怎么集成到QGraphicsView框架中的，有这个功能吗？

https://github.com/wang-bin/mdk-examples/tree/master/Qt/graphicsview

**Comment by liquanguo** [comment]
> > > 建议用新的项目 https://github.com/wang-bin/mdk-sdk
> > 
> > 
> > 新项目这个怎么集成到QGraphicsView框架中的，有这个功能吗？
> 
> https://github.com/wang-bin/mdk-examples/tree/master/Qt/graphicsview

谢谢！
