### ISSUE TITLE
How to use ffplay's "-vcodec h264_qsv" hardsolution option in QtAV

### ISSUE THREAD

**Issue by Mangomm** [wang-bin/QtAV#1423]
I use ffplay for hard decoding, command:
ffplay -x 640 -y 480 -vcodec h264_qsv 1.mp4
It can be hardsolved normally, but it fails in QtAV.

How do I do the same in QtAV?
I tried the options "FFmpeg QSV DXVA D3D11 CUDA" and checked in the task manager. "Video Decode" in the GPU was not used and was still 0.

![88418F4F-A693-48a7-9C79-E8087D334AAA](https://user-images.githubusercontent.com/58781546/217786835-7c58bcec-c34b-4e93-9ea9-45eb4c0ee26e.png)

**Comment by wang-bin** [comment]
try this https://github.com/wang-bin/mdk-sdk
