### ISSUE TITLE
No audio on iOS device using OpenAL

### ISSUE THREAD

**Issue by sladage** [wang-bin/QtAV#154]
```
OpenAL devices available: 0
AudioOutputOpenAL Opening default device: Default Audio Device
AudioOutputOpenAL creating context...
AudioOutputOpenAL Error: No OpenAL format available for audio data format flt stereo.
OpenAL audio format: 0x0 ch:2, sample format: flt
Failed to generate OpenAL buffers: Invalid Operation
```

**Comment by usbting** [comment]
is possible this player come to iOS app store or tvOS? or as beta testflight or via safari

**Comment by wang-bin** [comment]
@usbting Yes. But I have trouble in enrolling apple developer program.

**Comment by usbting** [comment]
@wang-bin 
cool hope in version 2.0 come to iOS app store or as beta version for testflight. then in the future for tvOS.

what is that problen in apple developer program? money?

**Comment by wang-bin** [comment]
@usbting I can't pay using my visa card. I don't know the reason. I contact apple but they don't know either. No problem to pay for google and windows store.

**Comment by usbting** [comment]
maybe not Accepted Activitation E-mail. forget? or create new apple id and test again. or say to apple hotline why not working ;)

**Comment by wang-bin** [comment]
@usbting I'm joined developer program using my friend's card. iOS support will be better in the next release. And I will publish my player to app store.
Did you try QtAV player in android and windows store?

**Comment by usbting** [comment]
@wang-bin 
QtAV on Android not good. Seeking is slow, UI not optimized for many resolution from android devices.

Windows/OSX no test. maybe in the next weeks ;)

Only iOS missing

**Comment by wang-bin** [comment]
Now I can run on iphone. Video rendering is good. But no sound. I have no idea.

**Comment by wang-bin** [comment]
Seems openal is deprecated https://forums.developer.apple.com/thread/7081 Even the official example https://developer.apple.com/library/ios/samplecode/oalTouch/Introduction/Intro.html#//apple_ref/doc/uid/TP40016102-Intro-DontLinkElementID_2 does not work on ios9.2

**Comment by wang-bin** [comment]
OpenAL works fine. I muted my device so I heard nothing. I also add audiotoolbox support for ios and osx.

**Comment by wang-bin** [comment]
currently audiotoolbox is the default backend because it supports more sample formats. openal can not even support float samples

**Comment by usbting** [comment]
@wang-bin 
cool. when in app-store? use current 3rd library(update pls) . can you add avfoundation for smooth seeking from mp4 files? iOS photos app it supports. thxx

**Comment by wang-bin** [comment]
Not sure. I find that on iOS I can't open external videos from my player. It's a big problem.
apple's smooth seeking is impressive. What avfoundation class to use?

**Comment by usbting** [comment]
then create local library. the user import the video files via itunes file sharing. and support iOS open in share sheet menu.
