### ISSUE TITLE
Find stream info only for MPEG1/MPEG2 

### ISSUE THREAD

**Issue by cedric-rtd** [wang-bin/QtAV#162]
Hi,

Maybe we can filter the call of the avformat_find_stream_info function (AVDemuxer.cpp:491) only for the streams we need to get the information, such as MPEG1/MPEG2.

The starting time is much faster with this modificiation. I don't know if this causes other issues (I guess no).

Below is the content of the AVDemuxer.patch I've just made:

https://gist.github.com/cedric-rtd/9247244

Maybe we can filter on other kind of streams.

BR,
Cedric

**Comment by wang-bin** [comment]
can not reproduce it,
