### ISSUE TITLE
Delay while playing

### ISSUE THREAD

**Issue by cascarpato** [wang-bin/QtAV#183]
Hi all,
i have noted that if i use QtAV to play rtsp stream from a camera where audio is disabled and for this QtAV use ExternalClock, the video accumulate a small delay that become also hours  after a day of continues playing. I  compared with ffplay and no delay arise. 
This is ffplay command:
ffplay "rtsp://admin:admin@10.10.10.104/cam/realmonitor?channel=1&subtype=1" -rtsp_transport tcp -probesize 2048

ps: last version of QtAV tested

**Comment by wang-bin** [comment]
try latest release
