### ISSUE TITLE
one core dump problem.

### ISSUE THREAD

**Issue by kingctan** [wang-bin/QtAV#185]
After I compile the QTAV project,I run player to watch a rtmp video,and the core dump out. and another linux I compile and run normally. please see the log. thanks.
kingctan@kingctan-ThinkPad-T61:~/projects/build-LinuxKTV-Desktop_Qt_5_2_1_GCC_32bit-Debug/bin$ ./player rtmp://192.168.1.104:1936/myapp/out2.mp4
__init_AudioResamplerFF id=0
instance = (nil)
Singleton 0x98b3e58 created...
instance = 0x98b3e58
Build with libavcodec-53.61.100
Build with libavformat-53.32.100
Build with libavutil-51.35.100
Build with libswscale-2.1.100
Build with libswresample-0.6.100
__init_ImageConverterFF id=1
instance = (nil)
Singleton 0x98b3f08 created...
instance = 0x98b3f08
__init_VideoRendererWidget id=2
instance = (nil)
Singleton 0x98b4030 created...
instance = 0x98b4030
__init_VideoRendererGraphicsItem id=3
instance = 0x98b4030
instance = 0x98b4030
__init_VideoRendererGLWidget id=4
instance = 0x98b4030
instance = 0x98b4030
__init_VideoDecoderFFmpeg id=1
instance = (nil)
Singleton 0x98b41c8 created...
instance = 0x98b41c8
loading qm:  "/home/kingctan/projects/build-LinuxKTV-Desktop_Qt_5_2_1_GCC_32bit-Debug/bin/i18n/QtAV_en_US" 
loading qm:  ":/i18n/QtAV_en_US" 
loading qm:  "/home/kingctan/projects/build-LinuxKTV-Desktop_Qt_5_2_1_GCC_32bit-Debug/bin/i18n/player_en_US" 
loading qm:  ":/i18n/player_en_US" 
loading qm:  "/home/kingctan/projects/build-LinuxKTV-Desktop_Qt_5_2_1_GCC_32bit-Debug/bin/i18n/qt_en_US" 
loading qm:  ":/i18n/qt_en_US" 
Debug: exe: ./player
Debug: vo: 
instance = 0x98b4030
Debug: 35 x 140
instance = 0x98b41c8
instance = 0x98b41c8
instance = 0x98b41c8
get id of 'FFmpeg'instance = 0x98b41c8
get id of 'FFmpeg'instance = 0x98b41c8
instance = 0x98b41c8
instance = 0x98b41c8
instance = 0x98b41c8
Debug: AO>>>>>>>>>>> portaudio
Debug: QtAV 1.3.2(Mar 30 2014, 14:25:35)
A media playing library base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Copyright (C) 2012-2014 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Shanghai University->S3 Graphics, Shanghai, China
Donate: http://wang-bin.github.io/QtAV#donate
Source: https://github.com/wang-bin/QtAV
Downloads: https://sourceforge.net/projects/qtav
instance = 0x98b3f08
Debug: player created
Debug: >>>>>>>>>>setRenderer
Debug: out rect: 0.000000 0x0 ==>
Debug: 0.000000 0x320 <<<<<<<<
Warning: Not implemented
Warning: Not implemented
Warning: Not implemented
Warning: Not implemented
Debug: loading: rtmp://192.168.1.104:1936/myapp/out2.mp4 ...
Debug: av_register_all and avformat_network_init
Debug: all closed and reseted
Debug: avformat_open_input: format_context:'0x9bc86c0', url:'rtmp://192.168.1.104:1936/myapp/out2.mp4'...
Segmentation fault (core dumped)

**Comment by wang-bin** [comment]
release build should work without crash
