### ISSUE TITLE
播放FLAC文件一开始存在撕裂声

### ISSUE THREAD

**Issue by Harinlen** [wang-bin/QtAV#217]
播放其它类型的音频文件并不存在这个问题，只有在播放FLAC文件的时候，最开始会存在一定时间的撕裂声，会持续不到一秒左右。
不一定能重现，因为有时候播放就不会出现这个问题。
多次setFilePath有可能触发。
输出大量的：
{FFmpeg} sample/frame number mismatch in adjacent frames
{FFmpeg} broken stream, invalid padding
{FFmpeg} invalid sample size code (7)
{FFmpeg} invalid channel mode: 15。
疑似上一次的Cache没有清理造成的。

**Comment by wang-bin** [comment]
貌似没有了，不知怎么修复的 ＝＝+
