### ISSUE TITLE
Mac Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by weewillie** [wang-bin/QtAV#221]
On Mac OS X 10.9.3, with Qt Creator 3.1.1 and Qt 5.2.1
with ffmpeg v. 2.2.2 and the portaudio-v19_mac.tar.bz2 libs from your sourceforge page,

I get the following error:

```
clang: warning: argument unused during compilation: '-pg'
Undefined symbols for architecture x86_64:
  "_av_buffer_create", referenced from:
      QtAV::ffmpeg_get_va_buffer2(AVCodecContext*, AVFrame*, int) in VideoDecoderFFmpegHW.o
  "_av_pix_fmt_count_planes", referenced from:
      QtAV::VideoFormatPrivate::init() in VideoFormat.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../lib_mac_x86_64_llvm/libQtAV_debug.1.3.4.dylib] Error 1
make: *** [sub-src-libQtAV-pro-make_first] Error 2
05:11:34: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project QtAV (kit: Desktop Qt 5.3.0 clang 64bit)
When executing step 'Make'
```

All of my environment vars are set correctly, and my ffmpeg libs pass all build tests.

In fact, some of the ffmpeg build tests use calls to those functions succussfully.

I can also see that the symbols are in the libs.

Are there any special flags for successfully QtAV building on Mac?

**Comment by cgilles** [comment]
Same problem here, under MacOS 10.12.1 and ffmpeg from macports :

ffmpeg version 3.2.git Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --prefix=/opt/digikam --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-libtheora --enable-libschroedinger --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libsoxr --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-libxcb --disable-libxcb-shm --disable-libxcb-xfixes --disable-indev=jack --disable-outdev=xv --enable-audiotoolbox --enable-sdl2 --mandir=/opt/digikam/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --enable-vda --enable-videotoolbox --arch=x86_64 --enable-yasm --enable-libx265 --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libsmbclient --enable-nonfree --enable-libfdk-aac
  libavutil      55. 41.101 / 55. 41.101
  libavcodec     57. 66.109 / 57. 66.109
  libavformat    57. 58.101 / 57. 58.101
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 68.100 /  6. 68.100
  libavresample   3.  2.  0 /  3.  2.  0
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100

It come from QtAV 1.11.0 : 

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names -stdlib=libc++ '-Wl,-rpath,/Users/gilles/Devel/GIT/5.x/project/bundles/macports/temp.build/ext_qtav/ext_qtav-prefix/src/ext_qtav/lib_osx_x86_64_llvm' '-Wl,-rpath,@loader_path/../Frameworks' '-Wl,-rpath,@executable_path/../Frameworks' -Wl,-
syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -single_module -dynamiclib -compatibility_version 1.11 -current_version   1.11.0 -Wl,-install_name,@rpath/QtAV.framework/Versions/1/QtAV -o QtAV ../.obj/QtAV_osx_x86_64_llvm/CopyFrame_SSE2.o ../.obj/QtAV_osx_x86_64_llvm/uchardet.o ../.obj/QtAV_osx_x86_64_llvm/nsEUCTWProber.o ../.obj/QtAV_osx_x86_64_llvm/LangCyrillicModel.o ../.obj/QtAV_osx_x86_64_llvm/nsSBCharSetProber.o ../.obj/QtAV_osx_x86_64_llvm/CharDistribution.o ../.obj/QtAV_osx_x86_64_llvm/nsLatin1Prober.o ../.obj/QtAV_osx_x86_64_llvm/nsEscSM.o ../.obj/QtAV_osx_x86_64_llvm/nsUTF8Prober.o ../.obj/QtAV_osx_x86_64_llvm/nsBig5Prober.o ../.obj/QtAV_osx_x86_64_llvm/LangBulgarianModel.o ../.obj/QtAV_osx_x86_64_llvm/nsGB2312Prober.o ../.obj/QtAV_osx_x86_64_llvm/nsCharSetProber.o ../.obj/QtAV_osx_x86_64_llvm/nsEscCharsetProber.o ../.obj/QtAV_osx_x86_64_llvm/nsEUCKRProber.o ../.obj/QtAV_osx_x86_64_llvm/nsEUCJPProber.o ../.obj/QtAV_osx_x86_64_llvm/nsSJISProber.o ../.obj/QtAV_osx_x86_64_llvm/nsMBCSSM.o ../.obj/QtAV_osx_x86_64_llvm/nsHebrewProber.o ../.obj/QtAV_osx_x86_64_llvm/nsUniversalDetector.o ../.obj/QtAV_osx_x86_64_llvm/nsSBCSGroupProber.o ../.obj/QtAV_osx_x86_64_llvm/nsMBCSGroupProber.o ../.obj/QtAV_osx_x86_64_llvm/LangThaiModel.o ../.obj/QtAV_osx_x86_64_llvm/LangHebrewModel.o ../.obj/QtAV_osx_x86_64_llvm/JpCntx.o ../.obj/QtAV_osx_x86_64_llvm/LangHungarianModel.o ../.obj/QtAV_osx_x86_64_llvm/LangGreekModel.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutputAudioToolbox.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutputOpenAL.o ../.obj/QtAV_osx_x86_64_llvm/openal_api.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderCUDA.o ../.obj/QtAV_osx_x86_64_llvm/SurfaceInteropCUDA.o ../.obj/QtAV_osx_x86_64_llvm/cuda_api.o ../.obj/QtAV_osx_x86_64_llvm/SurfaceInteropCV.o ../.obj/QtAV_osx_x86_64_llvm/SurfaceInteropIOSurface.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderVDA.o ../.obj/QtAV_osx_x86_64_llvm/GLSLFilter.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLRendererBase.o ../.obj/QtAV_osx_x86_64_llvm/gl_api.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLTypes.o ../.obj/QtAV_osx_x86_64_llvm/Geometry.o ../.obj/QtAV_osx_x86_64_llvm/GeometryRenderer.o ../.obj/QtAV_osx_x86_64_llvm/SubImagesGeometry.o ../.obj/QtAV_osx_x86_64_llvm/SubImagesRenderer.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLVideo.o ../.obj/QtAV_osx_x86_64_llvm/VideoShaderObject.o ../.obj/QtAV_osx_x86_64_llvm/VideoShader.o ../.obj/QtAV_osx_x86_64_llvm/ShaderManager.o ../.obj/QtAV_osx_x86_64_llvm/ConvolutionShader.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLHelper.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLWindowRenderer.o ../.obj/QtAV_osx_x86_64_llvm/AVCompat.o ../.obj/QtAV_osx_x86_64_llvm/QtAV_Global.o ../.obj/QtAV_osx_x86_64_llvm/SubImage.o ../.obj/QtAV_osx_x86_64_llvm/CharsetDetector.o ../.obj/QtAV_osx_x86_64_llvm/PlainText.o ../.obj/QtAV_osx_x86_64_llvm/PlayerSubtitle.o ../.obj/QtAV_osx_x86_64_llvm/Subtitle.o ../.obj/QtAV_osx_x86_64_llvm/SubtitleProcessor.o ../.obj/QtAV_osx_x86_64_llvm/SubtitleProcessorFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/GPUMemCopy.o ../.obj/QtAV_osx_x86_64_llvm/Logger.o ../.obj/QtAV_osx_x86_64_llvm/AudioThread.o ../.obj/QtAV_osx_x86_64_llvm/internal.o ../.obj/QtAV_osx_x86_64_llvm/AVThread.o ../.obj/QtAV_osx_x86_64_llvm/AudioFormat.o ../.obj/QtAV_osx_x86_64_llvm/AudioFrame.o ../.obj/QtAV_osx_x86_64_llvm/AudioResampler.o ../.obj/QtAV_osx_x86_64_llvm/AudioResamplerTemplate.o ../.obj/QtAV_osx_x86_64_llvm/AudioDecoder.o ../.obj/QtAV_osx_x86_64_llvm/AudioDecoderFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/AudioEncoder.o ../.obj/QtAV_osx_x86_64_llvm/AudioEncoderFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/AVDecoder.o ../.obj/QtAV_osx_x86_64_llvm/AVEncoder.o ../.obj/QtAV_osx_x86_64_llvm/AVMuxer.o ../.obj/QtAV_osx_x86_64_llvm/AVDemuxer.o ../.obj/QtAV_osx_x86_64_llvm/AVDemuxThread.o ../.obj/QtAV_osx_x86_64_llvm/ColorTransform.o ../.obj/QtAV_osx_x86_64_llvm/Frame.o ../.obj/QtAV_osx_x86_64_llvm/FrameReader.o ../.obj/QtAV_osx_x86_64_llvm/Filter.o ../.obj/QtAV_osx_x86_64_llvm/FilterContext.o ../.obj/QtAV_osx_x86_64_llvm/FilterManager.o ../.obj/QtAV_osx_x86_64_llvm/LibAVFilter.o ../.obj/QtAV_osx_x86_64_llvm/SubtitleFilter.o ../.obj/QtAV_osx_x86_64_llvm/EncodeFilter.o ../.obj/QtAV_osx_x86_64_llvm/ImageConverter.o ../.obj/QtAV_osx_x86_64_llvm/ImageConverterFF.o ../.obj/QtAV_osx_x86_64_llvm/Packet.o ../.obj/QtAV_osx_x86_64_llvm/PacketBuffer.o ../.obj/QtAV_osx_x86_64_llvm/AVError.o ../.obj/QtAV_osx_x86_64_llvm/AVPlayer.o ../.obj/QtAV_osx_x86_64_llvm/AVPlayerPrivate.o ../.obj/QtAV_osx_x86_64_llvm/AVTranscoder.o ../.obj/QtAV_osx_x86_64_llvm/AVClock.o ../.obj/QtAV_osx_x86_64_llvm/VideoCapture.o ../.obj/QtAV_osx_x86_64_llvm/VideoFormat.o ../.obj/QtAV_osx_x86_64_llvm/VideoFrame.o ../.obj/QtAV_osx_x86_64_llvm/MediaIO.o ../.obj/QtAV_osx_x86_64_llvm/QIODeviceIO.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutput.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutputBackend.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutputNull.o ../.obj/QtAV_osx_x86_64_llvm/VideoRenderer.o ../.obj/QtAV_osx_x86_64_llvm/VideoOutput.o ../.obj/QtAV_osx_x86_64_llvm/QPainterRenderer.o ../.obj/QtAV_osx_x86_64_llvm/AVOutput.o ../.obj/QtAV_osx_x86_64_llvm/OutputSet.o ../.obj/QtAV_osx_x86_64_llvm/Statistics.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoder.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderFFmpegBase.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderFFmpegHW.o ../.obj/QtAV_osx_x86_64_llvm/VideoEncoder.o ../.obj/QtAV_osx_x86_64_llvm/VideoEncoderFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/VideoThread.o ../.obj/QtAV_osx_x86_64_llvm/VideoFrameExtractor.o ../.obj/QtAV_osx_x86_64_llvm/qrc_QtAV.o ../.obj/QtAV_osx_x86_64_llvm/qrc_shaders.o ../.obj/QtAV_osx_x86_64_llvm/moc_ShaderManager.o ../.obj/QtAV_osx_x86_64_llvm/moc_GLSLFilter.o ../.obj/QtAV_osx_x86_64_llvm/moc_OpenGLVideo.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoShaderObject.o ../.obj/QtAV_osx_x86_64_llvm/moc_OpenGLWindowRenderer.o ../.obj/QtAV_osx_x86_64_llvm/moc_AudioEncoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_AudioOutput.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVDecoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVEncoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVDemuxer.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVMuxer.o ../.obj/QtAV_osx_x86_64_llvm/moc_Filter.o ../.obj/QtAV_osx_x86_64_llvm/moc_LibAVFilter.o ../.obj/QtAV_osx_x86_64_llvm/moc_EncodeFilter.o ../.obj/QtAV_osx_x86_64_llvm/moc_FrameReader.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVPlayer.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVTranscoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoCapture.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoOutput.o ../.obj/QtAV_osx_x86_64_llvm/moc_MediaIO.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVClock.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoEncoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoFrameExtractor.o ../.obj/QtAV_osx_x86_64_llvm/moc_Subtitle.o ../.obj/QtAV_osx_x86_64_llvm/moc_SubtitleFilter.o ../.obj/QtAV_osx_x86_64_llvm/moc_PlayerSubtitle.o ../.obj/QtAV_osx_x86_64_llvm/moc_AudioOutputBackend.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVDemuxThread.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVThread.o ../.obj/QtAV_osx_x86_64_llvm/moc_AudioThread.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoThread.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoDecoderFFmpegHW.o ../.obj/QtAV_osx_x86_64_llvm/moc_OutputSet.o  -F/opt/digikam/libexec/qt5/lib -L/opt/digikam/lib/ -lavcodec -lavformat -lswscale -lavutil -framework AudioToolbox -framework IOSurface -framework CoreVideo -framework CoreFoundation -framework VideoDecodeAcceleration -L/opt/digikam/libexec/qt5/lib -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL  
Undefined symbols for architecture x86_64:
  "_ff_vda_create_decoder", referenced from:
      QtAV::VideoDecoderVDAPrivate::setup(AVCodecContext*) in VideoDecoderVDA.o
  "_ff_vda_destroy_decoder", referenced from:
      QtAV::VideoDecoderVDAPrivate::setup(AVCodecContext*) in VideoDecoderVDA.o
      QtAV::VideoDecoderVDAPrivate::close() in VideoDecoderVDA.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../lib_osx_x86_64_llvm/QtAV.framework/QtAV] Error 1
make: *** [sub-src-libQtAV-pro-make_first] Error 2

**Comment by wang-bin** [comment]
@cgilles vda api changes in ffmpeg and i haven't update the code. You can remove the line `CONFIG += config_vda` in src/libQtAV.pro

**Comment by cgilles** [comment]
Wang,

The line is commented in src/libQtAV.pro. The previous error disappear, but now, another problem appear : 

# make
cd src/ && ( test -e Makefile.libQtAV || /opt/digikam/libexec/qt5/bin/qmake /Users/gilles/Devel/GIT/5.x/project/bundles/macports/temp.build/ext_qtav/ext_qtav-prefix/src/ext_qtav/src/libQtAV.pro PREFIX=/opt/digikam -o Makefile.libQtAV ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.libQtAV 
rm -f QtAV QtAV.framework/QtAV ../lib_osx_x86_64_llvm/QtAV.framework/QtAV
rm: QtAV: is a directory
make[1]: [../lib_osx_x86_64_llvm/QtAV.framework/QtAV] Error 1 (ignored)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names -stdlib=libc++ '-Wl,-rpath,/Users/gilles/Devel/GIT/5.x/project/bundles/macports/temp.build/ext_qtav/ext_qtav-prefix/src/ext_qtav/lib_osx_x86_64_llvm' '-Wl,-rpath,@loader_path/../Frameworks' '-Wl,-rpath,@executable_path/../Frameworks' -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -single_module -dynamiclib -compatibility_version	1.11 -current_version	1.11.0 -Wl,-install_name,@rpath/QtAV.framework/Versions/1/QtAV -o QtAV ../.obj/QtAV_osx_x86_64_llvm/CopyFrame_SSE2.o ../.obj/QtAV_osx_x86_64_llvm/uchardet.o ../.obj/QtAV_osx_x86_64_llvm/nsEUCTWProber.o ../.obj/QtAV_osx_x86_64_llvm/LangCyrillicModel.o ../.obj/QtAV_osx_x86_64_llvm/nsSBCharSetProber.o ../.obj/QtAV_osx_x86_64_llvm/CharDistribution.o ../.obj/QtAV_osx_x86_64_llvm/nsLatin1Prober.o ../.obj/QtAV_osx_x86_64_llvm/nsEscSM.o ../.obj/QtAV_osx_x86_64_llvm/nsUTF8Prober.o ../.obj/QtAV_osx_x86_64_llvm/nsBig5Prober.o ../.obj/QtAV_osx_x86_64_llvm/LangBulgarianModel.o ../.obj/QtAV_osx_x86_64_llvm/nsGB2312Prober.o ../.obj/QtAV_osx_x86_64_llvm/nsCharSetProber.o ../.obj/QtAV_osx_x86_64_llvm/nsEscCharsetProber.o ../.obj/QtAV_osx_x86_64_llvm/nsEUCKRProber.o ../.obj/QtAV_osx_x86_64_llvm/nsEUCJPProber.o ../.obj/QtAV_osx_x86_64_llvm/nsSJISProber.o ../.obj/QtAV_osx_x86_64_llvm/nsMBCSSM.o ../.obj/QtAV_osx_x86_64_llvm/nsHebrewProber.o ../.obj/QtAV_osx_x86_64_llvm/nsUniversalDetector.o ../.obj/QtAV_osx_x86_64_llvm/nsSBCSGroupProber.o ../.obj/QtAV_osx_x86_64_llvm/nsMBCSGroupProber.o ../.obj/QtAV_osx_x86_64_llvm/LangThaiModel.o ../.obj/QtAV_osx_x86_64_llvm/LangHebrewModel.o ../.obj/QtAV_osx_x86_64_llvm/JpCntx.o ../.obj/QtAV_osx_x86_64_llvm/LangHungarianModel.o ../.obj/QtAV_osx_x86_64_llvm/LangGreekModel.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutputAudioToolbox.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutputOpenAL.o ../.obj/QtAV_osx_x86_64_llvm/openal_api.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderCUDA.o ../.obj/QtAV_osx_x86_64_llvm/SurfaceInteropCUDA.o ../.obj/QtAV_osx_x86_64_llvm/cuda_api.o ../.obj/QtAV_osx_x86_64_llvm/SurfaceInteropCV.o ../.obj/QtAV_osx_x86_64_llvm/SurfaceInteropIOSurface.o ../.obj/QtAV_osx_x86_64_llvm/GLSLFilter.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLRendererBase.o ../.obj/QtAV_osx_x86_64_llvm/gl_api.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLTypes.o ../.obj/QtAV_osx_x86_64_llvm/Geometry.o ../.obj/QtAV_osx_x86_64_llvm/GeometryRenderer.o ../.obj/QtAV_osx_x86_64_llvm/SubImagesGeometry.o ../.obj/QtAV_osx_x86_64_llvm/SubImagesRenderer.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLVideo.o ../.obj/QtAV_osx_x86_64_llvm/VideoShaderObject.o ../.obj/QtAV_osx_x86_64_llvm/VideoShader.o ../.obj/QtAV_osx_x86_64_llvm/ShaderManager.o ../.obj/QtAV_osx_x86_64_llvm/ConvolutionShader.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLHelper.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLWindowRenderer.o ../.obj/QtAV_osx_x86_64_llvm/AVCompat.o ../.obj/QtAV_osx_x86_64_llvm/QtAV_Global.o ../.obj/QtAV_osx_x86_64_llvm/SubImage.o ../.obj/QtAV_osx_x86_64_llvm/CharsetDetector.o ../.obj/QtAV_osx_x86_64_llvm/PlainText.o ../.obj/QtAV_osx_x86_64_llvm/PlayerSubtitle.o ../.obj/QtAV_osx_x86_64_llvm/Subtitle.o ../.obj/QtAV_osx_x86_64_llvm/SubtitleProcessor.o ../.obj/QtAV_osx_x86_64_llvm/SubtitleProcessorFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/GPUMemCopy.o ../.obj/QtAV_osx_x86_64_llvm/Logger.o ../.obj/QtAV_osx_x86_64_llvm/AudioThread.o ../.obj/QtAV_osx_x86_64_llvm/internal.o ../.obj/QtAV_osx_x86_64_llvm/AVThread.o ../.obj/QtAV_osx_x86_64_llvm/AudioFormat.o ../.obj/QtAV_osx_x86_64_llvm/AudioFrame.o ../.obj/QtAV_osx_x86_64_llvm/AudioResampler.o ../.obj/QtAV_osx_x86_64_llvm/AudioResamplerTemplate.o ../.obj/QtAV_osx_x86_64_llvm/AudioDecoder.o ../.obj/QtAV_osx_x86_64_llvm/AudioDecoderFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/AudioEncoder.o ../.obj/QtAV_osx_x86_64_llvm/AudioEncoderFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/AVDecoder.o ../.obj/QtAV_osx_x86_64_llvm/AVEncoder.o ../.obj/QtAV_osx_x86_64_llvm/AVMuxer.o ../.obj/QtAV_osx_x86_64_llvm/AVDemuxer.o ../.obj/QtAV_osx_x86_64_llvm/AVDemuxThread.o ../.obj/QtAV_osx_x86_64_llvm/ColorTransform.o ../.obj/QtAV_osx_x86_64_llvm/Frame.o ../.obj/QtAV_osx_x86_64_llvm/FrameReader.o ../.obj/QtAV_osx_x86_64_llvm/Filter.o ../.obj/QtAV_osx_x86_64_llvm/FilterContext.o ../.obj/QtAV_osx_x86_64_llvm/FilterManager.o ../.obj/QtAV_osx_x86_64_llvm/LibAVFilter.o ../.obj/QtAV_osx_x86_64_llvm/SubtitleFilter.o ../.obj/QtAV_osx_x86_64_llvm/EncodeFilter.o ../.obj/QtAV_osx_x86_64_llvm/ImageConverter.o ../.obj/QtAV_osx_x86_64_llvm/ImageConverterFF.o ../.obj/QtAV_osx_x86_64_llvm/Packet.o ../.obj/QtAV_osx_x86_64_llvm/PacketBuffer.o ../.obj/QtAV_osx_x86_64_llvm/AVError.o ../.obj/QtAV_osx_x86_64_llvm/AVPlayer.o ../.obj/QtAV_osx_x86_64_llvm/AVPlayerPrivate.o ../.obj/QtAV_osx_x86_64_llvm/AVTranscoder.o ../.obj/QtAV_osx_x86_64_llvm/AVClock.o ../.obj/QtAV_osx_x86_64_llvm/VideoCapture.o ../.obj/QtAV_osx_x86_64_llvm/VideoFormat.o ../.obj/QtAV_osx_x86_64_llvm/VideoFrame.o ../.obj/QtAV_osx_x86_64_llvm/MediaIO.o ../.obj/QtAV_osx_x86_64_llvm/QIODeviceIO.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutput.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutputBackend.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutputNull.o ../.obj/QtAV_osx_x86_64_llvm/VideoRenderer.o ../.obj/QtAV_osx_x86_64_llvm/VideoOutput.o ../.obj/QtAV_osx_x86_64_llvm/QPainterRenderer.o ../.obj/QtAV_osx_x86_64_llvm/AVOutput.o ../.obj/QtAV_osx_x86_64_llvm/OutputSet.o ../.obj/QtAV_osx_x86_64_llvm/Statistics.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoder.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderFFmpegBase.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderFFmpegHW.o ../.obj/QtAV_osx_x86_64_llvm/VideoEncoder.o ../.obj/QtAV_osx_x86_64_llvm/VideoEncoderFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/VideoThread.o ../.obj/QtAV_osx_x86_64_llvm/VideoFrameExtractor.o ../.obj/QtAV_osx_x86_64_llvm/qrc_QtAV.o ../.obj/QtAV_osx_x86_64_llvm/qrc_shaders.o ../.obj/QtAV_osx_x86_64_llvm/moc_ShaderManager.o ../.obj/QtAV_osx_x86_64_llvm/moc_GLSLFilter.o ../.obj/QtAV_osx_x86_64_llvm/moc_OpenGLVideo.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoShaderObject.o ../.obj/QtAV_osx_x86_64_llvm/moc_OpenGLWindowRenderer.o ../.obj/QtAV_osx_x86_64_llvm/moc_AudioEncoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_AudioOutput.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVDecoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVEncoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVDemuxer.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVMuxer.o ../.obj/QtAV_osx_x86_64_llvm/moc_Filter.o ../.obj/QtAV_osx_x86_64_llvm/moc_LibAVFilter.o ../.obj/QtAV_osx_x86_64_llvm/moc_EncodeFilter.o ../.obj/QtAV_osx_x86_64_llvm/moc_FrameReader.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVPlayer.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVTranscoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoCapture.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoOutput.o ../.obj/QtAV_osx_x86_64_llvm/moc_MediaIO.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVClock.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoEncoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoFrameExtractor.o ../.obj/QtAV_osx_x86_64_llvm/moc_Subtitle.o ../.obj/QtAV_osx_x86_64_llvm/moc_SubtitleFilter.o ../.obj/QtAV_osx_x86_64_llvm/moc_PlayerSubtitle.o ../.obj/QtAV_osx_x86_64_llvm/moc_AudioOutputBackend.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVDemuxThread.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVThread.o ../.obj/QtAV_osx_x86_64_llvm/moc_AudioThread.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoThread.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoDecoderFFmpegHW.o ../.obj/QtAV_osx_x86_64_llvm/moc_OutputSet.o  -F/opt/digikam/libexec/qt5/lib -L/opt/digikam/lib/ -lavcodec -lavformat -lswscale -lavutil -framework AudioToolbox -framework IOSurface -framework CoreVideo -framework CoreFoundation -L/opt/digikam/libexec/qt5/lib -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL  
ld: can't open output file for writing: QtAV, errno=21 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../lib_osx_x86_64_llvm/QtAV.framework/QtAV] Error 1
make: *** [sub-src-libQtAV-pro-make_first] Error 2

**Comment by wang-bin** [comment]
You can't build in qtav root dir on mac because the compiler try to generate the QtAV framework file in src with the same name as src/QtAV directory. You can create a directory in any place and build there. Delete .qmake.cache and .qmake.stash first.

**Comment by cgilles** [comment]
How to process exactly ?

I customized BUILD_DIR = build in .qmake.conf. bin files are properly generated in this directory, but error still here : 

rm: QtAV: is a directory
ld: can't open output file for writing: QtAV, errno=21 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [build/lib_osx_x86_64_llvm/QtAV.framework/QtAV] Error 1
make[4]: *** [sub-src-libQtAV-pro-make_first] Error 2
ext_qtav/CMakeFiles/ext_qtav.dir/build.make:110 : la recette pour la cible « ext_qtav/ext_qtav-prefix/src/ext_qtav-stamp/ext_qtav-build » a échouée
gmake[3]: *** [ext_qtav/ext_qtav-prefix/src/ext_qtav-stamp/ext_qtav-build] Erreur 2
CMakeFiles/Makefile2:865 : la recette pour la cible « ext_qtav/CMakeFiles/ext_qtav.dir/all » a échouée
gmake[2]: *** [ext_qtav/CMakeFiles/ext_qtav.dir/all] Erreur 2
CMakeFiles/Makefile2:877 : la recette pour la cible « ext_qtav/CMakeFiles/ext_qtav.dir/rule » a échouée
gmake[1]: *** [ext_qtav/CMakeFiles/ext_qtav.dir/rule] Erreur 2
Makefile:313 : la recette pour la cible « ext_qtav » a échouée
gmake: *** [ext_qtav] Erreur 2

Gilles

**Comment by cgilles** [comment]
Ok i found the response myself on wiki page

https://github.com/wang-bin/QtAV/wiki/Build-QtAV

**Comment by wang-bin** [comment]
mkdir -p build_dir
cd build_dir
qmake path_of_QtAV.pro
make
