### ISSUE TITLE
Qt 1.3.4. Slow playback of wmv files compare to Windows Media Player

### ISSUE THREAD

**Issue by MartinSchulze1** [wang-bin/QtAV#238]
Hello, i noticed qtav does not play some wmv files slower then WMP.
about 15% slower ( and choppy video playback )
When you take a sample which comes with the windows7 installation, such as wildlife.wmv,
it plays correct.

but when using a different one with better advanced audio it becomes slow.
i guess its an audio problem? portaudio?

i was using qml-player. ( simpleplayer does only play green :-) )

--------------------- fileinfo from mediainfo
General
Complete name                            : C:\temp\wmv\Amazon_720.wmv
Format                                   : Windows Media
File size                                : 79.4 MiB
Duration                                 : 1mn 42s
Overall bit rate mode                    : Constant
Overall bit rate                         : 6 518 Kbps
Maximum Overall bit rate                 : 6 410 Kbps
Encoded date                             : UTC 2003-11-21 03:54:41.802

Video
ID                                       : 2
Format                                   : VC-1
Format profile                           : MP@HL
Codec ID                                 : WMV3
Codec ID/Info                            : Windows Media Video 9
Codec ID/Hint                            : WMV3
Description of the codec                 : Windows Media Video 9 - Professional
Duration                                 : 1mn 42s
Bit rate mode                            : Constant
Bit rate                                 : 6 000 Kbps
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 23.976 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.272
Stream size                              : 73.1 MiB (92%)
Language                                 : English (US)

Audio
ID                                       : 1
Format                                   : WMA
Format profile                           : Pro
Codec ID                                 : 162
Codec ID/Info                            : Windows Media Audio
Description of the codec                 : Windows Media Audio 9 Professional - 384 kbps, 48 kHz, 5.1 channel 24 bit 1-pass CBR
Duration                                 : 1mn 42s
Bit rate mode                            : Constant
Bit rate                                 : 384 Kbps
Channel(s)                               : 6 channels
Sampling rate                            : 48.0 KHz
Bit depth                                : 24 bits
Stream size                              : 4.68 MiB (6%)
Language                                 : English (US)

**Comment by wang-bin** [comment]
audio clock time computation was wrong. fixed in f50fa77
