### ISSUE TITLE
MediaStatus::BufferedMedia is not emitted

### ISSUE THREAD

**Issue by christau** [wang-bin/QtAV#244]
Hello,
I just came across this problem when trying wait until the movie is preloaded.
In line 65 of [AVDemuxer.cpp](https://github.com/wang-bin/QtAV/blob/master/src/AVDemuxer.cpp#L65) i see it commented. So it seems prepared to do this. But is this working if i uncomment the line or is there any other technique i have to use?
Thanks in advance.
-chris-

**Comment by wang-bin** [comment]
Supported by latest code. Also the coming 1.6.0 release
