### ISSUE TITLE
 Unknown module(s) in QT: av

### ISSUE THREAD

**Issue by eliezerreis** [wang-bin/QtAV#259]
How can I use the module av inside my qt creator 5.3.0 on my MAC OS? I follow exactly what is described on QtAV wiki. Everything compile without error but when I try to use on my project (QT += av) the error appears.

 Unknown module(s) in QT: av

What can I do?

**Comment by jesensilence** [comment]
nice job！
王老板！在这里看到你了 ^ ^

**Comment by channing333** [comment]
My problem is about QtAVWidgets.framework, when I install the QtAV
