### ISSUE TITLE
Using multiple MediaPlayers in an application

### ISSUE THREAD

**Issue by Promytheus** [wang-bin/QtAV#272]
I am trying to add 2 MediaPlayers in my application, each playing a playlist of videos. For every VideoPlayer I use the stop() or pause() function, and then the play() function with the next video in the playlist.

I use Qt 5.3.1 and when I use the MSVC 2013 compiler my application is crushing immediately when the second VideoPlayer is starting to play a video. When I use the mingw compiler then crushing is less predictable but still happens. Using DXVA with mingw causes crushing to be more often.

When I'm not using the stop() and play() functions but instead set the source of each player to its next video, using mingw without DXVA, there is no crushing but I’m still investigating possible memory leaks.

Have you ever tried having more than one MediaPlayers in an application? Is MediaPlayer designed so that multiple instances can function correctly at the same time?

**Comment by wang-bin** [comment]
use VideoOutput2 instead
