### ISSUE TITLE
How to play a set of videos synchronized?

### ISSUE THREAD

**Issue by aley2003** [wang-bin/QtAV#309]
I want to play a bunch of videos synchronized in one process. All videos should display the same timecode. What is the best way to get the videos (including 1 audio stream) synchronized (and seeked together)?
In https://github.com/wang-bin/QtAV/wiki/Multiple-Players-Synchronization there is an advice to use AVClock. I have tried to use AVPlayer.masterClock()->updateExternalClock(AVClock) but without success. Is it possible to use one AVClock for all my AVPlayers? 
At the moment I use AVPlayer->setPosition(qint64) in an loop but I guess that is not the best way to achieve the desired result.
Thanks in advance

**Comment by wang-bin** [comment]
The latest code and videowall example should work
