### ISSUE TITLE
QtAV Android compile error

### ISSUE THREAD

**Issue by mzafers** [wang-bin/QtAV#320]
Hello. I'm on Ubuntu 14.04, Qt5.3.2 and Qt Creator 3.2.2 . I could compile QtAV for Ubuntu successfully and I try to compile QtAV for Android. But Qt Creator gives errors. I spend a few days, but I couldn't solve the problem. It gives 4 errors you can find below. What is the problem, do you have any idea?

Error1:
/home/zafer/androidNDK/sources/cxx-stl/gnu-libstdc++/4.9/include/typeinfo:41: error: expected unqualified-id before string constant
 extern "C++" {
        ^
Error2:
/home/zafer/androidNDK/sources/cxx-stl/gnu-libstdc++/4.9/include/typeinfo:220: error: expected '}' before end of line
 #pragma GCC visibility pop
                           ^
Error3:
/home/zafer/androidNDK/sources/cxx-stl/gnu-libstdc++/4.9/include/typeinfo:220: error: expected unqualified-id before end of line
Error4:
/home/zafer/androidNDK/sources/cxx-stl/gnu-libstdc++/4.9/include/typeinfo:220: error: expected declaration before end of line

**Comment by wang-bin** [comment]
when building qml module or example?

**Comment by mzafers** [comment]
It was on qml module. It's solved. Thanks again.
