### ISSUE TITLE
网络不流畅时，播放网络视频自动退出的问题

### ISSUE THREAD

**Issue by sweord** [wang-bin/QtAV#332]
跟踪了一下，每次从这里退出。
把这里的if条件直接写成if (0)，还是会从demux退出。

请问有什么方法可以设置成一直等待网络字节流么？一直到播放完成或者主动stop。
或者您是否可以提供一点思路，怎么修改代码能达到一直等待的效果？
非常感谢。

        // FIXME: now stop instead of seek if reach media's end. otherwise will not get eof again
        if (stopPosition() == mediaStopPosition() || !d->demuxer.isSeekable()) {
            // if not seekable, how it can start to play at specified position?
            qDebug("stopPosition() == mediaStopPosition() or !seekable. d->repeat_current=%d", d->repeat_current);
            d->reset_state = false;
            stop(); // repeat after all threads stopped
        } else {

**Comment by wang-bin** [comment]
最新代码已支持缓冲
