### ISSUE TITLE
How to use QtAV to record video from the camera

### ISSUE THREAD

**Issue by tangzhenhao** [wang-bin/QtAV#348]
I want to display video from the camera  on my laptop and save it. Could QtAV do it?

**Comment by wang-bin** [comment]
start to support encoding now. can record camera and save.  see examples/simpletranscode

**Comment by gakwaya** [comment]
Hi,great project here.
I just looked at the simpletranscode example and it seems it only does transcoding from file to file.I have been playing with the library and it meets project playback requirements,the only remaining thing is recording from webcam.Which leads to the following questions ;-)

1.How does one specify input video and audio devices?Something like:
`ffmpeg -f dshow -i  video="WEB_CAM_DEVICE" -f dshow -i audio="MicroPhone Realtek High Defini" output.mp4`

2.Is it possible to direcly pass the recorded frame sequence to a widget for display?If yes a good example
  would be great.

**Comment by wang-bin** [comment]
> it seems it only does transcoding from file to file
Not true. You can use custom input and output stream by implementing a QIODevice or MediaIO class. If you build with libavdevice, QtAV should support what ffmpeg does.

1. You can use `avdevice:` protocol in QtAV

    player.setFile("avdevice:dshow:video=WEB_CAM_DEVICE");

I don't know how to use audio and video device at the same time. I have no device to test. BTW, audio encoding is not supported in QtAV now.

2. QtAV renderers only support `VideoFrame`, a video frame contains uncompressed picture data, data layout and pixel format information.

**Comment by lrangel82** [comment]
Hi all of you, I spended a lot of time searching some solution to same problem, but I can't find how to do this(record from usb web cam), the principal problem try to implement the example of "simpletranscode" is the output file never created, and when close the app send difernte tipes of errors. 

like:
(101% of size: 3041280 [rtbufsize parameter])! frame dropped!
[FFmpeg:dshow] real-time buffer [@device_pnp_\\?\usb#vid_045e&pid_0728&mi_00#7&1f85cd05&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global] [video input] too full or near too full (101% of size: 3041280 [rtbufsize parameter])! frame dropped!
[FFmpeg:dshow] real-time buffer [@device_pnp_\\?\usb#vid_045e&pid_0728&mi_00#7&1f85cd05&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global] [video input] too full or near too full (101% of size: 3041280 [rtbufsize parameter])! frame dropped!
[FFmpeg:dshow] real-time buffer [@device_pnp_\\?\usb#vid_045e&pid_0728&mi_00#7&1f85cd05&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global] [video input] too full or near too full (101% of size: 3041280 [rtbufsize parameter])! frame dropped!
[FFmpeg:dshow] real-time buffer [@device_pnp_\\?\usb#vid_045e&pid_0728&mi_00#7&1f85cd05&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global] [video input] too full or near too full (101% of size: 3041280 [rtbufsize parameter])! frame dropped!
"Not playing~"
"(repeat 1)Not playing~\nCan not copy codec properties when it's open"
[FFmpeg:dshow] real-time buffer [@device_pnp_\\?\usb#vid_045e&pid_0728&mi_00#7&1f85cd05&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global] [video input] too full or near too full (101% of size: 3041280 [rtbufsize parameter])! frame dropped!
"closing d->format_ctx"
[FFmpeg:dshow] real-time buffer [@device_pnp_\\?\usb#vid_045e&pid_0728&mi_00#7&1f85cd05&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global] [video input] too full or near too full (101% of size: 3041280 [rtbufsize parameter])! frame dropped!

thx for the advice
Luis Rangel
