### ISSUE TITLE
在Mac OS X下编译，提示avutil is required, but compiler can not find it

### ISSUE THREAD

**Issue by Harinlen** [wang-bin/QtAV#349]
FFMpeg版本 2.2，所在位置/usr/bin。
但是在编译的时候提示avutil is required, but compiler can not find it。
编译输出：
Project MESSAGE: BUILD_DIR=/Users/Saki/Documents/Projects/Builds/QtAV/Debug
Project MESSAGE: To disable config tests, you can use 1 of the following methods
Project MESSAGE: 1. create '.qmake.conf' in the root source dir, add 'CONFIG += no_config_tests'(Qt5)
Project MESSAGE: 2. pass 'CONFIG += no_config_tests' or '-config no_config_tests' to qmake
Project MESSAGE: 3. add 'CONFIG += no_config_tests' in /Users/Saki/Documents/Projects/QtAV/user.conf
Project MESSAGE: To manually set a config test result to true, disable config tests and enable config_name like above
Checking for avutil... no
Project ERROR: avutil is required, but compiler can not find it
make: *** [Makefile] Error 3
15:19:14: 进程"/usr/bin/make"退出，退出代码 2 。
Error while building/deploying project QtAV (kit: Desktop Qt 5.4.0 clang 64bit)
When executing step "Make"
Qt版本5.4。一直觉得我的FFMpeg配置的有问题，直接使用-lavutil就是提示找不到。除非使用/usr/bin/libavutil.dylib才可以。求教一下FFMpeg应该怎么配置？谢谢~！

**Comment by wang-bin** [comment]
对任何平台都适用的方法是将依赖的头文件放到qtdir/include,库文件到qtdir/lib，这样编译能通过

**Comment by Harinlen** [comment]
已经成功通过编译！谢谢！

**Comment by zhangmin93** [comment]
作者，我的情况也是这样的…还是编译不过，我是新手，不太明白：你答案里的qtdir是指“项目”里的环境变量吗？

**Comment by wang-bin** [comment]
@zhangmin93 qtdir是指所使用的qt目录，比如`$HOME/Qt5.4.1/5.4/clang_64`，该目录下有bin,include,lib,mkspecs等目录
