### ISSUE TITLE
播放网络视频，正在加载但还没播放就退出程序会挂，怎样可以快速安全的退出？

### ISSUE THREAD

**Issue by sabri-x** [wang-bin/QtAV#350]
您好：
        这段时间需要做一个PC的播放器，目前正在用您的QtAV，非常好用，非常感谢!
        在这里遇到一个问题，向您请教下，在播放网络视频时，在还没开始播放时就退出，windows会弹出异常提醒:
MultiMedia playback framework
 based on Qt & FFmpeg
http://www.qtav.org已停止工作
出现了一个问题，导致程序停止工作，请关闭该程序。
（按钮）    关闭程序
（按钮）    调试程序

看了代码，应该是avformat_open_input（...）还没有返回就退出，FFmpeg出错造成的，尝试了一些方法，还是没能解决，想请教下，有什么方法可以取消avformat_open_input(...)，使程序可以快速安全的退出？
谢谢.

**Comment by wang-bin** [comment]
试试最新代码

**Comment by sabri-x** [comment]
问题已解决，非常感谢!
