### ISSUE TITLE
No audio after recompile QtAV and Player.

### ISSUE THREAD

**Issue by Ben1024** [wang-bin/QtAV#352]
Bin thanks for your great work.

I try to recompile this QtAV lib and player example on Ubuntu 14.10, but there's no sound during playing.  I used the binary downloaded from sourceforge and it can work. Do I miss any libraries or others?

From the Qtcreator application output I saw:
...
Debug: "auto select clock: audio > external"
Debug: "No audio found or audio not supported. Using ExternalClock."
...

And after changed the audio channel, I saw the warning below:
Warning: No audio output!

Any tips about this problem? Thanks.

**Comment by wang-bin** [comment]
How did you build it? Did you run `apt-get install libopenal-dev`? If not, install that and delete YOUR_QtAV_BUILD_DIR/.qmake.cache then rebuild QtAV

**Comment by Ben1024** [comment]
Thanks, I removed .qmake.cache and it fixed.
