### ISSUE TITLE
拔掉耳机，视频就会播放缓慢

### ISSUE THREAD

**Issue by fuyanzhi1234** [wang-bin/QtAV#356]
问题描述：
在有些机器上，插上耳机开始正常播放音频或视频，但在播放的过程中，拔掉耳机，视频就会播放缓慢。

------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
以下是我上次和你反馈问题的邮件内容：

在 2014-10-17 10:23:22，"WangBin" <wbsecg1@gmail.com> 写道：
你音频输出用的是openal还是portaudio？

于 14-10-17 上午10:22, willing4567 写道:
我 试了4四台机器，都是win7，64bit，有两台有问题，还未找出硬件上的区别

在 2014-10-17 10:19:55，"WangBin" <wbsecg1@gmail.com> 写道：
拔掉耳机可能输出设备变了的缘故，我试试看

于 14-10-17 上午10:17, willing4567 写道:
你好，你开发的qtav帮助我解决了很多的问题，一定程度替代了qt自带的播放器，但有一个问题我想请教一下：
你有没有发现，在有些机器上，插上耳机开始正常播放音频或视频，但在播放的过程中，拔掉耳机，视频就会播放缓慢。

我有注意到在AudioThread.cpp中有一段这样的代码：
            /*
             * why need this even if we add delay? and usleep sounds weird
             * the advantage is if no audio device, the play speed is ok too
             * So is portaudio blocking the thread when playing?
             */
                static bool sWarn_no_ao = true; //FIXME: no warning when replay. warn only once
                if (sWarn_no_ao) {
                    qDebug("Audio output not available! msleep(%lu)", (unsigned long)((qreal)chunk/(qreal)byte_rate * 1000));
                    sWarn_no_ao = false;
                }
                //TODO: avoid acummulative error. External clock?
                msleep((unsigned long)(chunk_delay * 1000.0));

是否和这段代码有关系呢？

**Comment by wang-bin** [comment]
貌似是openal和portaudio问题. linux, mac上都正常。windows上测了用 openal的bino播放器也不正常。QtAV直接使用dsound发现正常

**Comment by wang-bin** [comment]
the latest code use XAudio2 as the default backend. XAudio2 works fine

**Comment by gaokunbuaa** [comment]
我的win7的机器也有XAudio2 ，USB耳机，视频播放过程中，拔掉耳机后，视频也会变慢，直到hangup

**Comment by gaokunbuaa** [comment]
调查后发现xaudio处理扬声器的可能有问题，拔掉耳机后，如果系统还有默认扬声器，不会有问题，如果没有了，则xaudio线程会推出， QtAVaudio thread线程死锁；

**Comment by wang-bin** [comment]
@gaokunbuaa 只有win7有问题？
