### ISSUE TITLE
win7  Qt5.4.0_vs213  命令行 qmake QtAV.pro出错，avutil 找不到(ffmpeg环境都设置了,甚至都copy到Qt目录下)

### ISSUE THREAD

**Issue by sabri-x** [wang-bin/QtAV#357]
首先在Qt creator中用Qt5.4.0-vs2013可以编译通过，完全没有问题。

但用Microsoft Visual Studio 编译之前，用命令行生成vs的工程文件时就是通不过，折腾了大半天，后来还把FFmpeg及portaudio的lib,include,bin全都是copy到Qt5.4.0_vs2013下，就是通不过，实在没有办法了，望大神指点下：

FFmpeg 及 protautio的位置都用环境变量设置如下：
set PATH=C:\Qt\Qt5.4.0_vs\5.4\msvc2013\bin;%PATH%

set FFMPEG_DIR=..\ffmpeg-2.5.2-mingw+msvc-x86+x64(好几个版本都用过)
set PORTAUDIO_DIR=..\portaudio-v19_msvc+mingw32_20130209

set INCLUDE=%FFMPEG_DIR%\include;%PORTAUDIO_DIR%\include;%INCLUDE%
set LIB=%FFMPEG_DIR%\lib;%PORTAUDIO_DIR%\lib;%LIB%

 然后命令:qmake -r -tp vc ..\QtAV-master\QtAV.pro  打印信息如下：

F:\WorkSpace\Work\git-project\QtAV\QtAV_build>qmake -r -tp vc ..\QtAV-master\QtAV.pro
Project MESSAGE: BUILD_DIR=F:/WorkSpace/Work/git-project/QtAV/QtAV_build
Info: creating cache file F:\WorkSpace\Work\git-project\QtAV\QtAV_build\.qmake.cache
Project MESSAGE: target arch:
Project MESSAGE: target arch features:
Project MESSAGE: To disable config tests, you can use 1 of the following methods
Project MESSAGE: 1. create '.qmake.conf' in the root source dir, add 'CONFIG += no_config_tests'(Qt5
)
Project MESSAGE: 2. pass 'CONFIG += no_config_tests' or '-config no_config_tests' to qmake
Project MESSAGE: 3. add 'CONFIG += no_config_tests' in F:/WorkSpace/Work/git-project/QtAV/QtAV-maste
r/user.conf
Project MESSAGE: To manually set a config test result to true, disable config tests and enable confi
g_name like above
Checking for avutil... no
Project ERROR: avutil is required, but compiler can not find it

**Comment by wang-bin** [comment]
编译目录下的config.log内容贴下
`set FFMPEG_DIR=..\ffmpeg-2.5.2-mingw+msvc-x86+x64` 最好用绝对路径
最简单的方法是直接把头文件和库文件拷到qt的include和lib目录下，不用设环境变量

**Comment by sabri-x** [comment]
ffmpeg及portaudio目录都改成绝对路经了，还是同样问题，config.log内容如下：

executing config test avutil
+ cd F:\WorkSpace\Work\git-project\QtAV\QtAV_build\config.tests\avutil && C:\Qt\Qt5.4.0_vs\5.4\msvc2013\bin\qmake.exe -spec C:/Qt/Qt5.4.0_vs/5.4/msvc2013/mkspecs/win32-msvc2013 "CONFIG -= qt debug_and_release app_bundle lib_bundle" F:/WorkSpace/Work/git-project/QtAV/QtAV-master/config.tests/avutil
+ cd F:\WorkSpace\Work\git-project\QtAV\QtAV_build\config.tests\avutil && nmake
'nmake' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
test avutil FAILED

也把ffmpeg 复制到qt 的include和lib目录下了，也还是同样的问题，麻烦帮看下什么情况

**Comment by sabri-x** [comment]
问题解决啦，原因是cmd中没有visual studio2013的环境，我打开Microsoft visual studio 的tools->visual studio command prompt 再qmake，一切就都好了，谢啦
