### ISSUE TITLE
Impossible to run QtAV application

### ISSUE THREAD

**Issue by miguelangelorenes** [wang-bin/QtAV#359]
Hi,
I am trying to check QtAV on a project, after compiling QtAV and install as a Qt plugin on mi system I am getting an assemble error when trying create a "QtAV::WidgetRenderer".

...
...
0x77d03d89  <+0x0079>         xor     ecx,ebp
0x77d03d8b  <+0x007b>         call    ntdll!__security_check_cookie (77d001d0)
--> 0x77d03d90  <+0x0080>         mov     esp,ebp
0x77d03d92  <+0x0082>         pop     ebp
...
...

My example is an easy one QTWidget:

   QApplication a(argc, argv);
    qDebug("1");
    MainWindow w;
    qDebug("2");
    w.show();
    qDebug("3");
    QtAV::WidgetRenderer *renderer = new QtAV::WidgetRenderer;

If I remove lates line all works ok, but if I add it no debug traces appear.
Could be something related with the platform or the compile flags?

Regards

**Comment by miguelangelorenes** [comment]
Environment:
SO: Win8.1
Kit: Desktop Qt 5.4 MSVC2013 32bit

As information, I installed QtAV and it is working properly.

**Comment by wang-bin** [comment]
what about examples in QtAV?

**Comment by Piusn** [comment]
I have the same problem were you able to run it?

**Comment by miguelangelorenes** [comment]
Well, I was not able to run it with website version, but currently I am working with v1.5.0 from github and I have no problems.

**Comment by Piusn** [comment]
Please advice how I can set it up on vs 13,please

**Comment by miguelangelorenes** [comment]
I did:
# git clone https://github.com/wang-bin/QtAV.git
# git checkout v1.5.0

And the follow the steps you can get https://github.com/wang-bin/QtAV to configure your environment.

**Comment by Piusn** [comment]
I followed the above but I get the following

Starting C:\Users\Pius\Documents\GitHub\build-QtAV-Desktop_Qt_5_4_1_MinGW_32bit-Debug\bin\simpleplayer.exe...
The program has unexpectedly finished.
C:\Users\Pius\Documents\GitHub\build-QtAV-Desktop_Qt_5_4_1_MinGW_32bit-Debug\bin\simpleplayer.exe crashed

Kindly help me.

**Comment by wang-bin** [comment]
Qt app deployment problem
