### ISSUE TITLE
player: Qt5.4, render OpenGLWidget , crash

### ISSUE THREAD

**Issue by Xuno** [wang-bin/QtAV#360]
When select render OpenGLWidget, player crashes.

Debug: "OpenGL version: 3.3  hasGLSL: 1"
Warning: QOpenGLWidget cannot be used as a native child widget. Consider setting Qt::AA_DontCreateNativeWidgetAncestors and Siblings.
Warning: QOpenGLWidget cannot be used as a native child widget. Consider setting Qt::AA_DontCreateNativeWidgetAncestors and Siblings.
Warning: QOpenGLWidget cannot be used as a native child widget. Consider setting Qt::AA_DontCreateNativeWidgetAncestors and Siblings.
Warning: QOpenGLWidget cannot be used as a native child widget. Consider setting Qt::AA_DontCreateNativeWidgetAncestors and Siblings.
Warning: QOpenGLWidget cannot be used as a native child widget. Consider setting Qt::AA_DontCreateNativeWidgetAncestors and Siblings.
Warning: QOpenGLWidget cannot be used as a native child widget. Consider setting Qt::AA_DontCreateNativeWidgetAncestors and Siblings.
Warning: QOpenGLShaderProgram::bind: program is not valid in the current context.
Warning: QOpenGLBuffer::bind: buffer is not valid in the current context
Warning: QOpenGLBuffer::bind: buffer is not valid in the current context
Warning: QOpenGLBuffer::bind: buffer is not valid in the current context
Warning: QOpenGLBuffer::bind: buffer is not valid in the current context
The program has unexpectedly finished.

**Comment by wang-bin** [comment]
what's your Qt version? Qt>=5.4 is recommended. Otherwise GLWidgetRenderer2 is preferred. But I haven't seen this crash in my test.

**Comment by Xuno** [comment]
Qt5.4.0-vc2013-64-opengl

**Comment by wang-bin** [comment]
I got crash now. The same warning. I don't know the reason yet.
GLWidgetRenderer2  is a QGLWidget. QGLFormat can be used but QSurfaceFormat is not supported. You have to use Qt5 classes like QWindow, QOpenGLWidget. QtOpenGL module is deprecated.

**Comment by Xuno** [comment]
when compile in Qt 5.3, render OpenGLWidget work, but video flipped.

p.s. about multisample 
i try start Enabling OpenGL multisample buffer support in "global.cpp"
`    QGLFormat glf = QGLFormat::defaultFormat();`
`    glf.setSampleBuffers(true);`
`    glf.setSamples(4);`
`    QGLFormat::setDefaultFormat(glf);`

But it not should work without OpenGL extension ? 
I can't see result.

In additional try implement to code use  extensions by  `#include <GL/glew.h>` and install GLEW.

VideoShader.cpp:
`#define GLEW_BUILD`
`#include <GL/glew.h>`
`#define GL_GLEXT_PROTOTYPES`
`#include <QtOpenGL/QtOpenGL>`
`#include <qopenglext.h>`

`bool VideoMaterialPrivate::initTexture....`
`#ifdef  __GLEW_H__`
`    glewInit();`
`#endif`

`#if (GL_ARB_texture_multisample)`
 `   glTexImage2DMultisample(target, 4, internal_format, width, height, false);`
`#else`
`    glTexImage2D(target, 0, internal_format, width, height, 0/*border, ES not support*/, format, dataType, NULL);`
`#endif`

VideoShader_p.h:
`#if (GL_ARB_texture_multisample)`
`        , target(GL_TEXTURE_2D_MULTISAMPLE)`
`#else`
 `       , target(GL_TEXTURE_2D)`
`#endif`



but result bad, RED color instead of video

**Comment by wang-bin** [comment]
I implemented QOpenGLWidget myself for Qt<5.4. It has some bugs. I tested on mac and video displayed correctly, no flip. But on windows and linux video can not be updated correctly.
I don't know about multisample. What does it bring us?

**Comment by Xuno** [comment]
Multisample anti aliasing offers higher quality zoom, in our case with mouse wheel or stretching the video windows to a larger resolution.

**Comment by wang-bin** [comment]
do you have a simple example?

**Comment by Xuno** [comment]
SMAA: Enhanced Subpixel Morphological Antialiasing

smaa.glsl

https://github.com/vispy/experimental/blob/master/fsaa/smaa.glsl

**Comment by wang-bin** [comment]
ok, i think that's not a simple example

**Comment by wang-bin** [comment]
QtQuick already use msaa: http://doc-snapshot.qt-project.org/qt5-5.3/qtquick-visualcanvas-scenegraph-renderer.html
I read the code but can not find `glTexImage2DMultisample`
