### ISSUE TITLE
display raw h264 stream - fps control and lock (Raspbery Pi stream)

### ISSUE THREAD

**Issue by 3electrons** [wang-bin/QtAV#369]
First of all great work with QtAv it is awesome :)
I am trying to display realtime h264 stream form Raspberry Pi and will be glad for some suggestions where to head to. 
On the raspberry there is an tcp server that streams raw h264 stream from raspivid to the client. 
I have tested it with mplayer so something like :

nc 192.168.0.199 5500 | mplayer - -fps 100 -cache 512  
If stream has 30 fps allows me to see video in with no latency  the -fps 100 eat up all the delay and display video in realtime. 

I was trying to acheive the same setting AVPlayer as follows : 

        QVariantHash avfm_opt;
        avfm_opt["probesize"] = 512*1024;
        avfm_opt["fbsprobesize"] = 30;
        avfm_opt["framerate"] = 30;
        avfm_opt["rtbufsize"] = 512*1024;

        QVariantHash opt;
        opt["avformat"] = avfm_opt;
        m_player->setOptionsForFormat(opt);
        m_avPlayer->setQIODevice(m_socket); 

But I do not see any option how to control framerate from such stream. 
When socket allocates more than 512Kb i call AVPlayer::play(); 
It plays the whole content of "buffer" in less than haft second (huge framerate) and screen gets black. 

Hence my 2 questions: 
1. Ho to force given frame rate 
or 
2. How to play stream in following way: When there is no more data it stops (with last frame displayed) and when new data arrive it displays it immediately. 

P.S. How to map ffmpeg parameters to QVariantHash/Map and AVPlayer::setOptionsForXXXX ?

**Comment by wang-bin** [comment]
1. Not supported now. I assume all frames have timestamp information. I can support it.
2. It should work as you say without additional configurations. But you have to call `AVPlayer::setInterruptTimeout(qint64 timeout)` to a large value because default value is 30000 and playback will stop if no data read in 30s.

P.S.
the code you paste seems right.

**Comment by bevinhex** [comment]
Can't build it for raspberry pi by getting source code from git, does anyone succeed so far?

**Comment by wang-bin** [comment]
I don't know who tried pi. How you build it? What's the error you get?

**Comment by 3electrons** [comment]
@bevinhex 
Please mind that my QtAV is on regular PC and it does use Raspberry as an h264 server -stream accessed by simple tcp socket. 
- Unless you are doing crosscompilation and trying to build QtAV on PI - please mind that you will probably need  proper ffmpeg  with headers (developement version). You may refer to many resources on the net for example http://owenashurst.com/?p=242 (I have not tested that).

**Comment by bevinhex** [comment]
Here is what I did:

#ssh pi@192.168.0.3   (my rpi ip)
#sudo su
#cd /usr/src
#git clone https://github.com/wang-bin/QtAV.git
#cd QtAV
#qmake 

(works ok, sinece I already installed ffmpeg related stuff from raspberry pi repository, btw I have qtcreater+qt4 installed inside)

#make
After a long while I get
global.cpp:48:42: error: ‘mkid’ has not been declared
global.cpp:48:66: error: expected unqualified-id before 'i'
global.cpp:49:48: error: ‘mkid’ has not been declared
global.cpp:49:72: error: expected unqualified-id before 'O'
global.cpp:50:45: error: ‘mkid’ has not been declared
global.cpp:50:69: error: expected unqualified-id before 'G'
global.cpp:51:44: error: ‘mkid’ has not been declared
global.cpp:51:68: error: expected unqualified-id before 'G'
global.cpp:52:48: error: ‘mkid’ has not been declared
global.cpp:52:72: error: expected unqualified-id before 'G'
global.cpp:53:39: error: ‘mkid’ has not been declared
global.cpp:53:63: error: expected unqualified-id before 'D'
global.cpp:54:44: error: ‘mkid’ has not been declared
global.cpp:54:68: error: expected unqualified-id before '2'
global.cpp:55:38: error: ‘mkid’ has not been declared
global.cpp:55:62: error: expected unqualified-id before 'V'

**Comment by wang-bin** [comment]
@bevinhex can you show me the complete command that g++ build this file?

**Comment by bevinhex** [comment]
Here is some lines above:
cd install_sdk/ && make -f Makefile 
make[2]: Entering directory '/usr/src/QtAV/tools/install_sdk'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/usr/src/QtAV/tools/install_sdk'
make[1]: Leaving directory '/usr/src/QtAV/tools'
cd widgets/ && /usr/bin/qmake /usr/src/QtAV/widgets/libQtAVWidgets.pro -o Makefile.libQtAVWidgets
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:8: Unknown test function: !contains
Project MESSAGE: target: /usr/src/QtAV/lib_linux_arm/QtAVWidgets
Project MESSAGE: target: /usr/src/QtAV/lib_linux_arm/QtAVWidgets
Project MESSAGE: target: /usr/src/QtAV/lib_linux_arm/QtAVWidgets
cd widgets/ && make -f Makefile.libQtAVWidgets 
make[1]: Entering directory '/usr/src/QtAV/widgets'
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DBUILD_QTAVWIDGETS_LIB -DQTAV_HAVE_GL=1 -DQTAV_HAVE_XV=1 -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/include/qt4 -I../src -I/usr/src/QtAV -I../src/QtAV -I. -I/usr/src/QtAV -IQtAVWidgets -I/usr/X11R6/include -I../.moc/4.8.2/QtAVWidgets -o ../.obj/QtAVWidgets_linux_arm/global.o global.cpp
global.cpp:48:42: error: ‘mkid’ has not been declared
global.cpp:48:66: error: expected unqualified-id before 'i'
global.cpp:49:48: error: ‘mkid’ has not been declared
global.cpp:49:72: error: expected unqualified-id before 'O'
global.cpp:50:45: error: ‘mkid’ has not been declared
global.cpp:50:69: error: expected unqualified-id before 'G'
global.cpp:51:44: error: ‘mkid’ has not been declared
global.cpp:51:68: error: expected unqualified-id before 'G'

**Comment by wang-bin** [comment]
@bevinhex It's strange. `mkid` is defined in /usr/src/QtAV/src/QtAV/private/mkid.h and this file is included. I have no idea.
Try to copy mkid.h to QtAV/widgets/mkid.h, and change the line `#include "QtAV/private/mkid.h"` in global.cpp to `#include "mkid.h"`

**Comment by bevinhex** [comment]
That got rid of the mkid problem, but I got another one this time:
cd install_sdk/ && make -f Makefile 
make[2]: Entering directory '/usr/src/QtAV/tools/install_sdk'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/usr/src/QtAV/tools/install_sdk'
make[1]: Leaving directory '/usr/src/QtAV/tools'
cd widgets/ && make -f Makefile.libQtAVWidgets 
make[1]: Entering directory '/usr/src/QtAV/widgets'
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DBUILD_QTAVWIDGETS_LIB -DQTAV_HAVE_GL=1 -DQTAV_HAVE_XV=1 -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/include/qt4 -I../src -I/usr/src/QtAV -I../src/QtAV -I. -I/usr/src/QtAV -IQtAVWidgets -I/usr/X11R6/include -I../.moc/4.8.2/QtAVWidgets -o ../.obj/QtAVWidgets_linux_arm/global.o global.cpp
global.cpp: In function ‘QtAV::VideoRenderer* QtAV::__create_VideoRendererWidget()’:
global.cpp:61:80: error: cannot allocate an object of abstract type ‘QtAV::WidgetRenderer’
QtAVWidgets/WidgetRenderer.h:36:26: note:   because the following virtual functions are pure within ‘QtAV::WidgetRenderer’:
/usr/include/qt4/QtAV/VideoRenderer.h:192:18: note: 	virtual void QtAV::VideoRenderer::drawFrame()
global.cpp:61:82: warning: control reaches end of non-void function [-Wreturn-type]
Makefile.libQtAVWidgets:1039: recipe for target '../.obj/QtAVWidgets_linux_arm/global.o' failed

**Comment by wang-bin** [comment]
@bevinhex I don't know. I never had this kind of build error. ci is ok for Qt4.8~Qt5.2, see https://travis-ci.org/wang-bin/QtAV
What's your g++ version?

**Comment by bevinhex** [comment]
Oh, my bad:
pi@raspberrypi /usr/src/QtAV $ apt-cache show g++
Package: g++
Source: gcc-defaults (1.120)
Version: 4:4.6.3-8
Architecture: armhf
Maintainer: Debian GCC Maintainers <debian-gcc@lists.debian.org>
Installed-Size: 34
Depends: cpp (>= 4:4.6.3-8), gcc (>= 4:4.6.3-8), g++-4.6 (>= 4.4.7-1~), gcc-4.6 (>= 4.4.7-1~)
Provides: c++-compiler
Priority: optional
Section: devel
Filename: pool/main/g/gcc-defaults/g++_4.6.3-8_armhf.deb
Size: 1362
SHA256: 461bbd04d99bcccbfd6e53b66b31498dd6f7a970fd0308f0b422596dd2f51686
SHA1: 20f8e87fdb737ffe4587dd920756437c31368c8a
MD5sum: e54124d662f6034523985380b9a63812



It seems g++ in raspberry pi repository is too old, thought it was 4.8

**Comment by wang-bin** [comment]
@bevinhex I just compiled QtAV on virtualbox with g++4.6.3 successfully. Please try again

    git clean -dxf
    mkdir -p build
    cd build
    qmake ..
    make

**Comment by bevinhex** [comment]
```
ls -l /usr/bin/g++
lrwxrwxrwx 1 root root 7 Nov 17  2012 /usr/bin/g++ -> g++-4.6
```
raspberry pi g++ is linked to g++-4.6, even though I have g++-4.8 installed, and after doing the steps above I got the same results

Interestingly enough, I can find libQtAV.so* files in lib_linux_arm folder, 
```
pi@raspberrypi /usr/src/QtAV/build $ ls -l lib_linux_arm/
total 852
-rw-r--r-- 1 pi pi    889 Feb 12 07:22 libQtAV.prl
lrwxrwxrwx 1 pi pi     16 Feb 12 07:39 libQtAV.so -> libQtAV.so.1.4.2
lrwxrwxrwx 1 pi pi     16 Feb 12 07:39 libQtAV.so.1 -> libQtAV.so.1.4.2
lrwxrwxrwx 1 pi pi     16 Feb 12 07:39 libQtAV.so.1.4 -> libQtAV.so.1.4.2
-rwxr-xr-x 1 pi pi 862688 Feb 12 07:39 libQtAV.so.1.4.2
-rw-r--r-- 1 pi pi    921 Feb 12 07:39 libQtAVWidgets.prl
```
The error says
```
make[1]: Entering directory '/usr/src/QtAV/build/widgets'
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DBUILD_QTAVWIDGETS_LIB -DQTAV_HAVE_GL=1 -DQTAV_HAVE_XV=1 -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I/usr/src/QtAV/widgets -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/include/qt4 -I/usr/src/QtAV/src -I/usr/src/QtAV -I/usr/src/QtAV/src/QtAV -I/usr/src/QtAV/widgets -I/usr/src/QtAV -I/usr/src/QtAV/widgets/QtAVWidgets -I/usr/X11R6/include -I../.moc/4.8.2/QtAVWidgets -I. -o ../.obj/QtAVWidgets_linux_arm/global.o /usr/src/QtAV/widgets/global.cpp
/usr/src/QtAV/widgets/global.cpp: In function ‘QtAV::VideoRenderer* QtAV::__create_VideoRendererWidget()’:
/usr/src/QtAV/widgets/global.cpp:61:80: error: cannot allocate an object of abstract type ‘QtAV::WidgetRenderer’
/usr/src/QtAV/widgets/QtAVWidgets/WidgetRenderer.h:36:26: note:   because the following virtual functions are pure within ‘QtAV::WidgetRenderer’:
/usr/include/qt4/QtAV/VideoRenderer.h:192:18: note: 	virtual void QtAV::VideoRenderer::drawFrame()
/usr/src/QtAV/widgets/global.cpp:61:82: warning: control reaches end of non-void function [-Wreturn-type]
Makefile.libQtAVWidgets:1039: recipe for target '../.obj/QtAVWidgets_linux_arm/global.o' failed
make[1]: *** [../.obj/QtAVWidgets_linux_arm/global.o] Error 1
make[1]: Leaving directory '/usr/src/QtAV/build/widgets'
Makefile:87: recipe for target 'sub-widgets-libQtAVWidgets-pro-make_default' failed
make: *** [sub-widgets-libQtAVWidgets-pro-make_default] Error 2
```
Guess it should work without video widgets, so I'll test the library without widget later.

**Comment by 3electrons** [comment]
The issue is closed - however if anybody is looking for solution of problem I mentioned in first post here is an solution. 

<code>
    player->setBufferMode(QtAV::BufferMode::BufferPackets);
    player->setBufferValue(1);
    QVariantHash avfm_opt;
    avfm_opt["probesize"] = 256*1024;
    avfm_opt["analyzeduration"] = 640 * 1024 ;
    avfm_opt["framerate"] = 100;
    player->setOptionsForFormat(avfm_opt);
</code>

This plays nicely video steram from my RPI and works well. Howerver mplayer seems to be little more "realtime" and smooth - but it does the work wery well and simplify lot of work.  

You can also play RPI Video with QtAV player (example program)  - setting url as "tcp://hostname:port" and changing options of AVFormat (probe size to 256K and Max analyze duration to 512K ) additionally in Misc Tab you have to set "Force FPS" to be at least with FPS that you are streaming (PI does not contain this information or says it is 25 fps) and you have to set Buffer frames to at least 1 to have video working.
