### ISSUE TITLE
Need a how-to about frame extraction and making a video from an image sequence

### ISSUE THREAD

**Issue by isgursoy** [wang-bin/QtAV#370]
Hi All,
I really loved QtAV and want to use it for a project. But I need a conceptional road map to go forward and literally i am stuck with this class hierarchy.

What I want to do is;
1) Frame extraction from network stream (VideoCapture.h or VideoFrameExtractor.h ?) [https://trac.ffmpeg.org/wiki/Create%20a%20thumbnail%20image%20every%20X%20seconds%20of%20the%20video]
2) Process them in the box (will have a sequential OpenCV output)
3) Recreating video using original audio and these processed frames (truly have no idea about it) [https://trac.ffmpeg.org/wiki/Create%20a%20video%20slideshow%20from%20images]

Question: Are step 1 and 3 possible with using QtAV interface? If yes, how?

Thanks.
##

**Comment by wang-bin** [comment]
1) `VideoCapture` can get the current decoded image when video is playing. `VideoFrameExtractor` can get a video frame without playing it and works like the link you give.
3) It's about encoding. QtAV only supports decoding now.

**Comment by isgursoy** [comment]
I changed my approach a bit. Now I just need to know how to use VideoFrameExtractor.
-setSource(const QString value); // adding file://
-setAsync(true); // default
-setAutoExtract(true); // or giving position
-setPrecision(25); // fps
-extract();
But frameExtracted(const QtAV::VideoFrame& frame) never triggered. What I am missing?

**Comment by wang-bin** [comment]
check out the latest code. you can read tests/extract. It will start to extract the frame hen you call setPosition(msec). msec is the position of frame you want to extract. If async is used, you have to call setPosition when `frameExtracted()` is emitted, otherwise setPosition will be ignored when current frame is not extracted.
setSource : no "file://" prefix.
setPrecision: it's not fps, but the maximum position error.for example, precision is 500ms, you want to get the frame at 1000ms(1s), but decoder can not decode the frame at that point no frame at that point, you may get a frame with timestamp 1050ms. If decoder can not decode frames from 1000ms~1500ms, frameExtracted will not be emitted

**Comment by wang-bin** [comment]
video encoding is developing. audio will come soon

**Comment by sabativi** [comment]
How knowing fps can you be sure to extract all frames.

When setting 

`connect(extractor, SIGNAL(frameExtracted(QtAV::VideoFrame)), this, SLOT(onVideoFrameExtracted(QtAV::VideoFrame)));`

and incrementing a counter inside slot, i do not get expected number of frames in video.

I have tried several video, the precision is set to 250 whereas fps is 30...

Any help would be really appreciated

**Comment by wang-bin** [comment]
@sabativi What do you want to do? Extract frame one by one?

**Comment by sabativi** [comment]
Exactly !

**Comment by sabativi** [comment]
So @wang-bin is there any way ?

**Comment by wang-bin** [comment]
I can add another class to do this

**Comment by sabativi** [comment]
That would be awesome.
How can i help ?

**Comment by wang-bin** [comment]
@sabativi No help is required, I have one already. I was considering make it more powerful and replace `VideoFrameExtractor`

**Comment by sabativi** [comment]
@wang-bin  All right, please just update this thread when it can be tested.

**Comment by wang-bin** [comment]
`FrameReader` is introduced in 40f180dc
You can read the header or examples/framereader to know the usage.
Functionality is not complete, and APIs may change in the future

**Comment by isgursoy** [comment]
Hi again,
What about VA-API utilization on Linux while extracting frames? How can I configure QtAV properly to be able to achieve hardware acceleration?

**Comment by wang-bin** [comment]
@isgursoy `FrameReader.setVideoDecoders(QStringList() << "VAAPI" << "FFmpeg");`

**Comment by isgursoy** [comment]
FFmpeg is a fallback or backend? So `QStringList()<<"CUDA";` for Cuda is enough?

**Comment by wang-bin** [comment]
"FFmpeg" is a fallback.
`QStringList()<<"CUDA";` is enough

**Comment by cgilles** [comment]
I have a similar requirement with QtAV for digiKam.
The idea is simple : I want to encode and photo sequence as video.
We have already plenty of code to make frames sequence with photo (using ImageMagick C+ API) and we pass it to QtGstreamer interface. As now digiKam is based on QtAV, we wan to drop GStreamer puzzle, which never work properly.

1/ I'm sure that simple frame encoding is possible with QtAV. Some guidance will be welcome.
2/ What's about photo frame sequence computing. If i'm not too wrong ffmpeg has photo format support. right ? this will be possible to create the input stream with QtAV ?

Thanks in advance

Gilles Caulier

**Comment by wang-bin** [comment]
I will add a new class `FrameWriter`

**Comment by isgursoy** [comment]
Hi, where is the FrameWriter? Is it possible to use hw accel for encoding?
