### ISSUE TITLE
QMediaObject::setNotifyInterval - equivalent ? 

### ISSUE THREAD

**Issue by 3electrons** [wang-bin/QtAV#373]
Hi Wang 
Colud you please add equivalent of QtMultimedia 
QMediaObject::setNotifyInterval(int ms)  
that sets how often signal positionChanged is emited.

I am porting form QtMultimedia to QtAV
I used to set m_player->setNotifyInterval(50) for my QMediaPlayer 
I guess it can do it for now with my timer frequently checking current progress.

**Comment by wang-bin** [comment]
No such interface now. Do we really need this?

**Comment by 3electrons** [comment]
I see m_player->updateClock(200); does the job :) otherwise progress was updated once per second.

**Comment by wang-bin** [comment]
Really? It's strange. Usually this function is useless

**Comment by 3electrons** [comment]
Well I was mistaken - it does not do that. 
How often positionChanged is emited and what it is that time dependend of ? Because sometimes it is emitted once per second and sometimes more often.

**Comment by wang-bin** [comment]
It's in `computeNotifyPrecision` in AVPlayerPrivate.cpp

**Comment by wang-bin** [comment]
There's no public api to set the interval. I can add it if necessary.

**Comment by 3electrons** [comment]
It would be nice :) Adding it as public may be useful for applications where there is need to synchronize video with data attached to it - as it is in mine case - and because of different cpu load factors it could be adjusted to optimal value.

**Comment by wang-bin** [comment]
added in cd4de96
Unlike QtMultimedia, only progress update interval  changes,

**Comment by 3electrons** [comment]
Works like a charm :) Thanks
