### ISSUE TITLE
<cmath>

### ISSUE THREAD

**Issue by Xuno** [wang-bin/QtAV#375]
if used  <cmath> in tests\ao\main.cpp then definition `M_PI` is undefined when use C++ with VS2013.
if made changes 
```
#define _USE_MATH_DEFINES
#include <cmath>
```
then can.
But may be better use like in src\ColorTransform.cpp 
`#include <QtCore/qmath.h>`
where M_PI defined.

**Comment by wang-bin** [comment]
Fixed in 15544c2
Thanks
