### ISSUE TITLE
QML Api

### ISSUE THREAD

**Issue by RSATom** [wang-bin/QtAV#377]
Hi, where I can read about QtAV API available from QML?

**Comment by wang-bin** [comment]
QtAV/qml/plugins.qmltypes

**Comment by RSATom** [comment]
Did you ever try compare it to libvlc API? Does C++ QtAV api could be comparable to libvlc API? Or maybe QtAV API is even more powerfull than libvlc API?

I just think about go away from libvlc and trying to find alternatives...

**Comment by wang-bin** [comment]
No.  I think it's enough for most user

**Comment by RSATom** [comment]
Ok, thanks!
