### ISSUE TITLE
Build cross target win32 on host linux

### ISSUE THREAD

**Issue by Ligverd** [wang-bin/QtAV#380]
I do cross Assembly in linux mingw for the target platform win32 
install_sdk is created under the windows platform
not sure that I have correctly placed the scope in the pro file , but the idea I think it will be clear

```diff
diff --git a/tools/install_sdk/install_sdk.pro b/tools/install_sdk/install_sdk.pro
index 4b22c68..74f06c5 100644
--- a/tools/install_sdk/install_sdk.pro
+++ b/tools/install_sdk/install_sdk.pro
@@ -20,7 +20,7 @@ VERSION = $$QTAV_VERSION
 PROJECT_LIBDIR = $$qtLongName($$BUILD_DIR/lib)
 
 LIBPREFIX = lib
-win32 {
+win32:!mingw {
   MOVE = move /y
   COPY = copy /y
   COPY_DIR = xcopy /s /q /y /i
@@ -33,6 +33,19 @@ win32 {
     LIBSUFFIX = lib
     LIBPREFIX =
   }
+} else:win32:mingw {
+  MOVE = mv
+  COPY = cp -f
+  COPY_DIR = $$COPY -R
+  MKDIR = mkdir -p
+  RM = rm -f
+  RM_DIR = rm -rf
+  *g++* {
+    LIBSUFFIX = a
+  } else {
+    LIBSUFFIX = lib
+    LIBPREFIX =
+  }
 } else {
   MOVE = mv
   COPY = cp -f
```

**Comment by wang-bin** [comment]
A better solution is check whether `cross_compile` is in CONFIG. It should be defined in mkspec/qconfig.pri. Works for  both Qt4 and Qt5.
Another solution is check `$$QMAKE_HOST.os`, the value can be Darwin, Windows, Linux etc. It is already used in QtAV.
I prefer the latter.
: )
