### ISSUE TITLE
compiling error 

### ISSUE THREAD

**Issue by taktiker12** [wang-bin/QtAV#385]
hi Wang
i tried to compile the latest release but no success .
i got this error :   
VideoPreviewWidget.cpp:96:24: error: ‘const class QtAV::VideoFrame’ has no member named ‘to’
     VideoFrame f(frame.to(VideoFormat::Format_RGB32, s));
                        ^
Makefile.libQtAVWidgets:1533: recipe for target '../.obj/Qt5AVWidgets_linux_x86_64/VideoPreviewWidget.o' failed
make[1]: *** [../.obj/Qt5AVWidgets_linux_x86_64/VideoPreviewWidget.o] Error 1
make[1]: Leaving directory '/usr/local/src/QtAV-1.5.0/widgets'
Makefile:97: recipe for target 'sub-widgets-libQtAVWidgets-pro-make_first' failed
Thank You 
Mounir

**Comment by wang-bin** [comment]
did you install an old version? If yes, remove them. running sdk_uninstall.sh may helps

**Comment by taktiker12** [comment]
okay , i will try it 
thank you

**Comment by taktiker12** [comment]
it Woks!! 
Issue solved .
Thanky you Mr Wang for this great Project .

**Comment by wang-bin** [comment]
: )
