### ISSUE TITLE
player crashes while playing an MP3 file embedded with an image

### ISSUE THREAD

**Issue by GestureWei** [wang-bin/QtAV#387]
When I hovered on the time slider and player was going to show the preview, it crashed.
Qt version is 4.8.5, compiled by g++ (version 4.9.1, x86_64-w64-mingw32-seh-rev0, Built by MinGW-W64 project).
![bug](https://cloud.githubusercontent.com/assets/3354896/6411897/390de558-beb8-11e4-86ce-5085d470c835.png)
![dump](https://cloud.githubusercontent.com/assets/3354896/6411966/f58e9812-beb8-11e4-8a7b-79a40185bb14.png)

**Comment by wang-bin** [comment]
I tested 2 files and no crash, on OSX. I will disable preview for music, and also add an option to disable preview.

**Comment by GestureWei** [comment]
Preview for video is ok. Maybe there is something wrong on mingw64. So I try to discover something that will contribute to the project. And there is a bug in MainWindow.cpp I found just now.
![before](https://cloud.githubusercontent.com/assets/3354896/6412876/35af9f3a-bec4-11e4-9e78-f0d5393454a9.png)
Maybe you mean this?
![after](https://cloud.githubusercontent.com/assets/3354896/6412873/2c31df54-bec4-11e4-86e9-c5b8d6516194.png)

**Comment by wang-bin** [comment]
I added an option to disable preview in menu->setup->miscpage->preview. I'm not sure what's the correct way to detect a file is a music or not, so only manually disable option available now.

Yes, my mistake. You can fix this bug and create a PR (pull request). Update to latest code first.
