### ISSUE TITLE
Can QtAV support YUV raw format video?

### ISSUE THREAD

**Issue by Ben1024** [wang-bin/QtAV#389]
Hi, Bin, can QtAV support YUV format raw stream? I was looking into ffplayer which can play YUV stream, but for QtAV I saw in AVDemuxer::load() it seems the demuxer isn't designed for this case. Do you have any suggestions or plans for this? Or any tips?

**Comment by wang-bin** [comment]
How to create raw yuv video?

**Comment by Ben1024** [comment]
You can use ffmpeg to create a raw stream, such as, ffmpeg -i src_stream.mp4 -c:v rawvideo -pix_fmt yuv420p out_stream.yuv

**Comment by Ben1024** [comment]
In my environment, I can also get the raw stream from mobile sensor which run on Android platform.

**Comment by wang-bin** [comment]
How to play it with ffplay?

**Comment by Ben1024** [comment]
I use command, ffplay -f rawvideo -pix_fmt yuv420p -s 352x288 -i yuv_stream.yuv

**Comment by wang-bin** [comment]
Already supported by libavformat. You have to set some options for AVFormatContext. 
In player, you can: open setup dialog->AVFormat->Extra, fill "video_size=352x288 pixel_format=yuv420p framerate=25"
In C++, you can do like this

    QVariantHash fmt_opt;
    fmt_opt["video_size"] = "352x288";
    fmt_opt["pixel_format"] = "yuv420p";
    fmt_opt["framerate"] = 25;
    player->setOptionsForFormat(fmt_opt);
    player->setFile("yuv_stream.yuv");
    player->play();

**Comment by wang-bin** [comment]
But QtAV detect the stream is a raw stream by the file extension. I will fix this limitation soon

**Comment by wang-bin** [comment]
Commit e828f9c4 let you to force a format by setting AVFormatContext.format_whitelist

    fmt_opt["format_whitelist"] = "rawvideo"

Now it works even if the file suffix is not "yuv", "rgb" etc.

**Comment by Ben1024** [comment]
Thanks, Bin. I'll try this.

**Comment by Ben1024** [comment]
I pulled the latest code, and found an error while playing YUV file by using example player:
codec(rawvideo) or profile() is not supported
"Video codec not found"
load failed

In AVPlayer::Private::setupVideoThread(), new video decoder would be initialed, but for rawvideo stream the player doesn't need to use decoder. I'm thinking to add a stream type checking in 'setupVideoThread', do you have any suggestions or comments on this?

**Comment by wang-bin** [comment]
You only choose VA-API decoder. If you are using player, select FFmpeg decoder. If you are writing C++ code, use `AVPlayer.setPriority(....)` In fact, ffmpeg has such a decoder to process raw data.

**Comment by Ben1024** [comment]
Yes, thanks for your help, it works well.
