### ISSUE TITLE
Can I control framerate of this video ?

### ISSUE THREAD

**Issue by 3electrons** [wang-bin/QtAV#390]
The "attached" video is raw dump from raspivid on Raspberry Pi it is h264 that does not have additional information such as pts that allows to determine framerate.  You library can play it ... but it plays it with framerate that is probably hardware efficency dependend. On my computer whole movie is displayed in less than 1 second. 

Is there any way to control codec output framerate ? 
P.S. I have tried following:
<code> 
QVariantHash opt; 
opt["framerate"] = 25; 
m_player->setOptionsForFormat(opt); 
and 
m_player->setOptionsForVideoCodec(opt) 
</code> 
Without success. 
The attached video can be downloaded from here: 
ftp://qtav+3electrons.com:qtav1234@ftp.strefa.pl

Do you know any public storage for attachement like this ?

**Comment by wang-bin** [comment]
I can not download this video. It ask me to login.
You can use google drive and share the video with me.
Other sites: http://filebin.net  box.com

**Comment by wang-bin** [comment]
BTW, today's code supports to play raw yuv streams. https://github.com/wang-bin/QtAV/wiki/Play-Raw-Video-Streams

Not sure how to play a raw h264 stream

**Comment by 3electrons** [comment]
Hi Bin 
I know about yuv :) That is why I was wondering about that h264. But I have not checked it with newest code (I was trying with player - and setting extra options - I did this today - also without success ). 

File can be downloaded from here: 
http://filebin.net/5ix9dzx8f1

P.S. I noticed you are planning "But I'm going to add this feature, start to decode only if there are enough packets. I plan to finish it in 2 weeks." 
Sp I wonder if I could force framerate of such video and slowly feed AVPlayer component with data and  display (such as above) video directly from stream.

**Comment by wang-bin** [comment]
I find mpv creates pts for every packets, assuming fps = 25. But mpv can not seek this file.

**Comment by 3electrons** [comment]
Yes. You can also use mplayer directly setting -fps to given value. Right now I am using mplayer - embedding it into my app to display that video in real time as stream. I hope some day I will be able to use QtAV to do that :) -it will siplifiy deployment.

BTW. Have you considered croudfunding for doing it .. Many pepole on RPi forums are trying to do that .. but nobody share the knowledge or there really is the problem with displaying such video in realtime in own application.

**Comment by wang-bin** [comment]
I'm looking int ffplay source code. ffplay can seek correctly. of cause, your stream maybe not seekable, then the solution is simple, just add pts like mpv does.

what does `croudfunding` mean?

**Comment by 3electrons** [comment]
Do you mean add pts in realtime? Can you show me directions where to look - I am not familiar with video codes. But want to try ... :)

Croudfunding - please refer here http://en.wikipedia.org/wiki/Crowdfunding. Personally I have not done it .. because my bussiness model of work is different. But I guess it might fit the way you are working.

**Comment by wang-bin** [comment]
https://github.com/mpv-player/mpv/blob/master/video/decode/dec_video.c#L353

But I plan to compute realtime frame rate in VideoThread, no pts required.

Croudfunding sounds good. I will consider it. Thanks.

**Comment by wang-bin** [comment]
New function added: `void AVPlayer::setFrameRate(qreal)`. Set the value <=0 to switch to normal playback.
Call it before you play the video.
You can test in player example. Setup->Misc page, set fps to 25.

I can't find out how ffplay does.

**Comment by 3electrons** [comment]
Thank you again :)
I do appreciate your work and time , so please consider one more thing -  how much money you need for doing that. To be able play RPI video stream. This might be good oportunity for Croudfunding :) That might be bigger issue ... and I think there might be more pepole to support that iniciative. I am definitely willing to support that iniciative :) If you will not rise enough funds you are not obligated to do the job.

**Comment by wang-bin** [comment]
How pi create the video stream? From camera? I have a rpi device. But it is too slow so I don't use it.

**Comment by 3electrons** [comment]
Please donwload following code http://filebin.net/notxtl8gh4  this is very minimalistic use scenario. 
Compile the project - and run on PC. It will listen on port 5000 for incoming data. 

On Raspberry Pi launch following command: 
# raspivid -o - -t 0 -w 800 - h 600 | nc ip_of_pc_machine 5000 
this command will feed pistream program on the PC. 
After successful connection Logic::buildPlayerWindow will be called - and new window will apear that is QtAv renderer and AVPlayer connected to it. 
The new connection (socket) will be passed to AVPlayer. 
On the console where pistream is executed you will be informed how much data is already "cached" 
if you have more than 1MB than press play button on the window (upper left corner) and AVplayer will play the content of buffer. 

The concept I would like to achieve is to have constant video preview. 

If you like to see what  I am expecting,  instead of pistream on PC try to execute following command: 
# nc -l -p 5000 | mplayer - -fps 100 -cache 1000 
than on PI do again 
# raspivid -o - -t 0 -w 800 -h 600 | nc ip_of_pc 5000

**Comment by Xuno** [comment]
for 3electrons:
https://github.com/Xuno/Xuno-QtAV/blob/master/examples/player/MainWindow.cpp#L823
Here was applied like you ask early:
```
     QVariantHash tmp=Config::instance().avformatOptions();
        tmp["framerate"]=mCustomFPS;
        mpPlayer->setOptionsForFormat(tmp);
```
And It work for Sequence of images for now.

**Comment by 3electrons** [comment]
I would like to press "Like" button but I can not find any :) . Thanks again :)
