### ISSUE TITLE
Unable link to Static FFmpeg and OpenAL

### ISSUE THREAD

**Issue by dguskov** [wang-bin/QtAV#391]
Hi,
Add CONFIG += static_ffmpeg static_openal . but it does not matter
After compiling QtAV and install as , still needs ffmpeg libs

**Comment by wang-bin** [comment]
You are building a static QtAV library. A static library is created by ar command and simply put all object files together but no external library. I don't know how to create a static library contains other static libraries. The only solution a know is extracting other static libraries to get object files, and use `ar` to include all the object files.
