### ISSUE TITLE
QtAv可以播放一段读取出来的完整的mp3数据吗？要怎么用

### ISSUE THREAD

**Issue by sabri-x** [wang-bin/QtAV#394]
QtAv可以播放一段读取出来的完整的mp3数据吗？要怎么用，看到AudioOutput里面有个例子，用了下好像AudioOutput对像都没有构造成功，走到  ao->setAudioFormat(af); (第8行)就出挂了，例子如下：

int main(int argc, char** argv)
{  
    AudioOutput *ao = AudioOutputFactory::create(AudioOutputId_OpenAL);
    AudioFormat af;
    af.setChannels(2);
    af.setSampleFormat(AudioFormat::SampleFormat_Signed16);
    af.setSampleRate(44100);
    ao->setAudioFormat(af);
    ao->open();
    
    FILE *fp = fopen("1.mp3","rb");
    if( fp )
    {
        int reLen = 0;
        char *data = (char*)malloc(sizeof(char)*ao->bufferSize());
        while (true) {
            memset(data,0,ao->bufferSize());
            reLen = fread(data,1,ao->bufferSize(),fp);
            if( reLen <=0 )
                break;
            
            ao->waitForNextBuffer();
            ao->receiveData(QByteArray(data));
            ao->play();
        }
        free(data);
    }
    fclose(fp);
    ao->close();
    
    return 0;
}

麻烦指点下，这样用对不，要怎么用，谢谢

**Comment by wang-bin** [comment]
AudioOutput只能播放PCM数据。mp3这样的音频先要解码，把解码后的数据丢个AudioOutput。你可以直接用AVPlayer

**Comment by wang-bin** [comment]
崩溃可能是你没把openal编进去

**Comment by sabri-x** [comment]
哦，这样的啊，我现在用AudioOutputId_PortAudio来做为OUtPutId，可以跑了，但不会解码，直接把数据传进去后(ao->receiveData(QByteArray(data));)，几分钟的音频，几秒就完了，全都是乱音。

现在情况是这样的：
我现在有一个语音库，是有很多mp3数据在一个文件里，要发音时可以取出某个mp3数据来，要怎样用AvPlayer来播放，好像没有看到有这样的接口呢，

**Comment by wang-bin** [comment]
你用最新的代码，AudioOutput接口更加简单点，没有waitForNextBuffer receiveData了，直接play就行

可以这样（具体情况你要注意mp3data、buf的生命周期）

    QByteArray mp3data(...);
    QBuffer buf(&mp3data);
    if (buf.open(QIODevice::ReadOnly)) {
        player.setIODevice(&buf);
        player.play();
    }

**Comment by sabri-x** [comment]
刚更新了最新的代码，准备按你说的试下，编译不过：
QtAV\widgets\VideoPreviewWidget.cpp:96: error: 'const class QtAV::VideoFrame' has no member named 'to'
     VideoFrame f(frame.to(VideoFormat::Format_RGB32, s));

**Comment by wang-bin** [comment]
运行下编译目录里的sdk_uninstall.bat再重新编译

**Comment by sabri-x** [comment]
汗，没想到是编译时找到以前安装的头文件了，编译完成，用您说的试了，可以正常播放，就是要注意下QBuffer及数据的生命周期问题，非常感谢，谢谢。
