### ISSUE TITLE
QMLPlayer, player: Qt 5.4.0, after start play movie, crash

### ISSUE THREAD

**Issue by Xuno** [wang-bin/QtAV#398]
master / c9975e77a1823086a878de0fda646ec2fd15d191
Windows 7, x64, MSVC2013 OpenGL x64 debug

QMLPlayer.exe - Program: ..\Qt5Cored.dll, File: global\qglobal.cpp  Line 2810
player.exe - Program: player.exe - R6010  - abort() has been canceled

Debug: "Starting audio thread..."
Fatal: ASSERT: "m_value1 > m_value0" in file QtAV\src\PacketBuffer.cpp, line 85
Debug: "Starting video thread..."
Fatal: ASSERT: "m_value1 > m_value0" in file QtAV\src\PacketBuffer.cpp, line 85
Debug: "demux thread start running...2 avthreads"

in release ok

**Comment by wang-bin** [comment]
fixed in 505faee.

**Comment by msphair** [comment]
@wang-bin I still get this in my application:

```
"Invalid packet! flush audio codec context!!!!!!!! audio queue size=0"
"demuxer sync id: 2/2"
"audio seek: 166.789, id: 2"
"Invalid packet! flush video codec context!!!!!!!!!! video packet queue size: 0"
"request seek audio thread"
"video seek: 166.789, id: 2"
"wake up paused thread"
"request seek video thread"
"skip audio decode at 165.546667/166.789000 v=0.000000 a-v=165546.666667ms"
ASSERT: "m_value1 >= m_value0" in file ...\QtAV\src\PacketBuffer.cpp, line 87
```

**Comment by msphair** [comment]
I'm not using the `QMLPlayer`, but the problem goes away when I comment out 
```c++
m_pPlayer->setBufferMode(QtAV::BufferTime);
```
