### ISSUE TITLE
player: color space engine 'libswscale' changed visualization

### ISSUE THREAD

**Issue by Xuno** [wang-bin/QtAV#399]
master / c9975e77a1823086a878de0fda646ec2fd15d191
Qt 5.4.0, Windows 7, x64, MSVC2013 OpenGL x64 debug
GLWidget2, libswscale:
![libswscale_player](https://cloud.githubusercontent.com/assets/9219334/6743251/220efc5a-cea0-11e4-9659-30c6041205f2.PNG)
GLWidget2, glsl:
![glsl_player](https://cloud.githubusercontent.com/assets/9219334/6743256/2f3d4b52-cea0-11e4-91aa-7811b8e5b883.PNG)

in previous releases was ok

**Comment by wang-bin** [comment]
fixed in d13fbcb6e. thanks.

**Comment by Xuno** [comment]
if used bgr24 `bmp` in OpenGL now problem.

**Comment by wang-bin** [comment]
fixed in ae3e18c

**Comment by Xuno** [comment]
ok now, thanks.
