### ISSUE TITLE
播放数据流叠加

### ISSUE THREAD

**Issue by yuan631111976** [wang-bin/QtAV#401]
请问一下，我加载了一段数据，进行播放，在播放当中还能在添加数据吗（同一个视频文件）

**Comment by wang-bin** [comment]
你是指在播放一段数据时又来了一段数据需要在原先的数据播放好后继续播放？

**Comment by yuan631111976** [comment]
嗯，是的，但是新来的数据是之前视频的数据，之前数据没有加载完成(边加载边播放)

**Comment by wang-bin** [comment]
数据哪来的？应该用AVInput类扩展你这种情况

**Comment by yuan631111976** [comment]
你好，数据是从服务器端下载下来的，服务端加密，客户端脱密，所以加载数据流是一段一段的！

**Comment by wang-bin** [comment]
你用AVInput实现一个吧，或者自己扩展下ffmpeg的libavformat

**Comment by yuan631111976** [comment]
嗯的，谢谢
