### ISSUE TITLE
RPATH "$ORIGIN" on $libdir is not allowed

### ISSUE THREAD

**Issue by awissu** [wang-bin/QtAV#405]
Hello!
I can not build a package in OBS.
Cause: RPATH sets the path the runtime linker. This is only needed when the libs don't reside in a standard directory.
OBS has a RPMLINT check and its output gave me the following errors:

[  334s] ERROR: RPATH "/home/abuild/rpmbuild/BUILD/QtAV-1.5.0/build/lib_linux_x86_64" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/libQt5AV.so.1.5.0 is not allowed
[  334s] ERROR: RPATH "$ORIGIN" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/libQt5AV.so.1.5.0 is not allowed
[  334s] ERROR: RPATH "$ORIGIN/lib" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/libQt5AV.so.1.5.0 is not allowed
[  334s] ERROR: RPATH "/home/abuild/rpmbuild/BUILD/QtAV-1.5.0" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/libQt5AV.so.1.5.0 is not allowed
[  334s] ERROR: RPATH "/home/abuild/rpmbuild/BUILD/QtAV-1.5.0/build/lib_linux_x86_64" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/bin/libcommon.so.1.5.0 is not allowed
[  334s] ERROR: RPATH "$ORIGIN" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/bin/libcommon.so.1.5.0 is not allowed
[  334s] ERROR: RPATH "$ORIGIN/lib" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/bin/libcommon.so.1.5.0 is not allowed
[  334s] ERROR: RPATH "/home/abuild/rpmbuild/BUILD/QtAV-1.5.0" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/bin/libcommon.so.1.5.0 is not allowed
[  334s] ERROR: RPATH "/home/abuild/rpmbuild/BUILD/QtAV-1.5.0/build/lib_linux_x86_64" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/bin/player is not allowed
[  334s] ERROR: RPATH "$ORIGIN" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/bin/player is not allowed
[  334s] ERROR: RPATH "$ORIGIN/lib" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/bin/player is not allowed
[  334s] ERROR: RPATH "/home/abuild/rpmbuild/BUILD/QtAV-1.5.0" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/bin/player is not allowed
[  334s] ERROR: RPATH "/home/abuild/rpmbuild/BUILD/QtAV-1.5.0/build/lib_linux_x86_64" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/bin/QMLPlayer is not allowed
[  334s] ERROR: RPATH "$ORIGIN" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/bin/QMLPlayer is not allowed
[  334s] ERROR: RPATH "$ORIGIN/lib" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/bin/QMLPlayer is not allowed
[  334s] ERROR: RPATH "/home/abuild/rpmbuild/BUILD/QtAV-1.5.0" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/bin/QMLPlayer is not allowed
[  334s] ERROR: RPATH "/home/abuild/rpmbuild/BUILD/QtAV-1.5.0/build/lib_linux_x86_64" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/qml/QtAV/libQmlAV.so is not allowed
[  334s] ERROR: RPATH "$ORIGIN" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/qml/QtAV/libQmlAV.so is not allowed
[  334s] ERROR: RPATH "$ORIGIN/lib" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/qml/QtAV/libQmlAV.so is not allowed
[  334s] ERROR: RPATH "/home/abuild/rpmbuild/BUILD/QtAV-1.5.0" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/qt5/qml/QtAV/libQmlAV.so is not allowed
[  334s] ERROR: RPATH "/home/abuild/rpmbuild/BUILD/QtAV-1.5.0/build/lib_linux_x86_64" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/libQt5AVWidgets.so.1.5.0 is not allowed
[  334s] ERROR: RPATH "$ORIGIN" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/libQt5AVWidgets.so.1.5.0 is not allowed
[  334s] ERROR: RPATH "$ORIGIN/lib" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/libQt5AVWidgets.so.1.5.0 is not allowed
[  334s] ERROR: RPATH "/home/abuild/rpmbuild/BUILD/QtAV-1.5.0" on /home/abuild/rpmbuild/BUILDROOT/QtAV-1.5.0-19.1.x86_64/usr/lib64/libQt5AVWidgets.so.1.5.0 is not allowed

Thank you for the attention, hope this report helps development.

**Comment by wang-bin** [comment]
`RPATH sets the path the runtime linker. This is only needed when the libs don't reside in a standard directory.`
You are right. It should be disabled if it is a system package

**Comment by wang-bin** [comment]
now you can run `qmake "CONFIG+=no_rpath"`. I also disable rpath for debian packages
