### ISSUE TITLE
-

### ISSUE THREAD

**Issue by lexxai** [wang-bin/QtAV#407]

**Comment by Xuno** [comment]
At own fork we detect that video play ok at commit e4d366d2c8d59fc16998ddcc13364cee55c13cb6 (branch "nobug_choppy_here" )
After merging sets of commits  :
- Merge commit 1e7945e9dc7dd408165e935851b253b5fb2fff15 
- Merge commit 3969a04b3e3fbc704965fffe305bc12368550097
- Merge commit d9c433ac2596677d7b8c2ef7d5016ae6d3a25414

Result of commit 2ca3d135a9828d3c3be25f8833041f7dbd38439e (branch "bug-choppy")
is where choppy playback started

Can we ask for help on this issue?
