### ISSUE TITLE
Memory leak using VAAPI

### ISSUE THREAD

**Issue by bongas** [wang-bin/QtAV#413]
When I run the example "player" app using VAAPI as decoder and with infinite repeat on the video file, I can see that the memory for the process (checked with "top") increases with about 25mb every time the app is loading the file. The memory footprint increases until the computer is out of memory. 

It seems that this issue is not present for the ffmpeg decoder.
Would this be a bug in QtAV or in some native VAAPI code?

Environment:
Ubuntu 14.04
QtAV-master
VA-API Version: 0.35 (libva 1.3.0)
Driver version: Intel i965 driver - 1.3.0

**Edit:**
After a while (about 200 repeats), this is printed in the log:
libva error: va_getDriverName() failed with operation failed,driver_name=i965
Maximum number of clients reachedMaximum number of clients reachedlibva info: VA-API version 0.35.0
Maximum number of clients reachedlibva info: va_getDriverName() returns 1

*It's also possible to view the increasing number of allocated "X clients" with 'xrestop'.*

Thanks for great work!

**Comment by wang-bin** [comment]
Confirmed. Thanks.

**Comment by wang-bin** [comment]
I can't find out why. Only happens for GLX as display. Set display to X11 or drm is fine, but worse performance.

**Comment by bongas** [comment]
Thanks for checking!
However, when I try VAAPI using X11 or DRM I get the same behaviour (I check open X clients with 'xrestop').
I also tried to do a workaround by disposing the AVPlayer between each video file but that didn't help...

**Comment by wang-bin** [comment]
try latest code. now x11 without read back is used by default. I will try xrestop later

**Comment by wang-bin** [comment]
seems fixed in the latest code
