### ISSUE TITLE
change audio stream in qml components

### ISSUE THREAD

**Issue by PetrosW** [wang-bin/QtAV#415]
Is possible change audio stream in MediaPlayer or Video qml components?

**Comment by wang-bin** [comment]
no. I can add.

**Comment by wang-bin** [comment]
Now you can use `MediaPlayer.audioTrack` to set the stream, from 0~n-1. n is the internal/external audio tracks you can get when signal `internalAudioTracksChanged` is emitted.

try QMLPlayer audio settings page
