### ISSUE TITLE
player. interrupt demuxer when exiting 

### ISSUE THREAD

**Issue by Xuno** [wang-bin/QtAV#416]
player.  commit 6e5eb1436fac984be63b7fa22d29165e34af53c7
When using the stop button the following error [interrupted by user] occurs:
![qt1](https://cloud.githubusercontent.com/assets/9219334/7280453/8c2c5768-e92b-11e4-8407-a3b09f8d2058.PNG)

**Comment by wang-bin** [comment]
Does it always happen? If the network is bad, reading a frame will take too much time, then this error will be emitted if you press stop button.

**Comment by Xuno** [comment]
Local media file.
Always.
now other text:
![qt2](https://cloud.githubusercontent.com/assets/9219334/7280880/83aafe48-e92e-11e4-85f8-d77bb76a3c60.PNG)

**Comment by Xuno** [comment]
Always

**Comment by wang-bin** [comment]
oh, it's strange. Only happens on windows. works fine on linux and OSX. The interrupt callback is called. But it shouldn't be called for local files because reading from a local file is fast.
You can try to move AVPlayer.cpp:1219  `d->demuxer.setInterruptStatus(-1);` to line 1222 to see if it works

**Comment by Xuno** [comment]
```
    while (d->read_thread->isRunning()) {
        qDebug("stopping demuxer thread...");
        d->read_thread->stop();
        d->read_thread->wait(500);
        d->demuxer.setInterruptStatus(-1);
    }
```
now ok

**Comment by wang-bin** [comment]
I think read the disk file is slower on windows. 
If network is down, av_read_frame() will block it's thread and exit only when timeout. So I have to call the interrupt callback to stop the demuxer quickly. 500ms is enough to read a frame from disk for windows, so it should work. I will update my code soon.
