### ISSUE TITLE
Fails to build on arm due to qreal/double

### ISSUE THREAD

**Issue by awissu** [wang-bin/QtAV#418]
Hello!
Your package failed to build on arm:
[ 1064s] /home/abuild/rpmbuild/BUILD/QtAV-1.6.0/src/PacketBuffer.cpp:97:28: error: no matching function for call to 'qMin(const qreal&, double)'
[ 1064s]      return qMax(qMin(p, 1.0), 0.0);
See  logfile: https://pmbs.links2linux.de/package/live_build_log/Multimedia/QtAV/openSUSE_13.2_ARM/armv7l

**Comment by wang-bin** [comment]
try latest code

**Comment by awissu** [comment]
branch:Master?

**Comment by awissu** [comment]
Thanks. Fixed
