### ISSUE TITLE
Multiple video on same player

### ISSUE THREAD

**Issue by Piusn** [wang-bin/QtAV#424]
Hello, I am planning to have a look at qtav for a player solution I am coming up with. But I got a few questions?

1. Can I have more than one videos play at the same time on the single instance of a player?

2. Is it posible to have a html content rendered on the player? Or is it extendable to include such functionality?

Regards

**Comment by wang-bin** [comment]
1. No. It's not reasonable
2. Yes. See examples/filters

**Comment by Piusn** [comment]
Thanks! What tools do I need to develop?

**Comment by christianVT** [comment]
all you need is a programming IDE e.g. QtCreator and the source - both is free.
But regarding your question, you have to reand and do a lot of tutorials before you should start building your app. It is not a good idea to start with an video app in the beginning.
