### ISSUE TITLE
Unable to run the examples

### ISSUE THREAD

**Issue by Piusn** [wang-bin/QtAV#427]
I am trying to run the example but I get the following in the application output

Starting C:\Users\Pius\Documents\GitHub\build-QtAV-Desktop_Qt_5_4_1_MinGW_32bit-Debug\bin\simpleplayer.exe...
The program has unexpectedly finished.
C:\Users\Pius\Documents\GitHub\build-QtAV-Desktop_Qt_5_4_1_MinGW_32bit-Debug\bin\simpleplayer.exe crashed

**Comment by christianVT** [comment]
I had the same problem. But I had just the problem when I built debug. 
In Release mode it works. To be able to debug I switched off compiler optimisations by -O0

**Comment by dkomer** [comment]
Make sure to put DLLs in release folder (I just throw a bunch- will minimize later... all dlls from ffmpeg, portaudio, and qtav)

**Comment by wang-bin** [comment]
see https://github.com/wang-bin/QtAV/wiki/Can-Not-Run-QtAV-App
