### ISSUE TITLE
libavresample or libswresample is required. Setup your environment correctly

### ISSUE THREAD

**Issue by Piusn** [wang-bin/QtAV#428]
"libavresample or libswresample is required. Setup your environment correctly"

**Comment by wang-bin** [comment]
do you have libswresample? it is included in ffmpeg

**Comment by Piusn** [comment]
I have it but am not sure how to set it up. To be honest am new to qt if you can help on how to set it up correctly I will appreciate.

I have installed qt on "C:\Qt\5.4"

**Comment by wang-bin** [comment]
put ffmpeg/include and ffmpeg/lib in qt folder which contains include and lib. openal is the same

**Comment by xiaoweiChen** [comment]
@wang-bin The same issue I meet. I use the ffmpeg-v2.6.2 source.

May, I find the answer. Not use the source.... I found the lib and include directory in Dev version at [Dev Version](http://ffmpeg.zeranoe.com/builds/) for windows.

**Comment by xiaoweiChen** [comment]
Cost two days(other two days learn ffmpeg), this problem may resolved. 

Here, I share the way:

If you use Qt5, you should add `CONFIG += no_config_tests` in .qmake.conf

Then the qmake process will not tell you do this.

`libavresample or libswresample is required` problem, may, the author forget the without mingw sitation.

In QtAV.pro, we can see that beginning 72ed line:
```
runConfigTests()
!config_avresample:!config_swresample {
  error("libavresample or libswresample is required. Setup your environment correctly then delete $$BUILD_DIR/.qmake.conf and run qmake again")
}
```

well, `config_avresample` and `config_swresample` are functions in qmake, and I found the function body, like following(in libQtAV.pro beginning 93rd line)
```
config_swresample {
    DEFINES += QTAV_HAVE_SWRESAMPLE=1
    SOURCES += AudioResamplerFF.cpp
    LIBS += -lswresample
}
config_avresample {
    DEFINES += QTAV_HAVE_AVRESAMPLE=1
    SOURCES += AudioResamplerLibav.cpp
    LIBS += -lavresample
}
```

En, it is clear, the LIBS usage is the reason for `libavresample or libswresample is required` problem

I quote the newest qmake manual here [LIBS](http://doc.qt.io/qt-5/qmake-variable-reference.html#libs)
>LIBS
>Specifies a list of libraries to be linked into the project. If you use the Unix -l (library) and -L (library >path) flags, qmake handles the libraries correctly on Windows (that is, passes the full path of the >library to the linker). The library must exist for qmake to find the directory where a -l lib is located.

>For example:

>unix:LIBS += -L/usr/local/lib -lmath
>win32:LIBS += c:/mylibs/math.lib
>To specify a path containing spaces, quote the path using the technique described in Whitespace.

>win32:LIBS += "C:/mylibs/extra libs/extra.lib"
>unix:LIBS += "-L/home/user/extra libs" -lextra
>By default, the list of libraries stored in LIBS is reduced to a list of unique names before it is used. >To change this behavior, add the no_lflags_merge option to the CONFIG variable:

>CONFIG += no_lflags_merge

Well, this is a cross-platform or qmake bug, I think.

================================================================

On my side, I set libs by windows style. Badly, the problem still apearance.

I use `qmake -r -tp vc QtAV.pro` to generate the VS projects, the error still....

Well, I have no idea, except comment out the `error` line, I want to see what happen after that.

Amazing!! Succeed generate the VS projects and compiling successful in VS2013!! 

And I found Qt5AVd1.lib and Qt5AVd1.dll, and other libraries.... in specify directories.

PS. May you well meet  SAFESEH question, go to Property of Qt5AV project, or by `alt+enter`, then in `Link->command Line` type in ` /SAFESEH:NO`, this issue will be solved.

But, on my side, the qml part blocking in MsBuild, I will create new issue for that.

**Comment by wangyueliang** [comment]
remember  include mingw header file, for errno.h
example:
C:\MinGW\include
