### ISSUE TITLE
tuning for Zero Latency LiveStream

### ISSUE THREAD

**Issue by christianVT** [wang-bin/QtAV#429]
Hi,
I want to show a livestream from an IP-Camera with minimum latency.
Without modification my latency was ~1200ms. I read and tweaked some time around
and with the code below I have reached 440 - 560 ms latency.
The ONVIF Device Manager (which is also using ffmpeg) has on the same setup a latency of ~320ms.
So there is still space for improvement.

I think this is a very common requirement for an app, that is why 
I would like to do an community approach. 
In the code below you can see how I did it, and what I have already tried.
If you have some idea what I should try please tell me. I will try them out and I will post the optimal solution here.
I think it would be great feature if such tuning would be integrated in QtAV.

sincerely,

Christian

```Cpp
// call this before loading the stream
static void tuneForZeroLatencyLiveStream(QtAV::AVPlayer* player)
{
  QVariantHash settings;

  // sets av_opt_set_xx and av_dict_set settings
  QVariantHash avFormat;

  {// these settings seem to have no impact on latency?
    //avFormat["fpsprobesize"] = 32;
    //avFormat["framerate"] = 100; // from: https://github.com/wang-bin/QtAV/issues/369
    //avFormat["rtbufsize"] = 512 * 1024;
    //avFormat["flush_packets"] = 1;
    //avFormat["avioflags"] = "direct";
    //avFormat["max_delay"] = 1000;
    //avFormat["fflags"] = "nobuffer";
    //avFormat["vprofile"] = "baseline";
  }

  avFormat["probesize"] = 4096; // great impact but how to calc the optimum?  // from: https://github.com/wang-bin/QtAV/wiki/FFmpeg-dict-opt-in-QtAV
  avFormat["tune"] = "zerolatency,fastdecode";
  {
    // is what zerolatency does:
    //  avFormat["bframes"] = 0;
    //  avFormat["force-cfr"] = 1;
    //  avFormat["no-mbtree"] = 1;
    //  avFormat["sync-lookahead"] = 0;
    //  avFormat["sliced-threads"] = 1;
    //  avFormat["rc-lookahead"] = 0;
  }

  settings["avformat"] = avFormat;
  player->setOptionsForFormat(avFormat);
}
```

**Comment by wang-bin** [comment]
I'm thinking about it. Just like `preset: slow, medium, fast` in some encoders, we can add `preset: lowlatancy,...`. It will be convenient for users.

Since 1.6, QtAV use it's own buffer to support buffer progress report. Playback will be paused until `bufferValue` buffered, so I think it's another reason of high latency. Some people told me the latency is larger than 1.5. You can try

    player->setBufferMode(BufferPackets); //default
    player->setBufferValue(1); //playback goes on  if 1 packet buffered, i.e. immediatly

and tell me the result.

You avformat options is helpful, thanks. But I think some options do not exists

    //avFormat["vprofile"] = "baseline";
    avFormat["tune"] = "zerolatency,fastdecode";
    //  avFormat["bframes"] = 0;
    //  avFormat["force-cfr"] = 1;
    //  avFormat["no-mbtree"] = 1;
    //  avFormat["sync-lookahead"] = 0;
    //  avFormat["sliced-threads"] = 1;
    //  avFormat["rc-lookahead"] = 0;

The common avformat options can be found in ffmpeg/libavformat/options_table.h. There more options for a specific format, for example, the options in `ffmpeg/libavformat/udp.c`. All those options can be used.

**Comment by christianVT** [comment]
I have tried that out:

```Cpp
player->setBufferMode(BufferPackets); //default
player->setBufferValue(x); //playback goes on  if 1 packet buffered, i.e. immediatly
````
The results: 
x = 1, same latency, blurry image that gets never clean
x = 2, same latency, quality is the same like without these lines

**Comment by christianVT** [comment]
I think a lowlatancy preset would be a great feature!
I have 4 IP cameras from different vendors for testing. All of them are supporting H.264.
So I could do some testing. 
Furthermore I could support you by building a testbench for low latency:
The app would have a player and a Colored QLabel. The app turns the label white, and measures time until it can capture a remarkble brighter VideoFrame. This is repeated infrequent time and the measurements are shown. like that we would have a standardized measurement to compare the result of code changes or cameras.

If you think this would be helpful for your effort, I would build it,

Christian

**Comment by wang-bin** [comment]
can you try a old version 1.5.0?

**Comment by christianVT** [comment]
tried it out, compile error, both methods I should try did not exist in 1.5.0

**Comment by wang-bin** [comment]
Does the stream have timestamp information? If not, you have to call `player->setClockType(AVClock::VideoClock)` and set buffer value to 1, then the video frames will show as soon as possible

**Comment by slascos** [comment]
How do I set these settings when using the QML AVPlayer?  Is it part of the videoCodecOptions property?
