### ISSUE TITLE
Question about WidgetRenderer

### ISSUE THREAD

**Issue by cascarpato** [wang-bin/QtAV#430]
Hi Wang,
what do you think about the following patch?

    --- a/src/lib/QtAV/src/output/video/WidgetRenderer.cpp
    +++ b/src/lib/QtAV/src/output/video/WidgetRenderer.cpp
    @@ -87,7 +87,8 @@ bool WidgetRenderer::receiveFrame(const VideoFrame &frame)
          * workaround for the widget not updated if has parent. don't know why it works and why update() can't
          * Thanks to Vito Covito and Carlo Scarpato
          */
    -    emit imageReady();
    +    //emit imageReady();
    +    QCoreApplication::postEvent(this, new QEvent(QEvent::User));
         return true;
     }

    @@ -120,6 +121,14 @@ void WidgetRenderer::paintEvent(QPaintEvent *)
             d.painter->end();
     }

    +bool WidgetRenderer::event(QEvent *e)
    +{
    +    if (e->type() != QEvent::User)
    +        return QWidget::event(e);
    +    update();
    +    return true;
    +}
    +

You have used it in other renderer and i'm wondering why you didn't modify WidgetRenderer.

**Comment by wang-bin** [comment]
better than the signal solution. it's faster

**Comment by wang-bin** [comment]
I use `UpdateLater` instead. Less code than `User` event
