### ISSUE TITLE
QtAv是一款很好的开源项目，我想问下能不能直接播放内存中的数据呢？

### ISSUE THREAD

**Issue by zqh619304288** [wang-bin/QtAV#434]
比如我与服务器通过Tcp实时通信不断获得h264的数据，可以用QtAv进行实时的视频播放吗？

**Comment by wang-bin** [comment]
可以。使用AVInput类。也可以看下tests/qiodevice那个例子

**Comment by zqh619304288** [comment]
AVInput类怎么使用，有没有example?

**Comment by wang-bin** [comment]
src/input/QIODeviceInput.cpp
就是实现下读数据就行

**Comment by zqh619304288** [comment]
我自己实现了QIODevice的子类（LoopBuffer） ，在readData函数中实现读取从缓冲区中的数据(此数据是通过tcp与服务器通讯获得），我先缓存了3s左右的数据，之后往LoopBuffer类中写入每帧数据。有一个问题就是开始播放3s后，画面一闪一闪，出现错误信息是 
non-existing PPS 0 referenced"
"[FFmpeg:h264] non-existing PPS 0 referenced"
"[FFmpeg:h264] decode_slice_header error"
"[FFmpeg:h264] no frame!"

"no frame could be decompressed: Error number 14299 occurred 0/14299"
invalid video frame from decoder

video thread gets an eof packet. exit."
"QtAV::VideoRenderer::setInSize => calculating aspect ratio from converted input data(1.000000)"
"Invalid plane! Valid range is [0, 0)"
"Invalid plane! Valid range is [0, 0)"
"Video thread stops running..."
"Demux thread stops running...."
"demuxer thread emit finished."
"avplayer emit stopped()"

好像是解码速度快于接收的速度造成的，有没有好的解决办法？
