### ISSUE TITLE
dyld: Library not loaded when trying to run my first app.

### ISSUE THREAD

**Issue by dearn44** [wang-bin/QtAV#435]
After building and successfully running the examples I am trying to create something like the *simple player* myself.

I did tun `sdk_install.sh` and added *QT += avwidgets av* to my *pro* file, following the directions. 

The example won't compile though, returning

`dyld: Library not loaded: @rpath/QtAVWidgets.framework/Versions/1/QtAVWidgets
  Referenced from: /Users/administrator/Downloads/QtExamples/build-VideoTest3-Desktop_Qt_5_3_clang_64bit-Release/VideoTest3
  Reason: image not found
The program has unexpectedly finished.`

**Comment by wang-bin** [comment]
You have to run QtAV/tools/sdk_osx.sh to deploy the development files. sdk_install.sh does not work for osx. I forgot to mention it in wiki. Assume your Qt5.3 is installed in $HOME, you can install QtAV.framework and QtAVWidgets.framework to Qt dir like this

    cd qtav_build_dir
    qtav_src_dir/sdk_osx.sh  lib_mac_x86_64/QtAV*.framework  ~/Qt5.3/5.3/clang_64/lib

**Comment by dearn44** [comment]
Will this take care of QtAVWidets too?

**Comment by wang-bin** [comment]
the dynamic library loading on osx is different from linux and windows. sometimes you have to use `install_name_tool` to change your library id and dependencies, especially for a standalone app package with many dylibs.
