### ISSUE TITLE
AVPlayer muted and pulse audio

### ISSUE THREAD

**Issue by sherpya** [wang-bin/QtAV#437]
looks like if AVPlayer has muted: true the setMute() in AudioOutputPulse.cpp is called without prior calling init() so "loop" lock is null. PA asserts with:

```Assertion 'm' failed at pulse/thread-mainloop.c:163, function pa_threaded_mainloop_lock(). Aborting.```

**Comment by wang-bin** [comment]
You are right. I will try tomorrow
