### ISSUE TITLE
error: LNK1181: 无法打开输入文件“Qt5AVWidgets.lib”

### ISSUE THREAD

**Issue by xiaoweiChen** [wang-bin/QtAV#440]
In installer directory, I find the static libs is all .a file, this file can not be supported by windows compiler. So, the author can provide the .lib runtime libraries for the developers who use Microsoft compiler? Thanks!

May, we are Chinese, use Chinese is easily to understand.

我这里碰到一个问题。
我根据 [Deploy-SDK-Without-Building-QtAV](https://github.com/wang-bin/QtAV/wiki/Deploy-SDK-Without-Building-QtAV)想尝试运行安装包中自带的simpleplayer。
不过，我工作在windows平台下，且我的Qt版本是msvc2013_opengl的。

在安装路径下我看到提供了runtime库，不过lib里面提供的库都是linux下使用的`.a`文件，没有微软编译器识别的`.lib`文件。

所以，这里麻烦作者能在下一个安装包里面添加一下适合于windows编译器使用的`.lib`库。
多谢!!

**Comment by wang-bin** [comment]
你下错包了，你用vc编译器，下载的是mingw编译的包。
你的环境还是得自己编译，我发布的都是qt5.4 dynamic opengl的版本，你用的是opengl肯定不兼容。

**Comment by xiaoweiChen** [comment]
多谢回复，的确下错包了。又去sourceforge看了下，在下面地址中找到了正确的安装包
http://sourceforge.net/projects/qtav/files/release/1.6.0/
现在能在本地Qt下使用了。
