### ISSUE TITLE
Question Hardware Render (OpenGLRenderBase)

### ISSUE THREAD

**Issue by fmoyaarnao** [wang-bin/QtAV#442]
Hi Wang,

I'm trying to do a decode-render hardware in windows.
I do my own decode hardware and I like to use your hardware QtAV render, without copy the frame from GPU to CPU for rendering.
There is any way to get a reference of the surface of the OpenGL render to pass directly the decoded frame?. Or, there is any way to pass a reference (reference of the decoded frame saved in GPU) to the surface of your OpenGL render?

Thank you very much.

**Comment by wang-bin** [comment]
I plan to do this on windows. There are 2 solutions.
1. Use d3d. QtAV does not have a d3d renderer. But you can use Qt+ANGLE. ANGLE is an opengl implementation using d3d. It has an extension to share resource with other d3d surfaces. But I'm not familiar with d3d. You can read qtmultimedia/src/plugins/wmf, http://src.chromium.org/svn/trunk/src/content/common/gpu/media/dxva_video_decode_accelerator.cc
and http://dxr.mozilla.org/mozilla-central/source/dom/media/wmf/DXVA2Manager.cpp
2. OpenGL + d3d interop. An extension is required. I tried some months ago but failed. Eee https://www.opengl.org/registry/specs/NV/DX_interop.txt

CUDA also provide some functions to convert cuda resources to opengl resources.

**Comment by wang-bin** [comment]
QtAV supports OSX VDA, linux VA-API + OpenGL rendering without data copy back. You can try the class `VideoSurfaceInterop`. You may need do some changes in my opengl code (VideoShader.cpp) to support other decoders.

**Comment by allbabel** [comment]
I have been trying to do something like this on Windows a while ago and hit a wall.  I am looking at the WMF plugin in QtMultimedia, what should I be looking for in this plugin to help me understand the necessary work needed?

**Comment by wang-bin** [comment]
I think copy(share) textures from dxva decoded surface to ANGLE is enough. But I don't know how. You can read qtmultimedia/src/plugins/wmf/evrd3dpresentengine.cpp. I'm not sure whether we can do it without wmf. VLC is working on dxva 0-copy too.

**Comment by allbabel** [comment]
I have been digging further and yes it is possible using eglQuerySurfacePointerANGLE.  The example from Chromium shows how this can be done.  I have used shared resources in DirectX before using DXVA and DirectX textures so I know this can be done.  I have an external source of video frames decoded in DXVA surfaces so I am basically looking at hooking these surfaces with the QML renderer in QtAV.  

Looking through QtAV I am exploring whether I can attach a reference to my DXVA surface to a QtAV::VideoFrame and then using something like SurfaceInteropVAAPI transfer the DXVA to the Angle surface.  Is this the right way to go about this?

**Comment by allbabel** [comment]
I think I have fixed it, I will test it out and send a push request

**Comment by wang-bin** [comment]
@allbabel  Great!

Yes, you need a `VideoSurfaceInterop` like `SurfaceInteropVAAPI` and OSX `SurfaceInteropCVBuffer`. I'm not sure the whether APIs of `VideoSurfaceInterop` class are good enough to support variant hw decoders. Feel free to modify it.

**Comment by wang-bin** [comment]
latest code supports rendering dxva surfaces directly. ANGLE is required. I also add OpenGL extension support, but only works on an Intel GPU in my test.
