### ISSUE TITLE
Issue with drag and drop.

### ISSUE THREAD

**Issue by dearn44** [wang-bin/QtAV#444]
By playing around with the "player" example I noticed that dragging a video from a folder won't work most of the time. In MacOS it will usually crush saying

`Debug: status changed  "Loading..."
The program has unexpectedly finished.`

And on Windows it will make the window freeze.

The same videos play fine if I load them the traditional way.

PS. You might also want to edit a small typo that makes the app print -Debug: status changed  "Invalid meida"-

**Comment by wang-bin** [comment]
I don't know why. the url from drop is totally wrong, for example `/.file/id=6571367.2627438`

**Comment by dearn44** [comment]
Yes I should have said that the url ends up rather odd. I will try to see where the error is.

**Comment by wang-bin** [comment]
fixed in 00688ff
