### ISSUE TITLE
Video filters have no effect.

### ISSUE THREAD

**Issue by dearn44** [wang-bin/QtAV#446]
I had no idea there were video filter under the 'Setup' menu. 
I am trying many of them and clicking 'apply' but none has any effect on the video playing.

**Comment by wang-bin** [comment]
Is `Enable video` checked in AVFilter page?

**Comment by dearn44** [comment]
Yes it is. I forgot to mention that I also tested this with your binaries. I am leaving the parameters empty or trying to add some, the result is the same.

**Comment by wang-bin** [comment]
What's your platform? Is hardwared decoding enabled?
You can try parameters: swapuv

**Comment by dearn44** [comment]
I tested on MacOS Mavericks and Windows 7. I have the FFMpeg Selected in the decoder priority list.

One additional thing. The History list might need behaves oddly on my Mac as can be seen from the images (sometimes it does not scale up to allow for the time to be shown, and others the time gets displayed above the next item). Should I open a new issue for this?

![screen shot 2015-05-21 at 12 44 01](https://cloud.githubusercontent.com/assets/11329941/7746995/424842a4-ffb7-11e4-9857-4974e20052d3.png)
![screen shot 2015-05-21 at 12 44 17](https://cloud.githubusercontent.com/assets/11329941/7746996/451d0528-ffb7-11e4-9a52-4a708fceec32.png)

**Comment by wang-bin** [comment]
You can try the latest windows build from here (QtAV-Qt5.4.0-VS2013x86-7bffd07.7z): https://sourceforge.net/projects/qtav/files/ci/
You have to rename bin/OpenAL32-vc.dll to OpenAL32.dll 
I tested that binary just now and it works fine.

I'm not familiar with ui. ui is in a low priority in this project. If you know how to fix the history list, you can contribute your code.

**Comment by dearn44** [comment]
I will try, thanks.

**Comment by dearn44** [comment]
Just tried the latest build and still nothing. It probably has to do with my system (maybe my HD 4000 gpu) because if I chose some other decoder except ffmpeg (in mac or windows) it reports missing video codecs and it plays only the sound.

**Comment by wang-bin** [comment]
Filters in avfilter are cpu filters. I don't know why you failed.

**Comment by dearn44** [comment]
Filters are indeed working fine, I don't know what was the problem at that point. Maybe I accidentally changed something in the code. 
Also the issue with the list is present only in MacOS as far as I can tell. So basically all is fine.
