### ISSUE TITLE
qt5.4.1在windows上编译qtav成功后，使用编译出错的问提。

### ISSUE THREAD

**Issue by wujialiang** [wang-bin/QtAV#447]
C:/Qt/Qt5.4.1/Tools/mingw491_32/bin/../lib/gcc/i686-w64-mingw32/4.9.1/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lQt5AVd
collect2.exe: error: ld returned 1 exit status
Makefile.Debug:78: recipe for target 'debug\ktv.exe' failed
mingw32-make[1]: *** [debug\ktv.exe] Error 1
mingw32-make[1]: Leaving directory 'D:/svn/app/ktv/ktv'
makefile:34: recipe for target 'debug' failed
mingw32-make: *** [debug] Error 2
17:16:24: 进程"C:\Qt\Qt5.4.1\Tools\mingw491_32\bin\mingw32-make.exe"退出，退出代码 2 。
Error while building/deploying project ktv (kit: Desktop Qt 5.4.1 MinGW 32bit)
When executing step "Make"
17:16:24: Elapsed time: 00:17.

你好，我下载了qtav的源码，自己编译成功后，然后编译自己的程序，再debug模式下编译后，出现上面的错误，请问是什么原因呢？
然后我切换到release模式后，编译成功通过，但是运行的时候报下面的错误：
Starting D:\svn\app\ktv\ktv\release\ktv.exe...
qrc:/Singer/SingerMainWindow.qml:3 qrc:/Singer/SingerMainWindow.qml:3:1: plugin cannot be loaded for module "QtAV": ????????C:/Qt/Qt5.4.1/5.4/mingw491_32/qml/QtAV/QmlAV.dll?????????????????

请问是什么问题呢？
然后我下载了QtAV1.6.0-MinGW32安装后，直接编译release版本，成功，运行也成功。

qt版本：5.4.1
编译器：mingw32
操作系统：win7、win8 64位
下载的qt安装文件：qt-opensource-windows-x86-android-5.4.1

**Comment by xiaoweiChen** [comment]
`ld.exe: cannot find -lQt5AVd` 没有找到对应的库文件。编译的时候，最好先编译Qt5AV这个工程，然后再一起编译。你可以试试在debug模式下多编译几次。

**Comment by wujialiang** [comment]
问题是qtav我已经编译好，并且运行相关的脚本安装到qt的目录上，也检查过库文件是存在的，就是不能载入，很奇怪。

**Comment by wang-bin** [comment]
ffmpeg, openal的dll放对位置了没？你可以双击运行非qml的播放程序看看提示缺少什么dll。我上传的QtAV1.6.0-MinGW32是链接到静态库的不需要那些dll就能运行

**Comment by wujialiang** [comment]
解决了，谢谢。怪不得了，我看我编译后的dll比你编译出来的大小要小，原来是静态编译的。
请问相关的api接口说明，您是否会编写出来呢？现在只能看example来照着做，里面具体有多少的api，还不是好清楚哦。

在 2015-05-25 11:09:52，"WangBin" <notifications@github.com> 写道：


ffmpeg, openal的dll放对位置了没？你可以双击运行非qml的播放程序看看提示缺少什么dll。我上传的QtAV1.6.0-MinGW32是链接到静态库的不需要那些dll就能运行

**Comment by wang-bin** [comment]
接口主要看AVPlayer.h的public成员,signal slots及注释，可能还要看QtAV.h里罗列的其他头文件，看你需求。所有给应用开发的文件都在QtAV.h里了
