### ISSUE TITLE
VS2013中编译到qml部分引起MsBuild错误

### ISSUE THREAD

**Issue by xiaoweiChen** [wang-bin/QtAV#448]
```
1>  QmlAV.vcxproj -> E:\QtAV\qml\..\lib_win_\QmlAVd.dll
1>  '-' 不是内部或外部命令，也不是可运行的程序
1>  或批处理文件。
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(133,5): error MSB3073: 命令“
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(133,5): error MSB3073: if errorlevel 1 goto VCEnd
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(133,5): error MSB3073: - E:\QtAV\lib_win_\QmlAVd.dll E:\QtAV\bin\QtAV\
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd”已退出，代码为 9009。
```
我使用的是windows 7 64bit。

在qmake阶段应该对系统类型做判定的吧。是64bit不支持么？ 为什么我的目标文件夹会是“lib_win_”……

**Comment by wang-bin** [comment]
不知道什么问题。`'-' 不是内部或外部命令，也不是可运行的程序`它是执行了什么可以知道么？
64位支持，文件夹名没显示无影响

**Comment by xiaoweiChen** [comment]
在.obj文件夹下，我也看到了很多类似与“ao_win_”这样的文件夹。从其他博客上看到的，这里应该是和平台相关的字符，比如32bit平台，应该是“ao_win_x86”。不过，没有看到有人分享在64bit下编译的过程。这里的命令我觉得和这个有关系，很有可能命令需要的是-x86或-x64这样的选项，但是在某个过程中，平台没有去判别，所以造成这个选项的拼接出错，从而造成在命令中出现“-”的情况。

不过，具体的原因我还不清楚是为什么。

会和我将`error("libavresample or libswresample is required. Setup your environment correctly then delete $$BUILD_DIR/.qmake.conf and run qmake again")`在pro文件中注掉有关么？

**Comment by wang-bin** [comment]
没检测出来不影响编译和功能。为什么没检测出来我也不清楚。你是怎么运行qmake的？qtcreator里还是命令行还是其他？
另外你可以用命令行进入到QtAV/tests/arch进行qmake看看warning里有没有`ARCH=x86_64`等

**Comment by xiaoweiChen** [comment]
① 参照你在wiki中给出的命令`qmake -tp -r QtAV.pro`，是在windows下，使用Qt命令行下执行的，用来生成VS2013的工程文件。
②test部分，因为我使用的是Qt5.4.1，所以，根据qmake的提示：
>Project MESSAGE: target arch:
>Project MESSAGE: target arch features:
>Project MESSAGE: To disable config tests, you can use 1 of the following methods
>Project MESSAGE: 1. create '.qmake.conf' in the root source dir, add 'CONFIG += no_config_tests'(Qt5)
>Project MESSAGE: 2. pass 'CONFIG += no_config_tests' or '-config no_config_tests ' to qmake
>Project MESSAGE: 3. add 'CONFIG += no_config_tests' in E:/QtAV/user.conf

这里target arch和target arch features为空，会是这个原因么？

我就在.qmake.conf添加了CONFIG +=no_config_tests。

③注掉那个error()，是因为在windows下，这个error每次都会走到。所以，我就注掉了。这个error函数本身并不影响任何函数的执行。[error(string)](http://doc.qt.io/qt-5/qmake-test-function-reference.html#error-string)

我编译的过程我在[#428](https://github.com/wang-bin/QtAV/issues/428)中有所描述，以及我注掉error那行的具体原因。

**Comment by wang-bin** [comment]
我不清楚，自己试了下没有任何问题

**Comment by wang-bin** [comment]
`-` 命令错误我遇到了，之前的命令是给makefile写的，msbuild不能识别

**Comment by wang-bin** [comment]
msbuild的错误在最新的代码里修复了，可以正常编译。关于你的检测不到x86_64和swresample我不清楚怎么回事，我这里一切正常

**Comment by wang-bin** [comment]
fixed in 15558fd
