### ISSUE TITLE
Cannot play android QML app. plugin "QmlAV" not found

### ISSUE THREAD

**Issue by eewann** [wang-bin/QtAV#449]
sorry..my english is bad..i'm new with c++

i download qtav 1.6 and follow this guide ( https://github.com/wang-bin/QtAV/wiki/Deploy-SDK-Without-Building-QtAV ) and try to build cross platform ( desktop and android ) qml player.
Everything ok with desktop build but for android i got error <b>"module "QtAV" plugin "QmlAV" not found"</b> at runtime

then i try this ( https://github.com/wang-bin/QtAV/wiki/Make-app-for-Android ) and got <b>"avutil is required, but compiler can not find it"</b>

then i upgrade Qt to version 5.5 and got same problem..
can some one guide me how to make app that work for desktop and android??

here the code :
```
import QtQuick 2.4
import QtQuick.Window 2.2
import QtAV 1.5

Window {
    visible: true
    MainForm {
        anchors.fill: parent
        mouseArea.onClicked: {
            Qt.quit();
        }
        VideoOutput {
                anchors.fill: parent
                source: player
        }

        AVPlayer { //or MediaPlayer
            id: player
            source: "/storage/sdcard/op.mp4"
            autoPlay: true
        }
    }
}
````

**Comment by wang-bin** [comment]
did you put ffmpeg, openal include and lib to Qt's lib and lib dir?

**Comment by eewann** [comment]
yes i have

**Comment by wang-bin** [comment]
show me you config.log in qtav build dir. btw, I only tested android on linux and osx. I'm not sure whether you can build on windows

**Comment by eewann** [comment]
sorry for late reply
i try to build at ubuntu
this is log for linux build..and application output..

http://www.mediafire.com/download/u6j19z7mwdtk0j8/Log.zip

**Comment by wang-bin** [comment]
Sorry I didn't see it. can you upload your log again?

**Comment by eewann** [comment]
it is ok now. after I installed some tools and libraries. just a matter of performance on some device(rk3066)..

**Comment by wang-bin** [comment]
Fine. I think using hw decoder(omx) is the only way to improve performance.
