### ISSUE TITLE
Question：如何使用ffmpeg API对播放中的视频进行加/减速

### ISSUE THREAD

**Issue by xiaoweiChen** [wang-bin/QtAV#450]
想在播放的时候进行加速或减速，在打包好的播放器（player）中已经有这个功能了。

恩，在其他地方没有找到相关的资料。所以，这里想请教一下，这个功能应该如何做。

这里可否告诉一下，应该去看哪一个函数实现么？

或者，是否有相关的资料可以分享一下呢？

谢谢！！

**Comment by wang-bin** [comment]
这个和ffmpeg无关。`void AVPlayer::setSpeed(qreal)`
