### ISSUE TITLE
Bug : 【黑盒测试】连续播放小于3s的音频，播放器会有重放问题

### ISSUE THREAD

**Issue by xiaoweiChen** [wang-bin/QtAV#452]
由于编译代码遇到一些问题，这里就想尝试提供好的sdk。在使用sampleplayer的时候发现播放短音频的时候会出现问题，然后就相继测试了一下已编译好的player和QMLPlayer，发现在我这边都有问题。下面具体描述一下这个问题：

测试对象：
`QtAV1.6.0-VS2013x64.exe`
`QtAV1.6.0-VS2013x86.exe`
`QtAV1.6.0-MinGW32.exe`
中提供的player.exe和QMLPlayer.exe。

平台：
windows7 sp1 64bit

测试用例：
总长度小于3s的wav格式文件

bug描述
在播放完长度小于3s的音频时，再次播放其他音频或本音频会再次播放之前音频中最后的1~0.5s的内容。

复现步骤：
一：
① 播放一个长度小于3s的音频。
② 结束后，按下“play”键进行再次播放是，出现bug描述中的情况。
二：
① 播放一个长度小于3s的音频
② 结束后，打开另外一个小于3s的文件，出现bug描述中的情况。

PS. 这里尝试在播放完小音频文件后，再播放视频，并没出现bug描述中的现象。

因为音频没法附件，一会儿把我用的几个音频测试文件以邮件文件发你，看在你那里是否能复现。

**Comment by wang-bin** [comment]
已证实，待查

**Comment by wang-bin** [comment]
已修
