### ISSUE TITLE
Seek video by moving the slide bar.

### ISSUE THREAD

**Issue by dearn44** [wang-bin/QtAV#455]
Using the player example as a reference, currently one can seek either when the mouse is pressed or released in the slider. 
Some players though update the video even while you are dragging the slider. 

Is there a way to achieve something similar here too?

**Comment by wang-bin** [comment]
You mean seek when signal `sliderMoved(int value)` is emitted?

It's not a QtAV issue. It's about UI.

**Comment by dearn44** [comment]
Yeah thats what I meant. 
Thanks for the reply.
