### ISSUE TITLE
Stream program and track selecting

### ISSUE THREAD

**Issue by wswjwjcjlu** [wang-bin/QtAV#456]
I'm trying to be able to change a program in a multi-program stream. The API I can get is:

    bool setAudioStream(int n);
    bool setVideoStream(int n);
    bool setSubtitleStream(int n);
    int currentAudioStream() const;
    int currentVideoStream() const;
    int currentSubtitleStream() const;
    int audioStreamCount() const;
    int videoStreamCount() const;
    int subtitleStreamCount() const;

Is it possible if I can get program info and change programs in the same way like VLC or ffplay?

And is it possible if I can get the pids of audio/video/subtitle streams(tracks) instead of just the order?

**Comment by wang-bin** [comment]
What is `program`? what is pid?

**Comment by wswjwjcjlu** [comment]
A program is a combination of 1 or more audio/video/subtitle tracks. It's very common in .ts (MPEG-2) files. And pid means the packet identifier. If you can access wiki, check this page:

http://en.wikipedia.org/wiki/MPEG_transport_stream
