### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by aratkevich** [wang-bin/QtAV#458]
void AVPlayer::Private::initCommonStatistics(int s, Statistics::Common *st, AVCodecContext *avctx)
{
    if(!fmt_ctx) {
        qDebug() << " ---------------------- fmt_ctx is NULL (crash)";
        qDebug() << "return - no crash";
        return;
    }
    AVStream *stream = fmt_ctx->streams[s];
....

**Comment by wang-bin** [comment]
I got this crash a few times. But i don't understand when fmt_ctx can be null

Anyway, I will add this null check

**Comment by wang-bin** [comment]
BTW, how can I reproduce this crash?

**Comment by aratkevich** [comment]
Hi.
My code:
I create list video files in QListWidget and create preview image for each
item.

QList<QListWidgetItem*> listItem;

slot_createPreview();



void PageVideoMultimedia::slot_createPreview()

{

    if(!listItem.isEmpty()) {

        itemPreview = listItem.takeFirst();

        QString filename = itemPreview->data(FILENAME_ROLE).toString();


        m_playerCreatePreview = new AVPlayer(this);

    #ifndef QT_NO_OPENGL

        VideoRendererId vid = VideoRendererId_GLWidget2;

    #else

        VideoRendererId vid = VideoRendererId_Widget;

    #endif

        QtAV::VideoOutput *videoOutput = new VideoOutput(vid, this);

        if (!videoOutput->widget()) {

            QMessageBox::warning(0, "QtAV error", "Can not create
video renderer");

            return;

        }

        m_playerCreatePreview->setRenderer(videoOutput);

        m_playerCreatePreview->videoCapture()->setAutoSave(false);

        m_playerCreatePreview->setMute(true);

        connect(m_playerCreatePreview->videoCapture(),
SIGNAL(imageCaptured(QImage)), this,
SLOT(slot_createPreview(QImage)));

        connect(m_playerCreatePreview->videoCapture(),
SIGNAL(failed()), this, SLOT(slot_failed()));

        connect(m_playerCreatePreview, SIGNAL(started()), this,
SLOT(slot_preview_start()));

        //qDebug() << "[slot_createPreview] filename:" << filename;

        m_playerCreatePreview->play(filename);

    }

}


void PageVideoMultimedia::slot_preview_start()

{

    QTime duration = m_playerCreatePreview->statistics().duration;

    m_playerCreatePreview->seek((double)duration.msecsSinceStartOfDay()/2.f);

    m_playerCreatePreview->videoCapture()->request();

}


void PageVideoMultimedia::slot_failed()

{

    //qDebug() << "failed VIDEO (!)";

    m_playerCreatePreview->videoCapture()->request();

}

void PageVideoMultimedia::slot_createPreview(QImage image)

{

    //qDebug() << "slot_createPreview" << image;

    QPixmap pixmap = QPixmap::fromImage(image);

    m_playerCreatePreview->stop();

    m_playerCreatePreview->unload();

    itemPreview->setIcon(QIcon(pixmap));

    m_playerCreatePreview->deleteLater();

    slot_createPreview();

}



вт, 2 июня 2015 г. в 6:33, WangBin <notifications@github.com>:

**Comment by wang-bin** [comment]
can you try latest code

**Comment by aratkevich** [comment]
Works! Don't crash... ))

**Comment by wang-bin** [comment]
I just check null ptr as you mentioned.

btw, if you want to capture video frames without playback,  `VideoFrameExtractor` is a better choice. It's lightweight. You can read  tests/extract.

**Comment by aratkevich** [comment]
Yes, it would be better. Thank you!
