### ISSUE TITLE
Building fails on arm-linux-gnuabihf

### ISSUE THREAD

**Issue by guillaumesmo** [wang-bin/QtAV#460]
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQTAV_HAVE_GUI_PRIVATE=1 -DBUILD_QTAV_LIB -DQTAV_HAVE_CHARDET=1 -DBUILD_CHARDET_STATIC -D__STDC_CONSTANT_MACROS -DQTAV_HAVE_SWRESAMPLE=1 -DQTAV_HAVE_AVDEVICE=1 -DQTAV_HAVE_AVFILTER=1 -DQTAV_HAVE_OPENAL=1 -DQTAV_HAVE_PULSEAUDIO=1 -DQTAV_HAVE_CUDA=1 -DQTAV_HAVE_VAAPI=1 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/root/QtAV/src -I/usr/include/qt5 -I/root/QtAV/src -I/root/QtAV -I/root/QtAV/src/QtAV -I/root/QtAV/contrib/libchardet/src -I/root/QtAV/contrib/capi -I/root/QtAV/src/cuda -I/root/QtAV/src/cuda/dllapi -I/usr/include/qt5/QtGui/5.2.1 -I/usr/include/qt5/QtGui/5.2.1/QtGui -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I../.moc/5.2.1/QtAV -I. -o ../.obj/QtAV_linux_arm/moc_OpenGLVideo.o ../.moc/5.2.1/QtAV/moc_OpenGLVideo.cpp
/root/QtAV/src/codec/video/VideoDecoderVAAPI.cpp: In member function ‘virtual bool QtAV::VideoDecoderVAAPIPrivate::open()’:
/root/QtAV/src/codec/video/VideoDecoderVAAPI.cpp:545:41: error: expected primary-expression before ‘(’ token
         interop_res = InteropResourcePtr(new X11InteropResource());
                                         ^
/root/QtAV/src/codec/video/VideoDecoderVAAPI.cpp:545:46: error: expected type-specifier before ‘X11InteropResource’
         interop_res = InteropResourcePtr(new X11InteropResource());

Qt 5.2.1
ffmpeg 2.4.3

Do you have any clue ?

**Comment by wang-bin** [comment]
I have no idea. travis-ci can build QtAV with different Qt+FFmpeg combinations. https://travis-ci.org/wang-bin/QtAV

Do you have other errors? What's your compiler version?

**Comment by guillaumesmo** [comment]
It's the only error I get. My compiler is GCC 4.9.2

**Comment by wang-bin** [comment]
it's strange. what about no crosscompile?

**Comment by guillaumesmo** [comment]
I took off config_vaapi in CONFIG, I'll recompile again

**Comment by guillaumesmo** [comment]
Unfortunately I get this error right now (libraries seem to have been compiled successfully but the examples fail)

/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_PeepEvents'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_UnlockYUVOverlay'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_get_encoder_delay'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_decode'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `x264_encoder_close'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_process_data'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `x264_bit_depth'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `aacDecoder_DecodeFrame'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `xcb_shm_query_version_reply'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `jack_deactivate'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_set_bWriteVbrTag'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_set_style_overrides'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `x264_encoder_headers'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `aacDecoder_AncDataInit'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_get_cx_data'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_get_framesize'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `x264_encoder_encode'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `xcb_shm_get_image'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `jack_activate'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `xcb_shape_rectangles'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_FreeYUVOverlay'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `aacDecoder_GetStreamInfo'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `jack_port_get_buffer'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_PumpEvents'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_FillRect'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_CondSignal'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_DisplayYUVOverlay'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_WaitThread'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `aacEncEncode'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_mutexP'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_process_codec_private'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `aacDecoder_Close'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `x264_encoder_reconfig'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `aacDecoder_Fill'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `aacEncOpen'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_set_brate'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_Quit'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lzma_code'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `jack_port_register'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_vp9_cx'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `x264_param_parse'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `BZ2_bzDecompress'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_error'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_set_in_samplerate'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_new_track'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `jack_set_process_callback'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_MapRGB'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `pp_free_context'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `jack_on_shutdown'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `th_encode_ycbcr_in'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `opus_multistream_decode'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lzma_end'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `xcb_shm_attach'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `pp_postprocess'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_Delay'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `opus_multistream_decoder_create'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vaRenderPicture'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `opus_multistream_decoder_ctl'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_SetVideoMode'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_set_disable_reservoir'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `jack_frames_since_cycle_start'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_CreateYUVOverlay'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_vp9_dx_algo'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_control_'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `opus_multistream_encode_float'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_err_to_string'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `pp_free_mode'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_WM_SetCaption'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `aacDecoder_SetParam'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `opus_multistream_encoder_destroy'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_set_VBR'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_close'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `xcb_xfixes_get_cursor_image'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `jack_client_close'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_set_fonts'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_encode_buffer_int'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_CreateThread'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vaCreateBuffer'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_add_font'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_CondWait'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `th_info_init'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_set_aspect_ratio'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_set_message_cb'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_set_mode'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `opus_multistream_encoder_ctl'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vaMapBuffer'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `x264_param_apply_profile'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_get_caps'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_vp8_cx'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `th_comment_clear'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `th_comment_init'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `jack_set_xrun_callback'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `jack_get_sample_rate'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `opus_multistream_encode'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vaDestroyBuffer'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_mutexV'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `xcb_xfixes_get_cursor_image_cursor_image'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `th_encode_packetout'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_set_VBR_quality'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `aacDecoder_ConfigRaw'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_render_frame'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `x264_param_apply_fastfirstpass'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vaEndPicture'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_CreateMutex'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_version'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `opus_multistream_encoder_create'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `xcb_xfixes_query_version'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `th_encode_ctl'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_set_shaper'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_vp8_dx_algo'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_encode_buffer_float'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_destroy'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `x264_levels'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_DestroyCond'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_renderer_done'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_build_config'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `pp_get_context'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `jack_client_open'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_encode'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `aacEncInfo'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `x264_picture_init'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vaUnmapBuffer'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_LockYUVOverlay'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_read_file'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `x264_param_default'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `th_info_clear'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `th_encode_alloc'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `aacDecoder_Open'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_library_done'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `x264_encoder_open_142'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `th_encode_free'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_WasInit'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `opus_multistream_decode_float'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `x264_param_default_preset'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_get_frame'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `xcb_shm_detach'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_set_quality'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_free_track'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `xcb_shm_get_image_reply'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_DestroyMutex'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_error_detail'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `jack_get_buffer_size'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_GetError'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_set_num_channels'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `pp_get_mode_by_name_and_quality'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `xcb_xfixes_query_version_reply'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_library_init'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_img_wrap'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_encode_buffer'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_version_str'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `xcb_xfixes_get_cursor_image_reply'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_CreateCond'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `aacEncoder_SetParam'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_set_frame_size'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_init'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `xcb_shm_query_version'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vaBeginPicture'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_dec_init_ver'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `BZ2_bzDecompressInit'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lzma_stream_decoder'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_UpdateRect'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_enc_init_ver'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `x264_encoder_delayed_frames'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `BZ2_bzDecompressEnd'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `th_encode_flushheader'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_encode_flush'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `ass_renderer_init'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_init_params'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `aacEncClose'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `SDL_Init'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `opus_multistream_decoder_destroy'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_set_out_samplerate'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `vpx_codec_enc_config_default'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `lame_set_VBR_mean_bitrate_kbps'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `opus_strerror'

**Comment by wang-bin** [comment]
You ffmpeg is linked to a lot of libraries. add link flags like `LIBS += -lSDL -lvpx ...` in src/libQtAV.pri. You can get link flags by `pkg-config --libs libavcodec libavformat libavresample libavfilter libavdevice libswscale`. Or you can build your own ffmpeg without those depends. 
BTW, are you linking to static libs?

**Comment by guillaumesmo** [comment]
I built a custom ffmpeg for this (static) but I can't tell QtAV to not use the machine ffmpeg.

**Comment by guillaumesmo** [comment]
In the meantime, I found this : 
```
# PKG_CONFIG_LIBDIR=~/ffmpeg_build/lib/pkgconfig pkg-config --libs libavcodec libavformat libswresample libavfilter libavdevice libswscale
-pthread -L/root/ffmpeg_build/lib -lavdevice -lavfilter -lavformat -lavcodec -lva-x11 -lva -lxcb-shm -lxcb-xfixes -lxcb-render -lxcb-shape -lxcb -lXau -lXdmcp -ljack -lSDL -lasound -ldl -lpulse-simple -lpulse -lX11 -lXext -lcaca -lpthread -llzma -lbz2 -lz -lrt -lswresample -lswscale -lavutil -lm
```

Adding them to the libQtAV.pri like you advised yields much less errors : 

```
g++ -Wl,-z,origin '-Wl,-rpath,/root/QtAV/build/lib_linux_arm' '-Wl,-rpath,$ORIGIN' '-Wl,-rpath,$ORIGIN/lib' '-Wl,-rpath,.' '-Wl,-rpath,/usr/local/lib' '-Wl,-rpath,/usr/lib/arm-linux-gnueabihf' -Wl,-O1 -o ../../bin/simpleplayer ../../.obj/simpleplayer_linux_arm/main.o ../../.obj/simpleplayer_linux_arm/playerwindow.o ../../.obj/simpleplayer_linux_arm/moc_playerwindow.o   -pthread -L/root/ffmpeg_build/lib -lavdevice -lavfilter -lavformat -lavcodec -lva-x11 -lva -lxcb-shm -lxcb-xfixes -lxcb-render -lxcb-shape -lxcb -lXau -lXdmcp -ljack -lSDL -lasound -ldl -lpulse-simple -lpulse -lX11 -lXext -lcaca -llzma -lbz2 -lz -lrt -lswresample -lswscale -lavutil -lm -L/root/QtAV/build/lib_linux_arm -lQtAV -lQtAVWidgets -lQt5OpenGL -L/usr/lib/arm-linux-gnueabihf -lQt5Widgets -lQt5Gui -lQt5Core -lGLESv2 -lpthread 
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `av_rdft_end'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `av_adler32_update'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `avpriv_init_elbg'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `av_rdft_calc'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `av_rdft_init'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `avpriv_do_elbg'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `av_fft_end'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `av_fft_init'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `av_fft_calc'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `av_fft_permute'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `av_pixelutils_get_sad_fn'
```

Do you have any idea? This time I used the 2.7 ffmpeg from git

**Comment by wang-bin** [comment]
If you build ffmpeg yourself, you can disable many things when run configure for ffmpeg because they are useless, for example sdl. QtAV's encoding is not finished yet, you can disable encoders and muxers in ffmpeg too. Many dependencies are for encoders, such as opus, lame and vpx, you can disable them(actually they are disabled by default in ffmpeg). You can try

    ./configure --enable-pic --enable-runtime-cpudetect --enable-hwaccels --disable-postproc --disable-muxers --disable-encoders --disable-sdl --disable-lzma

`av_xxx` functions are in libavutil and libavcodec. If you are using static ffmpeg libs, additional link flags are required `-Wl,-Bsymbolic`, or you can pass `"CONFIG+=static_ffmpeg"` to qmake

I don't know how to not use system ffmpeg libs either. I uninstall them. Using system libs is fine too. I plan to add pkg-config support in qmake project files to fix link error

**Comment by chenfisher** [comment]
I'm having the same issue (regarding vaapi)
I disabled vaapi using ```CONFIG += no_vaapi``` in user.conf

now I'm getting this error:
#462

**Comment by guillaumesmo** [comment]
I recompiled ffmpeg without muxers, encoders, sdl, lzma and fft:
```
PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure --prefix="$HOME/ffmpeg_build" --pkg-config-flags="--static" --extra-cflags="-I$HOME/ffmpeg_build/include" --extra-ldflags="-L$HOME/ffmpeg_build/lib" --bindir="$HOME/bin" --enable-pic --enable-runtime-cpudetect --enable-hwaccels --disable-postproc --disable-muxers --disable-encoders --disable-sdl --disable-lzma --disable-fft --extra-cflags=" -O3 " --extra-libs=" -lrt" --enable-thumb
```

But I still get the following errors, I'm not sure what I have to disable more to get rid of this

```
g++ -Wl,-z,origin '-Wl,-rpath,/root/QtAV/build/lib_linux_arm' '-Wl,-rpath,$ORIGIN' '-Wl,-rpath,$ORIGIN/lib' '-Wl,-rpath,.' '-Wl,-rpath,/usr/local/lib' '-Wl,-rpath,/usr/lib/arm-linux-gnueabihf' -Wl,-O1 -o ../../bin/sharedoutput ../../.obj/sharedoutput_linux_arm/main.o ../../.obj/sharedoutput_linux_arm/widget.o ../../.obj/sharedoutput_linux_arm/moc_widget.o   -pthread -L/root/ffmpeg_build/lib -lavdevice -lavfilter -lavformat -lavcodec -lva-x11 -lva -lxcb-shm -lxcb-xfixes -lxcb-render -lxcb-shape -lxcb -lXau -lXdmcp -lX11 -ljack -lasound -lbz2 -lz -lrt -lswresample -lswscale -lavutil -lm -L/root/QtAV/build/lib_linux_arm -lQtAV -lQtAVWidgets -lQt5OpenGL -L/usr/lib/arm-linux-gnueabihf -lQt5Widgets -lQt5Gui -lQt5Core -lGLESv2 -lpthread 
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `av_adler32_update'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `avpriv_init_elbg'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `avpriv_do_elbg'
/root/QtAV/build/lib_linux_arm/libQtAV.so: undefined reference to `av_pixelutils_get_sad_fn'
```

**Comment by wang-bin** [comment]
I'm not sure. You didn't add `-Wl,-Bsymbolic` to your link flags. run qmake again like this

    qmake -r "CONFIG+=static_ffmpeg"

You also can set "CONFIG+=static_ffmpeg" in qtcreator
