### ISSUE TITLE
Get previous frame

### ISSUE THREAD

**Issue by LucaGallinari** [wang-bin/QtAV#463]
Is it possible somehow to get the previous frame?
In AVPlayer there's a method for the next frame "playNextFrame()" but not for the previous frame.

**Comment by wang-bin** [comment]
It's in my plan. But it's complex. I have to decode almost the frames between the nearest key frame before target frame and target frame to get a complete target frame.

**Comment by wang-bin** [comment]
Now you can use AVPlayer.stepBackward()
