### ISSUE TITLE
Error when run QtAV QML Android application on Android 4.2.2

### ISSUE THREAD

**Issue by sk2212** [wang-bin/QtAV#464]
Building process is fine but when I want to execute created APK file on my Android device with Android 4.2.2 I got following error:

E/dalvikvm(23236): dlopen("/data/data/org.qtproject.example.AndroidQmlAV/lib/libavcodec.so") failed: Cannot load library: soinfo_relocate(linker.cpp:975): cannot locate symbol "log2f" referenced by "libavcodec.so"...
W/System.err(23236): java.lang.reflect.InvocationTargetException
W/System.err(23236): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(23236): 	at java.lang.reflect.Method.invoke(Method.java:511)

Running application on Android 5.1.1 works fine.

What is wrong here? I compiled ffmpeg from latest git sources with build-script located in QtAv/scripts. I am using ANDROID NDK 10e.

I am building against Android API

android:targetSdkVersion="19"

Can someone help?

**Comment by wang-bin** [comment]
I think you have to use gcc 4.6 to build ffmpeg to let it run on old android. If you use gcc 4.8, the symbols can be found when building, but maybe not exists in runtime environment

**Comment by sk2212** [comment]
Okay...I will do the same process again with gcc4.6 and Android NDK 9. Well, can you tell me how to adjust build_ffmpeg script to use gcc4.6?

**Comment by wang-bin** [comment]
`  test -d $ANDROID_TOOLCHAIN_DIR || $NDK_ROOT/build/tools/make-standalone-toolchain.sh --platform=android-19 --toolchain=${ANDROID_TOOLCHAIN_PREFIX}-4.8 --install-dir=$ANDROID_TOOLCHAIN_DIR #--system=linux-x86_64`

change 4.8 to 4.6 in that line

**Comment by sk2212** [comment]
Hmmm...does not work. Still the same error. 

QtAV runs also on Android 4.2.2, right? Can you provide a sample application for testing?

**Comment by wang-bin** [comment]
please try ffmpeg 2.7.0 package here https://sourceforge.net/projects/qtav/files/depends/FFmpeg/android/

I build it with gcc4.6 and no symbol `log2f`. It should work

**Comment by sk2212** [comment]
Thank you! Unfortunately the archive file is corrupt. Can you please check? Other files from your link are working fine.

**Comment by wang-bin** [comment]
updated. try again please

**Comment by sk2212** [comment]
Works now! Big thanks!
