### ISSUE TITLE
QMLPlayer on Android  main.qml file not found

### ISSUE THREAD

**Issue by ShijinXincoz** [wang-bin/QtAV#473]
uI am using Qt5.3 to build QMLPlayer. I got the apk file correctly but when i run it shows some error messages like  
W/Qt      ( 1391): kernel/qcoreapplication.cpp:433 (QCoreApplicationPrivate::QCoreApplicationPrivate(int&, char**, uint)): WARNING: QApplication was not created in the main() thread.
D/libEGL  ( 1391): loaded /system/lib/egl/libGLES_android.so
D/dalvikvm( 1391): GC_CONCURRENT freed 517K, 7% free 9258K/9863K, paused 9ms+7ms
D/libEGL  ( 1391): loaded /system/lib/egl/libEGL_emulation.so
D/        ( 1391): HostConnection::get() New Host Connection established 0x177000, tid 1391
D/libEGL  ( 1391): loaded /system/lib/egl/libGLESv1_CM_emulation.so
D/libEGL  ( 1391): loaded /system/lib/egl/libGLESv2_emulation.so
W/EGL_emulation( 1391): eglSurfaceAttrib not implemented
D/OpenGLRenderer( 1391): Enabling debug mode 0
D/Qt      ( 1391): /home/shijin/QtAndroid/QtAV/examples/QMLPlayer/main.cpp:48 (int main(int, char**)): arguments=======  ("/data/data/org.qtav.qmlplayer/lib/libQMLPlayer.so")
D/Qt      ( 1391): /home/shijin/QtAndroid/QtAV/examples/QMLPlayer/main.cpp:60 (int main(int, char**)): ("/data/data/org.qtav.qmlplayer/lib", "/data/data/org.qtav.qmlplayer/qt-reserved-files/qml")
D/Qt      ( 1391): /home/shijin/QtAndroid/QtAV/examples/QMLPlayer/main.cpp:62 (int main(int, char**)): >>>>>>>>devicePixelRatio: 1.000000
D/Qt      ( 1391): /home/shijin/QtAndroid/QtAV/examples/QMLPlayer/main.cpp:64 (int main(int, char**)): dpi phy:  239.059 , logical:  108 , dpr:  1 ; vis rect: QRect(0,0 480x800)
W/Qt      ( 1391): assets:/qrc:///qml/QMLPlayer/main.qml:-1 ((null)): assets:/qrc:///qml/QMLPlayer/main.qml: File not found
W/EGL_emulation( 1391): eglSurfaceAttrib not implemented
D/        ( 1391): HostConnection::get() New Host Connection established 0x26a190, tid 1444
D/        ( 1391): HostConnection::get() New Host Connection established 0x273778, tid 1455
D/Qt      ( 1391): /home/shijin/QtAndroid/QtAV/examples/QMLPlayer/main.cpp:135 (int main(int, char**)): file:  ""
W/Qt      ( 1391): kernel/qobject.cpp:2603 (static QMetaObject::Connection QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)): QObject::connect: Cannot connect (null)::requestFullScreen() to QtQuick2ApplicationViewer::showFullScreen()
W/Qt      ( 1391): kernel/qobject.cpp:2603 (static QMetaObject::Connection QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)): QObject::connect: Cannot connect (null)::requestNormalSize() to QtQuick2ApplicationViewer::showNormal()
D/Qt      ( 1391): /home/shijin/QtAndroid/QtAV/examples/common/ScreenSaver.cpp:260 (bool ScreenSaver::retrieveState()): ScreenSaver::retrieveState
D/Qt      ( 1391): /home/shijin/QtAndroid/QtAV/examples/common/ScreenSaver.cpp:243 (bool ScreenSaver::enable(bool)): Succeed to enable screen saver (0)

When i install apk on device just shows white screen. can you please help me fix this issue.

**Comment by wang-bin** [comment]
It's weird.

**Comment by ShijinXincoz** [comment]
issue solved by recompile ffmpeg with gcc4.6
