### ISSUE TITLE
Video fading question

### ISSUE THREAD

**Issue by bongas** [wang-bin/QtAV#475]
Hi,

Is it possible to fade in/out the video somehow?
I'm trying to implement a playlist where I want the previous video fade out to black and then the new video fade in from black. Would it also be possible to use two AVPlayers and fade the first video into the second?

I'm using widget based AVPlayer with OpenGLWidget renderer.

Thanks

**Comment by wang-bin** [comment]
You can use LibAVFilter.h

Test in player:  open menu->Setup->AVFilter page, enable video filters, set parameters `fade=type=0:start_time=0:duration=2:color=black, fade=type=1:start_time=T-1:duration=1:color=black`, where `T-1` is the value of video duration-1.

C++:

    LibAVFilter *vf = new LibAVFilter(player);
    player->installVideoFilter(vf);
    ....
    vf->setOptions("fade=type=0:start_time=0:duration=2:color=black, fade=type=1:start_time=T-1:duration=1:color=black");
    ...
