### ISSUE TITLE
Build QtAVPlayer for Android

### ISSUE THREAD

**Issue by ShijinXincoz** [wang-bin/QtAV#476]
I could successfully build apk for QMLPlayer. Is it possible to directly built player (given in examples of QtAV)? I mean without changing the code. Please guide me.

**Comment by wang-bin** [comment]
in examples/examples.pro, add

    SUBDIRS += player
    player.depends += common

**Comment by wang-bin** [comment]
and change examples/player/main.cpp line115 to `vo = "opengl";`

**Comment by ShijinXincoz** [comment]
It works. Thanks :)
