### ISSUE TITLE
QtAV crashes during switch video clips

### ISSUE THREAD

**Issue by dguskov** [wang-bin/QtAV#477]
There are several video clips and the QtAV playing them successively. And crash can occur accidentally on any clip.  Bellow last log information:
OS - Ubuntu

DEBUG    12:36:15:593 | AVPlayer.cpp - void QtAV::AVPlayer::loadInternal()(597) | Loading  QVariant(QString, "/etc/xdg/DoCash/SmartPanel/data/templates/gamma-center-3_json_v_1_0/data/video/_5000_-_YouTube_avi_converted.avi")  ...
DEBUG    12:36:15:594 | AVDemuxer.cpp - bool QtAV::AVDemuxer::load()(663) | "all closed and reseted"
DEBUG    12:36:15:594 | AVDemuxer.cpp - bool QtAV::AVDemuxer::load()(714) | "avformat_open_input: d->format_ctx:'0xa87e1680', url:'/etc/xdg/DoCash/SmartPanel/data/templates/gamma-center-3_json_v_1_0/data/video/_5000_-_YouTube_avi_converted.avi'..."
DEBUG    12:36:15:599 | AVDemuxer.cpp - bool QtAV::AVDemuxer::load()(718) | "avformat_open_input: url:'/etc/xdg/DoCash/SmartPanel/data/templates/gamma-center-3_json_v_1_0/data/video/_5000_-_YouTube_avi_converted.avi' ret:0"
DEBUG    12:36:15:600 | QtAV_Global.cpp - void QtAV::qtav_ffmpeg_log_callback(void*, int, const char*, va_list)(225) | "[FFmpeg:avi] parser not found for codec msmpeg4v2, packets or times may be invalid."
DEBUG    12:36:15:600 | QtAV_Global.cpp - void QtAV::qtav_ffmpeg_log_callback(void*, int, const char*, va_list)(225) | "[FFmpeg:avi] parser not found for codec adpcm_ms, packets or times may be invalid."
DEBUG    12:36:15:600 | QtAV_Global.cpp - void QtAV::qtav_ffmpeg_log_callback(void*, int, const char*, va_list)(225) | "[FFmpeg:avi] parser not found for codec msmpeg4v2, packets or times may be invalid."
DEBUG    12:36:15:601 | QtAV_Global.cpp - void QtAV::qtav_ffmpeg_log_callback(void*, int, const char*, va_list)(225) | "[FFmpeg:avi] parser not found for codec adpcm_ms, packets or times may be invalid."
DEBUG    12:36:15:601 | AVPlayerPrivate.cpp - bool QtAV::AVPlayer::Private::setupAudioThread(QtAV::AVPlayer*)(294) | "has audio"
DEBUG    12:36:15:602 | AudioOutputOpenAL.cpp - ALenum QtAV::audioFormatToAL(const QtAV::AudioFormat&)(209) | "OpenAL audio format: 0x1103 ch:2, sample format: s16"
DEBUG    12:36:15:602 | AVPlayerPrivate.h - void QtAV::AVPlayer::Private::setAVOutput(Out*&, Out*, QtAV::AVThread*) [with Out = QtAV::AudioOutput](62) | "output not changed: 0x871cbc8"
DEBUG    12:36:15:602 | AVPlayerPrivate.h - void QtAV::AVPlayer::Private::setAVOutput(Out*&, Out*, QtAV::AVThread*) [with Out = QtAV::AudioOutput](85) | "set AVThread output"

**Comment by wang-bin** [comment]
what QtAV version or which commit id do you use?

**Comment by dguskov** [comment]
Thank you for your replay
Commit id - 7cace756cbbe381a2895730e9ce02406c5be332c
version 1.6.0 , label - v1.6.0

**Comment by wang-bin** [comment]
qml app or qtwidget app? can you try the latest code? I fixed a crash after 1.6

**Comment by dguskov** [comment]
We use qml app. Should i take a last commit from master for try to reproduce crash?

**Comment by wang-bin** [comment]
Yes, master branch. Are you using `VideoOutput` or `VideoOutput2`? `VideoOutput` crashes a lot

**Comment by dguskov** [comment]
I use Video element( VideoOutput2 )

**Comment by dguskov** [comment]
Crash is not reproducible more
