### ISSUE TITLE
Not playing last few frames of video (not flushing cached frames)

### ISSUE THREAD

**Issue by junaid-ebrahim** [wang-bin/QtAV#478]
I notice that the video_thread stops before the last few frames are decoded.

From my knowledge of ffmpeg software video decoding I know that after the last video AVPacket , the EOF packet, the call to avcodec_decode_video2 needs a packet with NULL data and  zero size.This would then return the last cached frames from the decoder.

I have no idea how this would be done for the hardware decoders or even if it still applies but I tried with CUDA and got the same result.

Any help is appreciated, I was using a video pulled by ffmpeg from a rtsp ip camera , it was a 5 FPS video in FLV format and it was 33.4 seconds long. It's basically a surveillance video with a time counter.Let me know if you need a sample.

**Comment by wang-bin** [comment]
Yes, you are right, I forgot to decode them. I will fix it soon.
I think CUDA needs packets with flag `CUVIDSOURCEDATAPACKET`. I will try later.
I need your sample. Thanks

**Comment by junaid-ebrahim** [comment]
On 04/07/2015 16:44, WangBin wrote:
>
> Yes, you are right, I forgot to decode them. I will fix it soon.
> I think CUDA needs packets with flag |CUVIDSOURCEDATAPACKET|. I will 
> try later.
> I need your sample. Thanks
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wang-bin/QtAV/issues/478#issuecomment-118517561>.
>
Ok, thanks  , set the sample to your gmail address.

**Comment by wang-bin** [comment]
Try the latest code.

**Comment by junaid-ebrahim** [comment]
On 05/07/2015 18:03, WangBin wrote:
>
> Try the latest code.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wang-bin/QtAV/issues/478#issuecomment-118635358>.
>
Still not showing the last 8 frames but it does decode them and 
"deliverVideoFrame" returns true so it does send the frame to the 
renderer I think,not sure what could be wrong, If you play the sample 
video I sent (use ffplay) you will see the last 1.6 seconds of the video 
(upper right corner timestamps 22:04:38 and 22:04:39)

The debug output below

"[debug] testQtAV (C:\Qt\QtAV-master\src\VideoShader.cpp:1030) - 
"creating texture for plane 2""

"[debug] testQtAV (C:\Qt\QtAV-master\src\VideoShader.cpp:1038) - 
"texture for plane 2 is created (id=3)""

"[debug] testQtAV (C:\Qt\QtAV-master\src\AVDemuxer.cpp:428) - "End of 
file. erreof=1 feof=1""

"[debug] testQtAV (C:\Qt\QtAV-master\src\VideoThread.cpp:300) - "video 
thread gets an eof packet.""

"[debug] testQtAV (C:\Qt\QtAV-master\src\AVPlayer.cpp:1333) - 
"stopPosition() 33556/33400 reached and no repeat: 0""

"[debug] testQtAV (C:\Qt\QtAV-master\src\AVPlayer.cpp:1257) - "timer: 2, 
current thread: 0x653480, player thread: 0x653480""

"[debug] testQtAV (C:\Qt\QtAV-master\src\AVPlayer.cpp:1281) - "stopping 
demuxer thread...""

"[debug] testQtAV (C:\Qt\QtAV-master\src\AVDemuxThread.cpp:278) - 
stopping thread QtAV::VideoThread(0x4d99508)"

"[debug] testQtAV (C:\Qt\QtAV-master\src\VideoThread.cpp:300) - "video 
thread gets an eof packet.""

"[debug] testQtAV (C:\Qt\QtAV-master\src\VideoThread.cpp:300) - "video 
thread gets an eof packet.""

"[debug] testQtAV (C:\Qt\QtAV-master\src\VideoThread.cpp:300) - "video 
thread gets an eof packet.""

"[debug] testQtAV (C:\Qt\QtAV-master\src\VideoThread.cpp:300) - "video 
thread gets an eof packet.""

"[debug] testQtAV (C:\Qt\QtAV-master\src\VideoThread.cpp:300) - "video 
thread gets an eof packet.""

"[debug] testQtAV (C:\Qt\QtAV-master\src\VideoThread.cpp:300) - "video 
thread gets an eof packet.""

"[debug] testQtAV (C:\Qt\QtAV-master\src\VideoThread.cpp:300) - "video 
thread gets an eof packet.""

"[debug] testQtAV (C:\Qt\QtAV-master\src\VideoThread.cpp:300) - "video 
thread gets an eof packet.""

"[warning] testQtAV 
(C:\Qt\QtAV-master\src\codec\video\VideoDecoderFFmpegBase.cpp:111) - "no 
frame could be decompressed: Error number 0 occurred 3/3""

"[warning] testQtAV (C:\Qt\QtAV-master\src\VideoThread.cpp:451) - 
"Decode video failed. undecoded: 3""

"[debug] testQtAV (C:\Qt\QtAV-master\src\VideoThread.cpp:453) - "decode 
eof done""

"[debug] testQtAV 
(C:\Qt\QtAV-master\src\output\video\VideoRenderer.cpp:206) - 
"QtAV::VideoRenderer::setInSize => calculating aspect ratio from 
converted input data(1.000000)""

"[debug] testQtAV (C:\Qt\QtAV-master\src\VideoShader.cpp:472) - "pixel 
format changed: yuv420p => ""

"[debug] testQtAV (C:\Qt\QtAV-master\src\VideoThread.cpp:538) - "Video 
thread stops running...""

"[debug] testQtAV (C:\Qt\QtAV-master\src\AVDemuxThread.cpp:285) - "all 
avthread finished. try to exit demux thread<<<<<<""

"[debug] testQtAV (C:\Qt\QtAV-master\src\AVDemuxThread.cpp:546) - "Demux 
thread stops running....""

"[debug] testQtAV (C:\Qt\QtAV-master\src\AVPlayer.cpp:1287) - "all 
audio/video threads stopped...""

"[debug] testQtAV (C:\Qt\QtAV-master\src\AVPlayer.cpp:1151) - "demuxer 
thread emit finished.""

"[debug] testQtAV (C:\Qt\QtAV-master\src\AVPlayer.cpp:1160) - "avplayer 
emit stopped()""
