### ISSUE TITLE
library "libmaliinstr.so" not found

### ISSUE THREAD

**Issue by siko** [wang-bin/QtAV#484]
any idea of below issue?
running on huawei 3x, MTK MT6592
 

    E/linker  (11422): soinfo_relocate(linker.cpp:994): cannot locate symbol "log2f" referenced by "libavcodec.so"...
    E/dalvikvm(11422): dlopen("/data/data/com.aaa.bbb/lib/libavcodec.so") failed: Cannot load library: soinfo_relocate(linker.cpp:994): cannot locate symbol "log2f" referenced by "libavcodec.so"...
    E/linker  (11422): load_library(linker.cpp:761): library "libmaliinstr.so" not found
    E/        (11422): appName=com.pprj.lemedia, acAppName=com.android.cts.openglperf
    E/        (11422): 0
    E/        (11422): appName=com.aaa.bbbb, acAppName=com.android.browser
    E/        (11422): 0

**Comment by wang-bin** [comment]
log2f is not available in your libm (android <4.4). you have to build ffmpeg with gcc4.6.try http://sourceforge.net/projects/qtav/files/depends/FFmpeg/android/ffmpeg-2.7.1-android-armv7.tar.xz/download

**Comment by siko** [comment]
this issue I am using your prebuilt ffmpeg , not of my own build.
do you mean I need build ffmpeg myself if my android < 4.4?

**Comment by wang-bin** [comment]
I forgot whether i built it with gcc4.6 or 4.8. If gcc 4.8 is used, ffmpeg will use logf from libm of build environment. but libm in the runtime environment does not have log2f

**Comment by wang-bin** [comment]
libm.so in api level>=18 has log2f. we must use lower level to build ffmpeg. I uploaded ffmpeg2.8 for android and should work. also fixed in build script here https://github.com/wang-bin
