### ISSUE TITLE
Problem with OpenGL rendering bgr24 

### ISSUE THREAD

**Issue by Xuno** [wang-bin/QtAV#489]
When playing image sequence 
bmp  - Pixel format: bgr24 Render: libswbscale - OK , OpenGL - black 
tif   - Pixel format: yuv444p Render: libswbscale - OK , OpenGL - OK

**Comment by wang-bin** [comment]
Do you have images to let me test?
I tested bgr24 by setting AVFilter: menu=>Setup=>AVFilter=>enable video filter and parameters is `format=pix_fmts=bgr24`. Now the pixel format to opengl renderer is bgr24. You can confirm it in the log `Debug: "pixel format changed:  => bgr24"`. I tested on OSX and it works fine

**Comment by Xuno** [comment]
sent  private samples of bmp

**Comment by wang-bin** [comment]
It's broken if ANGLE is used. Desktop opengl works fine.

**Comment by Xuno** [comment]
confirm.
if switch to OpenGL Desctop, now can see images
but Preview not use this option (black rectangle instead of preview). 

ANGLE was work early ?

**Comment by wang-bin** [comment]
Preview use WidgetRenderer. I don't know why it's black
Not sure previous versions. I will fix it soon.

**Comment by wang-bin** [comment]
I find a universal solution to deal with rgb formats. I call it channel mapping, which was used to render packed yuv formats. But the shader needs an additional uniform `u_c` in packed.f.glsl. This uniform used only for packed yuv formats now. I will always use it for packed pixel formats.

As an example, for bgr24, we can use GL_RGB for opengl, so the order of each channel is changed when it's uploaded to GPU. `r->b, g->g, b->r`. We always want (r,g,b,a) as result in the shader. So we can reorder them by a transform (`u_c` in shader). `b->r, g->g, r->b`, so the matrix(QMatrix4x4) of `u_c` is

    0, 0, 1, 0,  //b->r
    0, 1, 0, 0,  //g->g
    1, 0, 0, 0, //r->b
    0, 0, 0, 1

I test some formats and it does work for both desktop opengl and ANGLE. But I'm not sure if the additional matrix will hit the performance.

**Comment by wang-bin** [comment]
I find that some opengl versions support the channel mapping, but they call it swizzle

**Comment by wang-bin** [comment]
You can try gl_rgb branch

**Comment by wang-bin** [comment]
now I merge it into master. only rgb/bgr555 and rgb/bgr48 is not supported. all other formats should be supported by  both desktop and gles2.

**Comment by Xuno** [comment]
Tested.
All Ok, exclude (Preview not use this option (black rectangle instead of preview)).

**Comment by wang-bin** [comment]
oh, I forgot to test preview.

**Comment by wang-bin** [comment]
try the latest code. it should work

**Comment by Xuno** [comment]
Confirmed. Work.
Thanks.
