### ISSUE TITLE
Player. Repeat function

### ISSUE THREAD

**Issue by Xuno** [wang-bin/QtAV#491]
/Menu/Repeat/From To selector is broken.  The video starts from specified time period but plays through the entire video, it does not stop at specified ending.  Also,repeat function does not work for image sequences.

**Comment by wang-bin** [comment]
in AVPlayer::timerEvent, remove

    if (!d->demuxer.atEnd()) {
            if (!d->seeking) {
                Q_EMIT positionChanged(t);
            }
            return;
        }

**Comment by Xuno** [comment]
ok, now
