### ISSUE TITLE
ubuntu 编译后不能运行

### ISSUE THREAD

**Issue by jhkwei** [wang-bin/QtAV#493]
编译成功后，运行./simpleplayer ，打开.avi或.mp4文件马上挂掉，返回断错误没有其它有用信息
ffmpeg 这是安装了，libopenal-dev也是安装了
还有怎么静态编译QtAV

**Comment by wang-bin** [comment]
export QTAV_LOG=all后运行，贴下log

**Comment by jhkwei** [comment]
后面make deb 现在能运行了，又有新问题，我开另外一个issue
