### ISSUE TITLE
QtAV 关于播放 TS 复用流 (mux) 问题

### ISSUE THREAD

**Issue by jhkwei** [wang-bin/QtAV#494]
播放TS 流，我想在解复用(demux)时，　选择性的播放某节目应该用哪些接口，也就是过滤器接口，还有在用qiodevice时，有掉包节目老卡卡的，我想重新实现这个read接口，是不是重载QFile就可以吗，还是有另外的内部调用方式

**Comment by wang-bin** [comment]
·播放TS 流，我想在解复用(demux)时，　选择性的播放某节目应该用哪些接口，也就是过滤器接口·
这个不清楚，自定义解复用目前不支持，直接调用ffmpeg的接口的

`用qiodevice时，有掉包节目老卡卡的，我想重新实现这个read接口，是不是重载QFile就可以吗，还是有另外的内部调用方式`
重载qiodevice吧

**Comment by jhkwei** [comment]
其实我只想控制读入块的大小，大概是4K 或　8K 一个块，太小io忙不过来

**Comment by wang-bin** [comment]
ffmpeg控制的，自己应该无法控制

**Comment by jhkwei** [comment]
没有办法只能先转UDP，再转给它。
