### ISSUE TITLE
Rendering RGBA32

### ISSUE THREAD

**Issue by statefull** [wang-bin/QtAV#496]
Hi,

I have a problem rendering an RGBA32 image, colors and image are good but the size of the image differs from the original.

I'm using...

QtAV:VideoFrame f (width,hight, QtAV::VideoFormat::Format_RGBA32);
f.setBytesPerLine(w*4);
f.setBits(buffer,0); //buffer is the RGBA32 data

Rendering this frame the image displayed is smaller that the original widthxheight

is there something missing?

**Comment by wang-bin** [comment]
the displayed size is depending on renderer size

**Comment by statefull** [comment]
Thanks, the problem is solved.
