### ISSUE TITLE
1.7版本mingw32编译simpleplayer缺少Qt5AVWidgetsd和Qt5AVd

### ISSUE THREAD

**Issue by thons93** [wang-bin/QtAV#499]
用vs2013_x64版本的也是缺少这两个，另外编译整个项目的时候undefined reference to '_imp_XXXX'。还有个问题ffmpeg在qt中基本所有函数都是外部解析错误呢

**Comment by wang-bin** [comment]
debug应该没问题，至少我测过　vs2013的。_imp_XXXX具体是什么？

**Comment by thons93** [comment]
比如 error: undefined reference to `_imp___ZN4QtAV9AVDemuxerC1EP7QObject',我在qmake的时候libcommon.pri里的很多func都是is not a recognized test function,比如preparePaths,set_Paths

**Comment by wang-bin** [comment]
你把你完整的编译步骤贴下

**Comment by thons93** [comment]
直接下载的QTAV整个项目，打开的QTAV.pro导入项目的。
刚才清空了重新导入建立，重新导入bin,lib和include，先qamke有警告但是通过了，然后构建的时候QtAV\src\output\video\GDIRenderer.cpp:228: error: 'const class QtAV::VideoFrame' has no member named 'constBits'

**Comment by wang-bin** [comment]
你先看wiki有介绍字幕用vs编译

**Comment by thons93** [comment]
我是用Qt Creater+mingw32，我看看

**Comment by thons93** [comment]
ffmpeg的bin,lib和inlcude我是直接复制到mingw的目录下的

**Comment by wang-bin** [comment]
编译前sdk_uninstall.bat
mingw debug我最近编译过没问题
