### ISSUE TITLE
Request to add signal aboud videoRect change

### ISSUE THREAD

**Issue by Liberus** [wang-bin/QtAV#504]
Basically, title say what I want. In my application it's needed to know what videoRect is(it can change if we change aspect ratio or resize) because I want to paint something on top of video only(or rather to track when mouse is on top of video). I thought about re-implementing some of the WidgetRenderer functions, but it looks like all of them aren't virtual. 
If there is another way to know what videoRect is and when it changes - please let me know.

**Comment by Liberus** [comment]
I can workaround this with overriding virtual bool receiveFrame(const VideoFrame& frame) but this functionality seems needed IMHO

**Comment by Liberus** [comment]
Ok, I'm looking like spammer now, but it looks like there is proper way - which is to handle imageReady signal and resize events. You made really great job designing API for QtAV!)

**Comment by wang-bin** [comment]
You'd better not use `imageReady` because that signal is only used in WidgetRenderer and it was added to workaround a bug(not sure whether the bug exists now). If you use `VideoOutput` class, you can signals like `outAspectRatioChanged`. I will add them to widgetrenderer and other renderers

**Comment by Liberus** [comment]
ok, but if I use outAspectRatioChanged I won't know when videoRect changed for the first time. I used imageReady signal because I need this functionality right now.
