### ISSUE TITLE
link error when QMAKE_LFLAGS ='-Wl,--no-undefined'

### ISSUE THREAD

**Issue by awissu** [wang-bin/QtAV#508]
GCC complains that it can't build the library with undefined symbols:

[  256s] ../.obj/QtAV_linux_x86_64/SurfaceInteropVAAPI.o: In function
`QtAV::vaapi::X11InteropResource::ensureGLX()':
[  256s] /home/abuild/rpmbuild/BUILD/QtAV-1.8.0/src/vaapi/SurfaceInteropVAAPI.cpp:240: undefined reference to `XFree'
[  256s] ../.obj/QtAV_linux_x86_64/SurfaceInteropVAAPI.o: In function `QtAV::vaapi::X11InteropResource::ensurePixmaps(int, int)':
[  256s] /home/abuild/rpmbuild/BUILD/QtAV-1.8.0/src/vaapi/SurfaceInteropVAAPI.cpp:253: undefined reference to `XGetWindowAttributes'
[  256s] /home/abuild/rpmbuild/BUILD/QtAV-1.8.0/src/vaapi/SurfaceInteropVAAPI.cpp:254: undefined reference to `XCreatePixmap'

See: https://pmbs.links2linux.de/package/live_build_log/home:awissu:branches:Multimedia/Qt5AV/openSUSE_13.2/x86_64

**Comment by wang-bin** [comment]
seems -lX11 -lGLX is missing

**Comment by awissu** [comment]
https://pmbs.links2linux.de/package/view_file/Multimedia/QtAV/QtAV-1.8.0_link_libraries.patch?expand=1

**Comment by wang-bin** [comment]
LGTM. Thanks. Patch is applied.
