### ISSUE TITLE
Is this  Library（QtAV） have any way to  get UTC（time）of  every video frame？

### ISSUE THREAD

**Issue by AlexiaChen** [wang-bin/QtAV#509]
I heard some developers develop some real-time Camera Monitor based on  QtAV.  So,In many cases, the moniter system need to display UTC time of every frame with Video, for example, monitor in Supermarket display Date with Video,it good for analyzing Crime Time if have Thief .   This feature is base requirement for monitor from ip Camera.   the real-time data is from Camera over RTSP/RTP.

**Comment by AlexiaChen** [comment]
And  there is a issue:
    When I open the URL:rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp     the official  example player.exe based on QtAV   is too slower to display , the title of player is buffering too slow.    user cannot wait such long time.   the url I use VLC Media player to play is very quick to display.

**Comment by wang-bin** [comment]
`AVPlayer.setBufferValue(1)`. In the player, open setup dialog and set the buffer frames to 1

**Comment by AlexiaChen** [comment]
Thank you  for your reply. and the first Question ,How can I get UTC of every frame??  And  I need to display UTC of every frame with Video.

**Comment by wang-bin** [comment]
Is UTC encoded in to video frames? If yes, it's `VideoFrame.timestamp()`. You can write a VideoFilter to paint the informations on the video frame or the renderer

**Comment by wang-bin** [comment]
You can also get UTC from system and draw it in a filter
