### ISSUE TITLE
Video cropped on font size change

### ISSUE THREAD

**Issue by ShijinXincoz** [wang-bin/QtAV#512]
Hi,
     When i change the default windows font size ( 100% to 125%) then the part of video cropped in player.exe. How can i override this.

**Comment by wang-bin** [comment]
how can i reproduce this?

**Comment by ShijinXincoz** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10752063/9958597/3e9f653a-5e29-11e5-9ddd-69cf7eeb130f.png)

**Comment by ShijinXincoz** [comment]
change windows font size to medium (125%) then play any video then it happen

**Comment by wang-bin** [comment]
It doesn't happen on my win10

**Comment by ShijinXincoz** [comment]
I have the same error on win10 also.
![untitled](https://cloud.githubusercontent.com/assets/10752063/10038057/7b368d6e-61dc-11e5-8ba5-92985afd297c.jpg)

**Comment by ShijinXincoz** [comment]
when i change set custom scaling level then the same error happen

**Comment by wang-bin** [comment]
what is the steps?

- run player
- change font size
- start playback

or 

- change font size
- run player
- start playback

?

Can you take a screenshot of the player?

**Comment by ShijinXincoz** [comment]
First change font size then run player and playback

**Comment by ShijinXincoz** [comment]
![croped](https://cloud.githubusercontent.com/assets/10752063/10040367/91d60a42-61f8-11e5-86af-a5899f567721.jpg)

**Comment by ShijinXincoz** [comment]
left side is the cropped one and right side original.

**Comment by ShijinXincoz** [comment]
![original](https://cloud.githubusercontent.com/assets/10752063/10040394/cb3c099e-61f8-11e5-907d-dc55be9ae817.jpg)

**Comment by ShijinXincoz** [comment]
when you change the font size system ask for signout please do so. after that run the player

**Comment by wang-bin** [comment]
what about GLWidget2?

**Comment by wang-bin** [comment]
I'm not working on direct2d

**Comment by Liberus** [comment]
ShijinXincoz: are by any chance using ffmpeg and screen-capture-recorder to capture and stream your desktop? and QtAV to play that? if yes, then it might be the problem of screen-capture-recorder, since I encountered this error if I change screen resolution on system I'm streaming from.

**Comment by ShijinXincoz** [comment]
@Liberus  i am not using any screen capture recorder. it just a video from youtube

**Comment by ShijinXincoz** [comment]
@wang-bin  its work fine in GLwidget2.

**Comment by ShijinXincoz** [comment]
using these windows API we can correct this
SetProcessDPIAware ();
const float DEFAULT_DPI = 96.0;
HDC screen = GetDC( 0 );
GetDeviceCaps (screen, CLIPCAPS);
ReleaseDC( 0, screen );
float val =  dpiX / DEFAULT_DPI;
and apply the value to all layout.

**Comment by Liberus** [comment]
@ShijinXincoz Can you create pull request for that? It might be helpful for other people as well. Thanks!
