### ISSUE TITLE
Windows: player doesn't run, silent failure (qtav 1.8.0, windows 7, AMD APU)

### ISSUE THREAD

**Issue by jdb-vsn** [wang-bin/QtAV#513]
On Windows 7 (64bit, AMD APU), I downloaded and installed the 1.8.0 package.

Now, I try to run the player.exe or qmlplayer.exe and I get nothing.  No error message, no player window.  The only thing I get is a log file in c:\qtav\bin\log.txt:

        Debug: ("c:\\QtAV\\bin\\player.exe", "ex.mp4")
        Debug: vo: gl
I don't even get that log file if I try qmlplayer.exe instead of player.exe.

I have tried running both by double clicking the player.exe (and qmlplayer.exe) file, launching from cmd (again both player and qmlplayer), and right clicking on the video file and selecting "Open with QtAV".

Even just running with the -h flag produced no output from the program.

I did try installing the XAudio2.

*EDIT*: I should mention I grabbed the Mingw x86 installer.

**Comment by wang-bin** [comment]
You can enable the log for player.exe by setting environment var

    set QTAV_LOG=all

in cmd then run player.exe. Then show me your log.

qmlplayer.exe does not save a log file.

**Comment by jdb-vsn** [comment]
That doesn't increate the logging for some reason.

I deleted the old log.txt file, then I ran:

    set QTAV_LOG=all
    c:\qtav\bin\player.exe

and here is the contents of the new log.txt file:

    Debug: ("C:\\qtav\\bin\\player.exe")
    Debug: vo: gl

**Comment by wang-bin** [comment]
which installer do you use? can you try 1.7.0?

**Comment by wang-bin** [comment]
and what about `player -vo qt`?

**Comment by jdb-vsn** [comment]
I used the installer grabbed from: http://sourceforge.net/projects/qtav/files/release/1.8.0/QtAV1.8.0-MinGW32.exe/download

player -vo qt starts and plays video.  Here is the log output
```
Debug: ("C:\\qtav\\bin\\player.exe", "-vo", "qt")
Debug: vo: qt
Debug: status changed  "Loaded"
Debug: ScreenSaver::retrieveState
Debug: SucceedDebug: sync config to  "C:/Users/VSN-Test/AppData/Roaming/Player/Player.ini"
Debug: sync end
fered"
Warning: QObject::moveToThread: Cannot move objects with a parent
Debug: sync config to  "C:/Users/VSN-Test/AppData/Roaming/Player/Player.ini"
Debug: sync end
Warning: ScreenSaver::restoreState: no data, doing nothing
```

-vo qt doesn't seem to take proper advantage of dxva2, but perhaps that is a different issue?

**Comment by wang-bin** [comment]
`-vo qt` use software renderer and it's slow. Will it crash it you then change the `Render engine` menu to `GLWidget2`? Also please test 1.7.0.

**Comment by jdb-vsn** [comment]
The results with 1.7.0 are identical.  With -vo gl, the log is the same as in the initial message.  With -vo qt, it appears to work, but is slow.  If I start with qt, then choose GLWidget 2 from the menu in 1.7.0, it promptly crashes.  If I try choosing GLWidget, it says not available on your platform.  If I choose Direct2D, it crashes.  If I choose OpenGLWidget, it crashes.

Going back to 1.8.0, with the QPainter renderer, playback is much smoother than it was on 1.7.0.  GLWidget says it is not available for my platform.  OpenGLWidget crashes, GLWidget2 crashes. Direct2D does not crash this time and significantly improves playback quality when running full screen compared to QPainter.

Again, all of this is on an up to date Windows 7 machine with up to date Catalyst drivers.

**Comment by wang-bin** [comment]
Which QtAV installer do you use? Today I find libEGL.dll and libGLESv2.dll in MinGW32/64 installers have problems(I don't know the reason) on win7 and you have to replace them with ones from Qt official packages or vs installers. 
If it still does not work, please try an opengl example provided by Qt to see whether opengl works.

**Comment by wang-bin** [comment]
what's your GPU?

btw, please try `player -opengl desktop` or `player -opengl angle` and tell me which one works

**Comment by jdb-vsn** [comment]
My GPU is Radeon 8330 (integrated in AMD APU).  I did use the Mingw32 installers for both 1.7.0 and 1.8.0, so when I get back to that machine, I will try replacing those files, as well as the additional player options you asked me about.

**Comment by wang-bin** [comment]
You can try vs2013 installers. MinGW players can not run on my win7 too. I have to upload new installers

**Comment by jdb-vsn** [comment]
vs2013 installers don't have any issue.  The only issue is that what I really want is the sdk, and since I'm using mingw32 (the one included in the Qt devkit for windows), I was assuming I would be better off with the mingw installer.

BTW, would it be reasonable to offer zip files in addition to the installers?

**Comment by wang-bin** [comment]
libEGL.dll and libGLESv2.dll are broken in my mingw installers. You can replace them by qt official ones

**Comment by wang-bin** [comment]
I can upload 7z packages in the next release
