### ISSUE TITLE
请问怎么让QQ影音调用QtAV的解码器？

### ISSUE THREAD

**Issue by redstoneleo** [wang-bin/QtAV#514]

**Comment by wang-bin** [comment]
不能

**Comment by redstoneleo** [comment]
我看你的项目应该算是另外一个qt的media库，为什么不开发Qt 的Multimedia Backend呢？这样子开发者可以使用Qt的api，然后Qt自动调用你的项目来解码。
http://doc.qt.io/qt-5/multimediabackend.html
http://wiki.qt.io/Qt_5.5.0_Multimedia_Backends
我懂的不多，说错了希望多多指教！

**Comment by wang-bin** [comment]
qtmultimedia框架有它的局限性，自己写更自由
被其它播放器调用要包装成dshow滤镜，暂不考虑，lavfilter足够了
