### ISSUE TITLE
Strange behavior (and crashes) when deleting AVPlayer (also affecting QFileDialog)

### ISSUE THREAD

**Issue by agudpp** [wang-bin/QtAV#518]
Hi WangBin, first of all congrats for the awesome lib :), really nice!.
I'm reporting an issue since I already spend some time on this and maybe you know what can be happening.
I'm using the lib in one project and I started having a strange issue with the QFileDialog, after I delete the first QtAV::AVPlayer and then try to open a QFileDialog Qt freezes, I tried to debug but couldn't find the cause of it.
Later I decided to create a small sample and project using your sample code 

```
QHBoxLayout* mainLayout = new QHBoxLayout(this);
QtAV::WidgetRenderer* renderer = new QtAV::WidgetRenderer(this);
renderer->show();
avplayer = new QtAV::AVPlayer;
avplayer->setRenderer(renderer);
avplayer->play("tmp_video.mp4");
mainLayout->addWidget(renderer);
```

this code is inside of a Wrapper that creates the video player and shows the video playing correctly.
Later in the destructor I just delete the avplayer 
```
delete avplayer;
```

I had 3 buttons in the main window, one that creates a new wrapper and put it into a vector. Another button that removes all the instances created. And the third one that opens a file dialog. If I open the file dialog N times works perfectly as it should. If I create M VideoWrappers all of them are created properly and play the video properly as well. If I delete all of them also, and then I can recreate as many video players as I want and works perfectly. The strange thing is after I destroy the first (or second) AVPlayer and try to open the file dialog. If I'm executing normally (debug / release but without gdb) it is crashing the second time I do this: (create video player, delete video player, open file dialog, create video player, delete video player, open file dialog -> crash).
If I execute the same code with gdb, then it is not crashing but where is happening the crash the QFileDialog is changing the style (the first time shows normally, the second times is completely different). I guess is a threading problem since the timing (gdb is slower).
I tried to not destroy the AVPlayer (only), so leaving a leak, and the behavior is perfectly normal. I can create as many video players and the QFileDialog still works properly.

I tried with other Dialogs and is not happening (normal QDialog) when I execute them, so I'm not really sure why is affecting the QFileDialog.

Some of the errors I got (when opening the file dialog) are:
```
....
CoCreateInstance failed ()
```
But I'm not completely sure if this is related or not (sometimes when it not crash also appears).

The file dialog code is trivial:
```
QFileDialog fileDialog(0,
                       "file",
                       "",
                       "Any (*.*)");

if (!fileDialog.exec()) {
    return;
}
```

I hope you have any idea why this could be happening :).

I'm using Windows 8.1, MinGW4.8.2_32 , Qt5.3, QtAv 1.8.0 (2015-09-01), ffmpeg one version but not the standard (anyway is not a ffmpeg problem I guess because the videos are working perfectly).

Thanks a lot in advance,

**Comment by wang-bin** [comment]
complete sample code please

**Comment by agudpp** [comment]
Hi there, sorry, here it is
**main.cpp**

```

#include <QLayout>
#include <QHBoxLayout>
#include <QPushButton>
#include <QStatusBar>
#include <QApplication>

#include <QtAV/QtAV>
#include <QtAVWidgets/QtAVWidgets>

#include "TestClasses.h"

int
main(int argc, char *argv[])
{
    QtAV::Widgets::registerRenderers();

    QApplication a(argc, argv);

    QMainWindow mainWin;
    mainWin.show();

    QWidget widget;
    HandlerHelper handlerHelper;
    QHBoxLayout* m_mainLayout = new QHBoxLayout(&widget);

    // create buttons
    QPushButton* btnCreate = new QPushButton;
    QPushButton* btnClear = new QPushButton;
    QPushButton* btnDialog = new QPushButton;
    btnCreate->setText("CreateVideoPlayers");
    btnClear->setText("DestroyVideoPlayers");
    btnDialog->setText("FileDialog");
    m_mainLayout->addWidget(btnCreate);
    m_mainLayout->addWidget(btnClear);
    m_mainLayout->addWidget(btnDialog);

    // connect the buttons
    QObject::connect(btnCreate, SIGNAL(clicked()), &handlerHelper, SLOT(onCreateInstancePressed()));
    QObject::connect(btnClear, SIGNAL(clicked()), &handlerHelper, SLOT(onDeleteInstancesPressed()));
    QObject::connect(btnDialog, SIGNAL(clicked()), &handlerHelper, SLOT(onOpenFileDialogPressed()));

    // set the main layout and widget
    widget.setLayout(m_mainLayout);
    mainWin.layout()->addWidget(&widget);

    mainWin.show();


    return a.exec();
}
```

**TestClasses.h**
```

#ifndef TESTCLASSES_H
#define TESTCLASSES_H

#include <QMainWindow>
#include <QThread>
#include <QFileDialog>
#include <QHBoxLayout>

#include <QtAV/QtAV>
#include <QtAVWidgets/QtAVWidgets>


class WidgetWrapper : public QWidget {
public:
    WidgetWrapper(QWidget* p = 0) : QWidget(p), avplayer(0)
    {
        QHBoxLayout* mainLayout = new QHBoxLayout(this);


        QtAV::WidgetRenderer* renderer = new QtAV::WidgetRenderer(this);
        renderer->show();
        avplayer = new QtAV::AVPlayer;
        avplayer->setRenderer(renderer);
        avplayer->play("C:\\tmp_video.mp4");
        mainLayout->addWidget(renderer);
    }

    virtual ~WidgetWrapper()
    {
        if (avplayer) {
            delete avplayer;
            //avplayer->deleteLater();
        }
    }

private:
    QtAV::AVPlayer* avplayer;

};

class HandlerHelper : public QObject {

    Q_OBJECT

public:
    HandlerHelper(){};
    virtual ~HandlerHelper(){}

public slots:

    void
    onDeleteInstancesPressed(void)
    {
        for (WidgetWrapper* vp : videoPlayers) {
            delete vp;
            //vp->deleteLater();
        }
        videoPlayers.clear();
    }

    void
    onCreateInstancePressed(void)
    {
        // create a video player here
        for (int i = 0 ; i < 1; ++i) {
            WidgetWrapper* wwrapper = new WidgetWrapper;
            wwrapper->show();
            videoPlayers.push_back(wwrapper);
        }
    }

    void
    onOpenFileDialogPressed(void)
    {
        QFileDialog fileDialog(0,
                               "Package File",
                               "",
                               "Any (*.*)");

        if (!fileDialog.exec()) {
            // nothing to do
            return;
        }
    }

private:
    std::vector<WidgetWrapper*> videoPlayers;
};


#endif // TESTCLASSES_H
```

**project.pro** this is a simplified version of it but should work, note there are paths to where the QtAV libs are, so you should configure this by yourself.
```
QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

DEFINES -= UNICODE

TARGET = VideoPlayerTest
TEMPLATE = app

# DEPENDENCIES_PATH is where the "lib/" "include" folders are for the QtAVWidgets
QMAKE_CXXFLAGS += -isystem $$DEPENDENCIES_PATH/include

CONFIG(debug, debug|release) {
    # debug mode
    LIBS += -lQtAVWidgetsd1 -lQtAVd1
} else {
    # release / deploy
    LIBS += -lQtAVWidgets1 -lQtAV1
}

QMAKE_CXXFLAGS += -std=c++11 -Wno-trigraphs -fwrapv -DDEBUG

SOURCES += main.cpp

HEADERS  += ../VideoPlayer.h \
    TestClasses.h
```


To reproduce:
- press create button.
- press destroy button
- press file dialog and close it
- press create button
- press destroy button
- press file dialog (and it crashes).

if you do the same a little bit slower then it should change the "style" of the QFileDialog.

thanks in advance

**Comment by black-sire** [comment]
It happens after any CoUninitialize(). If you use XAudio2 backend it calls on destroy.

**Comment by wang-bin** [comment]
I can't test on windows until this weekend. @black-sire what if remove `CoUninitialize()` in XAudio2 backend?

**Comment by wang-bin** [comment]
@black-sire I'm not sure if `CoInitializeEx` and `CoUninitialize` are required. In my tests we can remove them

**Comment by black-sire** [comment]
Yes, I just remove CoInitializeEx and CoUninitialize and bug related with QFileDialog  disappeared. I think CoInitializeEx was call in the Qt core already.

**Comment by wang-bin** [comment]
@black-sire Can you help me check the return value of `CoInitializeEx`? If com is already initialized, it returns `S_FALSE` and I think we can not call `CoInitialize`.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms695279(v=vs.85).aspx

**Comment by wang-bin** [comment]
http://stackoverflow.com/questions/4455768/com-initialization-and-use-in-win32-c-dll
http://stackoverflow.com/questions/2154151/coinitialize-couninitialize-calls-pairing

**Comment by agudpp** [comment]
Hey there, how can I help?

**Comment by wang-bin** [comment]
@agudpp help me check the return value of `CoInitializeEx`
Workaround is remove `CoInitializeEx` and `CoUninitialize`

**Comment by agudpp** [comment]
@wang-bin I print the values:

```
const HRESULT coinitResult = CoInitializeEx(NULL, COINIT_MULTITHREADED);
qDebug() << "coinitResult: " << coinitResult;
```

the two calls returns this in the following order:
```
coinitResult:  -2147417850
coinitResult:  0
```

**Comment by black-sire** [comment]
First, CoInitializeEx called from main thread.
Second, "HRESULT - 0x80010106 - Cannot change thread mode after it is set"
It mean, it already initialized in Qt core for main thread
Third, initialized with other flags -> The call CoInitializeEx don't add ref -> CoUninitialize leads to uninitialization Com sub-system.

**Comment by wang-bin** [comment]
@black-sire Sounds reasonable. So we must check the return value, if it's `RPC_E_CHANGED_MODE`, do not call `CoUninitialize`

**Comment by wang-bin** [comment]
please try the latest code and tell me the result

**Comment by agudpp** [comment]
@wang-bin seems to work properly now :+1:
