### ISSUE TITLE
cannot find -lQt5AVWidgets and cannot find -lQt5AV

### ISSUE THREAD

**Issue by JovanJovanovic12345** [wang-bin/QtAV#520]
Hi,
I have a problem (i use linux 64-bit and qt 64 bit). I tried to use QtAV in my project. I pass directions ("Use QtAV In Your Projects") and try to run the project (simpleplayer) in Qt 5.5 and have errors : "cannot find -lQt5AVWidgets" and "cannot find -lQt5AV". Does anyone know what the problem is ?

**Comment by wang-bin** [comment]
rename libQtAV.so and libQtAVWidgets.so manually for now

**Comment by JovanJovanovic12345** [comment]
Thanks.

2015-10-04 14:26 GMT+02:00 WangBin <notifications@github.com>:

**Comment by wang-bin** [comment]
Should be fixed if you build from source and run sdk_install.sh

**Comment by rockon2** [comment]
hello 
I wanted to use QtAV in my projected and i followed the steps in the lin below
https://github.com/wang-bin/QtAV/wiki/Use-QtAV-In-Your-Projects
but in the 3 steps where i wanted to change the name of the file actually i couldnt find the .so file in the lib so could anyone please help
thanks

**Comment by rockon2** [comment]
I am getting this error
 cannot find -lQt5AVWidgetsd 
and i dont have .so file in the liv folder i have .a file without 'd' at the end 
please help
thanks

**Comment by rockon2** [comment]
Okay now the simpleplayer project is buliding but when i run the project it give me following errors please help


VideoEncoder::Register(..., FFmpeg)
Singleton 17747610 created...
VideoDecoder::Register(..., FFmpeg)
Singleton 17748918 created...
AudioOutputBackend::Register(..., null)
Singleton 17748980 created...
MediaIO::Register(..., QIODevice)
Singleton 17748a08 created...
MediaIO::Register(..., QFile)
ImageConverter::Register(..., FFmpeg)
Singleton 17748b50 created...
AudioEncoder::Register(..., FFmpeg)
Singleton 17748bd8 created...
AudioDecoder::Register(..., FFmpeg)
Singleton 17749250 created...
SubtitleProcessor::Register(..., FFmpeg)
Singleton 17749398 created...
SubtitleProcessor::Register(..., LibASS)
VideoRenderer::Register(..., OpenGLWindow)
Singleton 17748ca0 created...
VideoDecoder::Register(..., DXVA)
VideoDecoder::Register(..., CUDA)
AudioOutputBackend::Register(..., OpenAL)
AudioOutputBackend::Register(..., DirectSound)
AudioOutputBackend::Register(..., XAudio2)
AudioResampler::Register(..., Libav)
Singleton 17748d00 created...
AudioResampler::Register(..., FFmpeg)
VideoRenderer::Register(..., OpenGLWidget)
VideoRenderer::Register(..., QGLWidget2)
VideoRenderer::Register(..., Widget)
VideoRenderer::Register(..., GDI)
VideoRenderer::Register(..., Direct2D)
VideoRenderer::Register(..., GraphicsItem)
registerRenderers...........
Qt: Untested Windows version 10.0 detected!
AudioOutputBackend::next(17749400)
AudioOutputBackend::next(17749404)
AudioOutputBackend::next(17749408)
AudioOutputBackend::next(1774940c)
AudioOutputBackend::id("XAudio2")
VideoRenderer::id("Widget")
Unknown id
