### ISSUE TITLE
Undefined reference to MediaIO in Android

### ISSUE THREAD

**Issue by ShijinXincoz** [wang-bin/QtAV#521]
I am creating a video player for playing some encrypted file for that i created a new class and inherit AVInput to that. it successfully build for windows. But when i port it to Android it shows an error " error: undefined reference to 'QtAV::MediaIO::MediaIO()'".

#include <QtAV/QtAV>
#include "main.h"
class Decoder : public QtAV::AVInput
{
public:
Please guide me.

**Comment by wang-bin** [comment]
rename `AVInput` => `MediaIO`

**Comment by ShijinXincoz** [comment]
Now i just modified my code and defined the decrypt function inside the mediaIO and now it's work fine.
Thank you :)
