### ISSUE TITLE
Qt5.5-MSVC2013: fatal error C1060: compiler is out of heap space

### ISSUE THREAD

**Issue by cloud-rocket** [wang-bin/QtAV#523]
Hi 

I am trying to compile QtAV on Windows inside QtCreator and getting the following error no matter what:

```
cl -c -nologo -Zc:wchar_t -FS -Zi -MDd -GR -W3 -w34100 -w34189 -w44996 -EHsc /Fd..\..\bin\qrc.pdb -DUNICODE -DWIN32 -DWIN64 -D_CRT_SECURE_NO_WARNINGS -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -ID:\references\QtAV\tests\qrc -I. -ID:\references\QtAV\src -ID:\references\QtAV -ID:\references\QtAV\src\QtAV -ID:\QtAV\widgets -ID:\references\QtAV -ID:\references\QtAV\widgets\QtAVWidgets -IC:\Qt\Qt5.5.0\5.5\msvc2013_64\include -IC:\Qt\Qt5.5.0\5.5\msvc2013_64\include\QtOpenGL -IC:\Qt\Qt5.5.0\5.5\msvc2013_64\include\QtWidgets -IC:\Qt\Qt5.5.0\5.5\msvc2013_64\include\QtGui -IC:\Qt\Qt5.5.0\5.5\msvc2013_64\include\QtANGLE -IC:\Qt\Qt5.5.0\5.5\msvc2013_64\include\QtCore -I..\..\.moc\5.5.0\qrc -IC:\Qt\Qt5.5.0\5.5\msvc2013_64\mkspecs\win32-msvc2013 -Fo..\..\.obj\qrc_win_x86_64\ @C:\Users\Miro\AppData\Local\Temp\qrc_media.obj.6136.3234.jom
qrc_media.cpp
	link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:WINDOWS "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:..\..\bin\playerthread.exe @C:\Users\Miro\AppData\Local\Temp\playerthread.exe.2424.3953.jom
..\..\.rcc\5.5.0\qrc\qrc_media.cpp(1316869) : fatal error C1060: compiler is out of heap space
```

Build env:
Windows 10
MSVC2013
Qt 5.5 64bit (tried 32 bit as well)
QtAV 1.8 (or master)

Any ideas?
Thanks
Meir Tseitlin

**Comment by wang-bin** [comment]
I have no idea. what about other examples in QtAV?

**Comment by cloud-rocket** [comment]
Compilation per example works fine within QtCreator, but when I try to execute it fails on compiling some dependency containing resources.....
How do you suggest to check it out?

**Comment by wang-bin** [comment]
why do you have `qrc_media.cpp`?
Here is the build log with my own Qt5.5 build: https://ci.appveyor.com/project/wang-bin/qtav

**Comment by cloud-rocket** [comment]
Good question, I am checking it out. 
Anyway I have clean qt5.5 64bit install. I copied the contents of QtAV-depends-windows-x86+x64-20150706.7z (bin/x64, include, lib/x64) into qt 5.5
And now trying to compile from within QtCreator (opened QtAV.pro)

Attached some logs:
[general.txt] (https://drive.google.com/open?id=0Bxl4PHp4Z1xLTXcweGM1T3lhaTA) (general messages generated while QtAV.pro.user is created) - 
[qmake_output.txt](https://drive.google.com/open?id=0Bxl4PHp4Z1xLTXcweGM1T3lhaTA)
[.qmake.cache](https://drive.google.com/open?id=0Bxl4PHp4Z1xLTXcweGM1T3lhaTA) and [config.log](https://drive.google.com/open?id=0Bxl4PHp4Z1xLTXcweGM1T3lhaTA) from build dir
[compile.txt](https://drive.google.com/open?id=0Bxl4PHp4Z1xLTXcweGM1T3lhaTA) - compilation log 

(For some reason I cannot attach them here, so providing links)

**Comment by cloud-rocket** [comment]
Ok, 
I think I found the problem - qrc test asked for test.mp4 file, so I provided file of size 20Mb, which was obviously too large.....

Sorry for this....
You can close the issue....

**Comment by wang-bin** [comment]
You can ignore the warning unless you want to test it.

**Comment by Evil-Spirit** [comment]
I just leave it here https://twitter.com/Evl_Spirit/status/993777818294276096
