### ISSUE TITLE
Request for VS2013 x64 Dedug prebuilt binaries

### ISSUE THREAD

**Issue by nhatson1987** [wang-bin/QtAV#524]
I currently used Release 1.8.0 VS2013 X64 and it worked perfectly. 
Due to the nature of my project, I have to work in Debug sometimes and need to link to debug version of QtAV. I wonder if the main page could provide Debug binaries for VS13 x64. Thanks for any help.

**Comment by wang-bin** [comment]
You can give me qt debug *.lib files of these modules: core, gui, opengl, network, widgets, qml, quick

**Comment by wang-bin** [comment]
Now you can download latest vs2013x64 debug build here https://sourceforge.net/projects/qtav/files/ci/ or  get the artifacts here https://ci.appveyor.com/project/wang-bin/qtav

**Comment by nhatson1987** [comment]
Thank you !
