### ISSUE TITLE
Seeking changed video play speed (too fast)

### ISSUE THREAD

**Issue by nhatson1987** [wang-bin/QtAV#526]
When I performed seek on the following video (dropbox link):
https://www.dropbox.com/s/t2y79k9px7g5gwt/00013.MTS?dl=0
The player's speed was messed up, it played the clip too fast.
I'm using simpleplayer.exe in the samples (1.8.0 VS2013 x64). 
Looking for a hint to solve this problem. Thanks in advance.

**Comment by wang-bin** [comment]
pts and dts are invalid in many positions. I will try to interpolate them to see the result

**Comment by wang-bin** [comment]
try the latest code

**Comment by nhatson1987** [comment]
I'm sync the latest code in master branch. I got the following compilation errors

![qtavcompilationerror](https://cloud.githubusercontent.com/assets/1432094/10400531/f3a44026-6e7e-11e5-8edf-812101eb5eb6.PNG)

**Comment by wang-bin** [comment]
uninstall QtAV sdk first before building QtAV

**Comment by wang-bin** [comment]
header conflict

**Comment by nhatson1987** [comment]
Aha, it works. Compiled successfully. 
The seeking doesn't mess up video play speed anymore. 
It just slow down for a second and catch up with normal speed. 
Thanks!!!!!.

**Comment by wang-bin** [comment]
`It just slow down for a second and catch up with normal speed. `
Due to my crap a/v sync solution
