### ISSUE TITLE
Please how do I use the metadata variable in Statistics class to query file metadata. Also why is it that some usefull fucntions are not implemented in the QtAV::AVPlayer class

### ISSUE THREAD

**Issue by andyscratch** [wang-bin/QtAV#528]

**Comment by wang-bin** [comment]
statistics.metadata["some_key"]

what functions?

**Comment by andyscratch** [comment]
Check your todo list
hasAudio(), hasVideo() and hasPic() functions are useful functions media player development. Why? They are used to update functions and other key controls accordingly. For example if I use statistics.video.available it returns true though the file is not a video file. The clip art embedded in the file makes the player think it is video and so returning true means all video functions and controls are updated accordingly.

**Comment by andyscratch** [comment]
And also about how to query the metadata of the current file do I code like this:
statistics.metadata["Artist"]  or
statistics.metadata[QMediaMetaData::Artist"]

**Comment by wang-bin** [comment]
"artist". You can run qDebug() << statistics.metadata to see the metadata names. They are in lower case. There are some keys listed in qml/MediaMetadata.cpp

**Comment by wang-bin** [comment]
hasAudio(), hasVideo() are available in qml/QmlAVPlayer.cpp

**Comment by andyscratch** [comment]
so will definitely be available in the next release of QtAV or I have to provide my code as a C++ backend to QML in order to get this feature?

**Comment by wang-bin** [comment]
actually hasVideo() == videoStreamCount() > 0

**Comment by wang-bin** [comment]
do you mean if the music has a picture, the hasVideo() should be false?

**Comment by andyscratch** [comment]
yes of course or? And the statistics.metadata is always empty. Returns a null string if queried with any of the metadata strings

**Comment by wang-bin** [comment]
what about `qDebug() << statistics.metadata`? does that file has metadata?

**Comment by andyscratch** [comment]
program crashes

**Comment by wang-bin** [comment]
impossible. sample code please

**Comment by andyscratch** [comment]
if(stats.metadata.isEmpty()){//stats = player->statistics()
        qDebug() << "hash empty";
        return;
    }

    QString str[] = {"artist", "category", "album"};
    int index = 0;
    forever{
        qDebug() << stats.metadata[str[index++]];
        if(index > 2)
            break;
    }

**Comment by wang-bin** [comment]
does it crash?
run `ffprobe you_file` and show me the output

**Comment by andyscratch** [comment]
I think I found the error. I assigned my variable for accessing the statistics() function at the beginning in the constructor of the mainWindow instead of at run time. Yet still I was able to get only the album title and not the rest. Why? Also please am not good at command line arguments

**Comment by wang-bin** [comment]
so what's the result of ` qDebug() << statistics.metadata `? Maybe there's no such key in that file

**Comment by andyscratch** [comment]
QHash(("encoded_by", "Lavf52.32.0"))

**Comment by wang-bin** [comment]
that is in stream's metadata. you can query `statistics.metadata.video` or `statistics.metadata.audio`

**Comment by andyscratch** [comment]
You mean statistics.audio.metadata? Cos there's no statistics.metadata.audio

**Comment by andyscratch** [comment]
statistics.metadata.audio or video gives QHash()
And statistics.metadata.audio["album"] gives ""

**Comment by wang-bin** [comment]
sorry it's statistics.audio.metadata

**Comment by andyscratch** [comment]
I think the inbuilt metadata reader is not powerful enough cos most of the keys are valid and yet yields null strings. Is there any other external library I can use to compute this?

**Comment by wang-bin** [comment]
you can try ffmpeg/ffprobe. If they can read those metadata, QtAV can.
mediainfo is another tool

**Comment by andyscratch** [comment]
ok. A friend said TagLib will do
