### ISSUE TITLE
Renderer does not fill the entire widget when resized

### ISSUE THREAD

**Issue by andyscratch** [wang-bin/QtAV#529]
I wanted to provide additional functionality for the widget based renderer, WidgetRenderer so I sub-classed it to provide functionalities like double clicking to toggle fullscreen, updating and controlling functions while in fullscreen mode and stuff. When I resize the renderer window for the first time say to the left the renderer is shifted to the right unless I resize the height before it will be centered again. Anyway to fix this?

**Comment by wang-bin** [comment]
sample code please.
btw, you can use event filter on the renderer's parent widget

**Comment by andyscratch** [comment]
#include <QWidget>
#include <QtAVWidgets>
#include <QtAV>


class Window;

class VideoPlayer : public QtAV::WidgetRenderer
{
    Q_OBJECT
public:
    VideoPlayer(QWidget* parent = 0);

    void setFullScreen(bool fullscreen);
//    bool isFullScreen() const;
protected:
    void mouseDoubleClickEvent(QMouseEvent *event);
    void keyPressEvent(QKeyEvent * event);

private:
    Window* mainApp;
};



#include "videoplayer.h"
#include <QMouseEvent>
#include "window.h"

VideoPlayer::VideoPlayer(QWidget* parent)
    :WidgetRenderer(parent)
{
    mainApp = qobject_cast<Window *>(parent);

    sizePolicy().setHorizontalPolicy(QSizePolicy::Fixed);
}

void VideoPlayer::mouseDoubleClickEvent(QMouseEvent *event)
{
    if(!mainApp->player->isVideoAvailable() ||
            mainApp->player->state() == Player::StoppedState)
        return;

    if(!isFullScreen()){
        setParent(0);
        setFullScreen(true);
        mainApp->fullscreenAction->setChecked(isFullScreen());
    }else{
        mainApp->fullscreenButton_Triggered();
    }
    event->accept();
}

void VideoPlayer::keyPressEvent(QKeyEvent *event)
{
    if(event->key() == Qt::Key_Space){
      if(mainApp->player->state() == Player::PlayingState)
          mainApp->player->pause();
      else
          mainApp->player->play();
    }
}

void VideoPlayer::setFullScreen(bool fullscreen)
{
    if(fullscreen){
        showFullScreen();
    }else
        showNormal();
}
