### ISSUE TITLE
Unstable video rendering when using multiple OpenGLWidget renderers (players) in same application

### ISSUE THREAD

**Issue by bongas** [wang-bin/QtAV#532]
I'm trying to use multiple players in the same application using the VideoRendererId_OpenGLWidget renderer, but the players are unstable and freezes very often. It looks like the video is running but the screen is not updating...

I have tried to use this renderer in the VideoWall example which produces same issue - the videos freeze after some time. The application is also crashing sometimes.

Is this a known issue?

Environment:
Ubuntu 14.04
Master QtAV code from late August

**Comment by wang-bin** [comment]
OpenGLWidgetRenderer may crash if do not add `qApp->setAttribute(Qt::AA_DontCreateNativeWidgetSiblings);`
What about VideoRendererId_GLWidget2?

**Comment by bongas** [comment]
The AA_DontCreateNativeWidgetSiblings might be helpful for the crashes - I'll test more. 
But the most critical issue is that the video freezes all the time. In the videowall example with 4 videos, my tests show that at least one video freezes within 5-10 seconds.

Regarding GLWidget2 it looks like it doesn't freeze but the QGLWidget introduces other issues with native windows etc. so I would rather stick with OpenGLWidget instead. 

Do you think there is some kind of collision if you run more than one OpenGLWidget simultaneously on screen?

**Comment by bongas** [comment]
After some more investigation I have found out that when a video freezes the `onUpdate()` method in OpenGLWidgetRenderer is still called so the videoThread is running, but the `paintGL()` method is not called anymore. For me it sounds that the QT framework decides to stop painting this widget for some reason, but I cannot figure out why...

**Comment by wang-bin** [comment]
I tested on osx. It crashes a lot. I will try to fix it this week.
If it does not crash, some videos do freeze. It happens for WidgetRenderer too if the signal `WidgetRenderer ::imageReady` is removed and call `update()` directly. I don't know the reason.

**Comment by bongas** [comment]
Thanks! I'm really fighting against this here... :)

Maybe this could be the cause of the crashes (and also the freezing):
https://forum.qt.io/topic/28468/can-qwidget-update-be-called-in-a-sub-thread-other-than-the-gui-thread/12

From my investigations most of the crashes occur inside `QVector::append()` which probably is well tested and therefore it's likely to be a threading problem... It looks like the `OpenGLWidgetRenderer::update()` method is called from the VideoThread which, according to the forum thread, is not allowed. It must be called from the GUI thread! 
Could these assumptions be correct?

**Comment by wang-bin** [comment]
Thanks. That make sence. I thought `update()` only queues an event to the gui thread. I was wrong.

**Comment by wang-bin** [comment]
Try the latest code please

**Comment by bongas** [comment]
Great! 
So far the fix is working good - no freezing and no crashes (caused by this at least). I'm closing the case. Thank you so much for your quick fix.
