### ISSUE TITLE
Request: MSys2 package

### ISSUE THREAD

**Issue by PhenomRetroShare** [wang-bin/QtAV#533]
Hello,
First good work!!!
I'm a little developer for an other software. We want to include QtAV in it.
For Linux, I've got no pain to use it. But for Windows, it's an other way...
To simplify dependence, I'm using MSys2, as they've got most of libraries.
So, My question: Will you plan to make a MSys2 package so we can use:
pacman -S mingw-w64-i686-qtav mingw-w64-x86_64-qtav

Thanks

**Comment by wang-bin** [comment]
Can we install qt in msys2? If yes, I can have a try

**Comment by wang-bin** [comment]
and what qt version do you use? qt4 or qt5?

**Comment by PhenomRetroShare** [comment]
Hello,
Seems to be possible:
`pacman -Ss Qt` returns:
mingw32/mingw-w64-i686-qt4 4.8.7-3 (mingw-w64-i686-qt4)
mingw32/mingw-w64-i686-qt5 5.5.0-1 (mingw-w64-i686-qt mingw-w64-i686-qt5)
    A cross-platform application and UI framework (mingw-w64)
mingw64/mingw-w64-x86_64-qt4 4.8.7-3 (mingw-w64-x86_64-qt4)
mingw64/mingw-w64-x86_64-qt5 5.5.0-1 (mingw-w64-x86_64-qt mingw-w64-x86_64-qt5)
    A cross-platform application and UI framework (mingw-w64)
But I never use it.
You may compile for each Qt Version(adding Qt4 and Qt5 in name) as some developer stay using Qt4.
Thanks a lot for your reactivity.

**Comment by PhenomRetroShare** [comment]
And MSys2 packager seems to recommend Qt-Creator at end of:
[Contributing to MSYS2 ](http://sourceforge.net/p/msys2/wiki/Contributing%20to%20MSYS2/)

**Comment by wang-bin** [comment]
You never use that, so what do you use? the qt official one?
I can't try it until the next week.

**Comment by wang-bin** [comment]
I tried to install mingw-w64-x86_64-qt5. It's about 4G and too large. The packages in msys2 have too many dependencies. It's not a good idea to use msys2 packages in your productions.
Build QtAV on windows is simple. Just put ffmpeg include/lib to Qt include/lib dir, then you can start to build

**Comment by kelteseth** [comment]
Why is the filesize a big deal? It would be a lot(!) simpler to set up and use QtAV on Windows if there was a official msys2 package.  Please elaborate @wang-bin

**Comment by wang-bin** [comment]
I've add PKGBUILD file in msys2 dir. But how can I submit this to msys2?

**Comment by kelteseth** [comment]
@wang-bin Your are my hero! They have a wiki page for that https://github.com/msys2/msys2/wiki/Creating-packages

**Comment by kelteseth** [comment]
@wang-bin have you seen this issue? https://github.com/wang-bin/QtAV/issues/878 This could be a potential bug when using PKGBUILD
