### ISSUE TITLE
I can't stop playing video with QMLPlayer on android.

### ISSUE THREAD

**Issue by semigifn** [wang-bin/QtAV#534]
hi. I appreciate you always.
I uploaded QMLPlayer on android device(galaxy a7). Plays well, but I can't stop playing while pushing home or back button.
Is it normal?

QMLPlayer : google player version (updated 2015.09.09)
same situation when uploading after source building.

**Comment by wang-bin** [comment]
It's normal. These events are not processed. I don't know how to detect these events.

**Comment by pkoretic** [comment]
You have to do it manually (you have to do the same in Java on android)
for home button (application leave) listen for app state changed on main Window object if in qml, for example:
```
Window {
onStateChanged:  {
switch(Qt.application.state) {
case Qt.ApplicationSuspended:
case Qt.ApplicationInactive:
case Qt.ApplicationHidden:
// stop player here
...
}
```

for back key, it can be normally received with Keys.onPressed: event.key === Qt.Key_Back

**Comment by wang-bin** [comment]
Thanks. I will try out in the weekend

**Comment by wang-bin** [comment]
now player will pause if home is pressed
