### ISSUE TITLE
On "Videowall" example video not synchronised.

### ISSUE THREAD

**Issue by arthurgib** [wang-bin/QtAV#539]
OS: MacOS 10.8
QT: Based on Qt 5.5.0 (Clang 6.0 (Apple), 64 bit)
QT-AV: QtAV 1.8.0(Sep 1 2015, 14:10:43)
I tried to use "Videowall" example and saw that video playing is not synchronised. Pls see attached screenshots. 
![screen shot 2015-10-28 at 15 08 24](https://cloud.githubusercontent.com/assets/13028149/10788085/1908b232-7d86-11e5-9b5a-dd3d11ca73a8.png)

![screen shot 2015-10-28 at 15 11 21](https://cloud.githubusercontent.com/assets/13028149/10788125/5da72e82-7d86-11e5-8557-ca6d1ca57e67.png)

**Comment by wang-bin** [comment]
Try the latest code. Video should be synchronized but the sound is not

**Comment by wang-bin** [comment]
Now it should be fine. 4 videos plays fine on my mac. To play more videos, you may have to enable hardware decoding(add `player->setVideoDecoderPriority(QStringList() << QString::fromLatin1("VideoToolbox") << QString::fromLatin1("FFmpeg"));` at VideoWall.cpp+153) and use opengl `./videowall -vo opengl xxx.mp4`

**Comment by arthurgib** [comment]
Latest code from master?

**Comment by wang-bin** [comment]
yes

**Comment by arthurgib** [comment]
I have problems with QtAV linking:
Undefined symbols for architecture x86_64:
  "_AVMediaTypeAudio", referenced from:
      _avf_read_header in libavdevice.a(avfoundation.o)
  "_AVMediaTypeVideo", referenced from:
      _avf_read_header in libavdevice.a(avfoundation.o)
  "_BZ2_bzDecompress", referenced from:
      _matroska_decode_buffer in libavformat.a(matroskadec.o)
  "_BZ2_bzDecompressEnd", referenced from:
      _matroska_decode_buffer in libavformat.a(matroskadec.o)
  "_BZ2_bzDecompressInit", referenced from:
      _matroska_decode_buffer in libavformat.a(matroskadec.o)
  "_CMAudioFormatDescriptionGetStreamBasicDescription", referenced from:
      _avf_read_header in libavdevice.a(avfoundation.o)
  "_CMBlockBufferCopyDataBytes", referenced from:
      _avf_read_packet in libavdevice.a(avfoundation.o)
  "_CMBlockBufferGetDataLength", referenced from:
      _avf_read_header in libavdevice.a(avfoundation.o)
      _avf_read_packet in libavdevice.a(avfoundation.o)
  "_CMSampleBufferGetDataBuffer", referenced from:
      _avf_read_header in libavdevice.a(avfoundation.o)
      _avf_read_packet in libavdevice.a(avfoundation.o)
  "_CMSampleBufferGetFormatDescription", referenced from:
      _avf_read_header in libavdevice.a(avfoundation.o)
  "_CMSampleBufferGetImageBuffer", referenced from:
      _avf_read_header in libavdevice.a(avfoundation.o)
      _avf_read_packet in libavdevice.a(avfoundation.o)
  "_OBJC_CLASS_$_AVCaptureAudioDataOutput", referenced from:
      objc-class-ref in libavdevice.a(avfoundation.o)
  "_OBJC_CLASS_$_AVCaptureDevice", referenced from:
      objc-class-ref in libavdevice.a(avfoundation.o)
  "_OBJC_CLASS_$_AVCaptureDeviceInput", referenced from:
      objc-class-ref in libavdevice.a(avfoundation.o)
  "_OBJC_CLASS_$_AVCaptureSession", referenced from:
      objc-class-ref in libavdevice.a(avfoundation.o)
  "_OBJC_CLASS_$_AVCaptureVideoDataOutput", referenced from:
      objc-class-ref in libavdevice.a(avfoundation.o)
  "_OBJC_CLASS_$_NSAutoreleasePool", referenced from:
      objc-class-ref in libavdevice.a(avfoundation.o)
      objc-class-ref in libavdevice.a(qtkit.o)
  "_OBJC_CLASS_$_NSNumber", referenced from:
      objc-class-ref in libavdevice.a(avfoundation.o)
      objc-class-ref in libavdevice.a(qtkit.o)
  "_OBJC_CLASS_$_QTCaptureDecompressedVideoOutput", referenced from:
      objc-class-ref in libavdevice.a(qtkit.o)
  "_OBJC_CLASS_$_QTCaptureDevice", referenced from:
      objc-class-ref in libavdevice.a(qtkit.o)
  "_OBJC_CLASS_$_QTCaptureDeviceInput", referenced from:
      objc-class-ref in libavdevice.a(qtkit.o)
  "_OBJC_CLASS_$_QTCaptureSession", referenced from:
      objc-class-ref in libavdevice.a(qtkit.o)
  "_QTMediaTypeMuxed", referenced from:
      _qtkit_read_header in libavdevice.a(qtkit.o)
  "_QTMediaTypeVideo", referenced from:
      _qtkit_read_header in libavdevice.a(qtkit.o)
  "__objc_empty_cache", referenced from:
      _OBJC_CLASS_$_AVFFrameReceiver in libavdevice.a(avfoundation.o)
      _OBJC_METACLASS_$_AVFFrameReceiver in libavdevice.a(avfoundation.o)
      _OBJC_CLASS_$_AVFAudioReceiver in libavdevice.a(avfoundation.o)
      _OBJC_METACLASS_$_AVFAudioReceiver in libavdevice.a(avfoundation.o)
      _OBJC_CLASS_$_FFMPEG_FrameReceiver in libavdevice.a(qtkit.o)
      _OBJC_METACLASS_$_FFMPEG_FrameReceiver in libavdevice.a(qtkit.o)
  "__objc_empty_vtable", referenced from:
      _OBJC_CLASS_$_AVFFrameReceiver in libavdevice.a(avfoundation.o)
      _OBJC_METACLASS_$_AVFFrameReceiver in libavdevice.a(avfoundation.o)
      _OBJC_CLASS_$_AVFAudioReceiver in libavdevice.a(avfoundation.o)
      _OBJC_METACLASS_$_AVFAudioReceiver in libavdevice.a(avfoundation.o)
      _OBJC_CLASS_$_FFMPEG_FrameReceiver in libavdevice.a(qtkit.o)
      _OBJC_METACLASS_$_FFMPEG_FrameReceiver in libavdevice.a(qtkit.o)
  "_deflate", referenced from:
      _flashsv_decode_frame in libavcodec.a(flashsv.o)
  "_deflateBound", referenced from:
      _flashsv_decode_frame in libavcodec.a(flashsv.o)
  "_deflateEnd", referenced from:
      _flashsv_decode_frame in libavcodec.a(flashsv.o)
  "_deflateInit_", referenced from:
      _flashsv_decode_frame in libavcodec.a(flashsv.o)
  "_iconv", referenced from:
      _avcodec_decode_subtitle2 in libavcodec.a(utils.o)
  "_iconv_close", referenced from:
      _avcodec_open2 in libavcodec.a(utils.o)
      _avcodec_decode_subtitle2 in libavcodec.a(utils.o)
  "_iconv_open", referenced from:
      _avcodec_open2 in libavcodec.a(utils.o)
      _avcodec_decode_subtitle2 in libavcodec.a(utils.o)
  "_inflate", referenced from:
      _decode_frame_common in libavcodec.a(pngdec.o)
      _decode_text_chunk in libavcodec.a(pngdec.o)
      _flashsv_decode_frame in libavcodec.a(flashsv.o)
      _http_read_stream in libavformat.a(http.o)
      _matroska_decode_buffer in libavformat.a(matroskadec.o)
      _zlib_decomp in libavcodec.a(lcldec.o)
      _rtmp_open in libavformat.a(rtmpproto.o)
      ...
  "_inflateEnd", referenced from:
      _decode_frame_apng in libavcodec.a(pngdec.o)
      _decode_frame_png in libavcodec.a(pngdec.o)
      _decode_text_chunk in libavcodec.a(pngdec.o)
      _flashsv_decode_init in libavcodec.a(flashsv.o)
      _flashsv_decode_end in libavcodec.a(flashsv.o)
      _flashsv2_decode_end in libavcodec.a(flashsv.o)
      _http_close in libavformat.a(http.o)
      ...
  "_inflateInit2_", referenced from:
      _http_read_header in libavformat.a(http.o)
  "_inflateInit_", referenced from:
      _decode_frame_apng in libavcodec.a(pngdec.o)
      _decode_frame_png in libavcodec.a(pngdec.o)
      _decode_text_chunk in libavcodec.a(pngdec.o)
      _flashsv_decode_init in libavcodec.a(flashsv.o)
      _matroska_decode_buffer in libavformat.a(matroskadec.o)
      _decode_init in libavcodec.a(lcldec.o)
      _rtmp_open in libavformat.a(rtmpproto.o)
      ...
  "_inflateReset", referenced from:
      _flashsv_decode_frame in libavcodec.a(flashsv.o)
      _zlib_decomp in libavcodec.a(lcldec.o)
      _decode_frame in libavcodec.a(tscc.o)
      _zerocodec_decode_frame in libavcodec.a(zerocodec.o)
      _decode_frame in libavcodec.a(zmbv.o)
  "_inflateSync", referenced from:
      _flashsv_decode_frame in libavcodec.a(flashsv.o)
  "_objc_enumerationMutation", referenced from:
      _avf_read_header in libavdevice.a(avfoundation.o)
      _qtkit_read_header in libavdevice.a(qtkit.o)
  "_objc_msgSend", referenced from:
      _avf_read_header in libavdevice.a(avfoundation.o)
      _destroy_context in libavdevice.a(avfoundation.o)
      _qtkit_read_header in libavdevice.a(qtkit.o)
      _qtkit_close in libavdevice.a(qtkit.o)
  "_objc_msgSendSuper2", referenced from:
      -[AVFFrameReceiver initWithContext:] in libavdevice.a(avfoundation.o)
      -[AVFAudioReceiver initWithContext:] in libavdevice.a(avfoundation.o)
      -[FFMPEG_FrameReceiver initWithContext:] in libavdevice.a(qtkit.o)
  "_uncompress", referenced from:
      _decode_frame in libavcodec.a(cscd.o)
      _decode_frame in libavcodec.a(dxa.o)
      _decode_block in libavcodec.a(exr.o)
      _g2m_decode_frame in libavcodec.a(g2meet.o)
      _id3v2_read_internal in libavformat.a(id3v2.o)
      _mov_read_cmov in libavformat.a(mov.o)
      _svq3_decode_init in libavcodec.a(svq3.o)
      ...
  "_zlibCompileFlags", referenced from:
      _http_read_header in libavformat.a(http.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../lib_osx_x86_64_llvm/QtAV.framework/QtAV] Error 1
make: *** [sub-src-libQtAV-pro-make_first] Error 2
15:17:10: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project QtAV (kit: Desktop Qt 5.5.0 clang 64bit)
When executing step "Make"
15:17:10: Elapsed time: 01:49.

I tried add 
LIBS += -framework CoreVideo -framework Foundation -framework AVFoundation -framework CoreMedia -liconv -lm -lbz2 -lz -pthread 
to .pro file, but there is no changes.

**Comment by wang-bin** [comment]
You'd better to link against shared libraries. Otherwise you have to add more link flags which depends on how you build your static libs. You can see the flags like this `pkgconfig --libs libavcodec`

**Comment by arthurgib** [comment]
I added 
LIBS += -framework CoreVideo -framework Foundation -framework AVFoundation -framework CoreMedia -liconv -lm -lbz2 -lz -pthread 

to libqtav.pri and then i have only this errors:
ndefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_QTCaptureDecompressedVideoOutput", referenced from:
      objc-class-ref in libavdevice.a(qtkit.o)
  "_OBJC_CLASS_$_QTCaptureDevice", referenced from:
      objc-class-ref in libavdevice.a(qtkit.o)
  "_OBJC_CLASS_$_QTCaptureDeviceInput", referenced from:
      objc-class-ref in libavdevice.a(qtkit.o)
  "_OBJC_CLASS_$_QTCaptureSession", referenced from:
      objc-class-ref in libavdevice.a(qtkit.o)
  "_QTMediaTypeMuxed", referenced from:
      _qtkit_read_header in libavdevice.a(qtkit.o)
  "_QTMediaTypeVideo", referenced from:
      _qtkit_read_header in libavdevice.a(qtkit.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../lib_osx_x86_64_llvm/QtAV.framework/QtAV] Error 1
make: *** [sub-src-libQtAV-pro-make_first] Error 2
16:33:58: The process "/usr/bin/make" exited with code 2.

**Comment by wang-bin** [comment]
try `pkg-config --libs libavdevice` to see what you missed

**Comment by arthurgib** [comment]
$ pkg-config --libs libavdevice
-L/opt/local/lib -lavdevice

**Comment by arthurgib** [comment]
I built it but can't run:

dyld: Library not loaded: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
  Referenced from: /Users/a.sudneko/dev/libqtavnew/build/Release/bin/videowall
  Reason: Incompatible library version: videowall requires version 64.0.0 or later, but ApplicationServices provides version 1.0.0
The program has unexpectedly finished.
/Users/a.sudneko/dev/libqtavnew/build/Releas

**Comment by wang-bin** [comment]
If you link to ffmpeg dylibs, no such error. Now you have to set you mac target version to 10.8

**Comment by arthurgib** [comment]
I set 
QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.8
but there is no changes. If i tried to build with dylibs, i have errors:
Undefined symbols for architecture x86_64:
"AVMediaTypeAudio", referenced from:
_avf_read_header in libavdevice.a(avfoundation.o)
"_AVMediaTypeVideo", referenced from:
_avf_read_header in libavdevice.a(avfoundation.o)
"_BZ2_bzDecompress", referenced from:
_matroska_decode_buffer in libavformat.a(matroskadec.o)
"_BZ2_bzDecompressEnd", referenced from:
_matroska_decode_buffer in libavformat.a(matroskadec.o)
"_BZ2_bzDecompressInit", referenced from:
_matroska_decode_buffer in libavformat.a(matroskadec
...

**Comment by arthurgib** [comment]
I build it correctly with QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.8 in .qmake.conf ) Thank you! Syncronization works well
