### ISSUE TITLE
Crash using VAAPI

### ISSUE THREAD

**Issue by allbabel** [wang-bin/QtAV#540]
When I use VAAPI from the branch master the QMLPlayer crashes when using an mp4 file.
./vainfo gives me:
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/local/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_34
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.38 (libva 1.6.1)
vainfo: Driver version: Intel i965 driver for Intel(R) Broadwell - 1.6.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice

The trace from QMLPlayer has the following:

QML debugging is enabled. Only use this in a safe environment.
Debug: arguments=======  ("/home/montage/devel/build-QtAV-Desktop_Qt_5_4_2_GCC_64bit-Debug/bin/QMLPlayer")
Debug: QML Debugger: Waiting for connection on port 59890...
Debug: ("/home/montage/devel/build-QtAV-Desktop_Qt_5_4_2_GCC_64bit-Debug/bin", "/home/montage/Qt/5.4/gcc_64/qml")
Debug: >>>>>>>>devicePixelRatio: 1.000000
Debug: dpi phy:  93.6146 , logical:  96 , dpr:  1 ; vis rect: QRect(0,0 1920x1080)
AudioResampler::Register(..., FFmpeg)
Singleton 0x7fffd807f610 created...
AudioOutputBackend::Register(..., Pulse)
Singleton 0x7fffd807f740 created...
VideoDecoder::Register(..., CUDA)
Singleton 0x7fffd807f870 created...
VideoDecoder::Register(..., VAAPI)
VideoRenderer::Register(..., OpenGLWindow)
Singleton 0x7fffd807fa40 created...
SubtitleProcessor::Register(..., FFmpeg)
Singleton 0x7fffd807fc10 created...
AudioDecoder::Register(..., FFmpeg)
Singleton 0x7fffd80802c0 created...
AudioEncoder::Register(..., FFmpeg)
Singleton 0x7fffd80803b0 created...
ImageConverter::Register(..., FFmpeg)
Singleton 0x7fffd80804e0 created...
MediaIO::Register(..., QIODevice)
Singleton 0x7fffd8080810 created...
MediaIO::Register(..., QFile)
AudioOutputBackend::Register(..., null)
VideoDecoder::Register(..., FFmpeg)
VideoEncoder::Register(..., FFmpeg)
Singleton 0x7fffd8080a60 created...
VideoRenderer::Register(..., QQuickItem)
VideoRenderer::Register(..., QuickFBO)
AudioOutputBackend::next(0x7fffd80808a0)
AudioOutputBackend::next(0x7fffd80808a4)
Debug: "QtAV 1.8.0(Oct 29 2015, 08:58:33)
A media playing library base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2015 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://www.qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://www.qtav.org"
Debug: "Build with Qt-5.4.2"
Debug: "Build with avutil-52.92.101"
Debug: "Build with avcodec-55.69.100"
Debug: "Build with avformat-55.48.101"
Debug: "Build with avfilter-4.11.102"
Debug: "Build with avdevice-55.13.102"
Debug: "Build with swresample-0.19.100"
Debug: "Build with swscale-2.6.100"
Debug: Registered audio backends:  ("Pulse", "null")
AudioOutputBackend::id("Pulse")
Debug: engine: "LibASS"
SubtitleProcessor::id("LibASS")
Not found
Unknown id Debug: engine: "FFmpeg"
SubtitleProcessor::id("FFmpeg")
Debug: engine: "FFmpeg"
SubtitleProcessor::id("FFmpeg")
Debug: engine: "LibASS"
SubtitleProcessor::id("LibASS")
Not found
Unknown id VideoDecoder::id("VAAPI")
Debug: init>>>>>screen density logical: 3.7795275590551185 pixel: 3.685613777652585
Debug: file:  ""
Debug: ScreenSaver::retrieveState
Debug: ScreenSaver::retrieveState timeout: 0, interval: 0, preferBlanking:1, allowExposures:1
Debug: ScreenSaver::enable 0, ret 1 timeout origin: 0
Debug: Succeed to enable screen saver (0)
Debug: GL_VERSION: 3.0 Mesa 10.2.7
Debug: GL_VENDOR: Intel Open Source Technology Center
Debug: GL_RENDERER: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
Debug: GL_SHADING_LANGUAGE_VERSION: 1.30
Warning: qrc:///qml/QMLPlayer/main.qml:106: TypeError: Type error
Debug: Loading  QVariant(QString, "/home/montage/Downloads/SampleVideo_1080x720_50mb.mp4")  ...
Debug: "all closed and reseted"
Debug: "avformat_open_input: d->format_ctx:'0x7fffac001c80', url:'/home/montage/Downloads/SampleVideo_1080x720_50mb.mp4'..."
Debug: "avformat_open_input: url:'/home/montage/Downloads/SampleVideo_1080x720_50mb.mp4' ret:0"
Debug: "avfmtctx.flag: 513"
Debug: "AVFMT_NOTIMESTAMPS: 0, AVFMT_TS_DISCONT: 512, AVFMT_NO_BYTE_SEEK:0"
Warning: "invalid index 0 (valid is 0~0) for stream type 2."
Debug: "notify_interval: 500"
Debug: "stream: 1, duration=13531136 (281898 ms), time_base=0.000021"
Debug: "codec: aac(AAC (Advanced Audio Coding))"
Debug: "stream: 0, duration=3608064 (281880 ms), time_base=0.000078"
Debug: "codec: h264(H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)"
Debug: "has audio"
AudioDecoder::id("FFmpeg")
Debug: "QtAV::AudioDecoderFFmpeg thread type: Single, count: 1"
Debug: AudioOutput format:  QtAV::AudioFormat(48000Hz, 4Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "flt")
Debug: "PulseAudio 3.0.0, protocol: 27, server protocol: 4294967295"
Warning: "src audio parameters 'channel layout(or channels), sample rate and sample format must be set before initialize resampler"
Debug: "new audio thread"
Debug: "demux thread setAudioThread"
Debug: "output not changed: 0xa6adc0"
Debug: "set AVThread output"
Debug: "stream: 1, duration=13531136 (281898 ms), time_base=0.000021"
Debug: "codec: aac(AAC (Advanced Audio Coding))"
Debug: "**********trying video decoder: VAAPI..."
Debug: "libva-drm.so.1 loaded"
Debug: "libva-x11.so.1 loaded"
Debug: "libva-glx.so.1 loaded"
Debug: "libX11.so.6 loaded"
Debug: "vaGetDisplay X11..............."
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/local/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_34
libva info: va_openDriver() returns 0
Debug: "checking profile: h264, Main"
Debug: "using profile VAProfileH264Main (6)"
Debug: "checking surface resolution support"
Debug: "libva-x11.so.1 loaded"
Debug: "QtAV::VideoDecoderVAAPI thread type: Frame, count: 5"
Debug: "**************Video decoder found:0x27e7fd0"
Debug: "setCapture 0xa6d090"
Debug: "stream: 0, duration=3608064 (281880 ms), time_base=0.000078"
Debug: "codec: h264(H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)"
Debug: "auto select clock: audio > external"
Debug: "Using AudioClock"
Debug: "Clock initial value: 0.000000"
Debug: "Starting audio thread..."
Debug: "Starting video thread..."
Warning: qrc:///qml/QMLPlayer/main.qml:114: TypeError: Type error
Warning: qrc:///qml/QMLPlayer/main.qml:106: TypeError: Type error
Debug: "get av queue a/v thread = 0x27e7ff0 0x2b284f0"
Debug: "swr speed=1.00"
Warning: "no frame could be decompressed: Error number 105222 occurred 0/105222"
Warning: "invalid video frame from decoder. undecoded data size: 0"
Debug: "out: {cl: 3, fmt: flt, freq: 48000}"
Debug: "in {cl: 63, fmt: fltp, freq: 48000}"
Debug: "available software decoder output format 0 (yuv420p)"
Warning: "hardware acceleration is not available"
Debug: "ensureSurfaces 0->1 1280x720. discard old surfaces: 0"
Debug: "AVClock started!!!!!!!!"

After which the application crashes.

**Comment by wang-bin** [comment]
seems your ffmpeg does not support vaapi. how did you install ffmpeg?
