### ISSUE TITLE
VAAPI X11 client leak

### ISSUE THREAD

**Issue by ps17092012** [wang-bin/QtAV#544]
Hi,

I have the following setup: 
- QtAV 1.7 or QtAV 1.8 release
- using VAAPI on Intel Hardware (i965-va-driver)
- repeatedly stop and start a video with QMLPlayer

Whenever I stop and start the video, a new X-client will get created. You can observe this with the tool xrestop, which shows the current number of clients ("Monitoring xx clients").

Once the total number reaches a certain amount (seems to be around 230 for me), the maximum number of clients is reached and the VAAPI playback will fail: 

> Maximum number of clients reachedxcb_connection_has_error() returned true
> Maximum number of clients reachedMaximum number of clients reachedlibva info: VA-API version 0.36.0
> Maximum number of clients reachedlibva info: va_getDriverName() returns 1
> libva error: va_getDriverName() failed with operation failed,driver_name=i965

More importantly, this means that you cannot open any other applications / windows anymore on the system, until the application is closed.

**Comment by wang-bin** [comment]
fixed

**Comment by ps17092012** [comment]
confirmed!
