### ISSUE TITLE
V1.8.0  build failed with no ass.lib @ win7 32bit vs2013

### ISSUE THREAD

**Issue by changzg** [wang-bin/QtAV#546]
build failed with no ass.lib @ win7 32bit V1.8.0 vs2013

Does any MASTER know where or how to build ass.lib from source by vs2013 ?

**Comment by wang-bin** [comment]
ass.lib is not required. libass.dll is loaded at runtime. btw, how did you build qtav?

**Comment by changzg** [comment]
I did totally follow the building steps from https://github.com/wang-bin/QtAV/wiki/Build-QtAV

1)download QtAV-1.8.0.zip, unzip to E:\QtAV-1.8.0
2)download ffmepg libs and ddls from https://sourceforge.net/projects/qtav/files/depends, put libs and dlls into E:\QtAV-1.8.0\ffmepg,
3)open a command window and CD to E:\QtAV-1.8.0, then run the commands list below to generate VisualStudio project:

@echo off
set HERE=%cd%
call "%qt5.5.0%\bin\qtenv2.bat"
call "%VS2013_PATH%\vcvarsall.bat"
set FFMPEG_INCLUDE=ffmpeg/include/
set FFMPEG_LIB=ffmpeg/lib/
cd /D %HERE%
set INCLUDE=%HERE%/%FFMPEG_INCLUDE%;%INCLUDE%
set LIB=%HERE%/%FFMPEG_LIB%;%LIB%

qmake -config no-examples -config no-tests -config no-ass -r -tp vc

4) qmake generate QtAV.sln successfully, still in the same command line, input command QtAV.sln to open it , it will bring up VisualSutio2013;

5) In VisualStudio2013, build QtAV project, compiling was succeed, but link failed, it was said could not find ass.lib

That is whole story.

**Comment by wang-bin** [comment]
please use the latest code
`-config no-ass` has no effect. Should be `no-libass`. ass.lib is required only when you set `config_libass_link`. So I don't know why you have such errors. 
https://ci.appveyor.com/project/wang-bin/qtav it build qtav if I push a commit, using nmake, msbuild(which is used by visualstudio) and make. Never see ass error
