### ISSUE TITLE
LNK1181: cannot open input file "Qt5AVWidgets.lib"

### ISSUE THREAD

**Issue by eddy3520** [wang-bin/QtAV#548]
when I used Qt5.5+msvc2013 to build the demo project simpleplayer, I got the error: LNK1181: cannot open input file "Qt5AVWidgets.lib". And I cannot find any  Qt5AVWidgets.lib file in my QTAV install path C:\\QTAV.   Anyone knows how to solve the problem? many Thanks~

**Comment by wang-bin** [comment]
rename QtAV1.lib and QtAVWidgets1.lib to Qt5AV.lib and Qt5AVWidgets.lib under Qt's lib dir. The issue should be fixed some days ago if you use the latest code

**Comment by eddy3520** [comment]
@wang-bin  I did as told, and solved the problem. Thank you very much!
