### ISSUE TITLE
 play multiple video file simultaneously issue

### ISSUE THREAD

**Issue by phantomgz** [wang-bin/QtAV#550]
I want to play multiple video file simultaneously. so in imitation of simpleplayer, I embed any PlayerWidget (A copy from PlayerWindow in simpleplayer, and make a little modify) in a gridLayoutWidget. after open two video file and play, it's running well, but when make some interaction, like seeking or shaking the whole window quickly. the program run mess up, even I can't stop the program.

I have make a whole project copy in here.
 http://pan.baidu.com/s/1jG6jnc6

    #include "MainWindow.h"
    #include "ui_MainWindow.h"
    #include "PlayerWidget.h"
    
    MainWindow::MainWindow(QWidget *parent) :
        QMainWindow(parent),
        ui(new Ui::MainWindow)
    {
        ui->setupUi(this);
        this->setCentralWidget(ui->gridLayoutWidget);
    
        this->init();
    }
    
    MainWindow::MainWindow(QString &uri, QWidget *parent) :
        QMainWindow(parent),
        ui(new Ui::MainWindow)
    {
        ui->setupUi(this);
        this->setCentralWidget(ui->gridLayoutWidget);
        this->init();
    
        if(uri.isEmpty())
            return;
        player[0]->openMedia(uri);
    }
    
    MainWindow::~MainWindow()
    {
        delete ui;
    }
    
    void MainWindow::init()
    {
        player[0] = new PlayerWidget(this);
        ui->gdVideo->addWidget(player[0], 1, 1, 1, 1);
        player[1] = new PlayerWidget(this);
        ui->gdVideo->addWidget(player[1], 1, 2, 1, 1);
    
        //player[2] = new PlayerWidget(this);
        //ui->gdVideo->addWidget(player[2], 2, 1, 1, 1);
        //player[3] = new PlayerWidget(this);
        //ui->gdVideo->addWidget(player[3], 2, 2, 1, 1);
    }

could you help me? 
thanks.

Cai.

**Comment by phantomgz** [comment]
running envirement: Win8.1 + QT5.5.1 + mingw32

**Comment by wang-bin** [comment]
http://pan.baidu.com/s/1jG6jnc6 invalid url

**Comment by wang-bin** [comment]
No problem for me. How to reproduce it?
