### ISSUE TITLE
Your application encountered a fatal error and cannot continue

### ISSUE THREAD

**Issue by brandy253** [wang-bin/QtAV#551]
Hi guys,

I followed this post https://github.com/wang-bin/QtAV/wiki/Make-app-for-Android
and had a successful build.
However, when it was deployed on my phone, the program showed a black screen and a message box said: "Your application encountered a fatal error and cannot continue"

What did I do wrong?

This line seems to be the problem which I found in the Application Output: 
E/dalvikvm(10848): dlopen("/data/data/org.qtproject.example.QtAV/lib/libQtAV.so") failed: dlopen failed: could not load library "libQtAV.so" needed by "libQtAV.so"; caused by OOPS: recursive link to "libQtAV.so"

**Comment by wang-bin** [comment]
Did you run sdk_install.sh after QtAV build? Also make sure ffmpeg so files are in qt's lib dir (where libQt5Core.so).

**Comment by brandy253** [comment]
Yes I did. like i said, I had the program built successful. If the *.so files don't present, I think Qt will show errors when compiling/building. It's only the problem when deploying to the device, my android is 4.4.2.

**Comment by wang-bin** [comment]
I don't know. What about QMLPlayer apk?
Open your apk to see what so is missing. I can create qmlplayer apk on osx and windows.

**Comment by wang-bin** [comment]
Need more information. For example so file list in apk
