### ISSUE TITLE
AVFilter not working

### ISSUE THREAD

**Issue by bongas** [wang-bin/QtAV#553]
When I add a video filter via AVPlayer I get this in the log:
`Warning: "[FFmpeg:?] Error av_buffersrc_write_frame(in_filter_ctx, avframe) @493 filter/LibAVFilter.cpp: (0xffffffea) Invalid argument"` and the filter is not working.

I have tried to add a fade filter with parameters "fade=type=0:start_time=0:duration=2:color=black" in your player example with same result.

I am using latest QtAV (source as of today) with your prebuilt ffmpeg 2.4.4 copied to Qt/lib.
Running on Ubuntu 15.10. What have I forgot :)?

regards
Gabriel

**Comment by wang-bin** [comment]
Try the latest fore again. The latest commit is 86a7dc8
I did some changes in filter. Now bugs should be fixed. Your parameters works fine in my test.

**Comment by bongas** [comment]
I am using the latest QtAV commit. 
I compiled QtAV on another machine and now the error messages are gone so the issue was local...
But - now the filter does not work if I use decoder priorities: VAAPI, ffmpeg. 
This has always worked before. If I only use ffmpeg as decoder the filter works.

**Comment by wang-bin** [comment]
VAAPI zero copy mode never supported avfilter. The latest code support avfilter now. But zero copy mode will be slower.

**Comment by bongas** [comment]
Oh, I didn't know. I'll check the latest code and benchmark the performance.
Thanks!!!
