### ISSUE TITLE
module "QtAV" plugin "QmlAV" not found

### ISSUE THREAD

**Issue by Aska12345678** [wang-bin/QtAV#556]
I use QtAV for android, when i import QtAV 1.5 then it show "module "QtAV" plugin "QmlAV" not found"

**Comment by wang-bin** [comment]
Run `sdk_install.sh` after building QtAV. Then build and deploy your app. Otherwise QtAV libraries will not be copied to apk.

**Comment by Aska12345678** [comment]
I can't building QtAV because "avutil is required, but compiler can not find it" then I download QtAV1.5.0-MinGW32 from http://sourceforge.net/projects/qtav/files/release/1.5.0/ and I run sdk_deploy. I can import QtAV 1.5 in desktop but in android then it show "module "QtAV" plugin "QmlAV" not found".

**Comment by wang-bin** [comment]
Use 1.9.0 please. And read the wiki before build.
