### ISSUE TITLE
windows sdk_install.bat file generated after compile seems to incorrectly generate dll file copy command

### ISSUE THREAD

**Issue by junaid-ebrahim** [wang-bin/QtAV#557]
I see line 94 of install_sdk.pro , when changed to the below seems to produce the correct dll copy command

win32:sdk_install.commands += $$quote($$COPY $$system_path($$BUILD_DIR/bin/Qt*AV*.dll) $$system_path($$[QT_INSTALL_BINS]/))

Note the * added between the Qt and AV

**Comment by junaid-ebrahim** [comment]
sorry, the asterisks got converted to markdown, not sure how to escape the like correctly for this issue reporting system, anyway , the "AV" in italics should have a asterisk before and after

**Comment by wang-bin** [comment]
No. On windows only `QtAV1.dll` and `QtAVWidgets1.dll` are created. What's your Qt version? Maybe Qt5.4 will create `Qt5AV1.dll`.

**Comment by junaid-ebrahim** [comment]
Yes, I am using Qt 5.4.1 msvc2013 edition, the dll created is Qt5AV1.dll and Qt5AVd1.dll for debug versions. They are missed during the install_sdk run because of the naming convention

**Comment by wang-bin** [comment]
It's a qt bug. Anyway, the latest code should work.
