### ISSUE TITLE
See first frame as a preview when a video is loaded

### ISSUE THREAD

**Issue by mariolatronico** [wang-bin/QtAV#558]
I'm developing a video browser using Qt and QtAV (no QML), which shows many video widgets (instances of  QtAV::GLWidgetRenderer2 ) in the main frame of the application. 
I would like to see the first frame when I load the video file (with setFileName() ), but when I load them I only see a black frame. 
I tried to browse the API but I couldn't find an easy way to do that. 
Is there a way to do that ? I also saw videoCapture() but I couldn't understand how to set the renderer to show only a frame.

Thank you,
Mario

**Comment by wang-bin** [comment]
No API now. I can add one in `VideoFrameExtractor`

**Comment by mariolatronico** [comment]
Thank you, it would be perfect. Is there a way I can help you ?

**Comment by wang-bin** [comment]
I think current `VideoFrameExtractor` is enough to show the first frame. See `tests/extract`. Run `./extract -f a.mov -t 0`

**Comment by mariolatronico** [comment]
Thank you. I just downloaded QtAV sources, explored the tree and saw that
the tests are simple enough to explain the API.

May I suggest to add to the wiki home page a mention to browse the source
tests folder to understand the API ?

**Comment by wang-bin** [comment]
`May I suggest to add to the wiki home page a mention to browse the source tests folder to understand the API ?`  
Good idea. Updated.
