### ISSUE TITLE
Qt creator 编译错误

### ISSUE THREAD

**Issue by faithg** [wang-bin/QtAV#559]
F:\QT\QtAV-master\src\cuda\cuda_api.cpp:-1: error: undefined reference to `_wassert'
F:\QT\QtAV-master\src\cuda\cuda_api.cpp:-1: error: undefined reference to `_wassert'
F:\QT\QtAV-master\src\cuda\cuda_api.cpp:-1: error: undefined reference to `_wassert'
F:\QT\QtAV-master\src\cuda\cuda_api.cpp:-1: error: undefined reference to `_wassert'
F:\QT\QtAV-master\src\cuda\cuda_api.cpp:-1: error: undefined reference to `_wassert'
F:\QT\QtAV-master\src\cuda\cuda_api.cpp:-1: error: more undefined references to `_wassert' follow
:-1: error: ./..\.obj\QtAV_win_x86\cuda_api.o: bad reloc address 0x4 in section `.rdata$_ZTV8cuda_api[__ZTV8cuda_api]'
collect2.exe:-1: error: error: ld returned 1 exit status

**Comment by wang-bin** [comment]
qt、编译器是什么

**Comment by faithg** [comment]
Qt5.3 mingw4.8.2

**Comment by wang-bin** [comment]
你更新下qt或mingw试试

**Comment by wang-bin** [comment]
我测了qt5.3+mingw4.9没问题

**Comment by faithg** [comment]
用了Qt5.4和mingw4.9.1也是类似的错，Qt默认安装的也把ffmpeg的库考到Qt目录了，不知道为什么？

**Comment by wang-bin** [comment]
不知道，没碰到过，相当于assert函数不能用。官方的5.5.1可以 https://ci.appveyor.com/project/wang-bin/qtav

**Comment by faithg** [comment]
可能是系统的原因吧，换了个系统测试编译可以通过，但是运行各个例子的时候又有一下问题了，求教。
Starting E:\QT\build-QtAV-Desktop_Qt_5_4_0_MinGW_32bit-Debug\bin\filters.exe...
程序异常结束。
E:\QT\build-QtAV-Desktop_Qt_5_4_0_MinGW_32bit-Debug\bin\filters.exe crashed

**Comment by wang-bin** [comment]
dll没找到。把ffmpeg、openal的dll放到qt的目录或可执行文件目录。具体确哪些可以双击运行看
