### ISSUE TITLE
hi, I got this error:undefined symbol: QtAV11VideoFilter

### ISSUE THREAD

**Issue by xsjqqq123** [wang-bin/QtAV#561]
all things are ready, and the exmple qmlplayer can exec.

the console output error:
QQmlApplicationEngine failed to load component
qrc:/main.qml:3 plugin cannot be loaded for module "QtAV":
Qt5.5.1/5.5/gcc_64/qml/QtAV/libQmlAV.so: undefined symbol: _ZNK4QtAV11VideoFilter11isSupportedENS_18VideoFilterContext4TypeE)

**Comment by wang-bin** [comment]
Seems loading the wrong libQtAV.so. How did you install or build qtav?

**Comment by xsjqqq123** [comment]
i build the lib by myself, and run it on deepin v15. Befroe that I install the qtav-dev libs, when this proble happren, I uninstall it. but the problem did not disappear。

when i open a project,it warns:
Warnings while parsing QML type information of /home/xusongjie/Qt5.5.1/5.5/gcc_64/qml/QtAV:
/home/xusongjie/Qt5.5.1/5.5/gcc_64/qml/QtAV/plugins.qmltypes:1:24: Reading only version 1.1 parts.
/home/xusongjie/Qt5.5.1/5.5/gcc_64/qml/QtAV/plugins.qmltypes:10:5: Expected only Component and ModuleApi object definitions.

Warnings while parsing QML type information of /home/xusongjie/Qt5.5.1/5.5/gcc_64/qml:
<dump of /home/xusongjie/Qt5.5.1/5.5/gcc_64/qml>:1:24: Reading only version 1.1 parts.
<dump of /home/xusongjie/Qt5.5.1/5.5/gcc_64/qml>:10:5: Expected only Component and ModuleApi object definitions.

**Comment by wang-bin** [comment]
You can't use qtav-dev to build the latest source. Uninstall and rebuild.

About the warnings: try `import QtQuick.tooling 1.2` => `import QtQuick.tooling 1.1`, remove `dependencies: ["QtQuick 2.0"]`
