### ISSUE TITLE
program crashes when executing after installing new API

### ISSUE THREAD

**Issue by andyscratch** [wang-bin/QtAV#562]
I don't know if the new API is the cause of the recent crash. I can't even build anymore. The program crashes before execution

**Comment by wang-bin** [comment]
you have to rebuild your app

**Comment by andyscratch** [comment]
Hi Wang. I really need your help as I can't continue with the project anymore. I have rebuilt the app several times and still the app crashes after running. When I copy it to Qt I get entry point not found errors which means there were build errors. The previous api was running fine so just don't know why this is causing this. At first I thought it was a bug in my code but after running the "how to use qtav code at your page" the test app still crashes. Please help me cos I left Qtmultimedia for QtAV. A month now and I can't continue

**Comment by wang-bin** [comment]
I need your test code

**Comment by andyscratch** [comment]
#include <QApplication>
#include <QtAV>
//#include <QtAV/AVPlayer.h>
#include <QDebug>
#include <QFileInfo>
#include <QWidget>
#include <QVBoxLayout>
#include <QPushButton>



int main(int arg, char *argc[])
{
    QApplication app(arg, argc);
    QtAV::AVPlayer player;
    player.setFile("D:/MUSIK/COOLS/02 Track 2.mp3");
    if(!QFileInfo(player.file()).exists()){
        qDebug() << "Source file does not exist";
        return 1;

    }
    else{
        QtAV::VideoRenderer *video = new QtAV::VideoOutput;
        if(!video->widget()){
            qDebug() << "Error creating video output";
            return 1;
        }
        player.setRenderer(video);
        QWidget window;
        QPushButton *button = new QPushButton;
        button->setText(QApplication::tr("Play"));
        QLayout *layout  = new QVBoxLayout;
        layout->addWidget(video->widget());
        layout->addWidget(button);
        window.setLayout(layout);

        QObject::connect(button, SIGNAL(clicked()), &player, SLOT(play()));
        window.resize(400, 400);
        window.show();
    }

**Comment by wang-bin** [comment]
You code can't work in any language. window will be destroyed immediately. You also forget to return `app.exec();`
