### ISSUE TITLE
QtCreator complains of Qt5AVWidgets.lib and Qt5AVs

### ISSUE THREAD

**Issue by andyscratch** [wang-bin/QtAV#563]
Gets link error when compiling my project.

**Comment by andyscratch** [comment]
Can't build in debug mode. Need details about how to install QtAV in windows because I usually get build errors with some files not getting copied

**Comment by wang-bin** [comment]
did you read wiki? how did you build?

**Comment by andyscratch** [comment]
After downloading QtAV1.9.0-VS2015x64 I opened the setup file. Navigating to the install directory I opened sdk_deploy.bat and pressed I in the install screen. Installation completed but I could see some files could not be located e.g. portaudio*.dll and lib\*Qt*AV*.a
When I go to the Qt lib folder I see QtAV1, QtAVWidgets1, Qt5AV and Qt5AVWidgets.

But when I compile in debug mode I get an error "LNK1104: cannot open file 'Qt5AVWidgetsd.lib" and in release mode the program crashes before execution with the message "the program has unexpectedly finished".

**Comment by wang-bin** [comment]
portaudio is disabled by default for a long time. Currently XAudio2 is used
by default on windows because it supports all windows versions, from xp to
10, and mobile. OpenAL is also enabled for most platforms.
The installer only has release build files. If you want debug files,
download  QtAV1.9.0-VS2015x64-release+debug.7z
<http://sourceforge.net/projects/qtav/files/release/1.9.0/QtAV1.9.0-VS2015x64-release%2Bdebug.7z/download>

Does simpleplayer_sdk.pro run in release mode? If program can not run,
double click in explorer to see what dlls are missing. Running in qtcreator
you can only get a message like "the program has unexpectedly finished".
Usually it's dll missing. Also you can put your program in qt's bin dir and
run it.

2016-01-05 17:10 GMT+08:00 andyscratch <notifications@github.com>:

**Comment by andyscratch** [comment]
simpleplayer_sdk.pro doesnt run in release mode. Anytime I try to run after building it says program has ended unexpectedly. The previous API was working pretty fine. Just having trouble with this one. Is not running anymore. App crashes.

**Comment by wang-bin** [comment]
don't run in qtcreator. double click the exe to see what dlls are missing, or other information. qtcreator tells you nothing.

**Comment by andyscratch** [comment]
Complains of QtAVWidgets1.dll, Qt5Core.dll, QtAV1.dll, Qt5Widgets.dll.

Earlier versions of QtAV were working though when you open the .exe file it
complains of these. QtCreator could run all fine. My problem is the
crashing cos other projects are running fine except when I add QtAV. Really
need your help.

My system is Intel core i3
windows 10 Pro 64 bit
8 gig mem

**Comment by wang-bin** [comment]
You have to rebuild your app with new qtav development files

**Comment by andyscratch** [comment]
I have deleted the built files from Qt's Workspace and built a new one. Yet
they program still crashes. Do I have to start a new project and add the
source files to the header file?

**Comment by wang-bin** [comment]
What's the message when you double click your app?

**Comment by andyscratch** [comment]
The files I mentioned earlier are still missing. When I copy the exe file
to Qt bin it says entry point not found error. Couldn't be located in
dynamic library QtAV1.dll

**Comment by wang-bin** [comment]
what entry point?

**Comment by andyscratch** [comment]
Check the salt.exe in the Qt bin folder. The message box is after double
clicking it.

what entry point?

—
Reply to this email directly or view it on GitHub
<https://github.com/wang-bin/QtAV/issues/563#issuecomment-171687397>.

**Comment by Hadi58** [comment]
I get error like your project when compiling too.
I read and do all comments and helps. but its not useful.
I have Win10 64bit on corei3.I installed qt-opensource-windows-x86-msvc2013_64-5.5.1 and QtAV1.9.0-VS2013x64 and use QtAV-depends-windows-x86+x64. but cant build and run simpleplayer\simpleplayer_sdk.pro.
![untitled](https://cloud.githubusercontent.com/assets/16745441/12378414/d769713e-bd51-11e5-903b-ae63715b1248.jpg)
 ... and continuous error windows QtAVd1.dll , Qt5Widgetsd.dll , ....

**Comment by wang-bin** [comment]
Copy them to exe folder. You should read doc about how to deploy a qt app
