### ISSUE TITLE
Pause on last frame

### ISSUE THREAD

**Issue by silly-git** [wang-bin/QtAV#566]
Hello - thanks for such a great library. Is it possible to pause on the last frame of a video when the eof is reached instead of stopping the video entirely? I also need to make sure it doesn't stop() when seeking to the last frame. I need to do this because I want to be able to seek through the video after the eof has been reached.

**Comment by wang-bin** [comment]
I can add this feature

**Comment by silly-git** [comment]
Great! That would be very much appreciated, is there something I can do to help?

Thanks

**Comment by wang-bin** [comment]
Try the latest code `player->setMediaEndAction(MediaEndAction_Pause)`

**Comment by silly-git** [comment]
Works great! Thank you very much for your time and effort.
