### ISSUE TITLE
Renderer size rounding

### ISSUE THREAD

**Issue by bongas** [wang-bin/QtAV#570]
Thanks for your great work!

This is an improvement request:
When I place QTAV widget on a solid panel in a Qt app I sometimes get a black line - either at the top or at the sides. I checked and it originated from a rounding error when calculating the renderer size. Would it be possible to change this in VideoRenderer_p.h:
Row 85: ```const int w = dar * qreal(h);```
to: ```const int w = qRound(dar * qreal(h));```
(Analogue change on row 90).

Sometimes the calculation gives a width e.g. 1023.999998 which will be converted to 1023 instead of the more accurate 1024. qRound will round it to 1024.

**Comment by wang-bin** [comment]
Sounds right. Code is updated. Thanks
