### ISSUE TITLE
Vorbis playback is awfull

### ISSUE THREAD

**Issue by Ilya87** [wang-bin/QtAV#577]
https://yadi.sk/d/0uHYHiIzoJTxb - test vorbis file that plays like a s**t in QMLPlayer and Miam-Player. ffplay decodes it without problem. No such problem with mp3 or flac.
My OS is Arch Linux, QtAV version - fafd3b0.

**Comment by wang-bin** [comment]
It should only happen with openal backend. Try the latest code. 56897c0 should fix this issue
