### ISSUE TITLE
Hardware decoding on Android 

### ISSUE THREAD

**Issue by bongas** [wang-bin/QtAV#579]
Hi!
I saw in issue #381 that you had plans for hardware decoding with OMX.
Have you had any progress with that? Do you have any time plan?
I would be awesome to try that out!

**Comment by wang-bin** [comment]
I don't have enough time now.

**Comment by bongas** [comment]
That's understandable!
I will still eagerly wait for it because it would be really nice.
Thanks.

**Comment by wang-bin** [comment]
The latest code using my private mediacodec library can get the best performance.
