### ISSUE TITLE
Seek a hls stream makes lag playback

### ISSUE THREAD

**Issue by NadaLess** [wang-bin/QtAV#581]
Hi wang, I tryed to seek a position of a hls (Apple http live stream) with a QmlAVPlayer, it does it well but playback starts to lag and console log shows continuosly:

> video too fast!!! sleep 0.60 s, nb fast: 121, v_a: 3.1954
> delay 13.060321s @215 666s pts:225.559 
> video too fast!!! sleep 0.61 s, nb fast: 122, v_a: 3.2094
> delay 13.171462s @215 666s pts:225.600 
> video too fast!!! sleep 0.61 s, nb fast: 123, v_a: 3.2233
> delay 13.227110s @215 666s pts:225.767 
> video too fast!!! sleep 0.62 s, nb fast: 124, v_a: 3.2371
> delay 13.282805s @215 666s pts:225.684 

Is there any trick or work flow to avoid this?

**Comment by NadaLess** [comment]
Any news about this?

**Comment by wang-bin** [comment]
What about the latest code?

**Comment by NadaLess** [comment]
latest code seems to sync when seek is finish after a while, but the problem is if I want to start at position.

I am playing hls youtube stream, and maybe there is something missing.

**Comment by wang-bin** [comment]
How to test youtube streams?

**Comment by NadaLess** [comment]
Sorry, it sync rigth after a while. Depends on network status. Thanks!
