### ISSUE TITLE
Grab video frames to openCV

### ISSUE THREAD

**Issue by sergiocopeto** [wang-bin/QtAV#586]
Hello!

How can I open a video and get every frame so I can use it in openCV?

Thanks in advance

**Comment by wang-bin** [comment]
use VideoFilter

**Comment by sergiocopeto** [comment]
Do I still need to have a renderer for the image or can I use just the audio?

Many Thanks!

**Comment by wang-bin** [comment]
If you don't call `AVPlayer.setRenderer/addVideoRenderer`, no video frame will be rendered. But the filters still work.

**Comment by wang-bin** [comment]
Then you can use AVPlayer as an audio player.

**Comment by PeterAkakpo** [comment]
i have a similar use case. i want to grab frames from AVPlayer and render it in a VideoFilter and use it as Picture in Picture
Any sample code will be appreciated
