### ISSUE TITLE
some questions about using qt creator_msvc to build code

### ISSUE THREAD

**Issue by Seakia** [wang-bin/QtAV#587]
Hello

Recently I am trying to build QtAV using qt creator with msvc2013_64 compiler in windows 10. And I have put the include file and lib file of "ffmpeg" in the qt directories. But I cannot get accurate results because there are a lot of "unresolved external symbols errors", which are all about the function about ffmpeg. And this errors happen in the make process. Can you give me some advices? Thanks.

The build Steps are:
qmake: qmake.exe QtAV.pro -r -spec win32-msvc2013 "CONFIG+=debug" "CONFIG += declarative_debug" "CONFIG+=qml_debug"
Make: jom.exe in C:\Code\build-QtAV-Desktop_Qt_5_5_1_MSVC2013_64bit-Debug

Is this setting right?

the Compile Output is 
 .......
VideoEncoderFFmpeg.obj : error LNK2019: unresolved external symbol avcodec_encode_video2 referenced in function "public: virtual bool __cdecl QtAV::VideoEncoderFFmpeg::encode(class QtAV::VideoFrame const &)" (?encode@VideoEncoderFFmpeg@QtAV@@UEAA_NAEBVVideoFrame@2@@Z)
..\lib_win_x86_64\QtAVd1.dll : fatal error LNK1120: 150 unresolved externals
jom: C:\Code\build-QtAV-Desktop_Qt_5_5_1_MSVC2013_64bit-Debug\src\Makefile.libQtAV [debug] Error 2
jom: C:\Code\build-QtAV-Desktop_Qt_5_5_1_MSVC2013_64bit-Debug\Makefile [sub-src-libQtAV-pro-make_first] Error 2
17:14:49: The process "C:\Qt\Qt5.5.1\Tools\QtCreator\bin\jom.exe" exited with code 2.
Error while building/deploying project QtAV (kit: Desktop Qt 5.5.1 MSVC2013 64bit)
When executing step "Make"
17:14:49: Elapsed time: 01:01.

**Comment by wang-bin** [comment]
How did you build ffmpeg?

**Comment by Seakia** [comment]
I used the prebuilt FFmpeg which you provided.

**Comment by Seakia** [comment]
I used ffmpeg-2.8.2-mingw+msvc-x86+x64

**Comment by wang-bin** [comment]
I don't know. Try this https://sourceforge.net/projects/qtav/files/depends/QtAV-depends-windows-x86%2Bx64.7z/download

**Comment by Seakia** [comment]
I used "QtAV-depends-windows-x86+x64" this library, but I encounter the same questions. Do I ignore some points when I build it with Qt Creator with MSVC in win10?

**Comment by wang-bin** [comment]
It's weird. Did you copy wrong libs? vs2013 should use the libs under libs/x64.
CI can build QtAV without error(vs2013x64 debug): https://ci.appveyor.com/project/wang-bin/qtav/build/job/b335lr5sbu6bc43o

**Comment by Seakia** [comment]
thanks!!! I have solved the question.
