### ISSUE TITLE
IOS build error

### ISSUE THREAD

**Issue by mohsenie** [wang-bin/QtAV#589]
Hi, 

I am building QtAv for Qt5.5 against an IOS target. I am building with QtCreator and everything compiles fine. However I get a strange make error at build time with error #65. I am building using Xcode 7.1 and everything seem to work fine for OSX target but IOS build fails. I wonder if I need to add some special config to the linker.

Regards,
Mo

**Comment by wang-bin** [comment]
Please show me your error message

**Comment by mohsenie** [comment]
Below is the last few lines from my terminal window.


PhaseScriptExecution Qt\ Qmake /Users/mosha/Desktop/mo/.obj/QMLPlayer_ios_arm+arm64_llvm/QMLPlayer.build/Debug-iphoneos/Qt\ Preprocess.build/Script-5E618435888B9D49F8540165.sh
    cd /Users/mosha/Desktop/mo/examples/QMLPlayer
    /bin/sh -c \"/Users/mosha/Desktop/mo/.obj/QMLPlayer_ios_arm+arm64_llvm/QMLPlayer.build/Debug-iphoneos/Qt\ Preprocess.build/Script-5E618435888B9D49F8540165.sh\"
make[4]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
make[4]: `QMLPlayer.xcodeproj/project.pbxproj' is up to date.

PhaseScriptExecution Qt\ Preprocessors /Users/mosha/Desktop/mo/.obj/QMLPlayer_ios_arm+arm64_llvm/QMLPlayer.build/Debug-iphoneos/Qt\ Preprocess.build/Script-7EF0942E79C014DCEC8976BC.sh
    cd /Users/mosha/Desktop/mo/examples/QMLPlayer
    /bin/sh -c \"/Users/mosha/Desktop/mo/.obj/QMLPlayer_ios_arm+arm64_llvm/QMLPlayer.build/Debug-iphoneos/Qt\ Preprocess.build/Script-7EF0942E79C014DCEC8976BC.sh\"
make[4]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
make[4]: *** No rule to make target `/Users/mosha/Desktop/mo/.rcc/5.5.1/QMLPlayer/qrc_qmlplayer.cpp', needed by `compilers'.  Stop.
Command /bin/sh failed with exit code 2

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Qt\ Preprocessors /Users/mosha/Desktop/mo/.obj/QMLPlayer_ios_arm+arm64_llvm/QMLPlayer.build/Debug-iphoneos/Qt\ Preprocess.build/Script-7EF0942E79C014DCEC8976BC.sh
(1 failure)
make[3]: *** [iphoneos-debug] Error 65
make[2]: *** [debug-iphoneos] Error 2
make[1]: *** [sub-QMLPlayer-make_first] Error 2
make: *** [sub-examples-make_first] Error 2

**Comment by mohsenie** [comment]
Ok found the the issue. You are missing an include in AVCompat.h. You need to add below to external includes.

`#include <libavfilter/avfilter.h>`

**Comment by wang-bin** [comment]
qmake creates a wrong makefile. Try the latest code.
