### ISSUE TITLE
请问qtav在播放url时能带上Refer和user-agent吗？

### ISSUE THREAD

**Issue by noahsai** [wang-bin/QtAV#595]
我打开的视频地址有些需要带上refer和user-agent才能获取数据，之前是用qt自带的媒体类做的，但由于在deepin2015里出现奇奇怪怪的问题，不想搞了，所以现在想用您的qtav试试。
不知道qtav在请求数据能不能带上Refer和user-agent？

**Comment by wang-bin** [comment]
user-agent可以，用AVPlayer.setOptionsForFormat({"user-agent": xxx})
refer是什么？

**Comment by noahsai** [comment]
sorry，记少两个字母，是Referer才对。都是一样设置的吧？
再请教一下有没有无缝播放在线的分段视频的项目推荐一下？或者如何正确使用qtav来实现无缝播放在线的分段视频，就是类似于国内视频网站的flash播放，能够从一段流畅的过度到下一段视频。
我之前是用两个qmediaplayer对像实现的，一个正在播放，一个预先加载下一段。后来在deepin2015
这方法就出问题了，现在只能一段一段的播放，这样中间就会卡几秒。。。

**Comment by wang-bin** [comment]
2个player出现什么问题了？
你试试ffmpeg的concat协议，可以把多个参数一样的视频当成一个放，但不知道有没有预加载机制

**Comment by noahsai** [comment]
我是用两个qmediaplayer指针，qplayer指向要播放的，tmpplayer用来预加载，切换时将qplayer指向tmpplayer，然后再设置一下输出setVideoOutput
但是播放预加载的视频时画面黑屏，但有声音，黑屏播放20多秒之后就会停止。这个方法在2014.3时还是能用的，2015开始就出现这情况了～～
那我有时间去看看ffmpeg的concat，谢谢了。

**Comment by wang-bin** [comment]
这样做应该没问题，和deepin没关系。

**Comment by noahsai** [comment]
唉～自从deepin2015之后我的渣软件就问题大爆发了，郁闷～
