### ISSUE TITLE
Segmentation fault on 1.10 linux64 release

### ISSUE THREAD

**Issue by oijazsh** [wang-bin/QtAV#597]
I downloaded QtAV1.10.0-Linux64.run from the http://qtav.org website. Attempting to execute the installer led to a Segmentation Fault:

```
$ ./QtAV1.10.0-Linux64.run
[1]    22721 segmentation fault  ./QtAV1.10.0-Linux64.run
```

I then proceeded to download and try version 1.9, for which the installer did not run into this issue.

**Comment by wang-bin** [comment]
which distribution and version?
btw, you can use tar.xz package here: http://sourceforge.net/projects/qtav/files/release/1.10.0/

**Comment by oijazsh** [comment]
Ubuntu 15.10.

Thank you for pointing me towards the tar.xz, managed to download and use in a test program.

**Comment by wang-bin** [comment]
It's strange because my environment is 15.10 too. I also tested on 14.04.

**Comment by gotakk** [comment]
Segmentation fault too on a Fedora 23 (kernel 4.4.8)

**Comment by wang-bin** [comment]
@gotakk The installer is made by qt installer framework. I will use it's latest version in the next release. Hope the issue will disappear. Currently please use tar.xz instead.

**Comment by gotakk** [comment]
@wang-bin ty for your fast answer and your incredible project !
I've tried to build it but I didn't success it
I have the follow error (even with ffmpeg-devel includes and libs copied in Qt dir) : "Project ERROR: avutil is required, but compiler can not find it"

I installed the QtAV 1.9 instead and it's rocks =)

**Comment by wang-bin** [comment]
@gotakk You have to install ffmpeg, pulse audio, openal, libva and libass dev packages. https://github.com/wang-bin/QtAV/wiki/Build-QtAV
You can also try this for fedora https://martinkg.fedorapeople.org/Review/SPECS/qtav.spec

**Comment by wang-bin** [comment]
That file is broken
