### ISSUE TITLE
sub package qtav-players conflicts with file from package player-3.0.2-45.fc23.x86_64 on Fedora

### ISSUE THREAD

**Issue by martinkg** [wang-bin/QtAV#598]
when trying to install the qtav rpm packages on Fedora, it conflicts with the file from an already existing
package with the name player.
file list of this player: http://koji.fedoraproject.org/koji/rpminfo?rpmID=6614383

error message:
file /usr/bin/player from install of qtav-players-1.10.0-0.2gitd930be8.fc23.x86_64 conflicts with file from package player-3.0.2-45.fc23.x86_64

is it possible to rename %{_bindir}/player to another rename ?
part of the rpm spec file:

%files players
%defattr(-,root,root,-)
%doc README.md Changelog
%license gpl-3.0.txt
%{_qt5_bindir}/player
%{_qt5_bindir}/QMLPlayer
%{_bindir}/player

**Comment by wang-bin** [comment]
I renamed `player` to `Player` for debian package

**Comment by martinkg** [comment]
ok, solves my problem.
Thanks
