### ISSUE TITLE
[solved] wrong stopPosition()

### ISSUE THREAD

**Issue by combiner** [wang-bin/QtAV#600]
```
int main(int argc, char **argv) {
	QCoreApplication app(argc, argv);
	QtAV::AVPlayer player;
	player.setFile(argv[1]);
	const qint64 stopPos = player.stopPosition();
	return app.exec();}
```
`stopPos` is always 9223372036854775807 no matter what audio file i feed to `setFile()`.
the file names are similar to "/media/partition/directory/track.ogg"
QtAV 1.10.0~git20160328.c8f88a0~wily

**Comment by wang-bin** [comment]
it's the maximum value of int64 if you don't call setStopPosition. You can use durationChanged() signal to get the length of media file. setFile will not load the file, so duration is not parsed.
