### ISSUE TITLE
examples, Player.  Color Space , OpenGL

### ISSUE THREAD

**Issue by Xuno** [wang-bin/QtAV#603]
With example Player.  
Changing values in the  Color Space menu [engine - OpenGL] doesn't  have any effect.
Tested at git 0d0087bda356515170ece283a7fd0f9d766cf5e2

**Comment by wang-bin** [comment]
Some uniforms are uploaded only once. But color matrix should be uploaded again if it is changed. It's a regression.

**Comment by wang-bin** [comment]
fixed in 787fe8b1

**Comment by Xuno** [comment]
thanks, now ok
