### ISSUE TITLE
好像是运行起来了，但没有界面出来。。。。。

### ISSUE THREAD

**Issue by hongoogle** [wang-bin/QtAV#604]
程序输出如下：
String::arg: Argument missing: /tmp/, index.m3u8
"QtAV 1.8.0(Apr  3 2016, 18:32:54)
A media playing library base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2015 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://www.qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://www.qtav.org"
"Build with Qt-5.3.2"
"Build with avutil-54.20.100"
"Build with avcodec-56.26.100"
"Build with avformat-56.25.101"
"Build with avfilter-5.11.102"
"Build with avdevice-56.4.100"
"Build with swresample-1.1.100"
"Build with swscale-3.1.101"
Registered audio backends:  ("null", "Pulse")
"framerate: -1.000/0.000"
Loading  QVariant(QString, "test.avi")  ...
"all closed and reseted"
"avformat_open_input: d->format_ctx:'0x7fecf0002f20', url:'test.avi'..."
"avformat_open_input: url:'test.avi' ret:0"
"avfmtctx.flag: 513"
"AVFMT_NOTIMESTAMPS: 0, AVFMT_TS_DISCONT: 512, AVFMT_NO_BYTE_SEEK:0"
"invalid index 0 (valid is 0~0) for stream type 2."
"notify_interval: 500"
"stream: 0, duration=2000 (80000 ms), time_base=0.040000"
"codec: mpeg4(MPEG-4 part 2)"
"invalid index 0 (valid is 0~0) for stream type 0."
"**********trying video decoder: FFmpeg..."
"**************Video decoder found:0x24ff4d0"
"setCapture 0x24e7b90"
"stream: 0, duration=2000 (80000 ms), time_base=0.040000"
"codec: mpeg4(MPEG-4 part 2)"
"Starting video thread..."
"onSourceStarted framerate: 0.000/25.000"
"get av queue a/v thread = 0x0 0x251dd30"
"AVClock started!!!!!!!!"
"no frame could be decompressed: Error number 4405 occurred 0/4405"
"invalid video frame from decoder. undecoded data size: 0"
"no frame could be decompressed: Error number 3640 occurred 0/3640"
"invalid video frame from decoder. undecoded data size: 0"
"no frame could be decompressed: Error number 3554 occurred 0/3554"
"invalid video frame from decoder. undecoded data size: 0"
"no frame could be decompressed: Error number 3214 occurred 0/3214"
"invalid video frame from decoder. undecoded data size: 0"
"no frame could be decompressed: Error number 3421 occurred 0/3421"
"invalid video frame from decoder. undecoded data size: 0"
"no frame could be decompressed: Error number 3372 occurred 0/3372"
"invalid video frame from decoder. undecoded data size: 0"
"no frame could be decompressed: Error number 1888 occurred 0/1888"
"invalid video frame from decoder. undecoded data size: 0"
"no frame could be decompressed: Error number 2052 occurred 0/2052"
"invalid video frame from decoder. undecoded data size: 0"
"use first supported pixel format: 0"
"size: 176x144 tbc: 0.040000=1/25"
"[FFmpeg:libx264] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX AVX2 FMA3 LZCNT BMI2"
"[FFmpeg:libx264] profile Main, level 2.1"
"dict: segment_list=>/tmp/"
"dict: segment_time=>4"
"dict: segment_format=>mpegts"
"dict: segment_list_size=>0"
"End of file. erreof=1 feof=1"
"video thread gets an eof packet."
"video thread gets an eof packet."
"video thread gets an eof packet."
"video thread gets an eof packet."
"video thread gets an eof packet."
"video thread gets an eof packet."
"video thread gets an eof packet."
"video thread gets an eof packet."
"video thread gets an eof packet."
"no frame could be decompressed: 成功 3/3"
"Decode video failed. undecoded: 3"
"decode eof done"
"Video thread stops running..."
"Demux thread stops running...."
"demuxer thread emit finished."
"avplayer emit stopped()"
"no packet got"
"[FFmpeg:libx264] frame I:200   Avg QP: 5.37  size: 10980"
"[FFmpeg:libx264] frame P:1800  Avg QP: 8.41  size:  4686"
"[FFmpeg:libx264] mb I  I16..4:  7.7%  0.0% 92.3%"
"[FFmpeg:libx264] mb P  I16..4:  0.8%  0.0%  4.7%  P16..4: 50.3% 17.0% 17.5%  0.0%  0.0%    skip: 9.7%"
"[FFmpeg:libx264] final ratefactor: 7.89"
"[FFmpeg:libx264] coded y,uvDC,uvAC intra: 91.7% 99.0% 95.5% inter: 53.7% 78.5% 76.7%"
"[FFmpeg:libx264] i16 v,h,dc,p:  5% 36% 52%  6%"
"[FFmpeg:libx264] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 12% 42% 12%  4%  5%  3% 10%  3% 10%"
"[FFmpeg:libx264] i8c dc,h,v,p: 73%  9%  6% 12%"
"[FFmpeg:libx264] Weighted P-Frames: Y:0.3% UV:0.0%"
"[FFmpeg:libx264] ref P L0: 88.0% 12.0%"
"[FFmpeg:libx264] kb/s:1063.04"
"Not playing~"
"Not playing~"
"Can not copy codec properties when it's open"
"closing d->format_ctx"
"~AVThreadPrivate wake up paused thread"

**Comment by wang-bin** [comment]
什么程序？另外请用最新的版本

**Comment by hongoogle** [comment]
用的就是 Latest release QtAV 1.8.0(Apr 3 2016, 18:32:54)，程序跑的是QtAV， 上面输出的"no frame could be decompressed: Error number 4405 occurred 0/4405"不知是什么意思，是不是它引起的呢？？？？？。。。。

**Comment by wang-bin** [comment]
解码出错。你用最新的版本试试，还有ffplay或者avplay试试
