### ISSUE TITLE
Problem with userShaderHeader, can't get location of uniform variables in GLSH array.

### ISSUE THREAD

**Issue by Xuno** [wang-bin/QtAV#605]
We try use your new  userShader code by use own custom class ShaderFilterXuno with: 
```
userShaderHeader(....
....    
return GLSL(
                uniform float u_filterkernel[9];
                uniform float u_gammaRGB;
                uniform vec2 u_pixeloffsetkernel[9];
                );
```
have  log file  with this:
```
Debug: QVector(uniform "float" u_filterkernel[9], dirty: true, location: -1, tupleSize: 1, value: QVector(0, 0, 0, 0, 0, 0, 0, 0, 0) ,  uniform "float" u_gammaRGB, dirty: true, location: 2, tupleSize: 1, value: QVector(0) ,  uniform "vec2" u_pixeloffsetkernel[9], dirty: true, location: -1, tupleSize: 2, value: QVector(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0) ) 
```

in log can see that for arrays location is undefined and = -1.

Here is [git class sample ShaderFilterXuno in test mode](https://github.com/Xuno/Xuno-QtAV/blob/tryUseCustomShader/examples/player/filters/ShaderFilterXuno.cpp)

Can test it, or something wrong at our side ?

**Comment by wang-bin** [comment]
Because you forgot to define `USED_FILTERS`?

**Comment by wang-bin** [comment]
btw, `setProperty("u_pixeloffsetkernel", QVariant::fromValue(QVector<float>(18) << 0.4f ));` in constructor will not work because a) property updating is depending on event/signal b) shader is not compiled.
With the latest code, you can put it in `VideoShaderObject::ready()`

**Comment by Xuno** [comment]
thanks,
not used uniform variables not compiled even if it declared.


P.S. What about detect textel size that depend from texture size ? 
Now I use fixed value in code. Because VideoMaterial not acceptable from my class.
```
QVector2D ShaderFilterXuno::pixeloffset () const
{
    //DPTR_D(const VideoMaterial);
    QSize d=QSize(640,480);
    float w=1.f/d.width();
    float h=1.f/d.height();
    return QVector2D(w,h);
}
```
What better solution ? Use instead it method prepared uniform u_texelSize array as in ConvolutionShader?

**Comment by wang-bin** [comment]
Yes, u_texelSize.

**Comment by Xuno** [comment]
How need set values if array used in uniform class ?
```
 GLfloat u_gammaRGB;
 QVector <GLfloat> u_filterkernel;
 QVector <QVector2D> u_pixeloffsetkernel;

void ShaderFilterXuno::setUserUniformValue(Uniform &u)
{
    if (u.name==QByteArray("u_gammaRGB")){
        u.set(u_gammaRGB);
    }else if(u.name==QByteArray("u_filterkernel")){
        u.set(u_filterkernel);
    }else if(u.name==QByteArray("u_pixeloffsetkernel")){
        u.set(u_pixeloffsetkernel);
    }
}
```
Now i have compile  errors:
: error C2664: 'void QtAV::Uniform::set(const int *,int)': cannot convert argument 1 from 'QVector<float>' to 'const float &'
note: Reason: cannot convert from 'QVector<float>' to 'const float'

error C2664: 'void QtAV::Uniform::set(const int *,int)': cannot convert argument 1 from 'QVector<QVector2D>' to 'const float &'
note: Reason: cannot convert from 'QVector<QVector2D>' to 'const float'

**Comment by wang-bin** [comment]
u.set(u_filterkernel.data())

QVector2D is not supported, so you have to use float array.
