### ISSUE TITLE
Hardware decoding Android

### ISSUE THREAD

**Issue by KolyanVM** [wang-bin/QtAV#609]
Hello!
There is a great need to add hardware decoding QtAV player for Android. I'm trying to implement with OMX library and some discussions that were here earlier.
Based on FFmpeg QtAV, I added a class VideoDecoderOMX...

```
class VideoDecoderOMX: public VideoDecoder
{
     DPTR_DECLARE_PRIVATE (VideoDecoderOMX)
public:
     VideoDecoderOMX ();
     VideoDecoderId id () const Q_DECL_OVERRIDE;
     QString description () const Q_DECL_OVERRIDE;
     VideoFrame frame () Q_DECL_OVERRIDE;
     bool decode (const Packet & packet) Q_DECL_OVERRIDE;
};
```

As I understand, I must to write processing in functions decode() and frame() with OMXCodec.
The main functions of OMX:

```
sp<MediaSource> Create(
            const sp<IOMX> &omx,
            const sp<MetaData> &meta, bool createEncoder,
            const sp<MediaSource> &source,
            const char *matchComponentName = NULL,
            uint32_t flags = 0,
            const sp<ANativeWindow> &nativeWindow = NULL);

status_t start(MetaData *params = NULL);
status_t stop();
status_t read( MediaBuffer **buffer, const ReadOptions *options = NULL);
```

Please tell me, can I get conversion data in  function decoder() with a call to OMX functions? And, is it right way to solve this problem?
##

**Comment by wang-bin** [comment]
I created omx branch some days ago. 
https://github.com/wang-bin/QtAV/commit/27b0c8f1c6fa508abd5e627f859bc9c3304804c2

**Comment by KolyanVM** [comment]
Sorry, didn't see.
Thank you, I hope you will have time to work on this issue soon.

**Comment by wang-bin** [comment]
The latest code using my private mediacodec library can get the best performance.
