### ISSUE TITLE
qtav ubantu编译后运行有画面，没有声音？

### ISSUE THREAD

**Issue by dalehqb** [wang-bin/QtAV#614]
set log file:  "/home/huang/QtAV-master/bin/log-Player.txt" 
Logger 
Debug: vo: qt
SubtitleProcessor::id("LibASS")
Not found
Unknown id SubtitleProcessor::id("FFmpeg")
SubtitleProcessor::id("FFmpeg")
VideoDecoder::id("FFmpeg")
VideoDecoder::id("FFmpeg")
VideoRenderer::next(0x1ed20c0)
VideoRenderer::next(0x1ed20c4)
VideoRenderer::next(0x1ed20c8)
VideoRenderer::next(0x1ed20cc)
VideoRenderer::next(0x1ed20d0)
Debug: -f set:  "test.avi" 
AudioOutputBackend::next(0x1ed0190)
AudioOutputBackend::next(0x1ed0194)
AudioOutputBackend::next(0x1ed0198)
AudioOutputBackend::id("Pulse")
VideoDecoder::id("FFmpeg")
Debug: QHash(("probesize", QVariant(uint, 5000000) ) ( "analyzeduration" ,  QVariant(int, 5000000) ) )  
Debug: status changed  "Loaded" 
AudioDecoder::id("FFmpeg")
Singleton 0x1ed3c60 created...
Unknown id Unknown id Home directory /home/routon not ours.
Debug: ScreenSaver::retrieveState
Debug: ScreenSaver::retrieveState timeout: 600, interval: 600, preferBlanking:1, allowExposures:1
Debug: ScreenSaver::enable 0, ret 1 timeout origin: 600
Debug: Succeed to enable screen saver (0)
Debug: track found!!!!!
Debug: status changed  "Buffering..." 
Debug: status changed  "Buffered"

**Comment by dalehqb** [comment]
export QTAV_LOG=all
之后的log：
Debug: Build with avutil-55.17.103
Debug: Build with avcodec-57.24.102
Debug: Build with avformat-57.25.100
Debug: Build with swscale-4.0.100
Debug: engine: "LibASS" 
SubtitleProcessor::id("LibASS")
Not found
Unknown id Debug: engine: "FFmpeg" 
SubtitleProcessor::id("FFmpeg")
Debug: engine: "FFmpeg" 
SubtitleProcessor::id("FFmpeg")
VideoDecoder::id("FFmpeg")
VideoDecoder::id("FFmpeg")
Warning: can not load cuda!
Debug: can not load va-drm: Cannot load library va-drm: (libva-drm.so: cannot open shared object file: No such file or directory)
Debug: libva-x11.so.1 loaded
Debug: libva-glx.so.1 loaded
VideoRenderer::next(0x23ce0c0)
VideoRenderer::next(0x23ce0c4)
VideoRenderer::next(0x23ce0c8)
VideoRenderer::next(0x23ce0cc)
VideoRenderer::next(0x23ce0d0)
Debug: -f set:  "test.avi" 
AudioOutputBackend::next(0x23cc190)
AudioOutputBackend::next(0x23cc194)
AudioOutputBackend::next(0x23cc198)
Debug: Registered audio backends:  ("OpenAL", "Pulse", "null") 
AudioOutputBackend::id("Pulse")
Debug: Not playing~
VideoDecoder::id("FFmpeg")
Debug: QHash(("probesize", QVariant(uint, 5000000) ) ( "analyzeduration" ,  QVariant(int, 5000000) ) )  
Debug: Loading  QVariant(QString, "test.avi")  ... 
Debug: all closed and reseted
Debug: avformat_open_input: d->format_ctx:'0x7f1c6000abe0', url:'test.avi'...
Debug: avformat_open_input: url:'test.avi' ret:0
Debug: avfmtctx.flag: 513
Debug: AVFMT_NOTIMESTAMPS: 0, AVFMT_TS_DISCONT: 512, AVFMT_NO_BYTE_SEEK:0, custom io: 0
Warning: invalid index 0 (valid is 0~0) for stream type 2.
Debug: notify_interval: 250
Debug: stream: 1, duration=2700000 (30000 ms), time_base=0.000011
Debug: codec: mp2(MP2 (MPEG audio layer 2))
Debug: stream: 0, duration=-9223372036854775808 (-102481911520608624 ms), time_base=0.000011
Debug: codec: mpeg2video(MPEG-2 video)
Debug: status changed  "Loaded" 
Debug: has audio
AudioDecoder::id("FFmpeg")
Singleton 0x25512a0 created...
Unknown id Unknown id Debug: QtAV::AudioDecoderFFmpeg thread type: Single, count: 1
Debug: audio format from codec:  QtAV::AudioFormat(48000Hz, 2Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "s16p") 
Debug: AudioOutput format:  QtAV::AudioFormat(48000Hz, 2Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "s16") 
Debug: "PulseAudio 1.1.0, protocol: 26, server protocol: 4294967295" 
Home directory /home/routon not ours.
Warning: PulseAudio context init failed
Warning: Connection refused
Debug: **********trying video decoder: FFmpeg...
Debug: "set QtAV::VideoDecoderFFmpeg() meta properties:" 
Debug: thread_type=>3
Debug: vismv=>0
Debug: skip_idct=>0
Debug: skip_loop_filter=>0
Debug: skip_frame=>0
Debug: threads=>0
Debug: codecName=>
Debug: QtAV::VideoDecoderFFmpeg thread type: Slice, count: 3
Debug: **************Video decoder found:0x243b590
Debug: setCapture 0x2536bf0
Debug: stream: 0, duration=-9223372036854775808 (-102481911520608624 ms), time_base=0.000011
Debug: codec: mpeg2video(MPEG-2 video)
Debug: Clock initial value: 0.685000
Debug: Starting video thread...
Debug: get av queue a/v thread = 0x0 0x254f470
Debug: ScreenSaver::retrieveState
Debug: ScreenSaver::retrieveState timeout: 600, interval: 600, preferBlanking:1, allowExposures:1
Warning: no frame could be decompressed: Error number 276144 occurred 0/276144
Warning: invalid video frame from decoder. undecoded data size: 0
Debug: ScreenSaver::enable 0, ret 1 timeout origin: 600
Debug: Succeed to enable screen saver (0)
Debug: track found!!!!!
Debug: status changed  "Buffering..." 
Debug: AVClock started!!!!!!!!
Debug: status changed  "Buffered" 
Debug: setInSize => calculating aspect ratio from converted input data(1.777778)

**Comment by wang-bin** [comment]
Pulse audio initialization error. What about other files?

**Comment by dalehqb** [comment]
其他文件表现相同。

**Comment by wang-bin** [comment]
这个没碰到过。什么系统？
用player -ao openal test.avi试试

**Comment by dalehqb** [comment]
ubantu 12.04.好的，还有其他的ao可选？支持sdl？其他的播放器都是有声音的。比如自带的，和smplayer

**Comment by wang-bin** [comment]
12.04没测过，太老了。ao只有pulseaudio和openal

**Comment by dalehqb** [comment]
升级到最新的系统，可以播放声音了，谢谢～
