### ISSUE TITLE
Playing two files at the same time causes audio problems

### ISSUE THREAD

**Issue by paul-h** [wang-bin/QtAV#615]
I'm trying to create a player using QML that can do 'picture-and-picture', so it has two VideoPlayer's side by side. Each player plays a different file or in my case a different stream from a local IP streamer.

The video side works well but there seems to be some contention with the audio. I can here both streams but the audio is broken up and has a lot of crackles/distortion etc.

I'd actually be happy to be able to disable the audio from one or other stream and just have one audio stream active but don't know if that is possible?

I'm using Kubuntu 16.04 with QTAV from your PPA. I think Ubuntu uses pulse audio for audio output if it matters.

**Comment by wang-bin** [comment]
OpenAL will be better. I don't know how to fix pulse audio.

    player->audio()->setBackends(QStringList() << "OpenAL");

**Comment by paul-h** [comment]
Like I said I'm using QML. You're going to have point me in the right direction I'm not seeing how to do from QML :)

**Comment by wang-bin** [comment]
I will add to qml

**Comment by wang-bin** [comment]
Try the latest code. I add audioBackends

**Comment by paul-h** [comment]
Setting the audio backend to OpenAL does indeed fix the audio problems.

Thanks for the quick fix.
