### ISSUE TITLE
seek to play doesn't send out positionChanged signal to QML

### ISSUE THREAD

**Issue by laborysun** [wang-bin/QtAV#616]
QtAV doesn't support to play with an offset directly such as play(int offset), so I have to start to play and when the playback state has been changed to MediaPlayer.PlayingState, then perform the seek operation. Now the video can be played and seeked, but I cannot receive the positionChanged signal from QtAV in QML in that condition(QT 5.5.1 for MINGW). However, a normal playback can receive the signal correctly with an interval of 400~500ms.
BTW, the same codes works on OSX, which means I can receive the signals and refresh the slider bar of playing progress by calculating the position.
Could you please help identify this problem? Thanks a lot.

**Comment by wang-bin** [comment]
Demo code please.

**Comment by laborysun** [comment]
I summarize the related codes, FYI. Thanks in advance.
Video {
	id: videoPreview
	visible: false
	anchors.fill: parent
	source: your_video_resource
	property var offset: 1000	// preset to a non-zero value
	onVisibleChanged: {
	if (visible == true) {
		play();
	} else {
		stop();
		offset = 0;
	}
	}
	onPlaybackStateChanged: {
		if (playbackState == MediaPlayer.PlayingState
				&& offset > 0 && seekable) {
			console.log("seek to offset " + offset);
			seek(offset);
			offset = 0;
		}
	}
	onSeekableChanged: {
		if (seekable && offset > 0) {
			seek(offset);
			offset = 0;
		}
	}
	onStatusChanged: {
		if (status == MediaPlayer.EndOfMedia) {
			stop();
			offset = 0;
			visible = false;
		}
	}	
	onPositionChanged: {
		console.log("position changed to " + position);
	}
}

**Comment by laborysun** [comment]
I looked into the codes, add some debug info and find some clue. In this case, the avplayer seeking status of d->seeking is always true, which prevent the player sending out the positionChanged signals in void AVPlayer::timerEvent(QTimerEvent *te)
And the reason is there is no seekFinished signal sent out from the audio/video read thread. I have no idea why the seek operation has been actually executed(as you can see from my piece of demo codes) but the seekFinished signal is not given. Maybe it needs more investigation in the demux threads.
Hope this info might be helpful.

**Comment by laborysun** [comment]
one more clue, the same codes work as expected on QtAV for OSX and QtAV for MSVC, so it seems more like a platform specific issue for QtAV for MINGW.

**Comment by laborysun** [comment]
It's a time sequence issue, the seek request is cleared in the avdemuxthread. I make some workaround in qml and fix this issue.

**Comment by wang-bin** [comment]
You are right, the demuxer thread  is not running when seeking

**Comment by wang-bin** [comment]
what about the latest code?

**Comment by laborysun** [comment]
I haven't got a chance to check the latest QtAV codes, my workaround is to pause() first before seek and then call play() after seek. It's a workaround and I will give your new codes a try next week. Thanks for your quick support.

**Comment by laborysun** [comment]
After testing the latest codes, this issue is gone. Thanks for your help.
