### ISSUE TITLE
How to record video from IP Camera (RTSP)

### ISSUE THREAD

**Issue by sergiocopeto** [wang-bin/QtAV#617]
Hello!

I'm trying to record a live feed from an IP camera (and at the same time display it, but that's working fine), following the simpletranscode example. The problem is that no file is produced. Is this example good for what I am trying to acomplish?

Thanks in advance

**Comment by wang-bin** [comment]
The example is right. You need add a video renderer to player, and don't call `setFrameRate()`. What about from a local file?

**Comment by sergiocopeto** [comment]
Ok got it working! Now I have 2 problems:
- Can't open the file in vlc media player or using qtav itself
- Image quallity is not the same as the stream I receive

Can you give a hint on what can be the problem?

**Comment by sergiocopeto** [comment]
My guess it that the file is not closed properly

**Comment by wang-bin** [comment]
What does `ffproble recorded_file` show?
Display quality?

**Comment by sergiocopeto** [comment]
Input #0, m4v, from 'testvideo.mp4':
Duration: N/A, start: 0.040000, bitrate: N/A
Stream #0:0: Video: mpeg4 (Simple Profile), yuv420p, 1920x1080 [SAR 1:1 DAR
16:9], 25 tbr, 1200k tbn, 25 tbc

**Comment by sergiocopeto** [comment]
Already figures out why quality is not the same.

**Comment by sergiocopeto** [comment]
Soved it! the problem was with the format/codec selection
