### ISSUE TITLE
qtav 能够捕获摄像头视频吗？

### ISSUE THREAD

**Issue by KangLin** [wang-bin/QtAV#619]
qtav 能够捕获摄像头视频吗？
##

**Comment by wang-bin** [comment]
Yes. https://github.com/wang-bin/QtAV/wiki/avdevice

**Comment by KangLin** [comment]
But, ffmpeg isn't support android carme.

**Comment by wang-bin** [comment]
You have to use android api, or qtmultimedia

**Comment by KangLin** [comment]
Yes. qtmultimedia is support android carme api. but is only 5.2.X is valid.

**Comment by KangLin** [comment]
你有好的解决方案么？

**Comment by wang-bin** [comment]
No

**Comment by KangLin** [comment]
是否要在QTAV中加入支持？

**Comment by wang-bin** [comment]
Maybe.

**Comment by KangLin** [comment]
Must :)
