### ISSUE TITLE
windows7 cannot build Qtav

### ISSUE THREAD

**Issue by moonlqer** [wang-bin/QtAV#620]
在win7系统下，Qt5.6.0 msvc2013版本编译QtAV的库文件，出现
libavresample or libswresample is required. Setup your environment correctly then delete C:/Users/Administrator/Desktop/QtPro/build-QtAV-Desktop_Qt_5_6_0_MSVC2013_32bit-Debug/.qmake.conf and run qmake again
已经下载
ffmpeg-2.8.2-mingw+msvc-x86+x64 并将其中的库文件和头文件放到Qt的安装目录下。
请问楼主这个问题该怎么解决？

**Comment by wang-bin** [comment]
https://github.com/wang-bin/QtAV/wiki/Build-QtAV
