### ISSUE TITLE
Problem to build QtAV

### ISSUE THREAD

**Issue by pierrexn** [wang-bin/QtAV#622]
i have a problem to build QtAV with Qt5.6.0 on Windows with nmake from VS2013. 
`d:\tmp\qtav\qtav\widgets\QtAVWidgets/GraphicsItemRenderer.h(82) : error C2143: syntax error : missing ';' before '*'
d:\tmp\qtav\qtav\widgets\QtAVWidgets/GraphicsItemRenderer.h(82) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
d:\tmp\qtav\qtav\widgets\QtAVWidgets/GraphicsItemRenderer.h(82) : warning C4183:
 'opengl': missing return type; assumed to be a member function returning 'int'
d:\tmp\qtav\qtav\widgets\QtAVWidgets/GraphicsItemRenderer.h(82) : error C3668: 'QtAV::GraphicsItemRenderer::opengl' : method with override specifier 'override'did not override any base class methodsGraphicsItemRenderer.cpp
d:\tmp\qtav\qtav\widgets\QtAVWidgets/GraphicsItemRenderer.h(82) : error C2143: syntax error : missing ';' before '*'
d:\tmp\qtav\qtav\widgets\QtAVWidgets/GraphicsItemRenderer.h(82) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
d:\tmp\qtav\qtav\widgets\QtAVWidgets/GraphicsItemRenderer.h(82) : warning C4183: 'opengl': missing return type; assumed to be a member function returning 'int'
d:\tmp\qtav\qtav\widgets\QtAVWidgets/GraphicsItemRenderer.h(82) : error C3668: 'QtAV::GraphicsItemRenderer::opengl' : method with override specifier 'override'did not override any base class methods.\GraphicsItemRenderer.cpp(157) : 
error C2556: 'QtAV::OpenGLVideo *QtAV::GraphicsItemRenderer::opengl(void) const' : overloaded function differs only by return
type from 'int *QtAV::GraphicsItemRenderer::opengl(void) const'
        d:\tmp\qtav\qtav\widgets\QtAVWidgets/GraphicsItemRenderer.h(82) : see declaration of 'QtAV::GraphicsItemRenderer::opengl'
.\GraphicsItemRenderer.cpp(157) : error C2371: 'QtAV::GraphicsItemRenderer::opengl' : redefinition; different basic types
        d:\tmp\qtav\qtav\widgets\QtAVWidgets/GraphicsItemRenderer.h(82) : see declaration of 'QtAV::GraphicsItemRenderer::opengl'`

If i build with VS2013 IDE, it works...

**Comment by wang-bin** [comment]
What's the first error?
nmake should work https://ci.appveyor.com/project/wang-bin/qtav/build/job/c0qvfdac697yn3i2

**Comment by pierrexn** [comment]
My fault, a problem with the headers....
