### ISSUE TITLE
New windows aren't showed when player is in full screen mode

### ISSUE THREAD

**Issue by aleksey-ho** [wang-bin/QtAV#625]
Windows 7, x64, qt5.5.1 mingw32, QtAV release 1.8.0.

I use QtAV in my project and recently I have feced with an issue. I have made some changes in simpleplayer example and reproduced the issue there, so what I do is:

I add button that will open label in new window
```
    btn = new QPushButton(tr("btn"));
    hb->addWidget(btn);
    connect(btn, SIGNAL(clicked()), SLOT(myslot()));
...
void PlayerWindow::myslot()
{
    QLabel *my = new QLabel("some text");
    my->show();
}
```
In main.cpp I do this:
```
    PlayerWindow player;
    player.showFullScreen();
//    player.resize(800, 600);
```

When I press my button I can see blinking of main window, but qlabel appears behind main mindow (I can see it when I press alt+f4)

I also noticed that when I remove this line:
`//    vl->addWidget(m_vo->widget());`
the qlabel shows as it should.
Or, of course, if i call `player.show();` instead of `player.showFullScreen();` it also appears well.

Please, tell me what could be the root of this issue (maybe I do something wrong).
I need a workaround of showing window in the foreground when player is working and the main window is in full screen mode
Thank you.

**Comment by wang-bin** [comment]
VideoOutput creates QOpenGLWidget by default. I did a simple test, I think it's a qt bug

    Widget::Widget(QWidget *parent) :  QWidget(parent)
    {
        QOpenGLWidget *gw = new QOpenGLWidget(this);
        QPushButton *b = new QPushButton("show label", this);
        connect(b, &QPushButton::clicked, []() {
            QLabel *lb = new QLabel("xxxx");
            lb->show();
        });
    }

As a workaround, you can use `m_vo = new VideoOutput(QtAV::VideoRendererId_GLWidget2, this);`  instead of `m_vo = new VideoOutput(this);` . Don't forget `#include <QtAVWidgets>`

**Comment by wang-bin** [comment]
It reported this bug to qt https://bugreports.qt.io/browse/QTBUG-53571

**Comment by aleksey-ho** [comment]
thanks a lot for your work!:)
workaround worked
