### ISSUE TITLE
partial playback

### ISSUE THREAD

**Issue by combiner** [wang-bin/QtAV#627]
i need to play an excerpt from a track. to use AVPlayer::setTimeRange() i have to keep in mind the duration of the track, but AVPlayer::duration() returns zero until i invoke AVPlayer::play(). how do i know the duration of the track before playing it?

**Comment by wang-bin** [comment]
Maybe no mediaStopPosition() check is better. I will change later.

**Comment by combiner** [comment]
i didn't get it. what do you mean?

**Comment by combiner** [comment]
i don't think that solved the problem. let's say a track is 100000 msec long. if i `setTimeRange(200000, 250000)` because i don't know the duration, then nothing will be played back. there's no way in QtAV to find out the duration before starting the playback to ensure the time range is set properly.

**Comment by wang-bin** [comment]
You can use signal durationChange. Video is async loaded, so no way to know the duration before play.

**Comment by combiner** [comment]
why can TagLib [which never plays anything] let me know [duration](https://taglib.github.io/api/classTagLib_1_1AudioProperties.html#a5321c07c5e4eb0bfc0f33c12a6584dfe), and QtAV can't?

**Comment by wang-bin** [comment]
If you simply want to know the duration, you can use avdemuxer.load(), a avplayer.load() (async by default).

**Comment by combiner** [comment]
from AVPlayer.h:
> bool load(); //NOT implemented.

but AVDemuxer::load() doesn't have such a comment and it works. that's nice! now i wonder why isn't the same implemented for AVPlayer?

**Comment by wang-bin** [comment]
`AVPlayer::load()` is done in the latest code.

**Comment by combiner** [comment]
that's cool! however, i couldn't build packages with `debuild -us -uc` because of the following error:

> In file included from plugin.cpp:25:0:
> QmlAV/QmlAVPlayer.h:94:47: warning: integer overflow in expression [-Woverflow]
>      enum PositionValue { PositionMax = (1<<31)-1};
>                                                ^
> QmlAV/QmlAVPlayer.h:94:48: error: overflow in constant expression [-fpermissive]
>      enum PositionValue { PositionMax = (1<<31)-1};
>                                                 ^
> QmlAV/QmlAVPlayer.h:94:48: error: enumerator value for ‘PositionMax’ is not an integer constant
> Makefile.libQmlAV:521: recipe for target '../.obj/QmlAV_linux_x86_64/plugin.o' failed
> make[2]: *** [../.obj/QmlAV_linux_x86_64/plugin.o] Error 1

**Comment by wang-bin** [comment]
It's strange. `(1<<31)-1` is the maximum of int32. What's your OS and toolchain? What about `(1<<(sizeof(PositionValue)*8-1)-1`?

**Comment by wang-bin** [comment]
ci build looks fine https://travis-ci.org/wang-bin/QtAV

**Comment by wang-bin** [comment]
int32 max value is `(1<<31)-1 `, but directly use the expression overflows. Try `int(~0)^(1<<(sizeof(PositionValue)*8-1))`

**Comment by combiner** [comment]
Kubuntu 16.04, g++ 5.3.1, make 4.1, devscripts 2.16.2ubuntu3

**Comment by combiner** [comment]
> In file included from plugin.cpp:25:0:
> QmlAV/QmlAVPlayer.h:94:73: error: invalid application of ‘sizeof’ to incomplete type ‘QmlAVPlayer::PositionValue’
>      enum PositionValue { PositionMax = int(~0)^(1<<(sizeof(PositionValue)*8-1))};
>                                                                          ^
> Makefile.libQmlAV:521: recipe for target '../.obj/QmlAV_linux_x86_64/plugin.o' failed
> make[2]: *** [../.obj/QmlAV_linux_x86_64/plugin.o] Error 1
