### ISSUE TITLE
Project ERROR: avutil is required, but compiler can not find it

### ISSUE THREAD

**Issue by langbluesky** [wang-bin/QtAV#629]
Hi, wang bin. I have downloaded the QtAV, and use Qt Creator to build it. But now I face this compile error: "Project ERROR: avutil is required, but compiler can not find it.". I have set the ffmpeg environment, still can not solve it, how can I solve this problem, thanks!

**Comment by wang-bin** [comment]
https://github.com/wang-bin/QtAV/wiki/Build-QtAV

**Comment by langbluesky** [comment]
I have tried the method under the webpage you give me. The config.log is saying: 
executing config test avutil.
+ cd E:\QtAV\QtAV-master\config.tests\avutil && "$(QTDIR)\bin\qmake.exe" -spec ....
系统找不到指定的目录
   I run this sentence in command line, it is the same problem. But when I replace "$(QTDIR)\bin\qmake.exe" with "D:\Qt\Qt5.5.0\5.5\msvc2013\bin\qmake.exe", and run the sentence, it successed! The makefile is produced. My QTDIR environment is correct. So what's the problem?

**Comment by wang-bin** [comment]
What did you do? You should never see `$(QTDIR)\bin\qmake.exe` in the output

**Comment by langbluesky** [comment]
我们还是用中文交流吧。我是在config.log文件中看到的，不是在输出窗口中看到的。对了，我的编译环境是MSVC2013。上面的问题是用MSVC2013打开QtAV.pro文件出现的，我的解决办法是这样的：
1、QtAV.pro文件中添加CONFIG += no_config_test
2、QtAV.pro文件中注释!config_avresample:!config-swresample {
 error("libavresample or libswresample is required. Setup your environment correctly then deletes $$BUILD_DIR/.qmake.conf and run qmake again")
}
注释完成后，就不会出现上面的问题。不过，现在编译工程还有些问题，我先看看能不能解决

**Comment by wang-bin** [comment]
vc编译器的话用msbuild或nmake，vs里编译很久没测了，不能保证能编

**Comment by langbluesky** [comment]
现在编译的问题是：pixelFormatFromFourcc无法找到函数定义，只有声明，链接不通过。这个是我的库文件没有引用？

**Comment by wang-bin** [comment]
你检测下编译步骤，正确的话不可能出现问题

**Comment by langbluesky** [comment]
我编译的是QtAV，这个工程没有依赖其他工程，因此编译顺序应该没问题。我用MSVC2013和QtCreator编译QtAV，都出现了图片中的问题。我的理解是pixelFormatFromFourcc函数缺少实现，所以才导致链接失败。下面的图片是错误信息
![default](https://cloud.githubusercontent.com/assets/15023049/15539493/6f925a16-22b5-11e6-9134-4aa432535793.jpg)

**Comment by wang-bin** [comment]
你编译环境或步骤有问题。你编译目录删了重新qmake，把config.log贴出来

**Comment by langbluesky** [comment]
问题已经解决了，确实是我的编译器问题。我在另外一台电脑上重新安装了Qt5.5.0和VS2013-x86，能够编译成功并运行。谢谢作者的耐心解答！

**Comment by langbluesky** [comment]
作者，请问下QtAV支持实时rtsp视频流播放吗？

**Comment by wang-bin** [comment]
支持

**Comment by langbluesky** [comment]
作者，我播放rtsp流时，缓冲特别慢。而用vlc播放时，基本不会产生延时。我将BufferMode设置成BufferPackets，bufferValue设置成1，仍旧没有改善。想请教下，如果能够改善延时的问题呢？

**Comment by wang-bin** [comment]
https://trac.ffmpeg.org/wiki/StreamingGuide#Latency
try `ffplay  -rtsp_transport tcp -probesize xxx -analyzeduration yyy url`

**Comment by langbluesky** [comment]
作者，我用ffplay播放了自己的rtsp流，并设置了rtsp_transport、probesize、analyzeduration参数，播放延时很小了。但是我设置自己创建的AVPlayer，设置相同的rtsp_transport、probesize、analyzeduration参数，播放延时还是很大，请问是不是我的参数设置不对，下面是我的设置参数代码。
QVariantHash opt;
opt[QString::fromLatin1("rtsp_transport")] = "tcp";
opt[QString::fromLatin1("analyzeduration")] = 100;
opt[QString::fromLatin1("probesize")] = 100;
myPlayer->play(rstpUrl);

**Comment by langbluesky** [comment]
上面代码忘输入了一句：myPlay->setOptionForFormat(opt);
