### ISSUE TITLE
Some Linux installation destinations are too generic and conflict-prone

### ISSUE THREAD

**Issue by akien-mga** [wang-bin/QtAV#632]
Hi there,

I'm trying to package QtAV 1.10 for Mageia, but I'm a bit bothered by some of the installation destinations, which are either wrong or susceptible to cause conflicts with other Qt 5 libraries (present and future).

Here are the files I find problematic (note that the paths are distro-specific, but the pattern should be the same on other distros):
- ``/usr/lib64/qt5/bin/libcommon.prl`` - This is not a binary! should go the Qt5's library dir like libQtAV.prl. Also, ``libcommon`` is a very generic name and does not describe at all how it's related to QtAV. The name should be changed to something more specific (e.g. ``libQtAVcommon.prl``)
- ``/usr/lib64/qt5/bin/player`` and ``/usr/share/applications/player.desktop`` - This is also a too generic name, you can't assume that QtAV's player will be the only application named ``player`` in the whole Linux ecosystem.
- ``/usr/lib64/qt5/include/common.h``, ``/usr/lib64/qt5/include/Config.h``, etc. - No files should be installed directly to Qt5's include directory without a subfolder, especially with such generic names. This is also prone to creating conflicts with other Qt5 libraries. If those files are the ones used for ``libcommon``, I would suggest to also move them to a ``QtAVcommon`` subfolder.
- ``/usr/share/icons/hicolor/64x64/apps/QtAV.svg`` - This is an SVG icon, it should go to ``/usr/share/icons/hicolor/scalable/apps/``
- ``/usr/share/doc/common`` and ``/usr/share/doc/player`` - Same issue, too generic. You should name your components in a what that makes them unique in the target ecosystem.

Sorry that I didn't check if those issues had already been addressed in the master branch already, I'm a bit short on time :)

**Comment by wang-bin** [comment]
Try the latest code. I rename `player` to `Player`, remove libcommon files which is used only when building players, and move svg to `scalable`

**Comment by akien-mga** [comment]
Thanks! It seems to work fine :)

I still get the ``player.destkop`` file instead with lower-case p, but I see you added a TODO, so I guess it's a known issue:
```
$ ack player.desktop
QtAV-1.10.0/examples/player/Makefile
6227:   -$(INSTALL_FILE) /home/akien/Mageia/Sandbox/_rpm/BUILD/QtAV-1.10.0/qtc_packaging/debian_generic/player.desktop $(INSTALL_ROOT)/usr/share/applications/
6230:   -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/player.desktop
```

**Comment by wang-bin** [comment]
I pushed the commit twice, the second one renamed player.desktop to Player.desktop

**Comment by akien-mga** [comment]
Right, I thought I had used the second commit but somehow my patched missed the rename :)

**Comment by wang-bin** [comment]
Can you try again?

**Comment by akien-mga** [comment]
It works fine, thanks :)
