### ISSUE TITLE
如何判断视频是播放完毕还是手动切换？

### ISSUE THREAD

**Issue by noahsai** [wang-bin/QtAV#642]

**Comment by wang-bin** [comment]
signal stopped()

**Comment by noahsai** [comment]
谢了，我以为用mediaStatusChanged()，一直卡在执行第二play()时会产生EndOfMedia的问题上。

**Comment by wang-bin** [comment]
mediaStatus是媒体文件的状态，而不是播放的状态

**Comment by mudfox** [comment]
if(position() == -25)
            playNext();
position() 为什么是-25？
