### ISSUE TITLE
QTAV does not work on Windows 10

### ISSUE THREAD

**Issue by l0phtgh0st** [wang-bin/QtAV#644]
I try using QTAV on Windows 10, but it was saying "this app can't run on your computer" and tell me to contact the vendor.

I wanted to know QTAV work on Windows 10.

Is the problem regarding Windows 10 or QT ?

**Comment by wang-bin** [comment]
Where do you get QtAV? Build yourself or download from sourceforge? 32 or 64 bit win10?

**Comment by l0phtgh0st** [comment]
The Windows 10 is 64 bit.

I try runing "simpleplayer" example from the qt creator.

I get the sorce code from git hub.

**Comment by wang-bin** [comment]
Are ffmpeg dlls in qt bin dir?

**Comment by l0phtgh0st** [comment]
Yes, I have run sdk_deploy.bat so I guess they are in the qt bin dir.

It have work on Windows 8.1.

I have put all the required dll (qt and ffmpeg), exe in a single folder on Windows 8.1 and it work.

When I copy that folder to Windows 10 and run the exe, it does now work.

**Comment by l0phtgh0st** [comment]
I mean it does not work.

Sorry for the typing error.

**Comment by wang-bin** [comment]
What do you see if double click the exe?

**Comment by l0phtgh0st** [comment]
"This app can't run on PC" dialogue box in Windows 10.

**Comment by wang-bin** [comment]
I don't know. Please build a simple qt app and run on win10

**Comment by l0phtgh0st** [comment]
I have try it and when I run on Windows 10, it show the "This app can't run on PC" error dialogue box in Windows 10.

**Comment by wang-bin** [comment]
So It's not a qtav issue if other qt apps can't run

**Comment by p4ws** [comment]
I use QtAV on Windows 10 64-bit and it builds and works without any problems.

**Comment by l0phtgh0st** [comment]
What version of QT do you build it on?
