### ISSUE TITLE
unresolved external symbol "enum QtAV::VideoFormat::PixelFormat __cdecl QtAV::pixelFormatFromFourcc(int)" 

### ISSUE THREAD

**Issue by anhlt309** [wang-bin/QtAV#645]
SurfaceInteropD3D9.obj : error LNK2019: unresolved external symbol "enum QtAV::VideoFormat::PixelFormat __cdecl QtAV::pixelFormatFromFourcc(int)" (?pixelFormatFromFourcc@QtAV@@YA?AW4PixelFormat@VideoFormat@1@H@Z) referenced in function "protected: void * __thiscall QtAV::d3d9::SurfaceInterop::mapToHost(class QtAV::VideoFormat const &,void *,int)" (?mapToHost@SurfaceInterop@d3d9@QtAV@@IAEPAXABVVideoFormat@3@PAXH@Z)

**Comment by wang-bin** [comment]
You build environment is not correct. What's your VS version?

**Comment by anhlt309** [comment]
I am building QtAV project on Windows 10, with QtCreator + Qt 5.6.0, ffmpeg download from [https://sourceforge.net/projects/qtav/files/depends/QtAV-depends-windows-x86%2Bx64.7z/download](url)

**Comment by wang-bin** [comment]
What's your VS version?

**Comment by wang-bin** [comment]
Are you using shadow build?

**Comment by anhlt309** [comment]
I am using Visual Studio 2013. And I dont use shadow build, i use Qt download from [https://download.qt.io/archive/qt/5.6/5.6.0/qt-opensource-windows-x86-msvc2013-5.6.0.exe](url)

**Comment by anhlt309** [comment]
Can you give me a QtAV version build-debug of VS2013 x86?
