### ISSUE TITLE
error: C3668: 'QtAV::GraphicsItemRenderer::opengl' : method with override specifier 'override' did not override any base class methods

### ISSUE THREAD

**Issue by anhlt309** [wang-bin/QtAV#646]
qtav-master\build\debug\.moc\5.6.0\qtavwidgetsd\../../../../../widgets/QtAVWidgets/GraphicsItemRenderer.h(82) : error C2143: syntax error : missing ';' before '*'

\qtav-master\build\debug\.moc\5.6.0\qtavwidgetsd\../../../../../widgets/QtAVWidgets/GraphicsItemRenderer.h(82) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

\qtav-master\widgets\QtAVWidgets\GraphicsItemRenderer.h:82: error: C3668: 'QtAV::GraphicsItemRenderer::opengl' : method with override specifier 'override' did not override any base class methods

**Comment by wang-bin** [comment]
See #622 I don't know how to fix it because I can't reproduce it. You must have wrong steps

**Comment by anhlt309** [comment]
Follow your link, i saw that is his fault. But I am building project libQtAV + libQtAVWidgets with QtCreator, Qt5.6 on Windows, and I dont edit any your code.

**Comment by wang-bin** [comment]
Show me the content of .qmake.cache in build dir. And show me your first error
