### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by yuetianle** [wang-bin/QtAV#653]
D:\github\QtAV\src\QtAV\private\AVCompat.h:406: error: C4430: missing type specifier - int assumed. Note: C++ does not support default-int

code 
const char *avfilter_pad_get_name(const AVFilterPad *pads, int pad_idx);
enum AVMediaType avfilter_pad_get_type(const AVFilterPad *pads, int pad_idx);

需要什么其他操作吗
ffmpeg已经添加到目录

**Comment by wang-bin** [comment]
编译器、目标系统、cpu、ffmpeg版本 是什么？
编译目录的.qmake.cache内容也贴下
