### ISSUE TITLE
build error on mac of commit: v1.11.0 origin/master origin/HEAD

### ISSUE THREAD

**Issue by laborysun** [wang-bin/QtAV#655]
build on mac and receive the following compiling error:
Undefined symbols for architecture x86_64:
  "openal::capi::loaded()", referenced from:
      QtAV::AudioOutputOpenAL::AudioOutputOpenAL(QObject*) in AudioOutputOpenAL.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../lib_osx_x86_64_llvm/QtAV.framework/QtAV] Error 1
make: *** [sub-src-libQtAV-pro-make_first] Error 2
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names '-Wl,-rpath,/Users/zmsun/work/RefCodes/QtAV_Prj/build-QtAV-Desktop_Qt_5_5_1_clang_64bit-Release/lib_osx_x86_64_llvm' '-Wl,-rpath,@loader_path/../Frameworks' '-Wl,-rpath,@executable_path/../Frameworks' -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -stdlib=libc++ -mmacosx-version-min=10.8 -single_module -dynamiclib -compatibility_version	1.11 -current_version	1.11.0 -Wl,-install_name,@rpath/QtAV.framework/Versions/1/QtAV -o QtAV ../.obj/QtAV_osx_x86_64_llvm/CopyFrame_SSE2.o ../.obj/QtAV_osx_x86_64_llvm/CopyFrame_SSE4.o ../.obj/QtAV_osx_x86_64_llvm/uchardet.o ../.obj/QtAV_osx_x86_64_llvm/nsEUCTWProber.o ../.obj/QtAV_osx_x86_64_llvm/LangCyrillicModel.o ../.obj/QtAV_osx_x86_64_llvm/nsSBCharSetProber.o ../.obj/QtAV_osx_x86_64_llvm/CharDistribution.o ../.obj/QtAV_osx_x86_64_llvm/nsLatin1Prober.o ../.obj/QtAV_osx_x86_64_llvm/nsEscSM.o ../.obj/QtAV_osx_x86_64_llvm/nsUTF8Prober.o ../.obj/QtAV_osx_x86_64_llvm/nsBig5Prober.o ../.obj/QtAV_osx_x86_64_llvm/LangBulgarianModel.o ../.obj/QtAV_osx_x86_64_llvm/nsGB2312Prober.o ../.obj/QtAV_osx_x86_64_llvm/nsCharSetProber.o ../.obj/QtAV_osx_x86_64_llvm/nsEscCharsetProber.o ../.obj/QtAV_osx_x86_64_llvm/nsEUCKRProber.o ../.obj/QtAV_osx_x86_64_llvm/nsEUCJPProber.o ../.obj/QtAV_osx_x86_64_llvm/nsSJISProber.o ../.obj/QtAV_osx_x86_64_llvm/nsMBCSSM.o ../.obj/QtAV_osx_x86_64_llvm/nsHebrewProber.o ../.obj/QtAV_osx_x86_64_llvm/nsUniversalDetector.o ../.obj/QtAV_osx_x86_64_llvm/nsSBCSGroupProber.o ../.obj/QtAV_osx_x86_64_llvm/nsMBCSGroupProber.o ../.obj/QtAV_osx_x86_64_llvm/LangThaiModel.o ../.obj/QtAV_osx_x86_64_llvm/LangHebrewModel.o ../.obj/QtAV_osx_x86_64_llvm/JpCntx.o ../.obj/QtAV_osx_x86_64_llvm/LangHungarianModel.o ../.obj/QtAV_osx_x86_64_llvm/LangGreekModel.o ../.obj/QtAV_osx_x86_64_llvm/AudioResamplerFF.o ../.obj/QtAV_osx_x86_64_llvm/AudioResamplerLibav.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutputAudioToolbox.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutputOpenAL.o ../.obj/QtAV_osx_x86_64_llvm/openal_api.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderCUDA.o ../.obj/QtAV_osx_x86_64_llvm/SurfaceInteropCUDA.o ../.obj/QtAV_osx_x86_64_llvm/cuda_api.o ../.obj/QtAV_osx_x86_64_llvm/SurfaceInteropCV.o ../.obj/QtAV_osx_x86_64_llvm/SurfaceInteropIOSurface.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderVDA.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderVideoToolbox.o ../.obj/QtAV_osx_x86_64_llvm/GLSLFilter.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLRendererBase.o ../.obj/QtAV_osx_x86_64_llvm/gl_api.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLTypes.o ../.obj/QtAV_osx_x86_64_llvm/Geometry.o ../.obj/QtAV_osx_x86_64_llvm/GeometryRenderer.o ../.obj/QtAV_osx_x86_64_llvm/SubImagesGeometry.o ../.obj/QtAV_osx_x86_64_llvm/SubImagesRenderer.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLVideo.o ../.obj/QtAV_osx_x86_64_llvm/VideoShaderObject.o ../.obj/QtAV_osx_x86_64_llvm/VideoShader.o ../.obj/QtAV_osx_x86_64_llvm/ShaderManager.o ../.obj/QtAV_osx_x86_64_llvm/ConvolutionShader.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLHelper.o ../.obj/QtAV_osx_x86_64_llvm/OpenGLWindowRenderer.o ../.obj/QtAV_osx_x86_64_llvm/AVCompat.o ../.obj/QtAV_osx_x86_64_llvm/QtAV_Global.o ../.obj/QtAV_osx_x86_64_llvm/SubImage.o ../.obj/QtAV_osx_x86_64_llvm/CharsetDetector.o ../.obj/QtAV_osx_x86_64_llvm/PlainText.o ../.obj/QtAV_osx_x86_64_llvm/PlayerSubtitle.o ../.obj/QtAV_osx_x86_64_llvm/Subtitle.o ../.obj/QtAV_osx_x86_64_llvm/SubtitleProcessor.o ../.obj/QtAV_osx_x86_64_llvm/SubtitleProcessorFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/GPUMemCopy.o ../.obj/QtAV_osx_x86_64_llvm/Logger.o ../.obj/QtAV_osx_x86_64_llvm/AudioThread.o ../.obj/QtAV_osx_x86_64_llvm/internal.o ../.obj/QtAV_osx_x86_64_llvm/AVThread.o ../.obj/QtAV_osx_x86_64_llvm/AudioFormat.o ../.obj/QtAV_osx_x86_64_llvm/AudioFrame.o ../.obj/QtAV_osx_x86_64_llvm/AudioResampler.o ../.obj/QtAV_osx_x86_64_llvm/AudioDecoder.o ../.obj/QtAV_osx_x86_64_llvm/AudioDecoderFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/AudioEncoder.o ../.obj/QtAV_osx_x86_64_llvm/AudioEncoderFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/AVDecoder.o ../.obj/QtAV_osx_x86_64_llvm/AVEncoder.o ../.obj/QtAV_osx_x86_64_llvm/AVMuxer.o ../.obj/QtAV_osx_x86_64_llvm/AVDemuxer.o ../.obj/QtAV_osx_x86_64_llvm/AVDemuxThread.o ../.obj/QtAV_osx_x86_64_llvm/ColorTransform.o ../.obj/QtAV_osx_x86_64_llvm/Frame.o ../.obj/QtAV_osx_x86_64_llvm/FrameReader.o ../.obj/QtAV_osx_x86_64_llvm/Filter.o ../.obj/QtAV_osx_x86_64_llvm/FilterContext.o ../.obj/QtAV_osx_x86_64_llvm/FilterManager.o ../.obj/QtAV_osx_x86_64_llvm/LibAVFilter.o ../.obj/QtAV_osx_x86_64_llvm/SubtitleFilter.o ../.obj/QtAV_osx_x86_64_llvm/EncodeFilter.o ../.obj/QtAV_osx_x86_64_llvm/ImageConverter.o ../.obj/QtAV_osx_x86_64_llvm/ImageConverterFF.o ../.obj/QtAV_osx_x86_64_llvm/Packet.o ../.obj/QtAV_osx_x86_64_llvm/PacketBuffer.o ../.obj/QtAV_osx_x86_64_llvm/AVError.o ../.obj/QtAV_osx_x86_64_llvm/AVPlayer.o ../.obj/QtAV_osx_x86_64_llvm/AVPlayerPrivate.o ../.obj/QtAV_osx_x86_64_llvm/AVTranscoder.o ../.obj/QtAV_osx_x86_64_llvm/AVClock.o ../.obj/QtAV_osx_x86_64_llvm/VideoCapture.o ../.obj/QtAV_osx_x86_64_llvm/VideoFormat.o ../.obj/QtAV_osx_x86_64_llvm/VideoFrame.o ../.obj/QtAV_osx_x86_64_llvm/MediaIO.o ../.obj/QtAV_osx_x86_64_llvm/QIODeviceIO.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutput.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutputBackend.o ../.obj/QtAV_osx_x86_64_llvm/AudioOutputNull.o ../.obj/QtAV_osx_x86_64_llvm/VideoRenderer.o ../.obj/QtAV_osx_x86_64_llvm/VideoOutput.o ../.obj/QtAV_osx_x86_64_llvm/QPainterRenderer.o ../.obj/QtAV_osx_x86_64_llvm/AVOutput.o ../.obj/QtAV_osx_x86_64_llvm/OutputSet.o ../.obj/QtAV_osx_x86_64_llvm/Statistics.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoder.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderFFmpegBase.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/VideoDecoderFFmpegHW.o ../.obj/QtAV_osx_x86_64_llvm/VideoEncoder.o ../.obj/QtAV_osx_x86_64_llvm/VideoEncoderFFmpeg.o ../.obj/QtAV_osx_x86_64_llvm/VideoThread.o ../.obj/QtAV_osx_x86_64_llvm/VideoFrameExtractor.o ../.obj/QtAV_osx_x86_64_llvm/qrc_QtAV.o ../.obj/QtAV_osx_x86_64_llvm/qrc_shaders.o ../.obj/QtAV_osx_x86_64_llvm/moc_ShaderManager.o ../.obj/QtAV_osx_x86_64_llvm/moc_GLSLFilter.o ../.obj/QtAV_osx_x86_64_llvm/moc_OpenGLVideo.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoShaderObject.o ../.obj/QtAV_osx_x86_64_llvm/moc_OpenGLWindowRenderer.o ../.obj/QtAV_osx_x86_64_llvm/moc_AudioEncoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_AudioOutput.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVDecoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVEncoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVDemuxer.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVMuxer.o ../.obj/QtAV_osx_x86_64_llvm/moc_Filter.o ../.obj/QtAV_osx_x86_64_llvm/moc_LibAVFilter.o ../.obj/QtAV_osx_x86_64_llvm/moc_EncodeFilter.o ../.obj/QtAV_osx_x86_64_llvm/moc_FrameReader.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVPlayer.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVTranscoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoCapture.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoOutput.o ../.obj/QtAV_osx_x86_64_llvm/moc_MediaIO.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVClock.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoEncoder.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoFrameExtractor.o ../.obj/QtAV_osx_x86_64_llvm/moc_Subtitle.o ../.obj/QtAV_osx_x86_64_llvm/moc_SubtitleFilter.o ../.obj/QtAV_osx_x86_64_llvm/moc_PlayerSubtitle.o ../.obj/QtAV_osx_x86_64_llvm/moc_AudioOutputBackend.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVDemuxThread.o ../.obj/QtAV_osx_x86_64_llvm/moc_AVThread.o ../.obj/QtAV_osx_x86_64_llvm/moc_AudioThread.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoThread.o ../.obj/QtAV_osx_x86_64_llvm/moc_VideoDecoderFFmpegHW.o ../.obj/QtAV_osx_x86_64_llvm/moc_OutputSet.o  -F/Users/zmsun/Qt5.5.1/5.5/clang_64/lib -lswresample -lavresample -lavdevice -lavfilter -framework AudioToolbox -framework IOSurface -framework CoreVideo -framework CoreFoundation -framework VideoDecodeAcceleration -framework CoreMedia -framework VideoToolbox -L/Users/zmsun/Qt5.5.1/5.5/clang_64/lib -lavcodec -lavformat -lswscale -lavutil -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL  
19:43:28: 进程"/usr/bin/make"退出，退出代码 2 。
Error while building/deploying project QtAV (kit: Desktop Qt 5.5.1 clang 64bit)
When executing step "Make"

**Comment by wang-bin** [comment]
run `git submodule update` first

**Comment by laborysun** [comment]
cool, the problem is solved, thanks.
