### ISSUE TITLE
Black screen at the end of the video playing

### ISSUE THREAD

**Issue by rpw98** [wang-bin/QtAV#656]
I was looking for a simple cross-platform video player and I just tried out QtAV and found it very nice. However, I found the black screen very unpleasing after video play and also makes looping look bad. How do I make the video player show the last frame of the video instead of a black screen when the video ends?

Thank you!

**Comment by rpw98** [comment]
Actually nevermind, I found the flag to set it.

**Comment by wang-bin** [comment]
`AVPlayer::setMediaEndAction()`
