### ISSUE TITLE
Paused video still emitting jumping noise

### ISSUE THREAD

**Issue by rpw98** [wang-bin/QtAV#657]
Environment: Windows 7 64bit, Qt 5.6.1 msvc2013_64, Pre-build QtAV libs downloaded from https://sourceforge.net/projects/qtav/files/release/1.11.0/

To reproduce the bug, you can just use the simpleplayer example, let it play this file online: https://instagram.fbos1-1.fna.fbcdn.net/t50.2886-16/12144449_629177423890491_1763369843_n.mp4

You can hard-code it in void PlayerWindow::openMedia() function.

While it is playing, press "Play/Pause" button to pause, the sound goes crazy. I tried another online video, same behavior.

Thanks!

**Comment by wang-bin** [comment]
I forgot to put OpenAL32.dll into the installer. Then QtAV fallback to use DirectSound. But DirectSound in QtAV is buggy. On windows, you can use either OpenAL or XAudio2. OpenAL dll is in https://sourceforge.net/projects/qtav/files/depends/QtAV-depends-windows-x86%2Bx64.7z/download Rename OpenAL32-VS2013.dll to OpenAL32.dll and put it to QtAV1.dll dir can solve your problem.
To let XAudio2 work on win7 or older versions, you have to manually install an driver https://sourceforge.net/projects/qtav/files/depends/DXSDK2010_XAudio2_redist.7z/download

**Comment by rpw98** [comment]
That worked! Thank you!
