### ISSUE TITLE
setLogLevel

### ISSUE THREAD

**Issue by rpw98** [wang-bin/QtAV#658]
How to turn off printing out log info? I run 

QtAV::setLogLevel(QtAV::LogOff);

But still gets lots of printout in the console.

Thanks!

**Comment by wang-bin** [comment]
the remaining output messages is not controlled by the logging tool. They use printf. You have to remove manually in source code.

**Comment by rpw98** [comment]
Can I make a suggestion to have an option to turn off those printout in the next version? Thank you!

**Comment by wang-bin** [comment]
Some messages are not from QtAV. I can turn off QtAV messages

**Comment by mash-graz** [comment]
a QTAV_LOG_LEVEL "quiet" [as default] would be really nice!
otherwise: great software! -- thanks!
