### ISSUE TITLE
是否可以支持arm embedded QT4.8.6

### ISSUE THREAD

**Issue by cl2006ky** [wang-bin/QtAV#661]
我想把这个移植到embedded arm QT4.8.6的版本上，请问是否可以支持？

**Comment by wang-bin** [comment]
支持

**Comment by xman1101** [comment]
hi， 我有同样的问题。
编译环境 ubuntu14.04 x86_64 交叉编译环境
我如何在编译qtav时， 指定使用某个路径下 arm版本的ffmpeg开发包呢

**Comment by xman1101** [comment]
arm板子上目前只有alsa，
还不支持pulseaudio和openal，这个能在编译的时候disable掉吗？我怕引起编译错误

谢谢！

**Comment by wang-bin** [comment]
@xman1101 编译方法看wiki，交叉编译一个道理。openal和pulseaudio都没有的话音频无法播放，你可以自己编译一下openal-soft
