### ISSUE TITLE
build error on Qt 5.7.0 MSVS2015 x64

### ISSUE THREAD

**Issue by thefastman** [wang-bin/QtAV#667]
build on win and receive the following compiling error:

Creating library ..\lib_win_x86_64\QtAVd1.lib and object ..\lib_win_x86_64\QtAVd1.exp
GeometryRenderer.obj : error LNK2019: unresolved external symbol __imp_glDrawElements referenced in function "public: void __cdecl QtAV::GeometryRenderer::render(class QtAV::Geometry *)" (?render@GeometryRenderer@QtAV@@QEAAXPEAVGeometry@2@@Z)
..\lib_win_x86_64\QtAVd1.dll : fatal error LNK1120: 1 unresolved externals

**Comment by thefastman** [comment]
I think it's just you forgot LIBS += -lopengl32

**Comment by wang-bin** [comment]
No. I forgot to add `DYGL()` around that function.

**Comment by wang-bin** [comment]
try the latest code

**Comment by thefastman** [comment]
Now is ok.
