### ISSUE TITLE
Build error with latest codes

### ISSUE THREAD

**Issue by nhatson1987** [wang-bin/QtAV#669]
I've encountered the following compilation error on Windows after sycning latest codes:
![image](https://cloud.githubusercontent.com/assets/1432094/16593481/16c80ec4-42ab-11e6-8500-24dd99c126a4.png)

**Comment by wang-bin** [comment]
`git submodule update` and then rebuild openal code in QtAV

**Comment by nhatson1987** [comment]
It works, thank you!
