### ISSUE TITLE
AVPlayer::stop() should stop the video for good, no matter how many repeats are left?

### ISSUE THREAD

**Issue by rpw98** [wang-bin/QtAV#670]
I found that if you setRepeat greater than 1 in AVPlayer, when you stop the video in the middle, it will restart again. It looks like it just stops the current repeat, but will continue on until all the repeats are performed. This doesn't make sense to me. It should stop the video unless play() is called again.

**Comment by wang-bin** [comment]
Try the latest code

**Comment by rpw98** [comment]
OK. Thanks!
