### ISSUE TITLE
How to tell if a video has played to the end when end action is set to MediaEndAction_Pause? 

### ISSUE THREAD

**Issue by rpw98** [wang-bin/QtAV#673]
I can't seem to figure out a way. AVPlayer::position() returns a value smaller than duration, so can't use that.

**Comment by wang-bin** [comment]
What about comparing position() and the old value in the slot connected to positionChanged()?

**Comment by rpw98** [comment]
It could work, but it is such a hassle. Have to monitor positionChanged() signal. There is no way simply to get the status of the player?

**Comment by wang-bin** [comment]
No. Maybe another signal `endOfStream()` should be added in AVPlayer

**Comment by rpw98** [comment]
FYI: monitoring positionChanged() did not work in my case, it can't tell the difference between pausing in the middle and pausing in the end. I had to use a hack that if position() is very close to duration (~100ms) and the player is paused, I consider it has reached the end.

**Comment by wang-bin** [comment]
Try the latest code. Now `mediaStatusChanged(QtAV::EndOfMedia)` is emitted when the last frame is decoded. You can use this signal. In the old code it is emitted when playback stopped. We already have `AVPlayer.stopped()` and `AVPlayer.stateChanged()` and it's not reasonable to set EndOfMedia there.

**Comment by rpw98** [comment]
Thanks.
