### ISSUE TITLE
Stream playback stops. Handle drops and restart stream automatically 

### ISSUE THREAD

**Issue by thefastman** [wang-bin/QtAV#674]
I try to play HLS stream using QtAV
Sometimes playback stops and in logs I see:

[FFmpeg:mpegts] DTS 1278270 < 3665070 out of order
[FFmpeg:hls,applehttp] DTS 1278270 < 3665070 out of order
[FFmpeg:?] skipping 5 segments ahead, expired from playlists
[FFmpeg:mpegts] DTS 1749870 < 3665070 out of order
[FFmpeg:hls,applehttp] DTS 1749870 < 3665070 out of order
[FFmpeg:?] skipping 2 segments ahead, expired from playlists
[FFmpeg:?] skipping 2 segments ahead, expired from playlists
[FFmpeg:?] skipping 2 segments ahead, expired from playlists
[FFmpeg:?] skipping 3 segments ahead, expired from playlists
[FFmpeg:?] skipping 3 segments ahead, expired from playlists
[FFmpeg:?] skipping 4 segments ahead, expired from playlists
[FFmpeg:?] skipping 2 segments ahead, expired from playlists
[FFmpeg:?] skipping 3 segments ahead, expired from playlists
[FFmpeg:?] skipping 4 segments ahead, expired from playlists
[FFmpeg:?] skipping 4 segments ahead, expired from playlists
[FFmpeg:?] skipping 4 segments ahead, expired from playlists
[FFmpeg:?] skipping 4 segments ahead, expired from playlists
[FFmpeg:?] skipping 4 segments ahead, expired from playlists
[FFmpeg:?] skipping 4 segments ahead, expired from playlists
[FFmpeg:?] skipping 3 segments ahead, expired from playlists
[FFmpeg:?] skipping 3 segments ahead, expired from playlists
[FFmpeg:?] skipping 1 segments ahead, expired from playlists
[FFmpeg:?] skipping 2 segments ahead, expired from playlists
[FFmpeg:?] skipping 2 segments ahead, expired from playlists
[FFmpeg:?] skipping 2 segments ahead, expired from playlists
[FFmpeg:?] skipping 5 segments ahead, expired from playlists
[FFmpeg:?] skipping 5 segments ahead, expired from playlists
[FFmpeg:?] skipping 5 segments ahead, expired from playlists
[FFmpeg:?] skipping 5 segments ahead, expired from playlists
[FFmpeg:?] skipping 2 segments ahead, expired from playlists
[FFmpeg:?] skipping 5 segments ahead, expired from playlists
[FFmpeg:?] skipping 5 segments ahead, expired from playlists
[FFmpeg:?] skipping 4 segments ahead, expired from playlists
[FFmpeg:?] skipping 4 segments ahead, expired from playlists
[FFmpeg:?] skipping 4 segments ahead, expired from playlists
[FFmpeg:?] skipping 2 segments ahead, expired from playlists
[FFmpeg:?] skipping 2 segments ahead, expired from playlists
[FFmpeg:?] skipping 2 segments ahead, expired from playlists
[FFmpeg:mpegts] DTS 65070 < 10767870 out of order
[FFmpeg:hls,applehttp] DTS 65070 < 10767870 out of order
[FFmpeg:?] skipping 2 segments ahead, expired from playlists
[FFmpeg:mpegts] DTS 65070 < 10767870 out of order
[FFmpeg:hls,applehttp] DTS 65070 < 10767870 out of order
[FFmpeg:mpegts] DTS 65070 < 10767870 out of order

Ok, for me is not important if I drop N frames, but is important to not stop
play stream. So, how is possible ignore drops/network problems and
play stream even if I get drops ? How is possible to restart stream playback
for example in case of network disconnect ?
Thanks.

**Comment by wang-bin** [comment]
The url is expired. Player will stop if `AVPlayer.interruptTimeout()` ms is elapsed, and `AVPlayer.void error(QtAV::AVError)` is emitted with `ReadTimedout` or `ReadError`

**Comment by thefastman** [comment]
Ok, it works. Thanks.
