### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by denistu** [wang-bin/QtAV#676]
### Environment

- QtAV: master
- Qt: 5.6.1, Windows 10, mingw64-clang, x64
- FFmpeg:  

> ffmpeg version 3.0.2 Copyright (c) 2000-2016 the FFmpeg developers  built with gcc 5.3.0 (Rev5, Built by MSYS2 project)

>   libavutil      55. 17.103 / 55. 17.103
>   libavcodec     57. 24.102 / 57. 24.102
>   libavformat    57. 25.100 / 57. 25.100
>   libavdevice    57.  0.101 / 57.  0.101
>   libavfilter     6. 31.100 /  6. 31.100
>   libavresample   3.  0.  0 /  3.  0.  0
>   libswscale      4.  0.100 /  4.  0.100
>   libswresample   2.  0.101 /  2.  0.101
>   libpostproc    54.  0.100 / 54.  0.100

### Actual behavior
error when building 
 ./../.obj/QtAV_win_/SurfaceInteropD3D9.o:SurfaceInteropD3D9.cpp:(.text+0x363): undefined reference to `QtAV::pixelFormatFromFourcc(int)' collect2.exe: error: ld returned 1 exit status

**Comment by wang-bin** [comment]
You didn't follow the wiki https://github.com/wang-bin/QtAV/wiki/Build-QtAV

BTW, clang on windows is not tested.

**Comment by wang-bin** [comment]
show me you build steps

**Comment by denistu** [comment]
![image](https://cloud.githubusercontent.com/assets/13941891/16679392/568e0a96-44f8-11e6-9fb0-899241625261.png)

**Comment by wang-bin** [comment]
Seems right. Show me `qtav_build_dir/.qmake.cache, config.log` content

**Comment by denistu** [comment]
well the issue is resolved. dont know what exactly helped, here is what i have done:
1) upgraded ffmpeg to ffmpeg version 3.1.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (Rev1, Built by MSYS2 project)
2) deleted QtAV folder and git clone https://github.com/wang-bin/QtAV.git

**Comment by ddv2005** [comment]
I have the same problem on mingw32_5.3, Qt5.7.1. It happened because VideoDecoderD3D.cpp is not included in D3D9 only build but required, I fix it by adding   CONFIG *= d3dva into win32:!winrt section

**Comment by wang-bin** [comment]
@ddv2005 I guess you only use libQtAV.pro. You have to build QtAV.pro instead.
