### ISSUE TITLE
How to enable openAL when building on Windows with MSVC?

### ISSUE THREAD

**Issue by rpw98** [wang-bin/QtAV#677]
Thanks.

**Comment by wang-bin** [comment]
You need openal headers which are included in the package https://sourceforge.net/projects/qtav/files/depends/QtAV-depends-windows-x86%2Bx64.7z/download
Then delete .qmake.cache in build dir to let qmake detect openal.

OpenAL32.dll is dynamically loaded at runtime, just choose 1 openal dll and rename it to OpenAL32.dll, and in your app, call `player->audio()->setBackends(QStringList()<<"OpenAL");`

**Comment by rpw98** [comment]
It doesn't seem to work. I don't even see openal32.lib in your depends package. How can qmake find it? I tried downloading openal sdk from their website and set include and lib path to it. But still QtAV is not build with them.

**Comment by wang-bin** [comment]
QtAV does not link to openal lib. Headers are enough.

**Comment by rpw98** [comment]
But it doesn't work. OpenAL was not found if I call 
player->audio()->setBackends(QStringList()<<"OpenAL");

Even though I have openal32.dll in the path.

**Comment by wang-bin** [comment]
Is there a line `CONFIG+=config_openal` in .qmake.cache in qtav build dir? If no, delete the build dir and rebuild

**Comment by rpw98** [comment]
oh, so I need to add CONFIG+=config_openal in the qmake command? Didn't know that. I'll give it a try.

**Comment by wang-bin** [comment]
No. Delete .qmake.cache and run qmake again. If you see `Checking for openal... yes` in qmake output message, then openal code will be enabled if rebuild libQtAV

**Comment by rpw98** [comment]
No I don't see it. Where does it look for openal?

**Comment by wang-bin** [comment]
you can put AL dir to qt include dir. Show me your config.log content.

**Comment by rpw98** [comment]
I put AL dir to qt include and re-did everything. Still not working. In my config.log I see:

LINK : fatal error LNK1181: cannot open input file 'OpenAL32.lib'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\x86_amd64\link.EXE"' : return code '0x49d'
Stop.
test openal FAILED

Are you sure we don't need openal32.lib?

**Comment by wang-bin** [comment]
Did you run `git submodule update --init`?

**Comment by rpw98** [comment]
I just download the latest code. Don't have git on Windows...

**Comment by rpw98** [comment]
OK. I installed git and cloned a fresh copy of the code, run git submodule update --init, this time test openal succeeded. Will let you know how it goes. Thank you!

**Comment by rpw98** [comment]
All worked well. Thank you!
