### ISSUE TITLE
无法加载qmlav.dll

### ISSUE THREAD

**Issue by wez733** [wang-bin/QtAV#679]
我对clone下来的版本成功编译，然后运行example中的qmlplayer时出现了古怪的错误：
Warning: qrc:///qml/QMLPlayer/main.qml:30:1: plugin cannot be loaded for module "QtAV": Cannot load library C:\Users\wez73\Desktop\build-QtAV-Desktop_Qt_5_7_0_MinGW_32bit-Release\bin\QtAV\QmlAV.dll: 锟揭诧拷锟斤拷指锟斤拷锟斤拷模锟介。

然后发现qml导入用的import QtAV 1.7
我自己编了一个qml项目，导入了qtav，结果出现了编译错误：
:-1: error: cannot find -lQt5AVWidgetsd
:-1: error: cannot find -lQt5AVd

我就把libQt5AV.a和libQt5AVWidgets.a复制了一份，结尾加上d，编译成功了，运行时报错：
QQmlApplicationEngine failed to load component
qrc:/main.qml:4 plugin cannot be loaded for module "QtAV": ??????D:/Qt/5.7/mingw53_32/qml/QtAV/QmlAV.dll?????????????Qt??(????????????????汾??????汾??)

这个问题太谜了，我研究了好久也无法解决，应该怎么办？

**Comment by wang-bin** [comment]
debug版本没编译。要么你程序也用release版本

**Comment by wez733** [comment]
谢谢！问题已经解决了
