### ISSUE TITLE
How do I build for debug?

### ISSUE THREAD

**Issue by croepha** [wang-bin/QtAV#680]
I have tried: 
```qmake --qt=5  ../QtAV/QtAV.pro CONFIG-=release CONFIG+=debug```

but it still seems to be building in release mode...

**Comment by wang-bin** [comment]
What is `--qt=5`? Everything else seem right.

**Comment by croepha** [comment]
the `--qt=5` is to keep qt from trying to use qt4 on Ubuntu.. . Alright there must be something else that I am doing that is wrong...  I'll close then, thanks
