### ISSUE TITLE
AudioFilter 

### ISSUE THREAD

**Issue by thefastman** [wang-bin/QtAV#681]
Is AudioFilter  implemented ? 

void CAFilter::process(Statistics * statistics, AudioFrame *frame) {
		Q_UNUSED(statistics);
		Q_UNUSED(frame);
		AudioFrame af = frame->clone();
		QByteArray baAudio = af.frameData(); // <= always zero
}

**Comment by wang-bin** [comment]
Use `AudioFrame.bits(plane)` access data. Or call `AudioFrame.clone()` before `AudioFrame.frameData()`

**Comment by wang-bin** [comment]
Please try the latest code

**Comment by thefastman** [comment]
Works. Thx !
