### ISSUE TITLE
plugin cannot be loaded for module "QtAV"

### ISSUE THREAD

**Issue by qnnming** [wang-bin/QtAV#683]
Starting D:\Qt\workspace\QtAV_Desktop_Qt_5_7_0_MinGW_32bit_Release\bin\QMLPlayer.exe...
event dispatcher: 0x48f790
set log file:  "D:/Qt/workspace/QtAV_Desktop_Qt_5_7_0_MinGW_32bit_Release/bin/log-QMLPlayer.txt"
Logger
Debug: arguments=======  ("D:\\Qt\\workspace\\QtAV_Desktop_Qt_5_7_0_MinGW_32bit_Release\\bin\\QMLPlayer.exe")
Debug: current dir:  "D:/Qt/workspace/QtAV_Desktop_Qt_5_7_0_MinGW_32bit_Release/bin"
8Debug: ("D:/Qt/workspace/QtAV_Desktop_Qt_5_7_0_MinGW_32bit_Release/bin", "qrc:/qt-project.org/imports", "D:/Qt/Qt5.7.0/5.7/mingw53_32/qml")
Debug: >>>>>>>>devicePixelRatio: 1.000000
Debug: dpi phy:  72.0177 , logical:  96 , dpr:  1 ; vis rect: QRect(0,0 1920x1080)
Debug: touch devices:  ()
Warning: qrc:///qml/QMLPlayer/main.qml:30:1: plugin cannot be loaded for module "QtAV": Cannot load library D:\Qt\workspace\QtAV_Desktop_Qt_5_7_0_MinGW_32bit_Release\bin\QtAV\QmlAV.dll: 锟揭诧拷锟斤拷指锟斤拷锟斤拷模锟介。
Debug: file:  ""
Warning: QObject::connect: Cannot connect (null)::requestFullScreen() to QtQuick2ApplicationViewer::showFullScreen()
Warning: QObject::connect: Cannot connect (null)::requestNormalSize() to QtQuick2ApplicationViewer::showNormal()
Debug: ScreenSaver::retrieveState
Debug: Succeed to enable screen saver (0)

**Comment by wang-bin** [comment]
Did you put ffmpeg dlls in qt bin dir?

**Comment by wang-bin** [comment]
Deployment problem. Not a QtAV  issue
