### ISSUE TITLE
Memory leaks when playing and seeking

### ISSUE THREAD

**Issue by Lexerys** [wang-bin/QtAV#686]
Hello!

I'm using QtAV in my project to play video, it works - but I've found memory leaks when any video is playing and large leaks when seeking.
For example, When playing full hd video, memory leak is 1Mb per second. When seeking this video by moving scrollbar slider, memory leak is ~300Mb per 2-3 second of moving.

Code playing:
  m_player->setFile(path_to_video);
  m_player->play();

Code seeking:
  m_player->seek(position);

Also I've noticed that player.exe from your distributive works without memory leaks.

Using VS2015, qt 5.6.0, QtAV 1.11.0, ffmpeg - static builds.

Can you guid me to possible solutions please?

==============================================================================================================
Debug output:
==============================================================================================================

QtAV 1.11.0(Jun 30 2016, 14:45:59)
"Build with Qt-5.6.0"
"FFmpeg/Libav configuration: --enable-asm --enable-yasm --arch=i386 --disable-ffserver --disable-doc --disable-ffplay --disable-ffprobe --disable-ffmpeg --enable-static --disable-bzlib --disable-libopenjpeg --disable-iconv --disable-zlib --prefix=ffmpeg --toolchain=msvc --enable-avresample"
"Build with avutil-55.5.100"
"Build with avcodec-57.13.102"
"Build with avformat-57.13.100"
"Build with avfilter-6.14.101"
"Build with avdevice-57.0.100"
"Build with avresample-3.0.0"
"Build with swresample-2.0.100"
"Build with swscale-4.0.100"
Registered audio backends:  ("XAudio2", "DirectSound", "null")
"XAudio2_9"
"Build with XAudio2 from Win8 or later SDK"
"Try symbol 'XAudio2Create' from WinSDK dll"
"xaudio2: 0xb1e0560"
"all closed and reseted"
"avformat_open_input: d->format_ctx:'0xa586560', url:'...2.16.643.29200.20160721173253250.20160721173235863.mp4'..."
D2DERR_RECREATE_TARGET
Resize bitmap to 0 x 0
[FFmpeg:swscaler] No accelerated colorspace conversion found from yuv420p to rgb24.
"avformat_open_input: url:'...2.16.643.29200.20160721173253250.20160721173235863.mp4' ret:0"
"avfmtctx.flag: 513"
"AVFMT_NOTIMESTAMPS: 0, AVFMT_TS_DISCONT: 512, AVFMT_NO_BYTE_SEEK:0, custom io: 0"
"invalid index 0 (valid is 0~0) for stream type 2."
"notify_interval: 500"
"stream: 1, duration=-9223372036854775808 (-230584300921369408 ms), time_base=0.000025"
"codec: ac3(ATSC A/52A (AC-3))"
"stream: 0, duration=60912 (2540540 ms), time_base=0.041708"
"codec: mpeg4(MPEG-4 part 2)"
"has audio"
"QtAV::AudioDecoderFFmpeg thread type: Single, count: 1"
audio format from codec:  QtAV::AudioFormat(48000Hz, 4Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "fltp")
"source_voice: 0x0, master: 0x0"
AudioOutput format:  QtAV::AudioFormat(48000Hz, 4Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "flt")
"XAudio2 error@201. winsdk.xaudio->CreateMasteringVoice(&winsdk.master, 0, 0): (0xffffffff8889000a) "
"**********trying video decoder: FFmpeg..."
"QtAV::VideoDecoderFFmpeg thread type: Frame, count: 9"
"**************Video decoder found:0xa04b2d0"
"setCapture 0x977e890"
"stream: 0, duration=60912 (2540540 ms), time_base=0.041708"
"codec: mpeg4(MPEG-4 part 2)"
"Clock initial value: 0.000000"
"Starting video thread..."
"get av queue a/v thread = 0x0 0xa04b260"
"no frame could be decompressed: Error number 3017 occurred 0/3017"
"invalid video frame from decoder. undecoded data size: 0"
"no frame could be decompressed: Error number 137 occurred 0/137"
"invalid video frame from decoder. undecoded data size: 0"
"no frame could be decompressed: Error number 9 occurred 0/9"
"invalid video frame from decoder. undecoded data size: 0"
"no frame could be decompressed: Error number 137 occurred 0/137"
"invalid video frame from decoder. undecoded data size: 0"
"AVClock started!!!!!!!!"
"no frame could be decompressed: Error number 9 occurred 0/9"
"invalid video frame from decoder. undecoded data size: 0"

... too many errors ...

"AVCodecContext.mpeg4 options:"
"skip_frame=>8"
"set QtAV::VideoDecoderFFmpeg() meta properties:"
"no frame could be decompressed: Error number 2537 occurred 0/2537"
"invalid video frame from decoder. undecoded data size: 0"
"video thread wait to sync end for sync id: 569"
"seeking... pkt.pts - d.render_pts0: 0.066"
"frame drop=>normal. nb_dec_slow: 0"
"AVCodecContext.mpeg4 options:"
"skip_frame=>0"
"set QtAV::VideoDecoderFFmpeg() meta properties:"
"video thread wait to sync end for sync id: 569"
"seeking... pkt.pts - d.render_pts0: 0.025"
"no frame could be decompressed: Error number 3740 occurred 0/3740"
"invalid video frame from decoder. undecoded data size: 0"
"video thread wait to sync end for sync id: 569"
"seeking... pkt.pts - d.render_pts0: 0.150"
"video thread wait to sync end for sync id: 569"
"seeking... pkt.pts - d.render_pts0: 0.108"
"no frame could be decompressed: Error number 2639 occurred 0/2639"
"invalid video frame from decoder. undecoded data size: 0"
"video thread wait to sync end for sync id: 569"
"seeking... pkt.pts - d.render_pts0: 0.233"
"video thread wait to sync end for sync id: 569"
"seeking... pkt.pts - d.render_pts0: 0.192"
"no frame could be decompressed: Error number 2218 occurred 0/2218"
"invalid video frame from decoder. undecoded data size: 0"
"video thread wait to sync end for sync id: 569"
"seeking... pkt.pts - d.render_pts0: 0.317"
"video thread wait to sync end for sync id: 569"
"seeking... pkt.pts - d.render_pts0: 0.275"
"no frame could be decompressed: Error number 2699 occurred 0/2699"
"invalid video frame from decoder. undecoded data size: 0"
"video thread wait to sync end for sync id: 569"
"seeking... pkt.pts - d.render_pts0: 0.400"
"video thread wait to sync end for sync id: 569"
"seeking... pkt.pts - d.render_pts0: 0.358"
"video seek finished @608.024000. id: 569"
The thread 0xd10 has exited with code 0 (0x0).
The thread 0x3bbc has exited with code 0 (0x0).

**Comment by Lexerys** [comment]
Some experiment:

	m_player->setRepeat(std::numeric_limits<int>::max());
	m_player->setBufferMode(QtAV::BufferMode::BufferPackets);
	m_player->setBufferValue(50000);

After loading video amount of memory used by process is ~200M. This value not changes while video is playing. But after end of video and repeat to begin, amount of memory became +80M in one step.
Each next repeat's also gives +80M.

**Comment by wang-bin** [comment]
Hi @Lexerys , I have no idea now. Please show me your video information using `ffprobe your_video_file`

**Comment by Lexerys** [comment]
Absolutely any video.
For example:
ffprobe version N-81045-g450cf40 Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 50.100 / 57. 50.100
  libavformat    57. 42.100 / 57. 42.100
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 47.100 /  6. 47.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, matroska,webm, from 'Turbo.2013.720p.x264-LEONARDO_[scarabey.org].mkv':
  Metadata:
    title           : -=LEONARDO=-
    encoder         : libebml v1.2.2 + libmatroska v1.3.0
    creation_time   : 2013-10-29 08:14:27
  Duration: 01:35:40.74, start: 0.000000, bitrate: 3750 kb/s
    Chapter #0:0: start 0.000000, end 209.626000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 209.626000, end 399.858000
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 399.858000, end 514.222000
    Metadata:
      title           : Chapter 3
    Chapter #0:3: start 514.222000, end 613.863000
    Metadata:
      title           : Chapter 4
    Chapter #0:4: start 613.863000, end 805.096000
    Metadata:
      title           : Chapter 5
    Chapter #0:5: start 805.096000, end 1035.785000
    Metadata:
      title           : Chapter 6
    Chapter #0:6: start 1035.785000, end 1313.354000
    Metadata:
      title           : Chapter 7
    Chapter #0:7: start 1313.354000, end 1542.708000
    Metadata:
      title           : Chapter 8
    Chapter #0:8: start 1542.708000, end 1704.494000
    Metadata:
      title           : Chapter 9
    Chapter #0:9: start 1704.494000, end 1817.899000
    Metadata:
      title           : Chapter 10
    Chapter #0:10: start 1817.899000, end 2060.892000
    Metadata:
      title           : Chapter 11
    Chapter #0:11: start 2060.892000, end 2300.340000
    Metadata:
      title           : Chapter 12
    Chapter #0:12: start 2300.340000, end 2445.109000
    Metadata:
      title           : Chapter 13
    Chapter #0:13: start 2445.109000, end 2680.219000
    Metadata:
      title           : Chapter 14
    Chapter #0:14: start 2680.219000, end 2860.941000
    Metadata:
      title           : Chapter 15
    Chapter #0:15: start 2860.941000, end 2969.925000
    Metadata:
      title           : Chapter 16
    Chapter #0:16: start 2969.925000, end 3208.956000
    Metadata:
      title           : Chapter 17
    Chapter #0:17: start 3208.956000, end 3420.751000
    Metadata:
      title           : Chapter 18
    Chapter #0:18: start 3420.751000, end 3578.825000
    Metadata:
      title           : Chapter 19
    Chapter #0:19: start 3578.825000, end 3725.972000
    Metadata:
      title           : Chapter 20
    Chapter #0:20: start 3725.972000, end 3950.780000
    Metadata:
      title           : Chapter 21
    Chapter #0:21: start 3950.780000, end 4087.166000
    Metadata:
      title           : Chapter 22
    Chapter #0:22: start 4087.166000, end 4388.801000
    Metadata:
      title           : Chapter 23
    Chapter #0:23: start 4388.801000, end 4586.791000
    Metadata:
      title           : Chapter 24
    Chapter #0:24: start 4586.791000, end 4788.450000
    Metadata:
      title           : Chapter 25
    Chapter #0:25: start 4788.450000, end 5006.126000
    Metadata:
      title           : Chapter 26
    Chapter #0:26: start 5006.126000, end 5189.726000
    Metadata:
      title           : Chapter 27
    Chapter #0:27: start 5189.726000, end 5740.736000
    Metadata:
      title           : Chapter 28
    Stream #0:0(eng): Video: h264 (High), yuv420p, 1280x544 [SAR 1:1 DAR 40:17], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Stream #0:1(rus): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s (default) (forced)
    Metadata:
      title           : Dub
    Stream #0:2(rus): Subtitle: subrip
    Metadata:
      title           : SRT, Full
    Stream #0:3(ukr): Subtitle: subrip
    Metadata:
      title           : SRT, Full
    Stream #0:4(eng): Subtitle: subrip
    Metadata:
      title           : SRT, Full
    Stream #0:5(eng): Subtitle: subrip
    Metadata:
      title           : SRT, (SDH)

**Comment by wang-bin** [comment]
Can you share 'Turbo.2013.720p.x264-LEONARDO_[scarabey.org].mkv' with me using google driver? I don't have a video with chapters.

**Comment by Lexerys** [comment]
It's my bug, i'm sorry.
After building latest ffmpeg version memory leaks gone.

Previous ffmpeg version build command line:
configure --enable-asm --arch=i386 --disable-ffserver --disable-doc --disable-ffplay --disable-ffprobe --disable-ffmpeg --enable-static --disable-bzlib --disable-libopenjpeg --disable-iconv --disable-zlib --prefix=ffmpeg --toolchain=msvc --enable-yasm --enable-avresample

Current ffmpeg version build command line:
configure --enable-asm --enable-yasm --arch=x86 --enable-static --prefix=ffmpeg --toolchain=msvc --enable-avresample --disable-network

Thank you for attention!
