### ISSUE TITLE
GeometryRenderer.cpp:126:144: error: 'glVertexAttribPointer' was not declared in this scope

### ISSUE THREAD

**Issue by martinkg** [wang-bin/QtAV#687]
Hi,

i tried to compile the recent git version on Fedora, but this fails with this error message:

`g++ -c -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -g -pg -Wall -W -D_REENTRANT -fPIC -DDEBUG -DBUILD_QTAV_LIB -DQTAV_HAVE_SSE4_1=1 -DQTAV_HAVE_SSE2=1 -D__STDC_CONSTANT_MACROS -DQTAV_HAVE_X11=1 -DQTAV_HAVE_SWRESAMPLE=1 -DQTAV_HAVE_AVRESAMPLE=1 -DQTAV_HAVE_AVDEVICE=1 -DQTAV_HAVE_AVFILTER=1 -DQTAV_HAVE_OPENAL=1 -DCAPI_LINK_OPENAL -DQTAV_HAVE_PULSEAUDIO=1 -DQTAV_HAVE_CUDA=1 -DQTAV_HAVE_VAAPI=1 -DQTAV_HAVE_QT_EGL=1 -DCAPI_LINK_ASS -DQTAV_HAVE_LIBASS=1 -DQT_GUI_LIB -DQT_CORE_LIB -I/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/src -I. -isystem /usr/include/qt5 -I/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/src -I/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71 -I/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/src/QtAV -I/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/src/cuda -I/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/src/cuda/dllapi -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I../.moc/5.6.1/QtAV -I/usr/lib64/qt5/mkspecs/linux-g++ -o ../.obj/QtAV_linux_x86_64/SubImagesGeometry.o /home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/src/opengl/SubImagesGeometry.cpp
/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/src/opengl/GeometryRenderer.cpp: In member function 'void QtAV::GeometryRenderer::updateGeometry(QtAV::Geometry*)':
/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/src/opengl/GeometryRenderer.cpp:126:144: error: 'glVertexAttribPointer' was not declared in this scope
             DYGL(glVertexAttribPointer(an, a.tupleSize(), a.type(), a.normalize(), g->stride(), reinterpret_cast<const void *>(qptrdiff(a.offset())))); //TODO: in setActiveShader
                                                                                                                                                ^
/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/src/opengl/GeometryRenderer.cpp:127:41: error: 'glEnableVertexAttribArray' was not declared in this scope
             DYGL(glEnableVertexAttribArray(an));
                                         ^
/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/src/opengl/GeometryRenderer.cpp: In member function 'void QtAV::GeometryRenderer::bindBuffers()':
/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/src/opengl/GeometryRenderer.cpp:170:106: error: 'glVertexAttribPointer' was not declared in this scope
         DYGL(glVertexAttribPointer(an, a.tupleSize(), a.type(), a.normalize(), g->stride(), vdata + a.offset()));
                                                                                                          ^
/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/src/opengl/GeometryRenderer.cpp:171:37: error: 'glEnableVertexAttribArray' was not declared in this scope
         DYGL(glEnableVertexAttribArray(an)); //TODO: in setActiveShader
                                     ^
/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/src/opengl/GeometryRenderer.cpp: In member function 'void QtAV::GeometryRenderer::unbindBuffers()':
/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/src/opengl/GeometryRenderer.cpp:202:38: error: 'glDisableVertexAttribArray' was not declared in this scope
         DYGL(glDisableVertexAttribArray(an));
                                      ^
Makefile.libQtAV:1553: recipe for target '../.obj/QtAV_linux_x86_64/GeometryRenderer.o' failed
make[1]: *** [../.obj/QtAV_linux_x86_64/GeometryRenderer.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/martin/rpmbuild/BUILD/QtAV-b3d08c00bd5991a97b17a2ecfaca96dfcebd3a71/build/src'
Makefile:47: recipe for target 'sub-src-libQtAV-pro-make_first' failed
make: *** [sub-src-libQtAV-pro-make_first] Error 2`

hope you can help me.

thanks

**Comment by wang-bin** [comment]
Fixed in the latest code

**Comment by martinkg** [comment]
Thanks works.
