### ISSUE TITLE
Playing big video file  error on runtime

### ISSUE THREAD

**Issue by johncn9** [wang-bin/QtAV#69]
D:\ffmpeg-1.2.1>ffmpeg -i D:\studio5media\mediaserver\Debug\25.ts
ffmpeg version 1.2.1 Copyright (c) 2000-2013 the FFmpeg developers
  built on Jun 30 2013 19:28:52 with gcc 4.6.2 (GCC)
  configuration: --enable-gpl --enable-shared --enable-libx264 --enable-pthreads
 --disable-ffserver --disable-ffplay --prefix=/usr --extra-cflags=-I/local/inclu
de --extra-ldflags=-L/local/lib
  WARNING: library configuration mismatch
  avutil      configuration: --enable-shared --enable-static --enable-ffplay --e
nable-gpl --enable-libx264 --extra-cflags=-I/usr/local/include --extra-ldflags=-
L/usr/local/lib
  avcodec     configuration: --enable-shared --enable-static --enable-ffplay --e
nable-gpl --enable-libx264 --extra-cflags=-I/usr/local/include --extra-ldflags=-
L/usr/local/lib
  libavutil      52. 18.100 / 52. 18.100
  libavcodec     54. 92.100 / 54. 92.100
  libavformat    54. 63.104 / 54. 63.104
  libavdevice    54.  3.103 / 54.  3.103
  libavfilter     3. 42.103 /  3. 42.103
  libswscale      2.  2.100 /  2.  2.100
  libswresample   0. 17.102 /  0. 17.102
  libpostproc    52.  2.100 / 52.  2.100
[mpegts @ 0070e9e0] max_analyze_duration 5000000 reached at 5000000 microseconds

Input #0, mpegts, from 'D:\studio5media\mediaserver\Debug\25.ts':
  Duration: 01:57:05.80, start: 1.400000, bitrate: 1770 kb/s
  Program 1
    Metadata:
      service_name    : The.Grey.2012.720p.BluRay.x264-xiaofriend
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 12
80x720, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x101]: Audio: mp2 ([3][0][0][0] / 0x0003), 44100 Hz, stereo, s1
6p, 128 kb/s
At least one output file must be specified

D:\ffmpeg-1.2.1>

**Comment by wang-bin** [comment]
not sure if it exists in latest release
