### ISSUE TITLE
播放无音频的视频源（文件或URL）时，视频画面不显示

### ISSUE THREAD

**Issue by roger912** [wang-bin/QtAV#697]
使用QtAV播放无音频的视频源（文件或URL）时，视频画面不显示。播放进度的时间在增加，就是画面没有显示。
QtAV 1.11.0(Jun 19 2016, 22:32:35)
运行环境：windows7 x64
安装包："QtAV1.11.0-VS2013x86.exe"
##

**Comment by wang-bin** [comment]
无法重现。报bug请参考模板 https://github.com/wang-bin/QtAV/wiki/Issue-Template
