### ISSUE TITLE
Multiple player instance cause buffering

### ISSUE THREAD

**Issue by georgef87** [wang-bin/QtAV#700]
Hi i'm working to a project where i want to display multiple streams on the screen simultaneous.

When i play only one stream with QtAv it works fine with video, there are some issues with audio as the sound it's not crystal clear, comparing to ffplay on the same stream.

On the other hand when having to instances of the player (in the same app and in different applications) cause the players to be jumpy. This is not happening with ffplay or vlc where it works fine with more than 4 players simultaneous.

Should i do something special to make QtAV work with multiple instances?

**Comment by wang-bin** [comment]
what platform? if it's linux, use openal as audio output

**Comment by georgef87** [comment]
I did some more investigation and i made it work after setting the fps to 10 as the stream is. Do you have any ideea why this is happening?

**Comment by wang-bin** [comment]
Answer my questions first. And why you set 10fps?

**Comment by georgef87** [comment]
Yes, the platform is Linux and i set 10 fps as the stream is at 10fps.
