### ISSUE TITLE
QtAV在线播放视频文件问题

### ISSUE THREAD

**Issue by abc137531** [wang-bin/QtAV#701]
你好，我在Mac OS环境下已经成功编译QtAV工程，但是使用example "play"工程【open URL】导入在线https视频：https://www.youtube.com/watch?v=mQClow-8fuI，提示无效的视频文件，输出：

QtAV 1.11.0(Aug 12 2016, 17:03:24)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
Debug: status changed  "Invalid meida"
Debug: sync config to  "/Users/huangwuxian/Library/Application Support/Player/Player.ini"
Debug: sync end

注：使用第三方库版本QtAV-depends-macOS.tar.xz

能帮忙看看是可能是什么原因引起的吗？折腾一天了，非常感谢！

**Comment by abc137531** [comment]
补充一下，在window下打开在线视频是没问题的

**Comment by wang-bin** [comment]
加环境变量QTAV_LOG=all后运行把log贴上来

**Comment by abc137531** [comment]
Starting /Users/huangwuxian/Desktop/QtAVTest/build-QtAV-Desktop_Qt_5_5_1_clang_64bit-Release/bin/Player.app/Contents/MacOS/Player...
"QtAV 1.11.0(Aug 12 2016, 18:20:07)\nMultimedia framework base on Qt and FFmpeg.\nDistributed under the terms of LGPLv2.1 or later.\nShanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com\nDonate: http://qtav.org/donate.html\nSource: https://github.com/wang-bin/QtAV\nHome page: http://qtav.org"
("/Users/huangwuxian/Desktop/QtAVTest/build-QtAV-Desktop_Qt_5_5_1_clang_64bit-Release/bin/Player.app/Contents/MacOS/Player")
set log file:  "/Users/huangwuxian/Desktop/QtAvTest/build-QtAV-Desktop_Qt_5_5_1_clang_64bit-Release/bin/Player.app/Contents/MacOS/log-Player.txt"
Logger
Debug: vo: Release/bin/Player
QtAV 1.11.0(Aug 12 2016, 18:20:07)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
Debug: QtAV 1.11.0(Aug 12 2016, 18:20:07)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
Debug: "Build with Qt-5.5.1"
Debug: "FFmpeg/Libav configuration: --extra-version=QtAV --disable-doc --disable-debug --enable-shared --enable-static --enable-small --enable-runtime-cpudetect --enable-hwaccels --enable-avresample --disable-postproc --install_name_dir='@rpath' --cc=clang --enable-pic --extra-cflags='-mmacosx-version-min=10.8' --extra-ldflags='-mmacosx-version-min=10.8 -Wl,-rpath,@loader_path -Wl,-rpath,@loader_path/../Frameworks -Wl,-rpath,@loader_path/lib -Wl,-rpath,@loader_path/../lib'"
Debug: "Build with avutil-55.27.100"
Debug: "Build with avcodec-57.48.101"
Debug: "Build with avformat-57.40.101"
Debug: "Build with avfilter-6.46.102"
Debug: "Build with avdevice-57.0.101"
Debug: "Build with avresample-3.0.0"
Debug: "Build with swresample-2.1.100"
Debug: "Build with swscale-4.1.100"
Debug: engine: "LibASS"
Debug: engine: "FFmpeg"
Debug: engine: "FFmpeg"
Warning: "can not load cuda!"
Debug: "~VideoDecoderVDAPrivate"
Debug: Registered audio backends:  ("AudioToolbox", "OpenAL", "null")
Debug: "OpenGL version: 2.1  hasGLSL: 1"
Debug: "GL_VERSION: 2.1 INTEL-10.14.73"
Debug: "GL_VENDOR: Intel Inc."
Debug: "GL_RENDERER: Intel Iris OpenGL Engine"
Debug: "GL_SHADING_LANGUAGE_VERSION: 1.20"
Debug: "Is OpenGLES: 0"
Debug: "Is EGL: 0"
Debug: "GLSL version: 120"
Debug: "Has PBO: 1"
Debug: "16 bit texture depth: 16.\n"
Debug: "using gl_param_3r16"
Debug: "Has 16bit texture: 1"
Debug: "check gl3 rg: 0x822B"
Debug: "Has RG texture: 1"
Debug: QSurfaceFormat(version 2.1, options QFlags(0x4), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior 2, swapInterval 1, profile  0)
Debug: Loading  QVariant(QString, "https://www.youtube.com/watch?v=mQClow-8fuI")  ...
Debug: "all closed and reseted"
Debug: "avformat_open_input: d->format_ctx:'0x7fb562800600', url:'https://www.youtube.com/watch?v=mQClow-8fuI'..."
Warning: [FFmpeg:tls] IO Error: -9806
Warning: [FFmpeg:tls] IO Error: -9806
Debug: "avformat_open_input: url:'https://www.youtube.com/watch?v=mQClow-8fuI' ret:-5"
Debug: "6666666"
Warning: Can't open media:  "failed to open media"
Debug: "222222"
Warning: "Load failed!"
Debug: status changed  "Invalid meida"

**Comment by abc137531** [comment]
你好，问题已经解决了，网络问题，我们的无线网络好像限制了不给播放视频，使用有线播放就可以了
