### ISSUE TITLE
libQtAVWidgets compile failed   Qt5.5.1 QtCreator vs2013 win7

### ISSUE THREAD

**Issue by cbdg** [wang-bin/QtAV#702]
E:\workspace\QtAV\QtAV-master\widgets\Direct2DRenderer.cpp(331) : error C3861: 'backgroundRegion': identifier not found
E:\workspace\QtAV\QtAV-master\widgets\Direct2DRenderer.cpp(335) : error C3861: 'backgroundColor': identifier not found
E:\workspace\QtAV\QtAV-master\widgets\GraphicsItemRenderer.cpp(127) : error C3861: 'preparePixmap': identifier not found

**Comment by wang-bin** [comment]
did you installed an very old version of QtAV? run builddir/sdk_uninstall.bat first before build
