### ISSUE TITLE
视频文件含有空格无法播放

### ISSUE THREAD

**Issue by abc137531** [wang-bin/QtAV#705]
视频文件名称含有空格，如A simple life.mp4，使用QtAV自带的例子play播放时，无法播放；但是如果视频文件不含空格，可以播放。版本信息：
Debug: vo: Release/bin/Player
QtAV 1.11.0(Aug 15 2016, 15:34:01)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
Debug: QtAV 1.11.0(Aug 15 2016, 15:34:01)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com

**Comment by abc137531** [comment]
@wang-bin 视频文件名称含有空格的问题什么时候能解决？如果不能最近解决，能不能给个办法？

**Comment by wang-bin** [comment]
无法重现。所有文件名都能播放。请在player设置对话框里的log选择all重新运行后看log

**Comment by abc137531** [comment]
@wang-bin 本地视频文件名称含有空格可以播放，但是如果是网络视频文件，使用QMediaPlayer可以播放，但是QtAV自带的example的paly工程Open URL播放不了, Log：
Debug: vo: Release/bin/Player
QtAV 1.11.0(Aug 17 2016, 11:21:05)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
Debug: QtAV 1.11.0(Aug 17 2016, 11:21:05)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
Debug: "Build with Qt-5.5.1"
Debug: "FFmpeg/Libav configuration: --extra-version=QtAV --disable-doc --disable-debug --enable-shared --enable-static --enable-small --enable-runtime-cpudetect --enable-hwaccels --enable-avresample --disable-postproc --install_name_dir='@rpath' --cc=clang --enable-pic --extra-cflags='-mmacosx-version-min=10.8' --extra-ldflags='-mmacosx-version-min=10.8 -Wl,-rpath,@loader_path -Wl,-rpath,@loader_path/../Frameworks -Wl,-rpath,@loader_path/lib -Wl,-rpath,@loader_path/../lib'"
Debug: "Build with avutil-55.27.100"
Debug: "Build with avcodec-57.48.101"
Debug: "Build with avformat-57.40.101"
Debug: "Build with avfilter-6.46.102"
Debug: "Build with avdevice-57.0.101"
Debug: "Build with avresample-3.0.0"
Debug: "Build with swresample-2.1.100"
Debug: "Build with swscale-4.1.100"
Debug: engine: "LibASS"
Debug: engine: "FFmpeg"
Debug: engine: "FFmpeg"
Warning: "can not load cuda!"
Debug: "~VideoDecoderVDAPrivate"
Debug: aaa 

Debug: Registered audio backends:  ("AudioToolbox", "OpenAL", "null")
Debug: "OpenGL version: 2.1  hasGLSL: 1"
Debug: "GL_VERSION: 2.1 INTEL-10.14.73"
Debug: "GL_VENDOR: Intel Inc."
Debug: "GL_RENDERER: Intel Iris OpenGL Engine"
Debug: "GL_SHADING_LANGUAGE_VERSION: 1.20"
Debug: "Is OpenGLES: 0"
Debug: "Is EGL: 0"
Debug: "GLSL version: 120"
Debug: "Has PBO: 1"
Debug: "16 bit texture depth: 16.\n"
Debug: "using gl_param_3r16"
Debug: "Has 16bit texture: 1"
Debug: "check gl3 rg: 0x822B"
Debug: "Has RG texture: 1"
Debug: QSurfaceFormat(version 2.1, options QFlags(0x4), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior 2, swapInterval 1, profile  0)
Debug: Loading  QVariant(QString, "http://video.ubtrobot.com/A Fly In The Hand.mp4")  ...
Debug: "all closed and reseted"
Debug: "avformat_open_input: d->format_ctx:'0x7fdb7a804000', url:'http://video.ubtrobot.com/A Fly In The Hand.mp4'..."
Warning: [FFmpeg:http] HTTP error 404 Not Found
Debug: "avformat_open_input: url:'http://video.ubtrobot.com/A Fly In The Hand.mp4' ret:-875574520"
Debug: "xxxxxxxxxt: url:'Server returned 404 Not Found'"
Debug: "6666666"
Warning: Can't open media:  "failed to open media"
Debug: "222222"
Warning: "Load failed!"
Debug: status changed  "Invalid meida"

**Comment by abc137531** [comment]
@wang-bin 本地视频文件中文件名含有空格可以播放，但是网络视频文件名称含有空格使用example的play工程Open URL播放不了(使用QMediaPlayer可以播放)，log:
Debug: vo: Release/bin/Player
QtAV 1.11.0(Aug 17 2016, 11:21:05)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
Debug: QtAV 1.11.0(Aug 17 2016, 11:21:05)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
Debug: "Build with Qt-5.5.1"
Debug: "FFmpeg/Libav configuration: --extra-version=QtAV --disable-doc --disable-debug --enable-shared --enable-static --enable-small --enable-runtime-cpudetect --enable-hwaccels --enable-avresample --disable-postproc --install_name_dir='@rpath' --cc=clang --enable-pic --extra-cflags='-mmacosx-version-min=10.8' --extra-ldflags='-mmacosx-version-min=10.8 -Wl,-rpath,@loader_path -Wl,-rpath,@loader_path/../Frameworks -Wl,-rpath,@loader_path/lib -Wl,-rpath,@loader_path/../lib'"
Debug: "Build with avutil-55.27.100"
Debug: "Build with avcodec-57.48.101"
Debug: "Build with avformat-57.40.101"
Debug: "Build with avfilter-6.46.102"
Debug: "Build with avdevice-57.0.101"
Debug: "Build with avresample-3.0.0"
Debug: "Build with swresample-2.1.100"
Debug: "Build with swscale-4.1.100"
Debug: engine: "LibASS"
Debug: engine: "FFmpeg"
Debug: engine: "FFmpeg"
Warning: "can not load cuda!"
Debug: "~VideoDecoderVDAPrivate"
Debug: aaa 

Debug: Registered audio backends:  ("AudioToolbox", "OpenAL", "null")
Debug: "OpenGL version: 2.1  hasGLSL: 1"
Debug: "GL_VERSION: 2.1 INTEL-10.14.73"
Debug: "GL_VENDOR: Intel Inc."
Debug: "GL_RENDERER: Intel Iris OpenGL Engine"
Debug: "GL_SHADING_LANGUAGE_VERSION: 1.20"
Debug: "Is OpenGLES: 0"
Debug: "Is EGL: 0"
Debug: "GLSL version: 120"
Debug: "Has PBO: 1"
Debug: "16 bit texture depth: 16.\n"
Debug: "using gl_param_3r16"
Debug: "Has 16bit texture: 1"
Debug: "check gl3 rg: 0x822B"
Debug: "Has RG texture: 1"
Debug: QSurfaceFormat(version 2.1, options QFlags(0x4), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior 2, swapInterval 1, profile  0)
Debug: Loading  QVariant(QString, "http://video.ubtrobot.com/A Fly In The Hand.mp4")  ...
Debug: "all closed and reseted"
Debug: "avformat_open_input: d->format_ctx:'0x7f932c8e3000', url:'http://video.ubtrobot.com/A Fly In The Hand.mp4'..."
Warning: [FFmpeg:http] HTTP error 400 Bad request
Debug: "avformat_open_input: url:'http://video.ubtrobot.com/A Fly In The Hand.mp4' ret:-808465656"
Debug: "xxxxxxxxxt: url:'Server returned 400 Bad Request'"
Debug: "6666666"
Warning: Can't open media:  "failed to open media"
Debug: "222222"
Warning: "Load failed!"
Debug: status changed  "Invalid meida"

**Comment by writeforbid** [comment]
//估计要改成这样l
QUrl url( "http://video.ubtrobot.com/A Fly In The Hand.mp4")
if (url.isValid())
    const char *url_for_ffmpeg = url.toEncoded().constData();

**Comment by wang-bin** [comment]
你是用最新代码吗？最近有修过这个问题 1e2a37b #618

**Comment by abc137531** [comment]
我去下载最新的试试，谢谢啦

**Comment by abc137531** [comment]
代码是最新的，使用example的play工程Open Url方式打开http含有空格的网络文件还是报错

**Comment by wang-bin** [comment]
http需要%编码的url

**Comment by abc137531** [comment]
//估计要改成这样l
QUrl url( "http://video.ubtrobot.com/A Fly In The Hand.mp4")
if (url.isValid())
const char *url_for_ffmpeg = url.toEncoded().constData();

按照这种方式可以解决

**Comment by wang-bin** [comment]
对
