### ISSUE TITLE
Debug Build for Qt 5.7.0 MingW

### ISSUE THREAD

**Issue by cmichaelis** [wang-bin/QtAV#709]
Hi there! Any chance I could get a Qt 5.7.0 debug build for MingW added to the set at https://sourceforge.net/projects/qtav/files/ci/? I attempted to build it myself, but am running into annoying complications and would love to see it added to your CI system.

Thanks!
Chris

**Comment by wang-bin** [comment]
Done. Download: https://ci.appveyor.com/project/wang-bin/qtav/build/job/twr1k7l71gaf5r75/artifacts

**Comment by cmichaelis** [comment]
Lovely! Thank you!
