### ISSUE TITLE
无法启动此程序，因为计算机中丢失 QtAVWidgets1.dll。尝试重新安装该程序以以解决此问题。

### ISSUE THREAD

**Issue by danian-hn** [wang-bin/QtAV#710]
开发环境：操作系统Windows8.1(64位)，IDE为Qt Creator3.5.1，Qt版本为5.5.1
下载的最新代码，用Qt Creator编译Release版成功后，将QtAVWidgets1.dll改名为Qt5AVWidgets.dll，QtAV1.dll改名为Qt5AV.dll，libQtAV1.a改名为libQt5AV.a，libQtAVWidgets1.a改名为libQt5AVWidgets，并放到Qt的bin目录及lib目录，此时我的工程编译是成功的，能成功运行，没有调用任何QtAV的API，当我在工程里面加入一行代码 QtAV::Widgets::registerRenderers()之后，就跑不起来了，在exe目录，双击exe运行，提示的错误就如标题所示。谁有类似情况么？我找遍了所有的issues都没发现有跟我类似的，多谢了。

<img width="488" alt="screen shot 2016-08-24 at 5 40 16 pm" src="https://cloud.githubusercontent.com/assets/15105528/17926583/3edd45d2-6a24-11e6-94b5-1ac0e2afc03c.png">

**Comment by danian-hn** [comment]
libQtAVWidgets1.a改名为libQt5AVWidgets.a，上面少打了一个后缀。

**Comment by danian-hn** [comment]
然后我尝试将改名之前的QtAV1.dll、QtAVWidgets1.dll、libQtAV1.a、libQtAVWidgets1.a也放一份到Qt的bin及lib目录，再次双击运行exe，得到的错误提示是：应用程序无法正常启动(0xc00007b)

**Comment by wang-bin** [comment]
编译好后运行编译目录的sdk_install.bat，不需要你改名字
