### ISSUE TITLE
moc_QuickVideoPreview.cpp:156:8: error: 'QQuickItemRenderer' has not been declared

### ISSUE THREAD

**Issue by martinkg** [wang-bin/QtAV#717]
I am trying to compile Fedora 26 (rawhid) on the rpmfusion build server but this fails with the following 
error message:
moc_QuickVideoPreview.cpp:156:8: error: 'QQuickItemRenderer' has not been declared

build logfile: http://koji.rpmfusion.org/kojifiles/work/tasks/9032/29032/build.log

build options ( for rpm package):
https://pkgs.rpmfusion.org/cgit/free/qtav.git/tree/qtav.spec

**Comment by sagitter** [comment]
`QtAV` looks uncompatible with modules from QT-5.7.* available on `> Fedora 24`.

**Comment by martinkg** [comment]
Is there a releas plan for supporting QT-5.7.x ?

**Comment by wang-bin** [comment]
It seems a moc bug. But I can't reproduce it with a simple test code.

**Comment by martinkg** [comment]
Thanks for your help, issue solved.
