### ISSUE TITLE
在QMainWindow或QWidget下使用player.setIODevice 播放导致程序crashed

### ISSUE THREAD

**Issue by lanjun2008** [wang-bin/QtAV#721]
环境：
QtAV: version (master branch)
Qt: Qt_5_7_0_MinGW_32bit-Release

期望：
在QMainWindow或QWidget下能采用setIODevice的方式播放文件流
实际：
在QMainWindow或QWidget下能采用setIODevice播放，程序crashed。但使用setFile可以正常播放。

代码：
```
#include "playerwindow.h"

#include <QPushButton>
#include <QSlider>
#include <QLayout>
#include <QVBoxLayout>
#include <QtAV>
#include <QtAVWidgets>
#include <QFile>
#include <QBuffer>


using namespace QtAV;
PlayerWindow::PlayerWindow(QWidget *parent) : QMainWindow(parent)
{
    QFile vidfile;
    vidfile.setFileName("h:/2.mp4");

    if (!vidfile.open(QIODevice::ReadOnly)){
        qDebug()<<"open file fail";
    }

    renderer = new WidgetRenderer();
    this->layout()->addWidget(renderer->widget());
    renderer->setVisible(true);
    renderer->resize(400,300);
    player = new AVPlayer();
    player->setRenderer(renderer);


     player->setIODevice(&vidfile);

    //player->setFile("h:/2.mp4");
     player->play();
}
```

日志：

Starting F:\Qt_project\build-QtavIoDevice-Desktop_Qt_5_7_0_MinGW_32bit-Release\release\QtavIoDevice.exe...
VideoEncoder::Register(..., FFmpeg)
Singleton 0236ccd8 created...
VideoDecoder::Register(..., FFmpeg)
Singleton 0236cd60 created...
AudioOutputBackend::Register(..., null)
Singleton 0236cdf8 created...
MediaIO::Register(..., QIODevice)
Singleton 0236CE90 created...
MediaIO::Register(..., QFile)
ImageConverter::Register(..., FFmpeg)
Singleton 0236d180 created...
AudioEncoder::Register(..., FFmpeg)
Singleton 0236d5d0 created...
AudioDecoder::Register(..., FFmpeg)
Singleton 0236d628 created...
SubtitleProcessor::Register(..., FFmpeg)
Singleton 0236d0b8 created...
SubtitleProcessor::Register(..., LibASS)
VideoRenderer::Register(..., OpenGLWindow)
Singleton 0236d930 created...
VideoDecoder::Register(..., DXVA)
VideoDecoder::Register(..., D3D11)
VideoDecoder::Register(..., CUDA)
AudioOutputBackend::Register(..., OpenAL)
AudioOutputBackend::Register(..., DirectSound)
AudioOutputBackend::Register(..., XAudio2)
AudioResampler::Register(..., Libav)
Singleton 0236e1b0 created...
AudioResampler::Register(..., FFmpeg)
VideoRenderer::Register(..., OpenGLWidget)
VideoRenderer::Register(..., QGLWidget2)
VideoRenderer::Register(..., Widget)
VideoRenderer::Register(..., GDI)
VideoRenderer::Register(..., Direct2D)
VideoRenderer::Register(..., GraphicsItem)
registerRenderers...........
AudioOutputBackend::id("XAudio2")
QMainWindowLayout::addItem: Please use the public QMainWindow API instead
程序异常结束。
F:\Qt_project\build-QtavIoDevice-Desktop_Qt_5_7_0_MinGW_32bit-Release\release\QtavIoDevice.exe crashed.

**Comment by wang-bin** [comment]
vidfile 生命周期太短了
