### ISSUE TITLE
我想使用DXVA解码，但是出现了错误 ...

### ISSUE THREAD

**Issue by nulijiabei** [wang-bin/QtAV#725]
`#include <QCoreApplication>
#include <QtDebug>
#include <QtCore/QDateTime>
#include <QtCore/QQueue>
#include <QtCore/QStringList>
#include <QtAV/AVDemuxer.h>
#include <QtAV/VideoDecoder.h>
#include <QtAV/Packet.h>

using namespace QtAV;

int main(int argc, char *argv[])
{
    qDebug("+++");
    QCoreApplication a(argc, argv);
    QString file = QString::fromLatin1("E:/b.mp4");
    int idx = a.arguments().indexOf(QLatin1String("-f"));
    if (idx > 0)
        file = a.arguments().at(idx + 1);
    QString decName = QString::fromLatin1("DXVA");
    idx = a.arguments().indexOf(QLatin1String("-vc"));
    if (idx < 0)
        idx = a.arguments().indexOf(QLatin1String("-vd"));
    if (idx > 0)
        decName = a.arguments().at(idx + 1);

    QString opt;
    QVariantHash decopt;
    idx = decName.indexOf(QLatin1String(":"));
    if (idx > 0) {
        opt = decName.right(decName.size() - idx -1);
        decName = decName.left(idx);
        QStringList opts(opt.split(QString::fromLatin1(";")));
        QVariantHash subopt;
        foreach (QString o, opts) {
            idx = o.indexOf(QLatin1String(":"));
            subopt[o.left(idx)] = o.right(o.size() - idx - 1);
        }
        decopt[decName] = subopt;
    }
    qDebug() << decopt;

    VideoDecoder *dec = VideoDecoder::create(decName.toLatin1().constData());
    if (!dec) {
        fprintf(stderr, "Can not find decoder: %s\n", decName.toUtf8().constData());
        return 1;
    }
    if (!decopt.isEmpty())
        dec->setOptions(decopt);
    AVDemuxer demux;
    demux.setMedia(file);
    if (!demux.load()) {
        qWarning("Failed to load file: %s", file.toUtf8().constData());
        return 1;
    }

    dec->setCodecContext(demux.videoCodecContext());
    qDebug("%d", dec->open());
    int count = 0;
    int vstream = demux.videoStream();
    QQueue<qint64> t;
    qint64 t0 = QDateTime::currentMSecsSinceEpoch();
    while (!demux.atEnd()) {
        if (!demux.readFrame())
            continue;
        if (demux.stream() != vstream)
            continue;
        const Packet pkt = demux.packet();
        if (dec->decode(pkt)) {
            VideoFrame frame = dec->frame(); // why is faster to call frame() for hwdec? no frame() is very slow for VDA
            Q_UNUSED(frame);
            count++;
            const qint64 now = QDateTime::currentMSecsSinceEpoch();
            const qint64 dt = now - t0;
            t.enqueue(now);
            printf("decode count: %d, elapsed: %lld, fps: %.1f/%.1f\r", count, dt, count*1000.0/dt, t.size()*1000.0/(now - t.first()));fflush(0);
            if (t.size() > 10)
                t.dequeue();
        }
    }
    return 0;
}

`

我想使用DXVA解码，但是出现了错误 ...

VideoEncoder::Register(..., FFmpeg)
Singleton 014aca58 created...
VideoDecoder::Register(..., FFmpeg)
Singleton 014acae0 created...
AudioOutputBackend::Register(..., null)
Singleton 014acb78 created...
MediaIO::Register(..., QIODevice)
Singleton 014ACC10 created...
MediaIO::Register(..., QFile)
ImageConverter::Register(..., FFmpeg)
Singleton 014acf00 created...
AudioEncoder::Register(..., FFmpeg)
Singleton 014ad350 created...
AudioDecoder::Register(..., FFmpeg)
Singleton 014ad3a8 created...
SubtitleProcessor::Register(..., FFmpeg)
Singleton 014ace38 created...
SubtitleProcessor::Register(..., LibASS)
VideoRenderer::Register(..., OpenGLWindow)
Singleton 014ad6b0 created...
VideoDecoder::Register(..., DXVA)
VideoDecoder::Register(..., D3D11)
VideoDecoder::Register(..., CUDA)
AudioOutputBackend::Register(..., OpenAL)
AudioOutputBackend::Register(..., DirectSound)
AudioOutputBackend::Register(..., XAudio2)
AudioResampler::Register(..., Libav)
Singleton 014adf30 created...
AudioResampler::Register(..., FFmpeg)
VideoDecoder::id("DXVA")
D:\QtAV\src\build-simpleplayer_sdk-Desktop_Qt_5_7_0_MinGW_32bit-Release\release\simpleplayer_sdk.exe exited with code 255

**Comment by wang-bin** [comment]
最新代码应该没问题

**Comment by nulijiabei** [comment]
我使用的是 QtAV1.11.0-MinGW32.exe

**Comment by nulijiabei** [comment]
@wang-bin 在线等，大神 ...

**Comment by wang-bin** [comment]
不是，要自己编译，或者用https://sourceforge.net/projects/qtav/files/ci里最新的vs2015版

**Comment by nulijiabei** [comment]
@wang-bin 我试试，谢大神，跪谢

**Comment by nulijiabei** [comment]
回来跪谢大神来了：

qt-opensource-windows-x86-mingw530-5.7.0.exe  换成 ->  qt-opensource-windows-x86-msvc2015-5.7.0.exe

URL -> http://download.qt.io/archive/qt/5.7/5.7.0/

安装了 https://developer.microsoft.com/en-us/windows/hardware/windows-driver-kit 

Get Visual Studio Community 2015  + WDK

安装了 Download QtAV1.11.0-VS2013x86.exe (35.5 MB) 后 获取 Qt5AV.lib + Qt5AVWidgets.lib 后删掉

安装 QtAV-Qt5.7-VS2015x86-release-cf78e2 ....

https://sourceforge.net/projects/qtav/files/ci/

**Comment by nulijiabei** [comment]
@wang-bin 求QtAV-Qt5.7-VS2015x86-release-cf78e27.7z最新编译debug版本 ... 谢

**Comment by nulijiabei** [comment]
@wang-bin :-1: error: LNK1104: 无法打开文件“Qt5AVWidgetsd.lib”

**Comment by Chien-Mu** [comment]
VS2015x86-debug 編譯無問題
error: LNK1104: 无法打开文件“Qt5AVWidgetsd.lib”
是因為你沒將編譯好的 debug 安裝到 QtDir
