### ISSUE TITLE
"no frame could be decompressed: Error number 16284 occurred 0/16284"

### ISSUE THREAD

**Issue by nulijiabei** [wang-bin/QtAV#729]
AudioResampler::Register(..., FFmpeg)
Singleton 007EB690 created...
AudioOutputBackend::Register(..., XAudio2)
Singleton 007EB438 created...
AudioOutputBackend::Register(..., DirectSound)
VideoDecoder::Register(..., CUDA)
Singleton 007EB5A0 created...
VideoDecoder::Register(..., D3D11)
VideoDecoder::Register(..., DXVA)
VideoRenderer::Register(..., OpenGLWindow)
Singleton 007EB078 created...
SubtitleProcessor::Register(..., FFmpeg)
Singleton 007EB000 created...
AudioDecoder::Register(..., FFmpeg)
Singleton 007EB0F0 created...
AudioEncoder::Register(..., FFmpeg)
Singleton 007F5A08 created...
ImageConverter::Register(..., FFmpeg)
Singleton 007F54E0 created...
MediaIO::Register(..., QIODevice)
Singleton 007F5828 created...
MediaIO::Register(..., QFile)
AudioOutputBackend::Register(..., null)
VideoDecoder::Register(..., FFmpeg)
VideoEncoder::Register(..., FFmpeg)
Singleton 007F5558 created...
WARNING: QApplication was not created in the main() thread.
QHash()
VideoDecoder::id("DXVA")
QtAV 1.11.0(Sep 22 2016, 14:23:52)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
QtAV 1.11.0(Sep 22 2016, 14:23:52)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
"Build with Qt-5.7.0"
"FFmpeg/Libav configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib"
"Build with avutil-55.29.100"
"Warning: avutil runtime version 55.30.100 mismatch!"
"Build with avcodec-57.55.101"
"Warning: avcodec runtime version 57.57.101 mismatch!"
"Build with avformat-57.49.100"
"Warning: avformat runtime version 57.50.100 mismatch!"
"Build with avfilter-6.62.100"
"Build with avdevice-57.0.102"
"Build with swresample-2.1.100"
"Build with swscale-4.1.100"
"all closed and reseted"
"avformat_open_input: d->format_ctx:'0x66dba0', url:'E:/b.mp4'..."
"avformat_open_input: url:'E:/b.mp4' ret:0"
"avfmtctx.flag: 2097665"
"AVFMT_NOTIMESTAMPS: 0, AVFMT_TS_DISCONT: 512, AVFMT_NO_BYTE_SEEK:0, custom io: 0"
"creating d3d9 device ex... dll: 0x69550000"
"IDirect3DDevice9Ex created"
"DXVA2 description:  DXVA2 (Intel(R) HD Graphics 520, vendor 32902(Intel), device 6422, revision 7)"
"OurDirect3DCreateDeviceManager9 Success!"
"obtained IDirect3DDeviceManager9"
- 'MPEG-2 variable-length decoder' is supported by hardware
- 'MPEG-2 inverse discrete cosine transform' is supported by hardware
- 'VC-1 variable-length decoder 2 (Intel)' is supported by hardware
- 'VC-1 variable-length decoder (Intel)' is supported by hardware
- 'VC-1 variable-length decoder' is supported by hardware
- 'H.264 variable-length decoder, no film grain technology' is supported by hardware
- 'H.264 stereo high profile, mbs flag set' is supported by hardware
- 'H.264 stereo high profile' is supported by hardware
- 'H.264 multiview high profile' is supported by hardware
- 'H.264 scalable video coding, Scalable Constrained Baseline Profile' is supported by hardware
- 'H.264 scalable video coding, Scalable Constrained High Profile' is supported by hardware
- Unknown GUID = C528916C-c0af-4645-8c-b2-37-2b-6d-4a-dc-2a
- Unknown GUID = 8DE911C4-c898-4364-97-15-1d-e6-b3-fe-77-3d
- Unknown GUID = 07CFAFFB-5a2e-4b99-b6-2a-e4-ca-53-b6-d5-aa
- Unknown GUID = 91CD2D6E-897b-4fa1-b0-d7-51-dc-88-01-0e-0a
- Unknown GUID = 442B942A-b4d9-4940-bc-45-a8-82-e5-f9-19-f3
- Unknown GUID = 8C56EB1E-2b47-466f-8d-33-7d-bc-d6-3f-3d-f2
- 'HEVC Main profile' is supported by hardware
- Unknown GUID = 75FC75F7-c589-4a07-a2-5b-72-e0-3b-03-83-b3
- 'HEVC Main 10 profile' is supported by hardware
- Unknown GUID = 463707F8-a1d0-4585-87-6d-83-aa-6d-60-b8-9e
- Unknown GUID = 76988A52-df13-419a-8e-64-ff-cf-4a-33-6c-f5
- Unknown GUID = 76988A52-df13-419a-8e-64-ff-cf-4a-33-6c-f5
- Unknown GUID = 80A3A7BD-89d8-4497-a2-b8-21-26-af-7e-6e-b8
- Unknown GUID = A74CCAE2-f466-45ae-86-f5-ab-8b-e8-af-84-83
- 'Windows Media Video 9 IDCT' is supported by hardware
- 'VC-1 inverse discrete cosine transform' is supported by hardware
- Unknown GUID = 49761BEC-4b63-4349-a5-ff-87-ff-df-08-84-66
codec does not match to h264: none
codec does not match to h264: none
codec does not match to h264: none
codec does not match to h264: none
codec does not match to h264: none
codec does not match to h264: mpeg2video
codec does not match to h264: mpeg2video
codec does not match to h264: mpeg1video
codec does not match to h264: none
codec does not match to h264: none
codec does not match to h264: none
D3D found codec: H.264 variable-length decoder, film grain technology. Check runtime support for the codec.
D3D found codec: H.264 variable-length decoder, no film grain technology (Intel ClearVideo). Check runtime support for the codec.
D3D found codec: H.264 variable-length decoder, no film grain technology. Check runtime support for the codec.
Check profile support: High
NV12 is supported for output
"QtAV::VideoDecoderD3D thread type: Single, count: 1"
"available hardware decoder output format 61 (dxva2_vld)"
"available hardware decoder output format 128 (d3d11va_vld)"
"available software decoder output format 0 (yuv420p)"
>>>>>>>>>>>>>>>>>>>>>surfaces: 20, active_thread_type: 0, threads: 1, refs: 3
"IDirectXVideoDecoderService=0x314e674 nb_surfaces=20 surface 3840x2160"
"IDirectXVideoAccelerationService_CreateSurface succeed with 20 surfaces (3840x2160)"
Decoder configurations: 4
configuration[0] ConfigBitstreamRaw 2
configuration[1] ConfigBitstreamRaw 1
configuration[2] ConfigBitstreamRaw 2
configuration[3] ConfigBitstreamRaw 1
"IDirectXVideoDecoderService.CreateVideoDecoder succeed. decoder=0x273eb4c"
"Using DXVA2 (Intel(R) HD Graphics 520, vendor 32902(Intel), device 6422, revision 7) for hardware decoding."
"no frame could be decompressed: Error number 16284 occurred 0/16284"

当运行 debug 版本时出现以上错误 ... release 正常 ...

**Comment by wang-bin** [comment]
这不是错误。debug编译的默认会打印很多log信息
