### ISSUE TITLE
Video screen turns black after changing parent widget.

### ISSUE THREAD

**Issue by rpw98** [wang-bin/QtAV#732]
So I have a video player embedded in another widget. I'm designing a feature that I can make the video widget pop out in a popup widget (or go fullscreen). To do that I have to assign a different parent for the widget. I found that after doing that, the video goes completely black. It is still playing but the render window just shows nothing but black. Is this a bug? 

Thank you!

**Comment by wang-bin** [comment]
See https://bugreports.qt.io/browse/QTBUG-53571

You can use GLWidgetRenderer2 instead

**Comment by rpw98** [comment]
I just tried it. It makes things worse. Even regular playing isn't working properly... But in any case, that bug report doesn't sound relative to the issue I'm having. The bugreport is about overlay widget doesn't show on top of a fullscreen QOpenGLWidget. My issue is the video player (or QOpenGLWidget) doesn't show video rendering after changing parent widget. And it happens not just in fullscreen.

Thank you.

**Comment by msphair** [comment]
I'm getting this too. I thought it was a special case of docking and undocking a `QDockWidget`. @rpw98, have you found a work-around yet?

**Comment by msphair** [comment]
When I turn on all of the logs, I get this out when I try to dock the video widget:

```
"~~~~~~~~~resetGL 0x11470d240. from sender 0x1054db800"
"No gl context"
"OpenGL version: 2.1  hasGLSL: 1"
material changed:  "gl material 16to8bit: 0, planar: 1, has alpha: 0, 2d texture: 1, 2nd plane rg: 0, xyz: 0"  =>  "gl material 16to8bit: 0, planar: 0, has alpha: 0, 2d texture: 1, 2nd plane rg: 0, xyz: 0"
```

After this, the video is black.

**Comment by wang-bin** [comment]
should work now
