### ISSUE TITLE
"Put FFmpeg headers into Qt directory"?

### ISSUE THREAD

**Issue by kuanyui** [wang-bin/QtAV#735]
> <img width="715" alt="2016-09-28 1 56 27" src="https://cloud.githubusercontent.com/assets/1370070/18902152/703f7c4c-8583-11e6-9c71-cbf838b005bf.png">

https://github.com/wang-bin/QtAV/wiki/Build-QtAV#recommended-put-ffmpeg-headers-and-libs-into-qt-directories

Can anyone elaborate this? Hmm, for instance, a more detailed example?

I still cannot get how to do this to let Qt able to include QtAV.

**Comment by wang-bin** [comment]
It's qmake parent dir, for example `C:\Qt\5.7\msvc2015_64\`. Goto that dir and put ffmpeg headers to `include`, libs to `lib`
