### ISSUE TITLE
Cannot import QtAV in QML

### ISSUE THREAD

**Issue by kuanyui** [wang-bin/QtAV#736]
# Environment
- OS X 11.5
- Qt 5.7 (from Qt official site)
- FFmpeg 3.1.3 (from brew)
- use QMake

# Question
- I have built `QtAV` successfully, and can `#include <QtAV>` in my project now. However I cannot use QtAV's QML modules.

I also tried to added the following line to the `.pro` in my project:
```
QML_IMPORT_PATH += [QtAV Source Code Dir]/qml
```
 But still cannot make 
<img width="970" alt="2016-09-28 2 10 19" src="https://cloud.githubusercontent.com/assets/1370070/18902885/72d3b6e4-8588-11e6-924c-1853edd43749.png">

- I have run following
```
QtAV/tools/sdk_osx.sh  QtAV_buildDir/lib_mac_x86_64_llvm/QtAV*.framework  ~/Qt5.7/5.7/clang_64/lib
```

Sorry, I know this is a superb basic question, but I totally have no idea how to deal with it...

**Comment by wang-bin** [comment]
Does it run? Does code completion works? Maybe qtcreator have problem to detect qtav module.

**Comment by kuanyui** [comment]
No. I cannot import QtAV in QML

**Comment by kuanyui** [comment]
So, my configuration for QML is correct? (`QML_IMPORT_PATH += [QtAV Source Code Dir]/qml`)

**Comment by wang-bin** [comment]
sdk_osx.sh does not install qml module. what about sdk_install.sh?

**Comment by kuanyui** [comment]
1. Which `sdk_install.sh`? in built QtAV dir?
2. Under OS X, does the `.sh` need arguments?

**Comment by wang-bin** [comment]
no, just run it without arguments.

**Comment by kuanyui** [comment]
Thanks a lot! I updated [Wiki](https://github.com/wang-bin/QtAV/wiki/Use-QtAV-In-Your-Projects) for this.
