### ISSUE TITLE
请问如何将map转换的GLuint通过opengl贴出来 ...

### ISSUE THREAD

**Issue by nulijiabei** [wang-bin/QtAV#739]
请问如何将map转换的GLuint通过opengl贴出来 ...

`int GLWidget::load()
{
    qDebug("---");
    QString file = QString::fromLatin1("E:/a.mp4");
    QString decName = QString::fromLatin1("DXVA");
    VideoDecoder *dec = VideoDecoder::create(decName.toLatin1().constData());
    if (!dec) {
        fprintf(stderr, "Can not find decoder: %s\n", decName.toUtf8().constData());
        return -1;
    }
    AVDemuxer *demux = new AVDemuxer();
    demux->setMedia(file);
    if (!demux->load()) {
        qWarning("Failed to load file: %s", file.toUtf8().constData());
        return -1;
    }
    dec->setCodecContext(demux->videoCodecContext());
    dec->open();
    int count = 0;
    int vstream = demux->videoStream();
    QQueue<qint64> t;
    qint64 t0 = QDateTime::currentMSecsSinceEpoch();
    // --------------------------------------------- //
    for(;;)
    {
        if (!demux->atEnd())
        {
            if (!demux->readFrame())
                continue;
            if (demux->stream() != vstream)
                continue;
            const Packet pkt = demux->packet();
            if (dec->decode(pkt)) {
                VideoFrame frame = dec->frame(); // why is faster to call frame() for hwdec? no frame() is very slow for VDA
                if (frame.width() == 0 || frame.height() == 0){
                    continue;
                }
                if (!frame.isValid()) {
                    qDebug("Decoder Error -> frame invalid .");
                    continue;
                }
                // ..................
                if (count == 100) {
                    GLuint &tex = texture[0];
                    frame.map(GLTextureSurface, &tex, 0);
                    glBindTexture(GL_TEXTURE_2D, tex);
                    break;
                }
                // ..................
                Q_UNUSED(frame);
                count++;
                const qint64 now = QDateTime::currentMSecsSinceEpoch();
                const qint64 dt = now - t0;
                t.enqueue(now);
                printf("decode count: %d, elapsed: %lld, fps: %.1f/%.1f\r", count, dt, count*1000.0/dt, t.size()*1000.0/(now - t.first()));fflush(0);
                if (t.size() > 10)
                    t.dequeue();
            }
        }
    }
    /* 释放 */
    dec->close();
    demux->unload();
    return 0;
}
`

**Comment by nulijiabei** [comment]
int GLWidget::load()
{
    qDebug("---");
    QString file = QString::fromLatin1("E:/a.mp4");
    QString decName = QString::fromLatin1("DXVA");
    VideoDecoder *dec = VideoDecoder::create(decName.toLatin1().constData());
    if (!dec) {
        fprintf(stderr, "Can not find decoder: %s\n", decName.toUtf8().constData());
        return -1;
    }
    AVDemuxer *demux = new AVDemuxer();
    demux->setMedia(file);
    if (!demux->load()) {
        qWarning("Failed to load file: %s", file.toUtf8().constData());
        return -1;
    }
    dec->setCodecContext(demux->videoCodecContext());
    dec->open();
    int count = 0;
    int vstream = demux->videoStream();
    QQueue<qint64> t;
    qint64 t0 = QDateTime::currentMSecsSinceEpoch();
    // --------------------------------------------- //
    for(;;)
    {
        if (!demux->atEnd())
        {
            if (!demux->readFrame())
                continue;
            if (demux->stream() != vstream)
                continue;
            const Packet pkt = demux->packet();
            if (dec->decode(pkt)) {
                VideoFrame frame = dec->frame(); // why is faster to call frame() for hwdec? no frame() is very slow for VDA
                if (frame.width() == 0 || frame.height() == 0){
                    continue;
                }
                if (!frame.isValid()) {
                    qDebug("Decoder Error -> frame invalid .");
                    continue;
                }
                // ..................
                if (count == 100) {
                    GLuint &tex = texture[0];
                    frame.map(GLTextureSurface, &tex, 0);
                    glBindTexture(GL_TEXTURE_2D, tex);
                    break;
                }
                // ..................
                Q_UNUSED(frame);
                count++;
                const qint64 now = QDateTime::currentMSecsSinceEpoch();
                const qint64 dt = now - t0;
                t.enqueue(now);
                printf("decode count: %d, elapsed: %lld, fps: %.1f/%.1f\r", count, dt, count*1000.0/dt, t.size()*1000.0/(now - t.first()));fflush(0);
                if (t.size() > 10)
                    t.dequeue();
            }
        }
    }
    /* 释放 */
    dec->close();
    demux->unload();
    return 0;
}

**Comment by wang-bin** [comment]
直接用OpenGLVideo类，可以渲染各种VideoFrame
