### ISSUE TITLE
VideoFrame 用 frame.map 拿到的 GLuint 是 0

### ISSUE THREAD

**Issue by nulijiabei** [wang-bin/QtAV#743]
const Packet pkt = demux->packet();
            if (dec->decode(pkt)) {
                VideoFrame frame = dec->frame(); // why is faster to call frame() for hwdec? no frame() is very slow for VDA
                if (frame.width() == 0 || frame.height() == 0){
                    continue;
                }
                if (!frame.isValid()) {
                    qDebug("Decoder Error -> frame invalid .");
                    continue;
                }
                while (Context::data.size() > 10) {
                    QThread::msleep(30);
                }
                GLuint gluint = 0;
                frame.map(GLTextureSurface, &gluint);
                Context::data.push(gluint);
                Q_UNUSED(frame);

**Comment by nulijiabei** [comment]
const QVariant v = d->metadata.value(QStringLiteral("surface_interop"));
    if (!v.isValid())
        return 0; // 在这里返回了 0 因为没有找到 surface_interop

  IDirect3DSurface9 *d3d = (IDirect3DSurface9*)(uintptr_t)d.frame->data[3];
// 跳过了这里 ，所以没有 surface_interop
    if (copyMode() == ZeroCopy && d.interop_res) {
        d3d9::SurfaceInterop *interop = new d3d9::SurfaceInterop(d.interop_res);
        interop->setSurface(d3d, d.width, d.height);
        VideoFrame f(d.width, d.height, VideoFormat::Format_RGB32);
        f.setBytesPerLine(d.width * 4); //used by gl to compute texture size
        f.setMetaData(QStringLiteral("surface_interop"), QVariant::fromValue(VideoSurfaceInteropPtr(interop)));
        f.setTimestamp(d.frame->pkt_pts/1000.0);
        f.setDisplayAspectRatio(d.getDAR(d.frame));
        return f;
    }

请问如何才能解决呢 。。。

**Comment by nulijiabei** [comment]
我只是想通过 

    QString decName = QString::fromLatin1("DXVA");
    VideoDecoder *dec = VideoDecoder::create(decName.toLatin1().constData());

解码并且通过  frame.map 获取 GLTextureSurface 纹理，然后在 opengl 中输出，因此而已

望大神给予帮助 ... 谢

**Comment by wang-bin** [comment]
log

**Comment by nulijiabei** [comment]
VideoEncoder::Register(..., FFmpeg)
Singleton 1b6811a8 created...
VideoDecoder::Register(..., FFmpeg)
Singleton 1b681230 created...
AudioOutputBackend::Register(..., null)
Singleton 1b6812c8 created...
MediaIO::Register(..., QIODevice)
Singleton 1B681360 created...
MediaIO::Register(..., QFile)
ImageConverter::Register(..., FFmpeg)
Singleton 1b681650 created...
AudioEncoder::Register(..., FFmpeg)
Singleton 1b681aa0 created...
AudioDecoder::Register(..., FFmpeg)
Singleton 1b681af8 created...
SubtitleProcessor::Register(..., FFmpeg)
Singleton 1b681588 created...
VideoRenderer::Register(..., OpenGLWindow)
Singleton 1b681e00 created...
VideoDecoder::Register(..., DXVA)
VideoDecoder::Register(..., D3D11)
VideoDecoder::Register(..., CUDA)
AudioOutputBackend::Register(..., DirectSound)
AudioOutputBackend::Register(..., XAudio2)
AudioResampler::Register(..., FFmpeg)
Singleton 1b681e78 created...
SetProcessDpiAwareness(2) failed: COM error 0x80070005  (Unknown error 0x0ffffffff80070005), using 2
VideoDecoder::id("DXVA")
QtAV 1.11.0(Sep 23 2016, 23:35:06)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
"Build with Qt-5.7.0"
"FFmpeg/Libav configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib"
"Build with avutil-55.29.100"
"Warning: avutil runtime version 55.30.100 mismatch!"
"Build with avcodec-57.55.101"
"Warning: avcodec runtime version 57.57.101 mismatch!"
"Build with avformat-57.49.100"
"Warning: avformat runtime version 57.50.100 mismatch!"
"Build with avfilter-6.62.100"
"Build with avdevice-57.0.102"
"Build with swresample-2.1.100"
"Build with swscale-4.1.100"
"all closed and reseted"
"avformat_open_input: d->format_ctx:'0x1b692040', url:'E:/a.mp4'..."
"avformat_open_input: url:'E:/a.mp4' ret:0"
"avfmtctx.flag: 2097665"
"AVFMT_NOTIMESTAMPS: 0, AVFMT_TS_DISCONT: 512, AVFMT_NO_BYTE_SEEK:0, custom io: 0"
"creating d3d9 device ex... dll: 0x694b0000"
QtAV 1.11.0(Sep 23 2016, 23:35:06)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
decode count: 1, elapsed: 22, fps: 45.5/inf

decode count: 2, elapsed: 38, fps: 52.6/125.0
"IDirect3DDevice9Ex created"
"DXVA2 description:  DXVA2 (Intel(R) HD Graphics 520, vendor 32902(Intel), device 6422, revision 7)"
"OurDirect3DCreateDeviceManager9 Success!"
"obtained IDirect3DDeviceManager9"
- 'MPEG-2 variable-length decoder' is supported by hardware
- 'MPEG-2 inverse discrete cosine transform' is supported by hardware
- 'VC-1 variable-length decoder 2 (Intel)' is supported by hardware
- 'VC-1 variable-length decoder (Intel)' is supported by hardware
- 'VC-1 variable-length decoder' is supported by hardware
- 'H.264 variable-length decoder, no film grain technology' is supported by hardware
- 'H.264 stereo high profile, mbs flag set' is supported by hardware
- 'H.264 stereo high profile' is supported by hardware
- 'H.264 multiview high profile' is supported by hardware
- 'H.264 scalable video coding, Scalable Constrained Baseline Profile' is supported by hardware
- 'H.264 scalable video coding, Scalable Constrained High Profile' is supported by hardware
- Unknown GUID = C528916C-c0af-4645-8c-b2-37-2b-6d-4a-dc-2a
- Unknown GUID = 8DE911C4-c898-4364-97-15-1d-e6-b3-fe-77-3d
- Unknown GUID = 07CFAFFB-5a2e-4b99-b6-2a-e4-ca-53-b6-d5-aa
- Unknown GUID = 91CD2D6E-897b-4fa1-b0-d7-51-dc-88-01-0e-0a
- Unknown GUID = 442B942A-b4d9-4940-bc-45-a8-82-e5-f9-19-f3
- Unknown GUID = 8C56EB1E-2b47-466f-8d-33-7d-bc-d6-3f-3d-f2
- 'HEVC Main profile' is supported by hardware
- Unknown GUID = 75FC75F7-c589-4a07-a2-5b-72-e0-3b-03-83-b3
- 'HEVC Main 10 profile' is supported by hardware
- Unknown GUID = 463707F8-a1d0-4585-87-6d-83-aa-6d-60-b8-9e
- Unknown GUID = 76988A52-df13-419a-8e-64-ff-cf-4a-33-6c-f5
- Unknown GUID = 76988A52-df13-419a-8e-64-ff-cf-4a-33-6c-f5
- Unknown GUID = 80A3A7BD-89d8-4497-a2-b8-21-26-af-7e-6e-b8
- Unknown GUID = A74CCAE2-f466-45ae-86-f5-ab-8b-e8-af-84-83
- 'Windows Media Video 9 IDCT' is supported by hardware
- 'VC-1 inverse discrete cosine transform' is supported by hardware
- Unknown GUID = 49761BEC-4b63-4349-a5-ff-87-ff-df-08-84-66
codec does not match to h264: none
codec does not match to h264: none
codec does not match to h264: none
codec does not match to h264: none
codec does not match to h264: none
codec does not match to h264: mpeg2video
codec does not match to h264: mpeg2video
codec does not match to h264: mpeg1video
codec does not match to h264: none
codec does not match to h264: none
codec does not match to h264: none
D3D found codec: H.264 variable-length decoder, film grain technology. Check runtime support for the codec.
D3D found codec: H.264 variable-length decoder, no film grain technology (Intel ClearVideo). Check runtime support for the codec.
D3D found codec: H.264 variable-length decoder, no film grain technology. Check runtime support for the codec.
Check profile support: High
NV12 is supported for output
"QtAV::VideoDecoderD3D thread type: Single, count: 1"
"available hardware decoder output format 61 (dxva2_vld)"
"available hardware decoder output format 128 (d3d11va_vld)"
"available software decoder output format 0 (yuv420p)"
>>>>>>>>>>>>>>>>>>>>>surfaces: 20, active_thread_type: 0, threads: 1, refs: 3
"IDirectXVideoDecoderService=0x1b68e554 nb_surfaces=20 surface 1920x1088"
"IDirectXVideoAccelerationService_CreateSurface succeed with 20 surfaces (1920x1088)"
Decoder configurations: 4
configuration[0] ConfigBitstreamRaw 2
configuration[1] ConfigBitstreamRaw 1
configuration[2] ConfigBitstreamRaw 2
configuration[3] ConfigBitstreamRaw 1
"IDirectXVideoDecoderService.CreateVideoDecoder succeed. decoder=0x1c0cb444"
"Using DXVA2 (Intel(R) HD Graphics 520, vendor 32902(Intel), device 6422, revision 7) for hardware decoding."
"no frame could be decompressed: Error number 423 occurred 0/423"
decode count: 3, elapsed: 61, fps: 49.2/76.9

decode count: 4, elapsed: 63, fps: 63.5/97.6

**Comment by nulijiabei** [comment]
VideoEncoder::Register(..., FFmpeg)
	Singleton 1d28c850 created...
	VideoDecoder::Register(..., FFmpeg)
	Singleton 1d28c928 created...
	AudioOutputBackend::Register(..., null)
	Singleton 1d28ca00 created...
	MediaIO::Register(..., QIODevice)
	Singleton 1D28CAD8 created...
	MediaIO::Register(..., QFile)
	ImageConverter::Register(..., FFmpeg)
	Singleton 1d28ced8 created...
	AudioEncoder::Register(..., FFmpeg)
	Singleton 1d28cf90 created...
	AudioDecoder::Register(..., FFmpeg)
	Singleton 1ecfef08 created...
	SubtitleProcessor::Register(..., FFmpeg)
	Singleton 1d28ce70 created...
	VideoRenderer::Register(..., OpenGLWindow)
	Singleton 1ecff360 created...
	VideoDecoder::Register(..., DXVA)
	VideoDecoder::Register(..., D3D11)
	VideoDecoder::Register(..., CUDA)
	AudioOutputBackend::Register(..., DirectSound)
	AudioOutputBackend::Register(..., XAudio2)
	AudioResampler::Register(..., FFmpeg)
	Singleton 1ecffb30 created...
	SetProcessDpiAwareness(2) failed: COM error 0x80070005  (Unknown error 0x0ffffffff80070005), using 2
	VideoDecoder::id("DXVA")
	QtAV 1.11.0(Sep 23 2016, 23:35:06)
	Multimedia framework base on Qt and FFmpeg.
	Distributed under the terms of LGPLv2.1 or later.
	Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
	Donate: http://qtav.org/donate.html
	Source: https://github.com/wang-bin/QtAV
	Home page: http://qtav.org"Build with Qt-5.7.0"
	"FFmpeg/Libav configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib"
	"Build with avutil-55.29.100"
	"Warning: avutil runtime version 55.30.100 mismatch!"
	"Build with avcodec-57.55.101"
	"Warning: avcodec runtime version 57.57.101 mismatch!"
	"Build with avformat-57.49.100"
	"Warning: avformat runtime version 57.50.100 mismatch!"
	"Build with avfilter-6.62.100"
	"Build with avdevice-57.0.102"
	"Build with swresample-2.1.100"
	"Build with swscale-4.1.100"
	"all closed and reseted"
	"avformat_open_input: d->format_ctx:'0x1ed0dd80', url:'E:/a.mp4'..."
	"avformat_open_input: url:'E:/a.mp4' ret:0"
	"avfmtctx.flag: 2097665"
	"AVFMT_NOTIMESTAMPS: 0, AVFMT_TS_DISCONT: 512, AVFMT_NO_BYTE_SEEK:0, custom io: 0"
	"creating d3d9 device ex... dll: 0x694b0000"
	"IDirect3DDevice9Ex created"
	"DXVA2 description:  DXVA2 (Intel(R) HD Graphics 520, vendor 32902(Intel), device 6422, revision 7)"
	"OurDirect3DCreateDeviceManager9 Success!"
	"obtained IDirect3DDeviceManager9"
	- 'MPEG-2 variable-length decoder' is supported by hardware
	- 'MPEG-2 inverse discrete cosine transform' is supported by hardware
	- 'VC-1 variable-length decoder 2 (Intel)' is supported by hardware
	- 'VC-1 variable-length decoder (Intel)' is supported by hardware
	- 'VC-1 variable-length decoder' is supported by hardware
	- 'H.264 variable-length decoder, no film grain technology' is supported by hardware
	- 'H.264 stereo high profile, mbs flag set' is supported by hardware
	- 'H.264 stereo high profile' is supported by hardware
	- 'H.264 multiview high profile' is supported by hardware
	- 'H.264 scalable video coding, Scalable Constrained Baseline Profile' is supported by hardware
	- 'H.264 scalable video coding, Scalable Constrained High Profile' is supported by hardware
	- Unknown GUID = C528916C-c0af-4645-8c-b2-37-2b-6d-4a-dc-2a
	- Unknown GUID = 8DE911C4-c898-4364-97-15-1d-e6-b3-fe-77-3d
	- Unknown GUID = 07CFAFFB-5a2e-4b99-b6-2a-e4-ca-53-b6-d5-aa
	- Unknown GUID = 91CD2D6E-897b-4fa1-b0-d7-51-dc-88-01-0e-0a
	- Unknown GUID = 442B942A-b4d9-4940-bc-45-a8-82-e5-f9-19-f3
	- Unknown GUID = 8C56EB1E-2b47-466f-8d-33-7d-bc-d6-3f-3d-f2
	- 'HEVC Main profile' is supported by hardware
	- Unknown GUID = 75FC75F7-c589-4a07-a2-5b-72-e0-3b-03-83-b3
	- 'HEVC Main 10 profile' is supported by hardware
	- Unknown GUID = 463707F8-a1d0-4585-87-6d-83-aa-6d-60-b8-9e
	- Unknown GUID = 76988A52-df13-419a-8e-64-ff-cf-4a-33-6c-f5
	- Unknown GUID = 76988A52-df13-419a-8e-64-ff-cf-4a-33-6c-f5
	- Unknown GUID = 80A3A7BD-89d8-4497-a2-b8-21-26-af-7e-6e-b8
	- Unknown GUID = A74CCAE2-f466-45ae-86-f5-ab-8b-e8-af-84-83
	- 'Windows Media Video 9 IDCT' is supported by hardware
	- 'VC-1 inverse discrete cosine transform' is supported by hardware
	- Unknown GUID = 49761BEC-4b63-4349-a5-ff-87-ff-df-08-84-66
	codec does not match to h264: none
	codec does not match to h264: none
	codec does not match to h264: none
	codec does not match to h264: none
	codec does not match to h264: none
	codec does not match to h264: mpeg2video
	codec does not match to h264: mpeg2video
	codec does not match to h264: mpeg1video
	codec does not match to h264: none
	codec does not match to h264: none
	codec does not match to h264: none
	D3D found codec: H.264 variable-length decoder, film grain technology. Check runtime support for the codec.
	D3D found codec: H.264 variable-length decoder, no film grain technology (Intel ClearVideo). Check runtime support for the codec.
	D3D found codec: H.264 variable-length decoder, no film grain technology. Check runtime support for the codec.
	Check profile support: High
	NV12 is supported for output
	"QtAV::VideoDecoderD3D thread type: Single, count: 1"
	"available hardware decoder output format 61 (dxva2_vld)"
	"available hardware decoder output format 128 (d3d11va_vld)"
	"available software decoder output format 0 (yuv420p)"
	>>>>>>>>>>>>>>>>>>>>>surfaces: 20, active_thread_type: 0, threads: 1, refs: 3
	"IDirectXVideoDecoderService=0x1ed0a91c nb_surfaces=20 surface 1920x1088"
	"IDirectXVideoAccelerationService_CreateSurface succeed with 20 surfaces (1920x1088)"
	Decoder configurations: 4
	configuration[0] ConfigBitstreamRaw 2
	configuration[1] ConfigBitstreamRaw 1
	configuration[2] ConfigBitstreamRaw 2
	configuration[3] ConfigBitstreamRaw 1
	"IDirectXVideoDecoderService.CreateVideoDecoder succeed. decoder=0x1ed5ec7c"
	"Using DXVA2 (Intel(R) HD Graphics 520, vendor 32902(Intel), device 6422, revision 7) for hardware decoding."
	"no frame could be decompressed: Error number 423 occurred 0/423"
	QtAV 1.11.0(Sep 23 2016, 23:35:06)
	Multimedia framework base on Qt and FFmpeg.
	Distributed under the terms of LGPLv2.1 or later.
	Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
	Donate: http://qtav.org/donate.html
	Source: https://github.com/wang-bin/QtAV
	Home page: http://qtav.org
	decode count: 1, elapsed: 15, fps: 66.7/inf

	decode count: 2, elapsed: 17, fps: 117.6/1000.0

	decode count: 3, elapsed: 28, fps: 107.1/230.8

**Comment by nulijiabei** [comment]
@wang-bin 辛苦了 , 这是下面代码的 Log , 环境是 mingw , QtAV 是我本机编译的 ...

		QString file = QString::fromLatin1("E:/a.mp4");
		QString decName = QString::fromLatin1("DXVA");
		VideoDecoder *dec = VideoDecoder::create(decName.toLatin1().constData());
		if (!dec) {
			fprintf(stderr, "Can not find decoder: %s\n", decName.toUtf8().constData());
			return -1;
		}
		AVDemuxer *demux = new AVDemuxer();
		demux->setMedia(file);
		if (!demux->load()) {
			qWarning("Failed to load file: %s", file.toUtf8().constData());
			return -1;
		}
		dec->setCodecContext(demux->videoCodecContext());
		dec->open();
		int count = 0;
		int vstream = demux->videoStream();
		QQueue<qint64> t;
		qint64 t0 = QDateTime::currentMSecsSinceEpoch();
		// --------------------------------------------- //
		for(;;)
		{
			if (!demux->atEnd())
			{
				if (!demux->readFrame())
					continue;
				if (demux->stream() != vstream)
					continue;
				const Packet pkt = demux->packet();
				if (dec->decode(pkt)) {
					VideoFrame frame = dec->frame(); // why is faster to call frame() for hwdec? no frame() is very slow for VDA
					if (frame.width() == 0 || frame.height() == 0){
						continue;
					}
					if (!frame.isValid()) {
						qDebug("Decoder Error -> frame invalid .");
						continue;
					}
					while (Context::data.size() > 30) {
						QThread::msleep(30);
					}
					GLuint texture = 0;
					frame.map(GLTextureSurface, &texture);
					Context::data.push(texture);
					Q_UNUSED(frame);
					count++;
					const qint64 now = QDateTime::currentMSecsSinceEpoch();
					const qint64 dt = now - t0;
					t.enqueue(now);
					printf("decode count: %d, elapsed: %lld, fps: %.1f/%.1f\r", count, dt, count*1000.0/dt, t.size()*1000.0/(now - t.first()));fflush(0);
					if (t.size() > 10)
						t.dequeue();
				}
			}else {
				demux->seek(qint64(0));
			}
		}
		/* 释放 */
		qDebug("### Stop ###");
		dec->close();
		demux->unload();

**Comment by nulijiabei** [comment]
@wang-bin 麻烦给看看

**Comment by wang-bin** [comment]
map 需要 opengl上下文，最好用opengles，得到texture后怎么用就是opengl的事了

**Comment by nulijiabei** [comment]
@wang-bin 要是再能详细点， 做梦都能乐醒了 …

**Comment by wang-bin** [comment]
map 需要opengl  上下文，texture有了后怎么用就是opengl的问题了

2016年10月3日 15:44，"努力加贝" <notifications@github.com>写道：

**Comment by nulijiabei** [comment]
@wang-bin 还是不知道如何 将 QOpenGLContext 应用到 VideoFrame 中，来通过 map 获取纹理 ... 5555

**Comment by nulijiabei** [comment]
@wang-bin 小白(吃)也有使用QtAV的权利，所以望提供傻瓜版提示

**Comment by wang-bin** [comment]
在渲染的时候进行map

**Comment by nulijiabei** [comment]
@wang-bin 感谢回复，看来小白还是去研究原生dxva + ffmpeg的好 ... 再谢

**Comment by nulijiabei** [comment]
大神都是永远惜字如金
