### ISSUE TITLE
"libavresample or libswresample is required" for Android build

### ISSUE THREAD

**Issue by tdauth** [wang-bin/QtAV#744]
I get this message although the libraries are clearly in the LIBRARY_PATH directory and I created symbolic links to the libraries in $HOME/Qt5.7.0/5.7/android_x86/lib as well. I've compiled ffmpeg for Android by myself with your script:
./build_ffmpeg.sh android x86

The LIBRARY_PATH is "<Path to my project>/build_ffmpeg/sdk-android-x86/lib/" and it contains both of the libraries:
ls "<Path to my project>/build_ffmpeg/sdk-android-x86/lib/"
ibavcodec.so  libavfilter.so  libavformat.so  libavresample.so  libavutil.so  libswresample.so  libswscale.so  pkgconfig

I call the whole build script from my CMake project which uses the toolchain for Android.

My call for qmake looks like this:
"$HOME/Qt5.7.0/5.7/android_x86/bin/qmake" ../qtav/QtAV.pro -config no_config_tests -r "CONFIG+=recheck"

edit: I think it was because of "-config no_config_tests" which I added to avoid avutil errors before.

**Comment by wang-bin** [comment]
Yes, it's because `-config no_config_tests`. You have to add `"CONFIG+=config_avutil config_avformat config_avcodec config_swscale config_swresample"` to qmake

**Comment by tdauth** [comment]
ok works wth the option, I just dropped "-config no_config_tests".
