### ISSUE TITLE
 error: unrecognized command line option '-msse2' for ARM and Android

### ISSUE THREAD

**Issue by tdauth** [wang-bin/QtAV#748]
I get the following errors when compiling with Android's NDK compiler for ARM as well as Qt's version for ARM:
```
arm-linux-androideabi-g++: error: unrecognized command line option '-msse2'
arm-linux-androideabi-g++: error: unrecognized command line option '-msse4.1'
```

These flags are added in file "common.pri". I've removed it from the generated file "Makefile.libQtAV" manually. Now I get the error:
```

qtav/src/utils/CopyFrame_SSE2.cpp:24:23: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>

```

Are ARM devices supported? Do I have to pass some more options? I use qmake from "Qt/5.7/android_armv7/bin/qmake" and ffmpeg from "sdk-android-armv7".

**Comment by wang-bin** [comment]
Don't change any thing. How do you build it?

**Comment by tdauth** [comment]
You can close this bug. I could not reproduce it.

**Comment by charlesgz** [comment]
我也出现了这个错误：arm-linux-androideabi-g++: error: unrecognized command line option '-msse2'
ndk-r12b
