### ISSUE TITLE
black widget with WidgetRenderer on Android Samsung J5 device (arm architecture)

### ISSUE THREAD

**Issue by tdauth** [wang-bin/QtAV#749]
Hello, I got another problem: http://stackoverflow.com/questions/39898671/qtav-displays-black-widget-on-android-instead-of-video

The sound works but no image just a black screen. It worked in the Android emulator but with the x86 architecture.

**Comment by wang-bin** [comment]
you have to use OpenGLWidgetRenderer on mobile platforms

**Comment by tdauth** [comment]
When I use OpenGLWidgetRenderer not even the widget in which OpenGLWidgetRenderer is embedded does appear. Is there any documentation when to use which renderer and what I do need as dependencies? Does OpenGLWidgetRenderer have to be in the main window or do I need any OpenGL dependencies except Qt5OpenGL?

**Comment by wang-bin** [comment]
Use OpenGLWidgetRenderer when possible. OpenGLWidgetRenderer is for old qt versions.

**Comment by tdauth** [comment]
But the widget does still not appear. Besides this output appears in the log:

0-13 18:50:24.827  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.827  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.827  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.827  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.827  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.827  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.837  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.837  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.837  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.837  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.837  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.837  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.837  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.837  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.837  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:24.837  9912  9952 W libOpenSLES: Leaving BufferQueue::Enqueue (SL_RESULT_BUFFER_INSUFFICIENT)
10-13 18:50:25.117  9912  9927 V MediaPlayer-JNI: getCurrentPosition: 2637 (msec)
10-13 18:50:26.117  9912  9927 V MediaPlayer-JNI: getCurrentPosition: 3637 (msec)
10-13 18:50:27.117  9912  9927 V MediaPlayer-JNI: getCurrentPosition: 4637 (msec)
10-13 18:50:28.117  9912  9927 V MediaPlayer-JNI: getCurrentPosition: 5637 (msec)

Do I need to specify some extra OpenGL dependencies? 

I added something like this to the AndroidManifst.xml:
<uses-feature android:glEsVersion="0x00020000"></uses-feature>

but still no changes.

**Comment by tdauth** [comment]
I think it was not displayed because it was in a modal QDialog which was shown on top of the main window. Adding it to the layout of the central widget of the main window works.
