### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by nulijiabei** [wang-bin/QtAV#752]
多个线程在同时 decoder 时会出现 

terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc

单个线程出现概率较低

    QObject::connect(z->m_thread, SIGNAL(started()), z->m_decoder, SLOT(start()));

    int Decoder::start()
    {
        // --------------------------- //
        m_demux.setMedia(m_path);
        if (!m_demux.load()) {
            qWarning("Can not load file: %s", m_path.toUtf8().constData());
            return -1;
        }
        // --------------------------- //
        VideoDecoder *decoder = VideoDecoder::create(m_mode.toLatin1().constData());
        if (!decoder) {
            qWarning("Can not find decoder: %s", m_mode.toUtf8().constData());
            return -1;
        }
        m_decoder.reset(decoder);
        m_decoder->setCodecContext(m_demux.videoCodecContext());
        if (!m_decoder->open())
        {
            qWarning("Can not open decoder: %s", m_mode.toUtf8().constData());
            m_demux.unload();
            m_decoder.reset(0);
            return -1;
        }
        // --------------------------------------------- //
        int size = 0;
        QQueue<qint64> t;
        qint64 t0 = QDateTime::currentMSecsSinceEpoch();
        // --------------------------------------------- //
        int count = 0;
        int vstream = m_demux.videoStream();
        qDebug("### decoder stop for ...");
        for(;;)
        {
            /* 停止状态 */
            if (m_stop)
                break;
            if (!m_demux.atEnd())
            {
                if (!m_demux.readFrame())
                    continue;
                if (m_demux.stream() != vstream)
                    continue;
                const Packet pkt = m_demux.packet();
                if (m_decoder->decode(pkt)) {
                    VideoFrame frame = m_decoder->frame();
                    if (!frame.isValid()) {
                        qWarning("Can not decoder -> frame invalid");
                        continue;
                    }
                    // --------------------------------------- //
                    // 解码核心都交给 QTAV 了 ... 看你的了 ...
                    for(;;)
                    {
                        /* 停止状态跳出 */
                        if (m_stop)
                            break;
                        size = m_frames->size();
                        /* TODO 暂定 15 帧缓存 ... */
                        if (size < 15) {
                            break;
                        }
                        /* 休息 10 毫秒 ... */
                        QThread::msleep(10);
                    }
                    /* 帧插入到队列 ... */
                    m_frames->push(frame);
                    // --------------------------------------- //
                    Q_UNUSED(frame);
                    count++;
                    const qint64 now = QDateTime::currentMSecsSinceEpoch();
                    const qint64 dt = now - t0;
                    t.enqueue(now);
                    qDebug("decode -> Z(%d), Buffer(%d), Count(%d), FPS(%.1f/%.1f)\r", m_index, size, count, (count  *1000.0 / dt), (t.size() * 1000.0 / (now - t.first())));fflush(0);
                    if (t.size() > 10)
                        t.dequeue();
                }
            }else {
                /* 循环播放 ... */
                m_demux.seek(qint64(0));
            }
        }
        /* 刷新 */
        m_decoder->flush();
        /* 释放 */
        m_demux.unload();
        m_decoder.reset(0);
        /* 结束标记 */
        m_finish = true;
        /* 完成 */
        return 0;
    }

多路线程解码 ... 

    /* 绘制 -> 由 QGraphicsView 中定时器触发 this->viewport()->update(); */
    void VideoItem::paint(QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
    {
        } else { /* 非暂停状态正常绘制 ... */
            /* 获取对应解码器中所拥有的缓存帧 */
            int i = m_decoder->m_frames->size();
            /* 当缓存帧不为零时绘制 */
            if (i > 0)
            {
                /* 从队列最前面获取一帧 */
                VideoFrame frame = m_decoder->m_frames->front();
                /* 所有 QGraphicsItem 使用相同绘制锁 ... 同时只能一个在绘制 */
                m_runtime->m_mutex.lock();
                /* OpenGL 绘制开始 ... */
                painter->beginNativePainting();
                /* 通过 QTAV 的 OpenGLVideo 绘制 ... VideoFrame 帧 ... */
                m_oglv.setCurrentFrame(frame);
                m_oglv.render();
                /* OpenGL 绘制结束 ... */
                painter->endNativePainting();
                /* 绘制锁解锁 ... */
                m_runtime->m_mutex.unlock();
            }
            /* 当缓存帧大于一帧时释放 ... 否则反复绘制缓存帧 ... */
            if (i > 1) {
                /* 将队列最前面一帧移除 ... */
                m_decoder->m_frames->pop();
            }
        }
    }

**Comment by wang-bin** [comment]
debug一下

**Comment by nulijiabei** [comment]
@wang-bin 感谢,  貌似由于我多路缓存4K的VideoFrame, 造成的 ...
