### ISSUE TITLE
请问如何强制VideoDecoder进行软解, 设置为FFmpeg依然在占用GPU

### ISSUE THREAD

**Issue by nulijiabei** [wang-bin/QtAV#753]
请问如何强制VideoDecoder进行软解, 设置为FFmpeg依然在占用GPU

VideoDecoder::create(FFmpeg);

**Comment by wang-bin** [comment]
渲染需要gpu，软解不用gpu

**Comment by nulijiabei** [comment]
@wang-bin 谢谢

**Comment by nulijiabei** [comment]
有办法让 OpenGLVideo 使用 CPU 渲染吗

**Comment by wang-bin** [comment]
使用WidgetRenderer渲染器，单gpu肯定会用到的，这个应该由系统控制的，软件控制不了，要不你把显卡驱动卸了

**Comment by wang-bin** [comment]
你是什么应用场景？

**Comment by nulijiabei** [comment]
@wang-bin 低性能Intel集成显卡播放4K视频，硬解解不动 .... 软解可以 .. 但是 OpenGLVideo 贴图的时候 ... 贴不动 ... GPU跑满 ...

**Comment by wang-bin** [comment]
不用gpu估计也画不动
