### ISSUE TITLE
最新 eeb8d8d 异常，之前 cf78e27 正常 ...

### ISSUE THREAD

**Issue by nulijiabei** [wang-bin/QtAV#759]
我使用 cf78e27 版本 mingw 编译 的 在直接使用 OpenGLVideo 的 render() 不加参数
绘制 VideoDecoder 解码的帧时，一切正常 ...

void GraphicsItem::paint(QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
{
        int i = m_decoder->m_frames->size();
        if (i > 0)
        {
            VideoFrame frame = m_decoder->m_frames->front();
            Runtime::m_draw_mutex.lock();
            painter->beginNativePainting();
            m_oglv.setCurrentFrame(frame);
            m_oglv.render();
            painter->endNativePainting();
            Runtime::m_draw_mutex.unlock();
}

今天我用 eeb8d8d 编译一版 然后 使用时发现 ：

一：render() 时画面的分辨率不对了 ... 通过 setProjectionMatrixToRect 设置的
二：QGraphicsView 的背景不能正常显示了 ...
三：QGraphicsScene 中 QWidget 不能显示了 ...
... 编译的软硬件环境都没有变化 ...

**Comment by wang-bin** [comment]
最近opengl渲染使用归一化坐标了，可以再OpenGLVideo.cpp例初始化norm_viewport为false。你问题的原因还要再看看。贴两个截图对比下吧

**Comment by nulijiabei** [comment]
![1](https://cloud.githubusercontent.com/assets/3850061/19934772/d358c726-a152-11e6-855a-ab06d734ac12.png)
![2](https://cloud.githubusercontent.com/assets/3850061/19934783/d8b07930-a152-11e6-98d5-01f7ee603664.png)

**Comment by nulijiabei** [comment]
@wang-bin 如何修改 OpenGLVideo 里面的 norm_viewport 参数呢 ...

**Comment by nulijiabei** [comment]
norm_viewport 改为 false 编译的 ... 结果 ... 白屏 ...

class OpenGLVideoPrivate : public DPtrPrivate<OpenGLVideo>
{
public:
    OpenGLVideoPrivate()
        : ctx(0)
        , manager(0)
        , material(new VideoMaterial())
        , material_type(0)
        , norm_viewport(false)
        , update_geo(true)
        , tex_target(0)
        , valiad_tex_width(1.0)
        , mesh_type(OpenGLVideo::SphereMesh)
        , geometry(NULL)
        , user_shader(NULL)
    {
    }

![3](https://cloud.githubusercontent.com/assets/3850061/19953862/be809986-a1ad-11e6-9b44-e7d4a441dcea.png)

**Comment by wang-bin** [comment]
试试最新代码

**Comment by nulijiabei** [comment]
好的 收到 我试试

**Comment by nulijiabei** [comment]
可以了，我主要换最新的 QTAV 原因还是因为 之前那个出现 内存不足了 。。。

https://github.com/wang-bin/QtAV/issues/760 给看看 ...

![6](https://cloud.githubusercontent.com/assets/3850061/19955194/e5c34cf8-a1b9-11e6-9727-c94d7408fd12.png)
