### ISSUE TITLE
使用VideoDecoder解码时如果视频格式不变的情况下可以不释放解码器继续解码吗

### ISSUE THREAD

**Issue by nulijiabei** [wang-bin/QtAV#761]
使用VideoDecoder解码时如果视频格式不变的情况下可以不释放解码器继续解码吗

如果可以，应该如何实现呢 ... 而不是每个视频都创建一次 VideoDecoder

**Comment by wang-bin** [comment]
不行，解码器参数会变，和视频本身有关
