### ISSUE TITLE
Video color changes

### ISSUE THREAD

**Issue by yejiangzhou** [wang-bin/QtAV#776]
![image](https://cloud.githubusercontent.com/assets/15336840/20822343/ee2c9d40-b884-11e6-9fbc-95a4b0466c5e.png)
1.Normal color: yellow

![image](https://cloud.githubusercontent.com/assets/15336840/20822398/5d0fcb4c-b885-11e6-8540-36eadd58afd4.png)
2.QtAvPlayer color: purple

![image](https://cloud.githubusercontent.com/assets/15336840/20822425/8fd419ca-b885-11e6-80ce-b3d61a4ee2d8.png)
3.MyPlayer color: green

The video file is search out in the system：
![image](https://cloud.githubusercontent.com/assets/15336840/20822492/0d2aa59c-b886-11e6-9597-26c240a323b7.png)
Is there any way to solve?

**Comment by wang-bin** [comment]
the color format is pal8, currently is not supported. I can try.

**Comment by yejiangzhou** [comment]
Thanks for your reply!

**Comment by wang-bin** [comment]
The latest code should work
