### ISSUE TITLE
mkspecs install dir shouldn't be relative to bindir

### ISSUE THREAD

**Issue by antonio-rojas** [wang-bin/QtAV#779]
In the Qt5 build, the .pri files are installed to MKSPECS_DIR = $$[QT_INSTALL_BINS]/../mkspecs

This is wrong if, for instance, QT_INSTALL_BINS is ${prefix}/bin (which is the default if you don't set --bindir when compiling Qt): it installs the pri files to /usr/mkspecs instead of /usr/lib/qt/mkspecs, which is the expected location

**Comment by wang-bin** [comment]
Yes, it's wrong. But I don't know the right way to get mkspec dir

**Comment by antonio-rojas** [comment]
I think it should be $$[QT_INSTALL_ARCHDATA]/mkspecs

**Comment by wang-bin** [comment]
http://doc.qt.io/qt-5/qmake-environment-reference.html

QT_HOST_DATA - location of data for host executables used by qmake

QT_INSTALL_ARCHDATA - location of general architecture-dependent Qt data

I think it is `$$[QT_HOST_DATA]/mkspecs`. Both Qt4 and 5 have `QT_HOST_DATA`, while `QT_INSTALL_ARCHDATA` is only available for qt5. Can you confirm it on your system?

**Comment by antonio-rojas** [comment]
pri files are arch-dependent, since they contain the path to libdir (which can be different for 32bit and 64bit libs). So it should be QT_INSTALL_ARCHDATA. That's where Qt and KDE install their mkspecs files.

**Comment by wang-bin** [comment]
Please try the latest code

**Comment by antonio-rojas** [comment]
It's OK now, thanks
