### ISSUE TITLE
使用directx渲染的时候，视频终止时，屏幕上留下一竖线

### ISSUE THREAD

**Issue by lrs0304** [wang-bin/QtAV#780]
测试连接 rtmp://live.hkstv.hk.lxdns.com/live/hks
测试版本 1.11，例子代码里面的player项目
重试方法 编译运行player工程，选择directx昨晚渲染引擎，播放url，点击停止按钮

![qq 20161212161343](https://cloud.githubusercontent.com/assets/6349495/21092614/63347b5c-c088-11e6-8813-510560410136.png)

**Comment by wang-bin** [comment]
试试最新代码
