### ISSUE TITLE
How to customize install path.

### ISSUE THREAD

**Issue by cgilles** [wang-bin/QtAV#781]
Hi,

I want to use QtAV into digiKam photo manager to play video files (http://www.digikam.org)

The integration is mostly done. Now, we want to be include QtAV into digiKam bundle for Windows and MacOS.

For Windows, we cross-compile using MXE (http://mxe.cc/). QtAV compile fine (dll and exe are generated) but installation do not work. It try to install it in Linux host instead to use prefix install path set to MXE build path.

Typically, qmake is called like this : 

${MXE_INSTALL_PREFIX}/qt5/bin/qmake DESTDIR=${MXE_INSTALL_PREFIX} CONFIG+=no_example

${MXE_INSTALL_PREFIX} is set to /mnt/data/5.x/project/bundles/mxe/build.win32/usr/i686-w64-mingw32.shared

At install time, make install try to run these : 

[100%] Performing install step for 'ext_qtav'
make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
install: cannot create regular file '/usr/share/icons/hicolor/scalable/apps/QtAV.svg': Permission denied
mkdir: cannot create directory ‘/usr/share/doc/QtAV’: Permission denied
Makefile.libQtAV.Release:15046: recipe for target 'install_share' failed
make[6]: *** [install_share] Error 1
Makefile.libQtAV:44: recipe for target 'release-install' failed
make[5]: *** [release-install] Error 2
Makefile:54: recipe for target 'sub-src-libQtAV-pro-install_subtargets' failed
make[4]: *** [sub-src-libQtAV-pro-install_subtargets] Error 2
ext_qtav/CMakeFiles/ext_qtav.dir/build.make:73: recipe for target 'ext_qtav/ext_qtav-prefix/src/ext_qtav-stamp/ext_qtav-install' failed
gmake[3]: *** [ext_qtav/ext_qtav-prefix/src/ext_qtav-stamp/ext_qtav-install] Error 2
CMakeFiles/Makefile2:1037: recipe for target 'ext_qtav/CMakeFiles/ext_qtav.dir/all' failed
gmake[2]: *** [ext_qtav/CMakeFiles/ext_qtav.dir/all] Error 2
CMakeFiles/Makefile2:1049: recipe for target 'ext_qtav/CMakeFiles/ext_qtav.dir/rule' failed
gmake[1]: *** [ext_qtav/CMakeFiles/ext_qtav.dir/rule] Error 2
Makefile:365: recipe for target 'ext_qtav' failed
gmake: *** [ext_qtav] Error 2

Which is wrong of course.

A similar problem will occurs with MacOS using Macports.

So the question is : how to customize the prefix install path at configuration time with qmake ?

Another question : there is a way to only compile the SDK with client application ?

Thanks in advance.

**Comment by wang-bin** [comment]
try the latest code

> there is a way to only compile the SDK with client application ?
No. You have to run qmake on QtAV.pro. There are some tests for qmake to detect what features are supported in your environment.

**Comment by cgilles** [comment]
This file can be closed now, since cmake port is completed.
Gilles Caulier
