### ISSUE TITLE
Patch for QtAV 1.11.0 to use Qt signals/szlots macro definitions in public headers

### ISSUE THREAD

**Issue by cgilles** [wang-bin/QtAV#782]
https://commits.kde.org/digikam-software-compilation/81f80197691925e5d8c6d882254c42b3991f44cc

Else libqtav clients application will not compile in MXE env (cross compilation from windows using MinGW)

Problem will be certainly the same under Macports. This patch has no side effect under Linux.

Gilles Caulier

**Comment by wang-bin** [comment]
what qtav version are you using? master branch has no such problem.

**Comment by cgilles** [comment]
It"s in the title : the last stable release QtAV 1.11.0
