### ISSUE TITLE
QIODevice in Android

### ISSUE THREAD

**Issue by manang** [wang-bin/QtAV#783]
Hi,
I'm trying to use a QIODevice (QBuffer) in Android, but the error that I receive is:

D/libsimpleplayer.so( 3549): /home/manang/qtav/src/AVPlayer.cpp:647 (void QtAV::AVPlayer::loadInternal()): Loading  QVariant(QIODevice*, QObject(0xa2d1ede8))  ...
D/libsimpleplayer.so( 3549): /home/manang/qtav/src/AVDemuxer.cpp:728 (bool QtAV::AVDemuxer::load()): "all closed and reseted"
D/libsimpleplayer.so( 3549): /home/manang/qtav/src/AVDemuxer.cpp:780 (bool QtAV::AVDemuxer::load()): "avformat_open_input: d->format_ctx:'0xb8d96fd0'..., MediaIO('QIODevice'): 0xb8cab0c0"
D/libsimpleplayer.so( 3549): /home/manang/qtav/src/AVDemuxer.cpp:782 (bool QtAV::AVDemuxer::load()): "avformat_open_input: (with MediaIO) ret:-1094995529"
W/libsimpleplayer.so( 3549): /home/manang/qtav/src/AVDemuxer.cpp:794 (bool QtAV::AVDemuxer::load()): Can't open media:  "failed to open media"
W/libsimpleplayer.so( 3549): /home/manang/qtav/src/AVPlayer.cpp:661 (void QtAV::AVPlayer::loadInternal()): "Load failed!"

My code is the following

`    QFile *vidfile = new QFile("/sdcard/Download/BigBuckBunny_320x180.mp4");
    bool value = vidfile->open(QIODevice::ReadOnly);
   QByteArray *data = new QByteArray();
 QBuffer *buffer = new QBuffer(data);
    buffer->open(QIODevice::ReadOnly);
    m_player->setIODevice(buffer);
    data->append(vidfile->read(1024*1024), 1024*1024);
    m_player->play();`

My configuration is:
Qt 5.7,
QtAv 1.11.0
Ffmpeg 3.1.1

What is wrong?

Thank you very much

angelo

**Comment by manang** [comment]
if I put
m_player->setIODevice(vidfile);
the playback is ok.
Why?

**Comment by wang-bin** [comment]
Because your QBuffer is using an empty QByteArray

**Comment by manang** [comment]
Hi,
thanks for your answer.
before m_player->play() I fill the QByteArray with 1024*1024 bytes (data->append(vidfile->read(1024*1024), 1024*1024)).

**Comment by wang-bin** [comment]
does test/qiodevice work on your computer?

**Comment by manang** [comment]
I recompiled all and now I can use the QBuffer.
I don't know why I had this problem.

Thank you for your answers
