### ISSUE TITLE
sdk_install doesn't copy QmlAV headers?

### ISSUE THREAD

**Issue by kuanyui** [wang-bin/QtAV#786]
I think I need to inherit `QmlAVPlayer` C++ class, to wrap an `AVTranscode` into it, for accessing `AVTranscode` in QML. However, I found it seems that `sdk_install` doesn't copy `/qml/QmlAV/` headers. So I cannot `#include <QmlAV/QmlAVPlayer>`.

Is this for purpose? (That is to say, I should not do something like this for customization, there is another right way to do?). Thank you for your work 🙇‍

**Comment by wang-bin** [comment]
qtquick plugins only provide qml api, no c++
