### ISSUE TITLE
No video when run QtAV.Player in XP 32bit

### ISSUE THREAD

**Issue by zhudonghe** [wang-bin/QtAV#790]
I downloaded the minGW version QtAV release installer from [official web page](http://www.qtav.org/install.html) and installed it on WinXP 32bit.

A mp4 video file to test.

- QtAV.Player: 
Correct audio, but the video screen is black.

- QtAV.Player.QML
Successfully!

Could anyone please tell me what is the reason of this problem and how to solve it?

Thanks!

**Comment by wang-bin** [comment]
Enable log and paste player log here

**Comment by zhudonghe** [comment]
Some of the player log below. The OS is XP sp3. 

Debug: vo: gl
Debug: QtAV 1.11.0(Jun 19 2016, 22:10:26)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
Debug: "Build with Qt-5.6.1"
Debug: "FFmpeg/Libav configuration: --extra-version=QtAV --disable-doc --disable-debug --enable-small --enable-shared --disable-static --enable-runtime-cpudetect --enable-hwaccels --enable-avresample --disable-postproc --disable-iconv --enable-pic --extra-ldflags=' -static-libgcc -Wl,-Bstatic'"
Debug: "Build with avutil-55.17.103"
Debug: "Build with avcodec-57.24.102"
Debug: "Build with avformat-57.25.100"
Debug: "Build with avfilter-6.31.100"
Debug: "Build with avdevice-57.0.101"
Debug: "Build with avresample-3.0.0"
Debug: "Build with swresample-2.0.101"
Debug: "Build with swscale-4.0.100"
Debug: engine: "LibASS"
Debug: engine: "FFmpeg"
Debug: engine: "FFmpeg"
Warning: "cannot load dxva2.dll"
Warning: "can not load cuda!"
Debug: -f set:  "C:\\test.mp4"
Debug: Registered audio backends:  ("XAudio2", "OpenAL", "DirectSound", "null")
Debug: "XAudio2_9"
Warning: "Cannot load library XAudio2_9: 找不到指定的模块。"
Debug: "XAudio2_8"
Warning: "Cannot load library XAudio2_8: 找不到指定的模块。"
Debug: "XAudio2_7"
Debug: "Build with XAudio2 from DXSDK"
Debug: "Try inline function 'XAudio2Create' from DXSDK"
Debug: "xaudio2: 0xa6b0728"
Debug: "Not playing~"
Debug: QHash(("probesize", QVariant(uint, 5000000))("analyzeduration", QVariant(int, 5000000)))
Debug: Loading  QVariant(QString, "C:\\test.mp4")  ...
Debug: "all closed and reseted"
Debug: "avformat_open_input: d->format_ctx:'0x17ec220', url:'C:\\test.mp4'..."
Debug: "avformat_open_input: url:'C:\\test.mp4' ret:0"
Debug: "avfmtctx.flag: 513"
Debug: "AVFMT_NOTIMESTAMPS: 0, AVFMT_TS_DISCONT: 512, AVFMT_NO_BYTE_SEEK:0, custom io: 0"
Warning: "invalid index 0 (valid is 0~0) for stream type 2."
Debug: "notify_interval: 500"
Debug: "stream: 1, duration=51581952 (1074624 ms), time_base=0.000021"
Debug: "codec: aac()"
Debug: "stream: 0, duration=26864000 (1074560 ms), time_base=0.000040"
Debug: "codec: h264()"
Debug: "has audio"
Debug: "QtAV::AudioDecoderFFmpeg thread type: Single, count: 1"
Debug: audio format from codec:  QtAV::AudioFormat(48000Hz, 4Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "fltp")
Debug: "source_voice: 0x0, master: 0x0"
Debug: AudioOutput format:  QtAV::AudioFormat(48000Hz, 4Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "flt")
Debug: "source_voice:0xa6be280"
Warning: "src audio parameters 'channel layout(or channels), sample rate and sample format must be set before initialize resampler"
Debug: "new audio thread"
Debug: "demux thread setAudioThread"
Debug: "output not changed: 0x175e718"
Debug: "set AVThread output"
Debug: "stream: 1, duration=51581952 (1074624 ms), time_base=0.000021"
Debug: "codec: aac()"
Debug: "**********trying video decoder: FFmpeg..."
Debug: "set QtAV::VideoDecoderFFmpeg() meta properties:"
Debug: "codecName=>"
Debug: "skip_frame=>0"
Debug: "threads=>0"
Debug: "vismv=>0"
Debug: "skip_idct=>0"
Debug: "skip_loop_filter=>0"
Debug: "thread_type=>3"
Debug: "QtAV::VideoDecoderFFmpeg thread type: Single, count: 1"
Debug: "**************Video decoder found:0x1752e08"
Debug: "setCapture 0x17bf7c8"
Debug: "stream: 0, duration=26864000 (1074559 ms), time_base=0.000040"
Debug: "codec: h264()"
Debug: "auto select clock: audio > external"
Debug: "Using AudioClock"
Debug: "Clock initial value: 0.000000"
Debug: "Starting audio thread..."
Debug: "Starting video thread..."
Debug: "get av queue a/v thread = 0x175d390 0x1752b98"
Debug: ScreenSaver::retrieveState
Debug: Succeed to enable screen saver (0)
Debug: track found!!!!!
Warning: "no frame could be decompressed: Error number 204357 occurred 0/204357"
Warning: "invalid video frame from decoder. undecoded data size: 0"
Debug: "buffersrc_args=time_base=1/1000000:sample_rate=48000:sample_fmt=fltp:channel_layout=0x3"
Warning: [FFmpeg:?] No such filter: ''
Warning: [FFmpeg:?] Error avfilter_graph_parse_ptr(filter_graph, options.toUtf8().constData(), &inputs, &outputs, __null) @160 D:\dev\QtAV\src\filter\LibAVFilter.cpp: (0xffffffea) Invalid argument
Warning: "setup audio filter graph error"
Debug: "swr speed=1.00"
Debug: "out: {cl: 3, fmt: flt, freq: 48000}"
Debug: "in {cl: 3, fmt: fltp, freq: 48000}"
Debug: "OpenGL version: 2.0  hasGLSL: 1"
Debug: "GL_VERSION: OpenGL ES 2.0 (ANGLE 2.1.99f075dade7c)"
Debug: "GL_VENDOR: Google Inc."
Debug: "GL_RENDERER: ANGLE (VMware SVGA II Direct3D9 vs_3_0 ps_3_0)"
Debug: "GL_SHADING_LANGUAGE_VERSION: OpenGL ES GLSL ES 1.00 (ANGLE 2.1.99f075dade7c)"
Debug: "Is OpenGLES: 1"
Debug: "Is EGL: 1"
Debug: "GLSL version: 100"
Debug: "Has PBO: 0"
Debug: "Do not support glGetTexLevelParameteriv. test_gl_param returns false"
Debug: "(repeat 1)Do not support glGetTexLevelParameteriv. test_gl_param returns false\ncheck desktop rg: 0x8227"
Debug: "Do not support glGetTexLevelParameteriv. test_gl_param returns false"
Debug: "check es3 rg: 0x822B"
Debug: "Do not support glGetTexLevelParameteriv. test_gl_param returns false"
Debug: "check GL_EXT_texture_rg"
Debug: "check gl es>=3 rg"
Debug: "fallback to gl_param_compat"
Debug: "Has 16bit texture: 0"
Debug: "Has RG texture: 0"
Debug: QSurfaceFormat(version 2.0, options QFlags(), depthBufferSize 24, redBufferSize 5, greenBufferSize 6, blueBufferSize 5, alphaBufferSize 0, stencilBufferSize 8, samples 0, swapBehavior 0, swapInterval -1, profile  0)
Warning: "no frame could be decompressed: Error number 230 occurred 0/230"
Warning: "invalid video frame from decoder. undecoded data size: 0"
Debug: status changed  "已加载"
Debug: status changed  "缓冲中..."
Debug: "AVClock started!!!!!!!!"
Debug: "buffersrc_args=video_size=1280x720:pix_fmt=0:time_base=1/1000000:pixel_aspect=1/1"
Warning: [FFmpeg:?] No such filter: ''
Warning: [FFmpeg:?] Error avfilter_graph_parse_ptr(filter_graph, options.toUtf8().constData(), &inputs, &outputs, __null) @160 D:\dev\QtAV\src\filter\LibAVFilter.cpp: (0xffffffea) Invalid argument
Warning: "setup video filter graph error"
Debug: "setInSize => calculating aspect ratio from converted input data(1.777778)"
Debug: status changed  "已缓冲"
Debug: QtAV::VideoFormat(pixelFormat: 15 "yuv420p" alpha: false, channels: 3, planes: 3, bpc: 8, bpp: 12/12 -8-8-8)
Debug: "pixel format changed:  => yuv420p 15"
Debug: material changed:  "gl material 16to8bit: 0, planar: 0, has alpha: 0, 2d texture: 0, 2nd plane rg: 0"  =>  "gl material 16to8bit: 0, planar: 1, has alpha: 0, 2d texture: 1, 2nd plane rg: 0"
Debug: "[ShaderManager] cache a new shader material type(10): gl material 16to8bit: 0, planar: 1, has alpha: 0, 2d texture: 1, 2nd plane rg: 0"
Debug: "bind attribute: a_Position => 0"
Debug: "bind attribute: a_TexCoords0 => 1"
Debug: "uniform locations:"
Debug: "u_Texture0: 1"
Debug: "u_Texture1: 2"
Debug: "u_Texture2: 3"
Debug: "u_Matrix: 0"
Debug: "u_colorMatrix: 5"
Debug: "u_opacity: 4"
Debug: "plane linesize 0: padded = 1280, effective = 1280. theoretical plane size: 1280x720"
Debug: "plane linesize 1: padded = 640, effective = 640. theoretical plane size: 640x360"
Debug: "plane linesize 2: padded = 640, effective = 640. theoretical plane size: 640x360"
Debug: "effective_tex_width_ratio=1.000000"
Debug: texture internal format:  QVector(6409, 6409, 6406)
Debug: texture data format:  QVector(6409, 6409, 6406)
Debug: texture data type:  QVector(5121, 5121, 5121)
Debug: "///////////bpp 2, bpc: 8"
Debug: "texture width: 1280 - 1280 = pad: 0. bpp(gl): 1"
Debug: "texture width: 640 - 640 = pad: 0. bpp(gl): 1"
Debug: "(repeat 1)texture width: 640 - 640 = pad: 0. bpp(gl): 1\ncreating texture for plane 0"
Debug: "texture for plane 0 is created (id=1)"
Debug: "creating texture for plane 1"
Debug: "texture for plane 1 is created (id=2)"
Debug: "creating texture for plane 2"
Debug: "texture for plane 2 is created (id=3)"
Debug: input yuv limited range
Debug: updating vao...
Debug: VAO is not supported
Debug: updating vbo...
Debug: updating vbo...
Debug: "timer: 3, current thread: 0x3fc780, player thread: 0x3fc780"
Debug: "stopping demuxer thread..."
Debug: stopping thread  QtAV::AudioThread(0x175d390)
Debug: "audio thread stop after decode()"
Debug: "Audio thread stops running..."
Debug: stopping thread  QtAV::VideoThread(0x1752b98)
Debug: "Video thread stops running..."
Debug: "setInSize => calculating aspect ratio from converted input data(0.000000)"
Debug: "all avthread finished. try to exit demux thread<<<<<<"
Debug: "stopping demuxer thread..."
Debug: "all avthread finished. try to exit demux thread<<<<<<"
Debug: "Demux thread stops running...."
Debug: "demuxer thread emit finished."
Debug: "avplayer emit stopped()"
Warning: "Can not copy codec properties when it's open"
Debug: "(repeat 1)Can not copy codec properties when it's open\nclosing d->format_ctx"
Debug: "all audio/video threads stopped... state: 0"
Debug: sync config to  "C:/Documents and Settings/Administrator/Application Data/Player/Player.ini"
Debug: sync end
Debug: "Not playing~"
Debug: "(repeat 1)Not playing~\nsource_voice: 0xa6be280, master: 0xa6baf28"
Debug: "source_voice: 0x0, master: 0x0"
Debug: 
Debug: "~AVThreadPrivate wake up paused thread"
Debug: "(repeat 1)~AVThreadPrivate wake up paused thread\nVideoFilterContext 0x17b3cf0 delete paint device in 0x17bf800"
Warning: ScreenSaver::restoreState: no data, doing nothing

**Comment by wang-bin** [comment]
The log looks fine. Video frame is rendered. I don't know why nothing is displayed. What about QMLPlayer log?

**Comment by zhudonghe** [comment]
QMLPlayer log

Debug: arguments=======  ("QMLPlayer.exe", "-f", "C:\\test.mp4")
Debug: current dir:  "C:/Documents and Settings/Administrator/桌面/bin"
Debug: ("C:/Documents and Settings/Administrator/桌面/bin", "C:/Documents and Settings/Administrator/桌面/bin/qml")
Debug: >>>>>>>>devicePixelRatio: 1.000000
Debug: dpi phy:  72.0177 , logical:  96 , dpr:  1 ; vis rect: QRect(0,0 1920x1080)
Debug: touch devices:  ()
Debug: QtAV 1.11.0(Jun 19 2016, 22:10:26)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
Debug: "Build with Qt-5.6.1"
Debug: "FFmpeg/Libav configuration: --extra-version=QtAV --disable-doc --disable-debug --enable-small --enable-shared --disable-static --enable-runtime-cpudetect --enable-hwaccels --enable-avresample --disable-postproc --disable-iconv --enable-pic --extra-ldflags=' -static-libgcc -Wl,-Bstatic'"
Debug: "Build with avutil-55.17.103"
Debug: "Build with avcodec-57.24.102"
Debug: "Build with avformat-57.25.100"
Debug: "Build with avfilter-6.31.100"
Debug: "Build with avdevice-57.0.101"
Debug: "Build with avresample-3.0.0"
Debug: "Build with swresample-2.0.101"
Debug: "Build with swscale-4.0.100"
Debug: Registered audio backends:  ("XAudio2", "OpenAL", "DirectSound", "null")
Debug: "XAudio2_9"
Warning: "Cannot load library XAudio2_9: 找不到指定的模块。"
Debug: "XAudio2_8"
Warning: "Cannot load library XAudio2_8: 找不到指定的模块。"
Debug: "XAudio2_7"
Debug: "Build with XAudio2 from DXSDK"
Debug: "Try inline function 'XAudio2Create' from DXSDK"
Debug: "xaudio2: 0xe660728"
Debug: engine: "LibASS"
Debug: engine: "FFmpeg"
Debug: engine: "FFmpeg"
Debug: engine: "LibASS"
Debug: init>>>>>screen density logical: 3.7795275590551185 pixel: 2.8353435141139114
Debug: file:  "C:\\test.mp4"
Debug: "source_voice: 0x0, master: 0x0"
Debug: 
Debug: "XAudio2_9"
Warning: "Cannot load library XAudio2_9: 找不到指定的模块。"
Debug: "XAudio2_8"
Warning: "Cannot load library XAudio2_8: 找不到指定的模块。"
Debug: "XAudio2_7.dll"
Debug: "Build with XAudio2 from DXSDK"
Debug: "Try inline function 'XAudio2Create' from DXSDK"
Debug: "xaudio2: 0xe660728"
Debug: ScreenSaver::retrieveState
Debug: Succeed to enable screen saver (0)
Debug: Loading  QVariant(QString, "C:/test.mp4")  ...
Debug: "all closed and reseted"
Debug: "avformat_open_input: d->format_ctx:'0xdd63d20', url:'C:/test.mp4'..."
Debug: "avformat_open_input: url:'C:/test.mp4' ret:0"
Debug: "avfmtctx.flag: 513"
Debug: "AVFMT_NOTIMESTAMPS: 0, AVFMT_TS_DISCONT: 512, AVFMT_NO_BYTE_SEEK:0, custom io: 0"
Warning: "invalid index 0 (valid is 0~0) for stream type 2."
Debug: "notify_interval: 500"
Debug: "stream: 1, duration=51581952 (1074624 ms), time_base=0.000021"
Debug: "codec: aac()"
Debug: "stream: 0, duration=26864000 (1074560 ms), time_base=0.000040"
Debug: "codec: h264()"
Debug: "OpenGL version: 2.1  hasGLSL: 1"
Debug: "GL_VERSION: 2.1 Mesa 10.0 (git-5da4fa2)"
Debug: "GL_VENDOR: VMware, Inc."
Debug: "GL_RENDERER: Gallium 0.4 on SVGA3D; build: RELEASE;  "
Debug: "GL_SHADING_LANGUAGE_VERSION: 1.20"
Debug: "Is OpenGLES: 0"
Debug: "Is EGL: 0"
Debug: "GLSL version: 120"
Debug: "Has PBO: 1"
Debug: "Do not support texture internal format: 0x822a (result 0x1)"
Debug: "Do not support texture internal format: 0x822b (result 0x1)"
Debug: "fallback to gl_param_compat"
Debug: "Has 16bit texture: 0"
Debug: "check desktop rg: 0x8227"
Debug: "Do not support texture internal format: 0x8227 (result 0x1)"
Debug: "check es3 rg: 0x822B"
Debug: "Do not support texture internal format: 0x822b (result 0x1)"
Debug: "check GL_EXT_texture_rg"
Debug: "check gl es>=3 rg"
Debug: "Has RG texture: 0"
Debug: QSurfaceFormat(version 2.1, options QFlags(0x4), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior 2, swapInterval 1, profile  0)
Debug: "has audio"
Debug: "QtAV::AudioDecoderFFmpeg thread type: Single, count: 1"
Debug: audio format from codec:  QtAV::AudioFormat(48000Hz, 4Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "fltp")
Debug: "source_voice: 0x0, master: 0x0"
Debug: AudioOutput format:  QtAV::AudioFormat(48000Hz, 4Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "flt")
Debug: "source_voice:0xe66e280"
Warning: "src audio parameters 'channel layout(or channels), sample rate and sample format must be set before initialize resampler"
Debug: "new audio thread"
Debug: "demux thread setAudioThread"
Debug: "output not changed: 0xdae06e0"
Debug: "set AVThread output"
Debug: "stream: 1, duration=51581952 (1074624 ms), time_base=0.000021"
Debug: "codec: aac()"
Debug: "**********trying video decoder: FFmpeg..."
Debug: "QtAV::VideoDecoderFFmpeg thread type: Single, count: 1"
Debug: "**************Video decoder found:0xde2a9a8"
Debug: "setCapture 0xdb1fae0"
Debug: "stream: 0, duration=26864000 (1074559 ms), time_base=0.000040"
Debug: "codec: h264()"
Debug: "auto select clock: audio > external"
Debug: "Using AudioClock"
Debug: "Clock initial value: 0.000000"
Debug: "Starting audio thread..."
Debug: "Starting video thread..."
Debug: "get av queue a/v thread = 0xde06ea0 0xde2a9c0"
Warning: qrc:///qml/QMLPlayer/main.qml:141: TypeError: Type error
Warning: qrc:///qml/QMLPlayer/main.qml:133: TypeError: Type error
Debug: duration changed: file:C:/test.mp4
Debug: add history: file:C:/test.mp4
Warning: "no frame could be decompressed: Error number 204357 occurred 0/204357"
Warning: "invalid video frame from decoder. undecoded data size: 0"
Debug: "swr speed=1.00"
Debug: "out: {cl: 3, fmt: flt, freq: 48000}"
Debug: "in {cl: 3, fmt: fltp, freq: 48000}"
Warning: "no frame could be decompressed: Error number 230 occurred 0/230"
Warning: "invalid video frame from decoder. undecoded data size: 0"
Debug: "AVClock started!!!!!!!!"
Debug: "setInSize => calculating aspect ratio from converted input data(1.777778)"
Debug: QtAV::VideoFormat(pixelFormat: 15 "yuv420p" alpha: false, channels: 3, planes: 3, bpc: 8, bpp: 12/12 -8-8-8)
Debug: "pixel format changed:  => yuv420p 15"
Debug: material changed:  "gl material 16to8bit: 0, planar: 0, has alpha: 0, 2d texture: 0, 2nd plane rg: 0"  =>  "gl material 16to8bit: 0, planar: 1, has alpha: 0, 2d texture: 1, 2nd plane rg: 0"
Debug: "[ShaderManager] cache a new shader material type(10): gl material 16to8bit: 0, planar: 1, has alpha: 0, 2d texture: 1, 2nd plane rg: 0"
Debug: "bind attribute: a_Position => 0"
Debug: "bind attribute: a_TexCoords0 => 1"
Debug: "uniform locations:"
Debug: "u_Texture0: 1"
Debug: "u_Texture1: 2"
Debug: "u_Texture2: 3"
Debug: "u_Matrix: 0"
Debug: "u_colorMatrix: 5"
Debug: "u_opacity: 4"
Debug: "plane linesize 0: padded = 1280, effective = 1280. theoretical plane size: 1280x720"
Debug: "plane linesize 1: padded = 640, effective = 640. theoretical plane size: 640x360"
Debug: "plane linesize 2: padded = 640, effective = 640. theoretical plane size: 640x360"
Debug: "effective_tex_width_ratio=1.000000"
Debug: texture internal format:  QVector(6409, 6409, 6406)
Debug: texture data format:  QVector(6409, 6409, 6406)
Debug: texture data type:  QVector(5121, 5121, 5121)
Debug: "///////////bpp 2, bpc: 8"
Debug: "texture width: 1280 - 1280 = pad: 0. bpp(gl): 1"
Debug: "texture width: 640 - 640 = pad: 0. bpp(gl): 1"
Debug: "(repeat 1)texture width: 640 - 640 = pad: 0. bpp(gl): 1\ncreating texture for plane 0"
Debug: "texture for plane 0 is created (id=22)"
Debug: "creating texture for plane 1"
Debug: "texture for plane 1 is created (id=23)"
Debug: "creating texture for plane 2"
Debug: "texture for plane 2 is created (id=24)"
Debug: input yuv limited range
Debug: updating vao...
Debug: updating vbo...
Debug: sync config to  "C:/Documents and Settings/Administrator/Application Data/QMLPlayer/QMLPlayer.ini"
Debug: sync end
Debug: "timer: 4, current thread: 0x3fa340, player thread: 0x3fa340"
Debug: "stopping demuxer thread..."
Debug: stopping thread  QtAV::AudioThread(0xde06ea0)
Debug: "audio thread stop after decode()"
Debug: "Audio thread stops running..."
Debug: stopping thread  QtAV::VideoThread(0xde2a9c0)
Debug: "Video thread stops running..."
Debug: "setInSize => calculating aspect ratio from converted input data(0.000000)"
Debug: "all avthread finished. try to exit demux thread<<<<<<"
Debug: "Demux thread stops running...."
Debug: "demuxer thread emit finished."
Debug: "avplayer emit stopped()"
Warning: "Can not copy codec properties when it's open"
Debug: "(repeat 1)Can not copy codec properties when it's open\nclosing d->format_ctx"
Debug: "all audio/video threads stopped... state: 0"
Warning: "No gl context"
Debug: "(repeat 2)No gl context\nNot playing~"
Debug: "source_voice: 0xe66e280, master: 0xe66af28"
Debug: "source_voice: 0x0, master: 0x0"
Debug: 
Debug: "~AVThreadPrivate wake up paused thread"
Warning: "(repeat 1)~AVThreadPrivate wake up paused thread\nNo gl context"
Warning: ScreenSaver::restoreState: no data, doing nothing

**Comment by zhudonghe** [comment]
The problem only happens in XP. The player runs successfully in Win7, Win10. 

One more info, when the QtAV.Player playing the mp4 file. The screen is black, but the thumbnail showed if mouse is on the progress bar.

**Comment by wang-bin** [comment]
thumbnail is not rendered  by opengl

**Comment by wang-bin** [comment]
Debug: "GL_VERSION: OpenGL ES 2.0 (ANGLE 2.1.99f075dade7c)"
    Debug: "GL_VENDOR: Google Inc."
    Debug: "GL_RENDERER: ANGLE (VMware SVGA II Direct3D9 vs_3_0 ps_3_0)"

这个是player的，用d3d实现的gles2接口

> Debug: "GL_VERSION: 2.1 Mesa 10.0 (git-5da4fa2)"
这个是qmplayer的，是用desktop gl。

你把player的设置对话框里opengl改成desktop就行，或用命令行-gl desktop参数
