### ISSUE TITLE
Port from qmake to cmake

### ISSUE THREAD

**Issue by cgilles** [wang-bin/QtAV#795]
QtAv use currently qmake to build whole source code. Scripts are complex and not optimized to published this framework.

As i have a long experience with Cmake (with digiKam and KDE projects), i propose to port QtAV to Cmake. I can give guidance and help on this task if you is interested.

**Comment by wang-bin** [comment]
I wrote one but not complete. I will push to github this weekend.

**Comment by knro** [comment]
This would be great! Also, is there a way to make this into a small light-weight library that can be embedded into projects?

**Comment by cgilles** [comment]
Wang,

What's the status of your cmake port ? I propose to review your cmake code when it's ready for you ?

I have a long cmake experience so i can guide you. Don't hesitate to ask. In digiKam and co, we have plenty of cmake code everywhere plus shared libraries.

digiKam goal is to be more more KDE non dependent. KDE has a large collection of factored scripts that i know to extract for your project to prevent to re-write unnecessary code. Don't waste time to re-invent the wheel...

Gilles Caulier

**Comment by wang-bin** [comment]
See 89747bd It only builds libQtAV module now

**Comment by cgilles** [comment]
ok. Do you plan to do the rest of QtAv with CMake ?

**Comment by cgilles** [comment]
And, what the release plan, including Cmake support ?

**Comment by wang-bin** [comment]
Of cause. QtAVWidgets module is supported now. CMake support is included in the next release.

**Comment by wang-bin** [comment]
Now you can build libQtAV, libQtAVWidgets and examples. The result Player example runs fine on my mac.

**Comment by wang-bin** [comment]
@cgilles Do you know how to write cmake files which can be used by sdk users? I see there are a lot of cmake files in Qt lib/cmake dir. Are they written by hand or generated by some tools?

**Comment by cgilles** [comment]
typically, with cmake 3 you must to provide a QtAVConfig.cmake file

In KDE, we have a ECM framework which do it very quickly. But this want mean that you need to depend of KDE framework, and you don't want to use this way and i recommend to never do it. To be clear,  digiKam goal is to become a pure Qt5 application in the future due to huge legacy with KDE which is problematic with non Linux system.

So, i  recommend to look in OpenCV project, based on cmake, and which do not depend of KDE
Warning this project is really huge and complex.

https://github.com/opencv/opencv/blob/master/CMakeLists.txt

The second approach, that i prefer and that i implemented in Exiv2 cmake port for ex, is to provide an old school FindXXXXX.cmake script. I write one for digiKam about QtAV. Look here :

https://cgit.kde.org/digikam.git/tree/cmake/modules/FindQtAV.cmake

This is really more simpler to write and maintain. It miss some rules to find the QtAV version found on the system, but mostly the script is ready to use and work on Linux, MacOS and Windows.

I recommend the last approach in first, and later to port to first approach.

**Comment by cfeck** [comment]
ECM does not depend on KDE frameworks.

**Comment by a17r** [comment]
Currently does not build on Linux:

`src/capi/egl_api.cpp:25:18: fatal error: capi.h: No such file or directory`

**Comment by cgilles** [comment]
yes reproducible here too under Linux Mageia 5 and 6

**Comment by wang-bin** [comment]
did you run `git submodule update --init`

**Comment by cgilles** [comment]
Wang,

I updated the QtAV source code here with last git/master, and all compile fine here with CMake rules.
And yes git submodule update --init fix the previous problem.

I think this file can be closed now.

Gilles Culier
