### ISSUE TITLE
QtAV\src\filter\SubtitleFilter.cpp(163) : error C2065: 'd' : undeclared identifier

### ISSUE THREAD

**Issue by cbdg** [wang-bin/QtAV#799]
QString subtitleText(qreal t) /*const*/;

QString SubtitleFilter::subtitleText(qreal t) /*const*/
{
   // here must add DPTR_D(SubtitleFilter);
  DPTR_D(SubtitleFilter); // must  so const need delete
    d.player_sub->subtitle()->setTimestamp(t);
    return d.player_sub->subtitle()->getText();
}

**Comment by wang-bin** [comment]
thanks
