### ISSUE TITLE
AnimationController

### ISSUE THREAD

**Issue by Artanidos** [wang-bin/QtAV#803]
Hi Wang Bin
I am using the AnimationController to render a qml scene into a movie.
In detail I am setting the "progress" property of the animationcontroller for each frame and then I call grabWindow() to get the image for that frame.
Is there a chance to make the property "position" writeable so that I can animate it with a NumberAnimation?

See sample:
----------------
import QtQuick 2.3
import QtAV 1.6

Rectangle {
    width: 864
    height: 800
    color: "#FF0000"

    Video {
         id: video
         width: 480
         height: 800
         source: "video.mp4"
     }

    Rectangle
    {   id: rect1
        x: 50
        y: 50
        width: 100
        height: 50
        color: "#00FF00"
    }

    AnimationController {
      objectName: "animationController"
      animation: ParallelAnimation {
        NumberAnimation { target: rect1; property: "opacity"; duration: 1000; from: 0; to: 1.0 }
        NumberAnimation { target: video; property: "position"; duration: video.duration; from: 0; to: video.duration }
      }
    }
}

**Comment by wang-bin** [comment]
You can add a property in Video item, call seek when this property is updated. But you should know seeking can be slow so it's not a good idea to do it in animation

**Comment by Artanidos** [comment]
Thanks for your quick answer.
Performance is not an issue because I am rendering asynchron in a non visual QQuickWindow. But please give me a hint how such a property might look like in code.

**Comment by Artanidos** [comment]
Oh, I found out on my own...
...but unfortunately the video is not being displayed at all.
Any ideas?
 
Video {
        property int pos
        onPosChanged: seek(pos)
        id: video
        width: 480
        height: 800
        source: "video.mp4"
     }
...
NumberAnimation { target: video; property: "pos"; duration: video.duration; from: 0; to: video.duration }

**Comment by wang-bin** [comment]
I need your player log

**Comment by Artanidos** [comment]
I found out more...
The video was only invisible when using the QQuickWindow create() method and was visible using the QQuickWindow show() method.
But even on show() the seek() method is not appropriate because its working async so that I need to put a sleep between each frame.
What I would like to have is that first the QtAV is working when the window is invisible using the create() method and second a seek method or a writeable position property which works synchronous. 
The next thing would be not to call play() before, because I have to call play() followed by pause() to display a single frame.

I use the QQuickWIndow like this which works for all other qml types except QtAV and Multimedia
    view = new QQuickView;
    view->setSource(QUrl::fromLocalFile("/home/olaf/SourceCode/AnimationMaker/demo.qml"));
    view->setResizeMode( QQuickView::SizeViewToRootObject );
    view->create();

**Comment by wang-bin** [comment]
> The video was only invisible when using the QQuickWindow create() method and was visible using the QQuickWindow show() method

QWindow is hidden unless show()/setVisible() is called.

> a seek method or a writeable position property which works synchronous

Seek can be very slow, for example 1s or more. UI will be frozen. Why don't you use a player to play the video?

**Comment by Artanidos** [comment]
I need to render each single frame to grab an image to encode as a video.
Even Mediaplayer does not work for me that way.

**Comment by wang-bin** [comment]
grab the whole window or only video frames?

**Comment by Artanidos** [comment]
The whole window including other QT objects.
But I am working on my own lightweight component now.
Thanks for your help.
