### ISSUE TITLE
videocapture的小问题

### ISSUE THREAD

**Issue by tudows** [wang-bin/QtAV#804]
我在调用
`player->play();`
之后直接调用
`player->videoCapture()->capture()`
是失败的。然后当中如果是
`player->play();`
`Sleep(1000);`
`player->videoCapture()->capture();`
就可以。
我设置了player->setAsyncLoad(false);也不行。

**Comment by wang-bin** [comment]
解码线程还没起来之前capture无效。你是要做什么功能？用VideoFilter的process函数可以截获每一个解码的帧，可以考虑用这个

**Comment by tudows** [comment]
我希望就是截取视频中间一帧作为缩略图，想setstartpos到视频中间的时间然后capture一下。就是希望马上就能截取到，而不是等到播放到那里再截取，所以采取了这个方案。是不是用VideoFilter的process可以直接获取任意一帧截图而不用播放到那里？

**Comment by tudows** [comment]
VideoFrameExtractor这个example里有么？我刚才试了下没找到怎么使用/(ㄒoㄒ)/~~
