### ISSUE TITLE
使用vs静态编译无法打开

### ISSUE THREAD

**Issue by tudows** [wang-bin/QtAV#805]
QT是5.7.0，vs是2015，使用了[http://www.npcglib.org/~stathis/blog/precompiled-qt4-qt5/](http://www.npcglib.org/~stathis/blog/precompiled-qt4-qt5/)里的编译库对程序进行了release的MT静态编译，
但是程序会在new QtAV::AVPlayer的时候提示
`QObject: cannot create children for a parent that is in a different thread ......`
然后在new QtAV::VideoOutput的时候提示
`QObject: cannot create children for a parent that is in a different thread ......`
`QPixmap: must construct a qguiapplication before a QPixmap`
然后程序关闭。
如果是debug调试没有问题。

release和debug都是我clone最新的源码按照wiki编译的

**Comment by wang-bin** [comment]
行，一直没有静态编译的qt，正好试试

**Comment by tudows** [comment]
好的，真的感谢O(∩_∩)O

**Comment by wang-bin** [comment]
原来vc编译静态库有很多问题。刚修改了下编译和运行都没问题了。用你链接里的qt5.7.0 x86 vs2015测的。你用最新代码，qmake后运行编译目录的sdk_uninstall.bat，然后编译，编译后的player.exe就能用了。然后运行sdk_install.bat，可以编译测试你自己的程序了。

qml还不行，还得研究下

**Comment by tudows** [comment]
好的，回头我尝试一下

**Comment by tudows** [comment]
我uninstall了所有的QtAV，然后编译最新源码（使用QtCreator，编译环境是Qt自身的ms2015环境），编译出来后我install到qt5.7.0 x86 vs2015里面的static release里，然后自己的程序设置release，MT，添加相应lib，编译改为qt5.7.0 x86 vs2015里面的static release，然后编译结束后，程序打不开（就是双击没有任何反应。把videoPreviewOutput = new QtAV::VideoOutput()这行代码删除就可以打开）

**Comment by wang-bin** [comment]
MT哪里设的？

**Comment by wang-bin** [comment]
simpleplayer_sdk.pro能编译运行么？

**Comment by tudows** [comment]
我自己的程序是用的vs编写的。在vs的工程属性里有MT（[http://blog.csdn.net/wyansai/article/details/51178631](http://blog.csdn.net/wyansai/article/details/51178631)）。因为比如QtAV编译出来的player.exe我在开发环境中是可以正常跑的，但是放在纯净的系统中需要拷贝相应的动态链接库dll和安装运行库才可以运行，我想通过MT编译，然后这样就可以不需要安装任何东西直接就能运行。
（我经过测试，一个普通的QT程序，MT编译后在纯净系统中什么也不需要安装就可以运行。而MT编译就如[http://blog.csdn.net/wyansai/article/details/51178631](http://blog.csdn.net/wyansai/article/details/51178631)教程所说的需要用到qt5.7.0 x86 vs2015）

**Comment by wang-bin** [comment]
> 把videoPreviewOutput = new QtAV::VideoOutput()这行代码删除就可以打开

你得在开始加一句`QtAV::Widgets::registerRenderers()`，不然QtAVWidgets模块不会被加载。动态库编译没问题是因为VideoOutput里有动态加载QtAVWidgets的dll

**Comment by tudows** [comment]
这句代码我一直添加在最开始的位置。不是这个原因。

后来不懈努力还是解决了。重新download了qt的源码自己编译了一次，然后再用编译出来静态库编译qtav。最后lib里添加所有需要的lib（不光qtav的lib，opengl的和av*、sw*系列的lib都需要）

年前鼓捣了好久哈哈

**Comment by wang-bin** [comment]
我在sharedouput例子里测的结果就是加这一行的问题

**Comment by tudows** [comment]
主要我也不知道脑子哪里搭住了，就是想不带qtav的dll，就一个裸exe在纯净系统里跑 ╮(╯▽╰)╭ ，example里面的两个player在纯净环境下都必须带qtav的dll，现在我那样设置一下工程，然后重新编译一下qtav的qt就可以不带dll了。

感谢作者解答O(∩_∩)O

**Comment by wang-bin** [comment]
静态编译没有qtav dll的
