### ISSUE TITLE
CUDA header files conflict with GPL

### ISSUE THREAD

**Issue by adrianschroeter** [wang-bin/QtAV#809]
I failed to get QtAV submitted to openSUSE because the legal check pointed out that the files

src/cuda/dllapi/cuviddec.h
src/cuda/dllapi/nvcuvid.h

have a restrictive Nvidia license which conflicts with GPL.
(submitted now with these removed and CUDA disabled, but there might be a better solution?)

**Comment by wang-bin** [comment]
I think I have to use dylink_cuda.h, dylink_cuviddec.h and dylink_nvcuvid.h instead like ffmpeg.  lavfilters did the same change.

**Comment by wang-bin** [comment]
I removed those headers. New headers are copied from ffmpeg, they can be used without restriction.
