### ISSUE TITLE
Ubuntu 12.04 build failed

### ISSUE THREAD

**Issue by adauvalter** [wang-bin/QtAV#81]
adauvalter@ubuntu:~/dev/QtAV_build$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.3 LTS
Release:    12.04
Codename:   precise
adauvalter@ubuntu:~/dev/QtAV_build$ ffmpeg --v
ffmpeg version git-2013-09-04-04dcdc4 Copyright (c) 2000-2013 the FFmpeg developers
  built on Sep  4 2013 11:27:33 with gcc 4.6 (Ubuntu/Linaro 4.6.3-1ubuntu5)
  configuration: --prefix=/home/adauvalter/dev/ffmpeg_build --extra-cflags=-I/home/adauvalter/dev/ffmpeg_build/include --extra-ldflags=-L/home/adauvalter/dev/ffmpeg_build/lib --bindir=/home/adauvalter/bin --extra-libs=-ldl --enable-gpl --enable-libass --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-x11grab
  libavutil      52. 43.100 / 52. 43.100
  libavcodec     55. 31.100 / 55. 31.100
  libavformat    55. 16.100 / 55. 16.100
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 83.102 /  3. 83.102
  libswscale      2.  5.100 /  2.  5.100
  libswresample   0. 17.103 /  0. 17.103
  libpostproc    52.  3.100 / 52.  3.100
Unrecognized option '-v'.
Error splitting the argument list: Option not found
adauvalter@ubuntu:~/dev/QtAV_build$ make
cd src/ && ( test -e Makefile.libQtAV || /home/adauvalter/dev/Qt5.1.1/5.1.1/gcc/bin/qmake /home/adauvalter/dev/QtAV/src/libQtAV.pro -o Makefile.libQtAV ) && make -f Makefile.libQtAV 
make[1]: Entering directory `/home/adauvalter/dev/QtAV_build/src'
Makefile.libQtAV:4702: warning: overriding commands for target`install_target'
Makefile.libQtAV:4612: warning: ignoring old commands for target `install_target'
Makefile.libQtAV:4712: warning: overriding commands for target`uninstall_target'
Makefile.libQtAV:4622: warning: ignoring old commands for target `uninstall_target'
make[1]: Nothing to be done for`first'.
make[1]: Leaving directory `/home/adauvalter/dev/QtAV_build/src'
cd qml/ && ( test -e Makefile.libQmlAV || /home/adauvalter/dev/Qt5.1.1/5.1.1/gcc/bin/qmake /home/adauvalter/dev/QtAV/qml/libQmlAV.pro -o Makefile.libQmlAV ) && make -f Makefile.libQmlAV 
make[1]: Entering directory`/home/adauvalter/dev/QtAV_build/qml'
Makefile.libQmlAV:1079: warning: overriding commands for target `install_target'
Makefile.libQmlAV:1060: warning: ignoring old commands for target`install_target'
Makefile.libQmlAV:1084: warning: overriding commands for target `uninstall_target'
Makefile.libQmlAV:1065: warning: ignoring old commands for target`uninstall_target'
make[1]: Nothing to be done for `first'.
make[1]: Leaving directory`/home/adauvalter/dev/QtAV_build/qml'
cd examples/ && ( test -e Makefile || /home/adauvalter/dev/Qt5.1.1/5.1.1/gcc/bin/qmake /home/adauvalter/dev/QtAV/examples/examples.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory `/home/adauvalter/dev/QtAV_build/examples'
cd vo-qt/ && ( test -e Makefile || /home/adauvalter/dev/Qt5.1.1/5.1.1/gcc/bin/qmake /home/adauvalter/dev/QtAV/examples/vo-qt/vo-qt.pro -o Makefile ) && make -f Makefile 
make[2]: Entering directory`/home/adauvalter/dev/QtAV_build/examples/vo-qt'
g++ -Wl,-z,origin -Wl,-O1 -Wl,-rpath,/home/adauvalter/dev/Qt5.1.1/5.1.1/gcc -Wl,-rpath,/home/adauvalter/dev/QtAV_build/lib_linux:'$ORIGIN':'$ORIGIN/lib':. -Wl,-rpath,/usr/local/lib -Wl,-rpath,/home/adauvalter/dev/Qt5.1.1/5.1.1/gcc/lib -o ../../bin/vo-qt ../../.obj/vo-qt_linux/main.o   -L/home/adauvalter/dev/QtAV_build/lib_linux -lQtAV -L/usr/local/lib -L/home/adauvalter/dev/Qt5.1.1/5.1.1/gcc/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_align_put_bits'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_ac3_channel_layout_tab'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_flac_parse_block_header'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_mjpeg_bits_ac_chrominance'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_h264_has_num_reorder_frames'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_vorbis_parse_frame'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `inflateInit2_'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_aac_parse_header'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `av_parser_parse2'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`zlibCompileFlags'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_mpa_decode_header'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_dca_sample_rates'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_mjpeg_val_dc'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`av_bitstream_filter_filter'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_flac_parse_streaminfo'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_copy_pce_data'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `inflate'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_ac3_parse_header'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_mjpeg_bits_dc_luminance'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_mjpeg_bits_dc_chrominance'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_find_pix_fmt'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_adx_decode_header'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_tak_parse_streaminfo'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_mjpeg_val_ac_luminance'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_flac_is_extradata_valid'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`inflateInit_'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `av_bitstream_filter_close'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avcodec_pix_fmt_to_codec_tag'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `av_parser_close'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`av_parser_init'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_mjpeg_bits_ac_luminance'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_mpa_freq_tab'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avcodec_register_all'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_dv_frame_profile'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_dnxhd_get_frame_size'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_split_xiph_headers'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_dirac_parse_sequence_header'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_copy_bits'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_mpa_bitrate_tab'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`uncompress'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `ff_raw_pix_fmt_tags'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`av_bitstream_filter_init'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_mjpeg_val_ac_chrominance'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_vorbis_parse_reset'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_dv_codec_profile'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_mpeg4audio_sample_rates'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `avpriv_vorbis_parse_extradata'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_mpegaudio_decode_header'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to `inflateEnd'
/home/adauvalter/dev/QtAV_build/lib_linux/libQtAV.so: undefined reference to`avpriv_mpeg4audio_get_config'
collect2: ld returned 1 exit status
make[2]: **\* [../../bin/vo-qt] Error 1
make[2]: Leaving directory `/home/adauvalter/dev/QtAV_build/examples/vo-qt'
make[1]: *** [sub-vo-qt-make_first] Error 2
make[1]: Leaving directory`/home/adauvalter/dev/QtAV_build/examples'
make: **\* [sub-examples-make_first] Error 2
adauvalter@ubuntu:~/dev/QtAV_build$

**Comment by qianda1992** [comment]
So,what is the final method to solve this problem?
