### ISSUE TITLE
Compiling with MAC error

### ISSUE THREAD

**Issue by manang** [wang-bin/QtAV#810]
Hi, I'm trying to compile QtAV in a mac.
I've installed ffmpeg with brew and the version is the 3.2.2.

I have the following error:
`Undefined symbols for architecture x86_64:
  "_ff_vda_create_decoder", referenced from:
      QtAV::VideoDecoderVDAPrivate::setup(AVCodecContext*) in VideoDecoderVDA.o
  "_ff_vda_destroy_decoder", referenced from:
      QtAV::VideoDecoderVDAPrivate::setup(AVCodecContext*) in VideoDecoderVDA.o
      QtAV::VideoDecoderVDAPrivate::close() in VideoDecoderVDA.o`

I don't understand what is the error.

Thank you very much

Angelo

**Comment by gaokunbuaa** [comment]
This only happens on MAC.
These two functions are not imported in ffmpeg 3.2.2, which is different from previous versions.

**Comment by wang-bin** [comment]
FFmpeg remove the old vda api. You can remove `CONFIG += config_vda` in libQtAV.pro and run qmake again

**Comment by manang** [comment]
I'm trying with commenting config_vda.
Now I have this problem

`Undefined symbols for architecture x86_64:
  "QtAV::OpenGLWindowRenderer::showEvent(QShowEvent*)", referenced from:
      vtable for PlayerWindow in main.o`

thanks

Angelo

**Comment by wang-bin** [comment]
Did you run `sdk_uninstall.sh` before build?

**Comment by manang** [comment]
No, because I did not install this libs in my qt environment.
Thanks

**Comment by wang-bin** [comment]
vda works now. `Undefined symbols for architecture x86_64: "QtAV::OpenGLWindowRenderer::showEvent(QShowEvent*)"` can not be produced in all my environmnets
