### ISSUE TITLE
Qt SDK path setting

### ISSUE THREAD

**Issue by leavittx** [wang-bin/QtAV#813]
Hi! I'm trying to build QtAV on windows 8.1, and have installed two versions of Qt5: 5.8 and 5.7
How do I switch between these versions for QtAV?
By default it chooses H:\Qt\5.8\msvc2015_64\bin\qmake.exe, so it's kind of magic for me, I want to be responsible for that myself.
Thanks!

**Comment by wang-bin** [comment]
Use qmake absolute path
