### ISSUE TITLE
Build Error: VideoDecoderCUDA.moc not found on Cross Compile to Raspberry Pi 2

### ISSUE THREAD

**Issue by MiaranaDIY** [wang-bin/QtAV#815]
Hi, thanks for the great work.

I have a build problem, what I need to do is cross compile Qt5.7.1 to Raspberry Pi 2. All modules and Qtbase were compiled smoothly, but failed with QtAV. I don't know that is the cause, for FFMPEG I compiled it on host RPi2 and success, then transfer it back to my laptop using rsync, already edited the .qmake.conf to include the lib and include path of FFMPEG build. Here is the make log, please help me to point out whats wrong:

`cd src/ && ( test -e Makefile.libQtAV || /home/scorpion/raspi/qt5/bin/qmake /home/scorpion/raspi/QtAV/src/libQtAV.pro -o Makefile.libQtAV ) && make -f Makefile.libQtAV 
cd tools/ && ( test -e Makefile || /home/scorpion/raspi/qt5/bin/qmake /home/scorpion/raspi/QtAV/tools/tools.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/scorpion/raspi/QtAV_build/tools'
cd install_sdk/ && ( test -e Makefile || /home/scorpion/raspi/qt5/bin/qmake /home/scorpion/raspi/QtAV/tools/install_sdk/install_sdk.pro -o Makefile ) && make -f Makefile 
make[2]: Entering directory '/home/scorpion/raspi/QtAV_build/tools/install_sdk'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/home/scorpion/raspi/QtAV_build/tools/install_sdk'
make[1]: Leaving directory '/home/scorpion/raspi/QtAV_build/tools'
make[1]: Entering directory '/home/scorpion/raspi/QtAV_build/src'
/home/scorpion/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++ -c -pipe -march=armv7-a -marm -mthumb-interwork -mfpu=neon-vfpv4 -mtune=cortex-a7 -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/scorpion/raspi/sysroot -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DBUILD_QTAV_LIB -DBUILD_UCHARDET -DQTAV_HAVE_CAPI=1 -DQTAV_HAVE_EGL_CAPI=1 -D__STDC_CONSTANT_MACROS -DQTAV_HAVE_X11=1 -DQTAV_HAVE_SWRESAMPLE=1 -DQTAV_HAVE_AVDEVICE=1 -DQTAV_HAVE_AVFILTER=1 -DQTAV_HAVE_PULSEAUDIO=1 -DQTAV_HAVE_CUDA=1 -DQTAV_HAVE_QT_EGL=1 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I/home/scorpion/raspi/QtAV/src -I/home/scorpion/raspi/QtAV_build/src -I/home/scorpion/raspi/QtAV/ffmpeg/include -I/home/scorpion/raspi/qt5pi/include -I/home/scorpion/raspi/QtAV/src -I/home/scorpion/raspi/QtAV -I/home/scorpion/raspi/QtAV/src/QtAV -I/home/scorpion/raspi/QtAV/contrib/uchardet/src -I/home/scorpion/raspi/QtAV/contrib/capi -I/home/scorpion/raspi/QtAV/src/cuda -I/home/scorpion/raspi/QtAV/src/cuda/dllapi -I/home/scorpion/raspi/qt5pi/include/QtGui -I/home/scorpion/raspi/qt5pi/include/QtCore -I../.moc/5.7.1/QtAV -I/home/scorpion/raspi/sysroot/opt/vc/include -I/home/scorpion/raspi/sysroot/opt/vc/include/interface/vcos/pthreads -I/home/scorpion/raspi/sysroot/opt/vc/include/interface/vmcs_host/linux -I/home/scorpion/raspi/qt5/mkspecs/devices/linux-rasp-pi2-g++ -o ../.obj/QtAV_linux_arm/VideoDecoderCUDA.o /home/scorpion/raspi/QtAV/src/codec/video/VideoDecoderCUDA.cpp
/home/scorpion/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++ -c -pipe -march=armv7-a -marm -mthumb-interwork -mfpu=neon-vfpv4 -mtune=cortex-a7 -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/scorpion/raspi/sysroot -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DBUILD_QTAV_LIB -DBUILD_UCHARDET -DQTAV_HAVE_CAPI=1 -DQTAV_HAVE_EGL_CAPI=1 -D__STDC_CONSTANT_MACROS -DQTAV_HAVE_X11=1 -DQTAV_HAVE_SWRESAMPLE=1 -DQTAV_HAVE_AVDEVICE=1 -DQTAV_HAVE_AVFILTER=1 -DQTAV_HAVE_PULSEAUDIO=1 -DQTAV_HAVE_CUDA=1 -DQTAV_HAVE_QT_EGL=1 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I/home/scorpion/raspi/QtAV/src -I/home/scorpion/raspi/QtAV_build/src -I/home/scorpion/raspi/QtAV/ffmpeg/include -I/home/scorpion/raspi/qt5pi/include -I/home/scorpion/raspi/QtAV/src -I/home/scorpion/raspi/QtAV -I/home/scorpion/raspi/QtAV/src/QtAV -I/home/scorpion/raspi/QtAV/contrib/uchardet/src -I/home/scorpion/raspi/QtAV/contrib/capi -I/home/scorpion/raspi/QtAV/src/cuda -I/home/scorpion/raspi/QtAV/src/cuda/dllapi -I/home/scorpion/raspi/qt5pi/include/QtGui -I/home/scorpion/raspi/qt5pi/include/QtCore -I../.moc/5.7.1/QtAV -I/home/scorpion/raspi/sysroot/opt/vc/include -I/home/scorpion/raspi/sysroot/opt/vc/include/interface/vcos/pthreads -I/home/scorpion/raspi/sysroot/opt/vc/include/interface/vmcs_host/linux -I/home/scorpion/raspi/qt5/mkspecs/devices/linux-rasp-pi2-g++ -o ../.obj/QtAV_linux_arm/cuda_api.o /home/scorpion/raspi/QtAV/src/cuda/cuda_api.cpp
/home/scorpion/raspi/QtAV/src/codec/video/VideoDecoderCUDA.cpp:799:32: fatal error: VideoDecoderCUDA.moc: No such file or directory
 #include "VideoDecoderCUDA.moc"
                                ^
compilation terminated.
Makefile.libQtAV:5564: recipe for target '../.obj/QtAV_linux_arm/VideoDecoderCUDA.o' failed
make[1]: *** [../.obj/QtAV_linux_arm/VideoDecoderCUDA.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/scorpion/raspi/QtAV_build/src'
Makefile:46: recipe for target 'sub-src-libQtAV-pro-make_first' failed
make: *** [sub-src-libQtAV-pro-make_first] Error 2
`

**Comment by wang-bin** [comment]
You have to use QtAV.pro instead of libQtAV.pro
