### ISSUE TITLE
How to rescale video to lower resolution and/or bitrate?

### ISSUE THREAD

**Issue by rpw98** [wang-bin/QtAV#817]
Hi,

Does QtAV have functions to reduce video to lower resolution and file size? I see ffmpeg has that command. I wonder if QtAV has implement that? Also, anyway to rotate a video?

Thank you!
Rp

**Comment by wang-bin** [comment]
What ffmpeg option?

**Comment by rpw98** [comment]
For example:

http://stackoverflow.com/questions/4490154/reducing-video-size-with-same-format-and-reducing-frame-size

**Comment by rpw98** [comment]
ffmpeg -i <inputfilename> -s 640x480 -b 512k -vcodec mpeg1video -acodec copy <outputfilename>

**Comment by wang-bin** [comment]
Transcoding video?

**Comment by rpw98** [comment]
Yes, "transcoding", however it was called. Basically keeps the same codec but reduce resolution and file size, with audio unchanged, I guess.

Thank you!

**Comment by wang-bin** [comment]
Did you try `videoEncoder()->setWidth()/setHeight()`? 0 means the same as input size

**Comment by rpw98** [comment]
Where is videoEncoder()? I have to say, QtAV is fantastic. But the lack of documentation really makes it hard to find what I was looking for...

**Comment by wang-bin** [comment]
AVTranscoder
