### ISSUE TITLE
delay in videothread

### ISSUE THREAD

**Issue by cascarpato** [wang-bin/QtAV#82]
Hi Wang,
in VideoThread.cpp there is these piece of code:

d.delay = pkt.pts  - d.clock->value();
if (qAbs(d.delay) < 2.718) {
            if (d.delay > kSyncThreshold) { //Slow down
                //d.delay_cond.wait(&d.mutex, d.delay*1000); //replay may fail. why?
                qDebug("Video ~~~~~wating for %f msecs pts:%f  clock:%f", d.delay*1000,pkt.pts,d.clock->value());
                usleep(d.delay * 1000000);
            } else if (d.delay < -kSyncThreshold) { //Speed up. drop frame?
                //continue;
            }
 else { //when to drop off?
            qDebug("delay %f/%f", d.delay, d.clock->value());
            if (d.delay > 0) {
                qDebug("Video X~~~~wating for %f msecs", 64.0);
                msleep(64);
            } else {
                //audio packet not cleaned up?
                continue;
            }
        }

on some network cameras pkt.pts  has a large value or not monotone growth  so d.delay became > 2.718 and video go slow down. So i have some questions:
1)  What does the number 2.718 ?
2) may i change or better avoid the if control?
3) It's correct that the d.clock->value() is always = 0 ?
4) why the msleep(64);

**Comment by wang-bin** [comment]
1.4.2 works perfect
