### ISSUE TITLE
D3D11VA 硬解码

### ISSUE THREAD

**Issue by feixiaku** [wang-bin/QtAV#824]
您好， QtAV支持D3D11VA 硬解方式吗？

**Comment by wang-bin** [comment]
支持，默认是编译进去的。player例子的解码器菜单里可以看到

**Comment by feixiaku** [comment]
我最近在做D3D11VA硬解码的事情，遇到一个问题，当解完码之后，从显存拷回到内存中，这一部分不太清楚，然后参看您的github上的代码(VideoDecoderD3d11.cpp)中的VideoDecoderD3D11::frame(),
 应为对D3D1不太熟悉，所以可以介绍一下，ID3D11VideoDecoderOutputView /
ID3D11DeviceContext_CopySubresourceRegion() / ID3D11DeviceContext_Map()
这个流程，谢谢~

2017-02-13 20:34 GMT+08:00 WangBin <notifications@github.com>:

**Comment by wang-bin** [comment]
没啥好介绍的，就是找能拷贝的函数看看
