### ISSUE TITLE
Circular main.o <- QtAV dependency dropped.

### ISSUE THREAD

**Issue by sonichy** [wang-bin/QtAV#827]
Deepin + Qt5.6.1 build error

QT += av avwidgets
TEMPLATE = app
TARGET = QtAV
INCLUDEPATH += .
SOURCES += main.cpp

#include <WidgetRenderer.h>
#include <QApplication>
#include <QtAV>
#include <QtAVWidgets>
#include <QtAV/AVPlayer.h>

using namespace QtAV;

int main(int argc,char *argv[])
{
    QApplication a(argc, argv);
    WidgetRenderer renderer;
    renderer.show();
    Widgets::registerRenderers();
    AVPlayer player;
    player.setRenderer(&renderer);
    player.play("/home/administrator/Videos/13D601569DFAC258E3068597681F11E1.mp4");
    return a.exec();
}

**Comment by wang-bin** [comment]
what error?

**Comment by sonichy** [comment]
解决了，TARGET不能和关键字一样。
