### ISSUE TITLE
How to set render to a layout ?

### ISSUE THREAD

**Issue by sonichy** [wang-bin/QtAV#828]
Something like:
ui->vbox->addWidget(renderer);

**Comment by wang-bin** [comment]
`ui->vbox->addWidget(renderer->widget())`

**Comment by sonichy** [comment]
可以了，但是有声音，无视频。

**Comment by wang-bin** [comment]
log

**Comment by sonichy** [comment]
使用 VideoOutput 代替 renderer，搞定了。
