### ISSUE TITLE
QML QtAV 能够硬解码么

### ISSUE THREAD

**Issue by SeptemberHX** [wang-bin/QtAV#844]
我想用qml做一个最简单的mp4播放程序，为了降低cpu使用，想要用硬解码，可以做到么？
Ubuntu 16.04

**Comment by wang-bin** [comment]
`Video.videoCodecPriority: ["VAAPI", "FFmpeg"]` or `MediaPlayer.videoCodecPriority: ["VAAPI", "FFmpeg"]`
