### ISSUE TITLE
iOs compile QMLPlayer

### ISSUE THREAD

**Issue by manang** [wang-bin/QtAV#846]
Hi,
I'm trying to compile QtAV for iOS and I have the following error:

`Check dependencies
No profiles for 'org.qtav.qmlplayer' were found:  Xcode couldn't find a provisioning profile matching 'org.qtav.qmlplayer'.
Code signing is required for product type 'Application' in SDK 'iOS 10.3'`

could you tell me how I can solve?

Thank you very much

Angelo

**Comment by wang-bin** [comment]
Google. You have to be a registered developer.

**Comment by kubark42** [comment]
I've got the same problem. I am a registered developer, but this still does not work. Pardon my ignorance, but should I replace this `org.qtav.qmlplayer` string by another? Or should I somehow register this?
