### ISSUE TITLE
error in iOs environment

### ISSUE THREAD

**Issue by manang** [wang-bin/QtAV#847]
Hi,
I'm trying to use QMLPlayer in an iPad air 2.
I have the following error:

`10:29:08: TransferAppSession(51728a37d16b843c483d287f93aa39e1aaed068c, /Users/angelomantellini/QtAV/examples/build-QMLPlayer_sdk-iphoneos_clang_Qt_5_7_1_for_iOS-Release/Release-iphoneos/QMLPlayer.app)TransferAppSession(/Users/angelomantellini/QtAV/examples/build-QMLPlayer_sdk-iphoneos_clang_Qt_5_7_1_for_iOS-Release/Release-iphoneos/QMLPlayer.app,51728a37d16b843c483d287f93aa39e1aaed068c) failed, AMDeviceTransferApplication returned The file could not be found. (0x-402653176)

Error while building/deploying project QMLPlayer_sdk (kit: iphoneos-clang Qt 5.7.1 for iOS)
When executing step "Deploy to Angelo Mantellini’s iPad"`

Could you explain me how to resolve this issue?
is there a guide for iOs?

Thank you very much

Angelo

**Comment by wang-bin** [comment]
What about other qml apps?

**Comment by manang** [comment]
with qt examples I don't have problems.

**Comment by manang** [comment]
I think I solved selecting ipad and not iphone with xcode. (I have to use an ipad..)
thank you very much
