### ISSUE TITLE
egl_api.cpp:25:18: fatal error: capi.h: No such file or directory

### ISSUE THREAD

**Issue by sashoalm** [wang-bin/QtAV#857]
I get this error when trying to build from Qt Creator. I'm on Ubuntu Xenial 16.04.2 LTS, 64-bit. I disabled BUILD_QT5OPENGL from cmake-gui, and I'm building on commit e22230b9c89facec1f6727cd63b6667568f26534.

The error:

    egl_api.cpp:25:18: fatal error: capi.h: No such file or directory

It's near these lines:

    #ifndef CAPI_LINK_EGL
    #include "capi.h"
    #endif //CAPI_LINK_EGL

**Comment by fcoiffie** [comment]
I just got the same error.

It's due to missing submodules.
The following command must be executed after the git clone:
```
git submodule update --init
```
and cmake must be re-executed to configure these submodules.

**Comment by lxlxdw** [comment]
so if I download the release code, (such as   https://github.com/wang-bin/QtAV/archive/v1.12.0.tar.gz)
will can't compile it?
