### ISSUE TITLE
播放任意链接，暂停5分钟，点击继续播放，稍等片刻（约1分钟）后播放器结束播放

### ISSUE THREAD

**Issue by lrs0304** [wang-bin/QtAV#860]
如题

测试连接： http://la.sdiread.cn/o_1as1jp3qimkhhuo1o54sve1nlt9.mp4
重现操作：播放连接后，任意暂停5分钟以上的时间后点击继续播放，稍等片刻播放器将结束播放

有两种结束播放的log

第一种
![_20170421093751](https://cloud.githubusercontent.com/assets/6349495/25259409/7d8293bc-2678-11e7-9d62-e04da355f5e6.png)

第二种
"09:51:37.163 ----"
"09:51:37.163 ++++"
"09:51:37.209 ----"
"09:51:37.210 " [FFmpeg:http] Stream ends prematurely at 13715202, should be 81757488
"09:51:37.210 ++++"
"09:51:37.210 currupt packet. pts: -1.000000"
"09:51:37.255 ----"
"09:51:37.255 " [FFmpeg:mov,mp4,m4a,3gp,3g2,mj2] stream 0, offset 0xd164da: partial file
"09:51:37.255 ++++"
"09:51:37.256 End of file. erreof=0 feof=1"
"09:51:37.256 av_demux_thread read_frame 0"
"09:51:37.256 audio is too short than video: 0.216, fake_apkt.duration: 14.590"
"09:51:51.559 audio thread gets an eof packet. pkt.pts: -1.000, d.render_pts0:-1.000"
"09:51:51.559 [AudioDecoder] got_frame_ptr=false. decoded: 0, un: 3"
"09:51:51.560 Decode audio failed. undecoded: 3"
"09:51:51.560 audio decode eof done"
"09:51:51.633 Invalid packet! flush video codec context!!!!!!!!!! video packet queue size: 1"
"09:51:51.650 video seek: 21.400, id: 13709160"
"09:51:51.650 video thread gets an eof packet."
"09:51:51.650 no frame could be decompressed: Error number 0 occurred 3/3"
"09:51:51.650 Decode video failed. undecoded: 3/3"
"09:51:51.650 video decode eof done. d.render_pts0: 21.400"
"09:51:51.650 video seek done at eof pts: 0.000. id: 0"
"09:51:51.651 Invalid packet! flush video codec context!!!!!!!!!! video packet queue size: 0"
"09:51:51.658 [repeat 1000]Invalid packet! flush video codec context!!!!!!!!!! video packet queue size: 0"
"09:51:51.659 Invalid packet! flush video codec context!!!!!!!!!! video packet queue size: 0"
"09:51:51.667 [repeat 1000]Invalid packet! flush video codec context!!!!!!!!!! video packet queue size: 0"
"09:51:51.667 Invalid packet! flush video codec context!!!!!!!!!! video packet queue size: 0"
"09:51:51.675 [repeat 1000]Invalid packet! flush video codec context!!!!!!!!!! video packet queue size: 0"

**Comment by lrs0304** [comment]
我发现其他基于ffmpeg的播放器也可以重现这个问题，暂时不处理，姑且认为了流断开了

**Comment by Leizxy** [comment]
你好，请问你解决了么，我也遇到类似的情况了，暂停1min以上后，突然就播放结束，播放器的MediaStatus突然就变成EndOfMedia了，有时候在结束之前会有一个seekFinished(0)传过来。

**Comment by gaoyang720** [comment]
你好，这个问题有解决方案吗？ 遇到同样的问题
