### ISSUE TITLE
Windows: error: avutil is required, but compiler can not find it

### ISSUE THREAD

**Issue by ThatOdieGuy** [wang-bin/QtAV#862]
I was able to get my app working in release mode with the pre-built QtAV SDK. But I wanted to get debug working and there doesn't seem to be an updated debug pre-built SDK. So I started trying to compile QtAV. And I'm having trouble getting it to work.

I've followed the instructions in the build guide.
https://github.com/wang-bin/QtAV/wiki/Build-QtAV

I've tried putting my ffmpeg files into the qt folders as described. I've tried setting the environmental variables. I've tried editing the .qmake.conf file. I've tried different versions of the pre-built ffmpeg and qt. And I just can't seem to get this problem fixed. `avutil is required, but compiler can not find it`. I don't know if I'm doing this wrong or just having problems with x64 libraries conflicting with x86, or MSVC2013 vs MSVC2015.

qt/5.8/msvc2015
qt/5.8/msvc2015_64

Is there a specific combination of Qt kit, ffmpeg pre-built, and compiler that is recommended on Windows?

**Comment by lrs0304** [comment]
没有配置好ffmpeg路径
![_20170422164934](https://cloud.githubusercontent.com/assets/6349495/25302926/b51b8118-277b-11e7-8fd6-5941aaef1ffa.png)

**Comment by ThatOdieGuy** [comment]
Your LIB is pointing to your bin path. Is that right?

I've tried setting all the different types of environmental variables with no success. :(
![image](https://cloud.githubusercontent.com/assets/5105729/25306744/4db84fde-2748-11e7-88e9-fb748e590cec.png)

I've also tried adding this to my .qmake.conf
`INCLUDEPATH += C:/Development/ffmpeg/include
LIBS += C:/Development/ffmpeg/lib`

What version of Qt do you use? Which compiler? And which version of the ffmpeg pre-built do you use?

**Comment by ThatOdieGuy** [comment]
Ah! So I figured out it was the avutil config test project that was failing to build. So I went into the avutil config test project and attempted to build that. That gave me useful errors which allowed me to solve the problem!

Here is how to debug the `avutil is required, but compiler can not find it` message:
```
> mkdir build
> cd build
> c:\Development\Qt\5.8\msvc2015\bin\qmake ..\QtAV.pro
Project ERROR: avutil is required, but compiler can not find it
> cd config.tests\avutil
> nmake
fatal error C1083: Cannot open include file: 'errno.h':
```

So I just ran nmake and fixed any errors that came up. QtAV is building now! :)

I had to fix some paths:

```
set INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\8.1\Include\um;C:\Program Files (x86)\Windows Kits\8.1\Include\shared

set LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x86

set PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
```

**Comment by ThatOdieGuy** [comment]
Just an update and I'll close this issue. 

I missed the part in the wiki where it says "Read config.log in build dir for details." if you run into the avutil issue. Oops. That would have saved me some time.

I've also moved on from Visual Studio builds. I just couldn't figure out how to get that to work properly. And then when I got it compiled, I had crashes. I'm not sure what was wrong, but I've moved on to just a straight mingw32 build and everything is working great.

My setup now:
Qt 5.8 / mingw53_32
ffmpeg-3.3-desktop-MINGW32-lite.7z

Thanks for your help.

**Comment by eagleFromHeaven** [comment]
I managed to compile but now I see that for some reason the version I compiled is not static and still requires the files `QtAVWidgets1.dll` and `QTAV1.dll` , how do i make QtAv fully static?

**Comment by vincensChan** [comment]
QT5.9 mingw53_32  编译：
debug/release: 
     error: Variable QMAKE_DEFAULT_INCDIRS is not defined.
     error: Variable QMAKE_CXX.COMPILER_MACROS is not defined.
     error: avutil is required, but compiler can not find it

不知道咋回事，太烂了...

**Comment by MingqianYang** [comment]
> QT5.9 mingw53_32 编译：
> debug/release:
> error: Variable QMAKE_DEFAULT_INCDIRS is not defined.
> error: Variable QMAKE_CXX.COMPILER_MACROS is not defined.
> error: avutil is required, but compiler can not find it
> 
> 不知道咋回事，太烂了...

配置路径就行了
![image](https://user-images.githubusercontent.com/15353430/103261171-6cfb3500-49db-11eb-8654-906a17eb0237.png)

**Comment by User-adult** [comment]
我是在windows下装的Qt，也报这个错了，没解决
