### ISSUE TITLE
使用“Deploy SDK Without Building QtAV”这种方式安装，运行报错

### ISSUE THREAD

**Issue by dc236621911** [wang-bin/QtAV#864]
在我自己的工程中，下载了编译好的sdk，运行sdk_deploy.bat，在工程文件中包含的QtAV；
工程文件中“QT       += av avwidgets”；cpp文件“#include <QtAV>
#include <QtAVWidgets>
using namespace QtAV;”
但调试运行后出现出现三个错误：
:-1: error: cannot find -lQt5AVWidgets
:-1: error: cannot find -lQt5AV
collect2.exe:-1: error: error: ld returned 1 exit status
这是什么错误，望得到帮助。谢谢！

**Comment by ourran** [comment]
编译器使用的是qt createo 4.2.1 下载qtav : QtAV-Qt5.8-VS2015x86-release-845df52 就出现你所示的问题 ,更换为 QtAV1.11.0-MinGW32.exe 之后编译就正常 (直接通过 http://qtav.org 下载对应平台的安装包即可 ...)

**Comment by wang-bin** [comment]
自己编译要用编译目录的sdk_install.bat
