### ISSUE TITLE
Decode and play two videos as one at the same time

### ISSUE THREAD

**Issue by qpearce19** [wang-bin/QtAV#882]
Hi. I need to create a kind of video player which will be able to play two video files at the same time. The main idea to show frames one after another (1st frame from 1st video, 1st frame from 2nd video, 2nd frame from 1st video, 2nd frame from 2nd video and so on). Is it possible to do it using QtAV? Maybe there're some examples with close idea. Thanks.

**Comment by wang-bin** [comment]
No. Is there a use case?

**Comment by qpearce19** [comment]
Using it with special glasses (like TV 3D kit) it's possible for a few people watch different videos on one display on the same time.

**Comment by wang-bin** [comment]
In fact AVPlayer instance can share the same video renderer, see examples/sharedoutput. I think you can create a new VideoRenderer class which maintains a VideoFrame queue. Frames in the queue are from 2 players, and interlaced. Then you can send the frames to a real VideoRenderer 1 by 1.

**Comment by wang-bin** [comment]
The use case is interesting.
