### ISSUE TITLE
/bin/sh: 1: Syntax error: EOF in backquote substitution

### ISSUE THREAD

**Issue by phlegeard** [wang-bin/QtAV#884]
Hi

I'd like to run QTAV in a step by step manner by launching the simple player of the examples
but when I launch the run option after clicking right on the simpleplayer options I have this error

/bin/sh: 1: Syntax error: EOF in backquote substitution
make[2]: *** [../../bin/Player] Error 2
make[1]: *** [sub-player-make_first] Error 2
make: *** [sub-examples-make_first] Error 2
Makefile:208: recipe for target 'sub-player-make_first' failed

Despite this the executable is created and I can launch it manually  :

-rwxrwxr-x  1 philippe philippe 850408 mai   29 23:15 simpleplayer*

23:31:07: Running steps for project QtAV...
23:31:07: Configuration unchanged, skipping qmake step.
23:31:07: Starting: "/usr/bin/make" 
cd src/ && ( test -e Makefile.libQtAV || /home/philippe/Qt5.7.0/5.7/gcc_64/bin/qmake /home/philippe/my_dev/qtav/src/libQtAV.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile.libQtAV ) && /usr/bin/make -f Makefile.libQtAV 
make[1]: Entering directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/src'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/src'
cd tools/ && ( test -e Makefile || /home/philippe/Qt5.7.0/5.7/gcc_64/bin/qmake /home/philippe/my_dev/qtav/tools/tools.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && /usr/bin/make -f Makefile 
make[1]: Entering directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/tools'
cd install_sdk/ && ( test -e Makefile || /home/philippe/Qt5.7.0/5.7/gcc_64/bin/qmake /home/philippe/my_dev/qtav/tools/install_sdk/install_sdk.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && /usr/bin/make -f Makefile 
make[2]: Entering directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/tools/install_sdk'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/tools/install_sdk'
make[1]: Leaving directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/tools'
cd widgets/ && ( test -e Makefile.libQtAVWidgets || /home/philippe/Qt5.7.0/5.7/gcc_64/bin/qmake /home/philippe/my_dev/qtav/widgets/libQtAVWidgets.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile.libQtAVWidgets ) && /usr/bin/make -f Makefile.libQtAVWidgets 
make[1]: Entering directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/widgets'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/widgets'
cd qml/ && ( test -e Makefile.libQmlAV || /home/philippe/Qt5.7.0/5.7/gcc_64/bin/qmake /home/philippe/my_dev/qtav/qml/libQmlAV.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile.libQmlAV ) && /usr/bin/make -f Makefile.libQmlAV 
make[1]: Entering directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/qml'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/qml'
cd examples/ && ( test -e Makefile || /home/philippe/Qt5.7.0/5.7/gcc_64/bin/qmake /home/philippe/my_dev/qtav/examples/examples.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && /usr/bin/make -f Makefile 
make[1]: Entering directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples'
cd common/ && ( test -e Makefile || /home/philippe/Qt5.7.0/5.7/gcc_64/bin/qmake /home/philippe/my_dev/qtav/examples/common/common.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && /usr/bin/make -f Makefile 
make[2]: Entering directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples/common'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples/common'
cd my_player/ && ( test -e Makefile || /home/philippe/Qt5.7.0/5.7/gcc_64/bin/qmake /home/philippe/my_dev/qtav/examples/my_player/my_player.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && /usr/bin/make -f Makefile 
make[2]: Entering directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples/my_player'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples/my_player'
cd audiopipeline/ && ( test -e Makefile || /home/philippe/Qt5.7.0/5.7/gcc_64/bin/qmake /home/philippe/my_dev/qtav/examples/audiopipeline/audiopipeline.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && /usr/bin/make -f Makefile 
make[2]: Entering directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples/audiopipeline'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples/audiopipeline'
cd sharedoutput/ && ( test -e Makefile || /home/philippe/Qt5.7.0/5.7/gcc_64/bin/qmake /home/philippe/my_dev/qtav/examples/sharedoutput/sharedoutput.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && /usr/bin/make -f Makefile 
make[2]: Entering directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples/sharedoutput'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples/sharedoutput'
cd simpletranscode/ && ( test -e Makefile || /home/philippe/Qt5.7.0/5.7/gcc_64/bin/qmake /home/philippe/my_dev/qtav/examples/simpletranscode/simpletranscode.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && /usr/bin/make -f Makefile 
make[2]: Entering directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples/simpletranscode'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples/simpletranscode'
cd simpleplayer/ && ( test -e Makefile || /home/philippe/Qt5.7.0/5.7/gcc_64/bin/qmake /home/philippe/my_dev/qtav/examples/simpleplayer/simpleplayer.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && /usr/bin/make -f Makefile 
make[2]: Entering directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples/simpleplayer'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples/simpleplayer'
cd player/ && ( test -e Makefile || /home/philippe/Qt5.7.0/5.7/gcc_64/bin/qmake /home/philippe/my_dev/qtav/examples/player/player.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && /usr/bin/make -f Makefile 
make[2]: Entering directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples/player'
g++ -Wl,-z,origin '-Wl,-rpath,/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/lib_linux_x86_64' '-Wl,-rpath,$ORIGIN' '-Wl,-rpath,$ORIGIN/lib' '-Wl,-rpath,.' '-Wl,-rpath,/usr/local/lib' '-Wl,-rpath,/home/philippe/Qt5.7.0/5.7/gcc_64/lib' -pg -Wl,--enable-new-dtags -Wl,-rpath,/home/philippe/Qt5.7.0/5.7/gcc_64/lib -o ../../bin/Player ../../.obj/Player_linux_x86_64/main.o ../../.obj/Player_linux_x86_64/MainWindow.o ../../.obj/Player_linux_x86_64/ClickableMenu.o ../../.obj/Player_linux_x86_64/StatisticsView.o ../../.obj/Player_linux_x86_64/Slider.o ../../.obj/Player_linux_x86_64/TVView.o ../../.obj/Player_linux_x86_64/EventFilter.o ../../.obj/Player_linux_x86_64/ConfigDialog.o ../../.obj/Player_linux_x86_64/ConfigPageBase.o ../../.obj/Player_linux_x86_64/CaptureConfigPage.o ../../.obj/Player_linux_x86_64/VideoEQConfigPage.o ../../.obj/Player_linux_x86_64/DecoderConfigPage.o ../../.obj/Player_linux_x86_64/MiscPage.o ../../.obj/Player_linux_x86_64/OSD.o ../../.obj/Player_linux_x86_64/OSDFilter.o ../../.obj/Player_linux_x86_64/PlayListModel.o ../../.obj/Player_linux_x86_64/PlayListItem.o ../../.obj/Player_linux_x86_64/PlayListDelegate.o ../../.obj/Player_linux_x86_64/PlayList.o ../../.obj/Player_linux_x86_64/PropertyEditor.o ../../.obj/Player_linux_x86_64/AVFormatConfigPage.o ../../.obj/Player_linux_x86_64/AVFilterConfigPage.o ../../.obj/Player_linux_x86_64/ShaderPage.o ../../.obj/Player_linux_x86_64/AVFilterSubtitle.o ../../.obj/Player_linux_x86_64/qrc_player.o ../../.obj/Player_linux_x86_64/moc_MainWindow.o ../../.obj/Player_linux_x86_64/moc_ClickableMenu.o ../../.obj/Player_linux_x86_64/moc_StatisticsView.o ../../.obj/Player_linux_x86_64/moc_Slider.o ../../.obj/Player_linux_x86_64/moc_TVView.o ../../.obj/Player_linux_x86_64/moc_EventFilter.o ../../.obj/Player_linux_x86_64/moc_ConfigDialog.o ../../.obj/Player_linux_x86_64/moc_ConfigPageBase.o ../../.obj/Player_linux_x86_64/moc_CaptureConfigPage.o ../../.obj/Player_linux_x86_64/moc_VideoEQConfigPage.o ../../.obj/Player_linux_x86_64/moc_DecoderConfigPage.o ../../.obj/Player_linux_x86_64/moc_MiscPage.o ../../.obj/Player_linux_x86_64/moc_PlayListModel.o ../../.obj/Player_linux_x86_64/moc_PlayListDelegate.o ../../.obj/Player_linux_x86_64/moc_PlayList.o ../../.obj/Player_linux_x86_64/moc_PropertyEditor.o ../../.obj/Player_linux_x86_64/moc_AVFormatConfigPage.o ../../.obj/Player_linux_x86_64/moc_AVFilterConfigPage.o ../../.obj/Player_linux_x86_64/moc_AVFilterSubtitle.o   -L/home/philippe/my_dev/ffmpeg_build/lib `sdl-config --cflags --libs` -L/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/lib_linux_x86_64 -lQtAV -lQtAVWidgets -lcommon -lavformat -lavcodec -lavutil -lswresample -lswscale -ldl -lX11 -lz -llzma -lva -lva-x11 -lva-drm -lvdpau --cflags --libs` -L/home/philippe/Qt5.7.0/5.7/gcc_64/lib -L/usr/lib64 -lQt5OpenGL -lQt5Svg -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Core -lGL -lpthread 
Makefile:200: recipe for target '../../bin/Player' failed
make[2]: Leaving directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples/player'
/bin/sh: 1: Syntax error: EOF in backquote substitution
make[2]: *** [../../bin/Player] Error 2
make[1]: *** [sub-player-make_first] Error 2
make: *** [sub-examples-make_first] Error 2
Makefile:208: recipe for target 'sub-player-make_first' failed
make[1]: Leaving directory '/home/philippe/my_dev/build-QtAV-Desktop_Qt_5_7_0_GCC_64bit-Debug/examples'
Makefile:149: recipe for target 'sub-examples-make_first' failed
23:31:08: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project QtAV (kit: Desktop Qt 5.7.0 GCC 64bit)
When executing step "Make"
23:31:08: Elapsed time: 00:01.

**Comment by wang-bin** [comment]
No idea
