### ISSUE TITLE
Pause video in QML

### ISSUE THREAD

**Issue by javlada** [wang-bin/QtAV#885]
I use the QML object "Video" to play video in my application.

I have problems with controlling the playback and getting some information. For example if I pause the video, I can not resume it. Calling pause() again does nothing and calling play() starts the playback from scratch.

I also have problem getting the state. If I use slots onStateChanged or onPaused. they are never executed. Am I doing something wrong?

**Comment by wang-bin** [comment]
sample code or log

**Comment by javlada** [comment]
Sorry, I just found i was a stupid mistake in my code. Instead of pausing the video I was stopping it and I didn't realize it. Now everything works perfectly. Once again sorry for reporting a false problem.
