### ISSUE TITLE
Error symbols not found

### ISSUE THREAD

**Issue by manang** [wang-bin/QtAV#891]
Hi, I'm trying to compile QtAV for Mac os x.

I have the following error:
`Undefined symbols for architecture x86_64:
  "QtAV::AVPlayer::internalVideoTracks() const", referenced from:
      QmlAVPlayer::internalVideoTracks() const in QmlAVPlayer.o
ld: symbol(s) not found for architecture x86_64`

Do you have idea why?

Thank you very much

**Comment by wang-bin** [comment]
No. I can't reproduce this.

**Comment by lessness** [comment]
Hello,
the same is here on Mac OS, using qmake + make, with out of the source build.
It looks like a problem with the linker when creating the shared library.
CPATH,  LIBRARY_PATH and DYLD_LIBRARY_PATH are properly set.
Exactly the same configuration and compilation process is used on linux and works like charm.
Do you have any suggestion? Or need more information?
Thank you in advance.

I paste below the very last line before the error as printed by make.

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -stdlib=libc++ '-Wl,-rpath,/Users/cynny/progetti/pathwithffmpeg/deps/QtAV/build/lib_osx_x86_64_llvm' '-Wl,-rpath,@loader_path/../Frameworks' '-Wl,-rpath,@executable_path/../Frameworks' -headerpad_max_install_names  -arch x86_64 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/cynny/Qt/5.9.1/clang_64/lib -single_module -dynamiclib -o libQmlAV.dylib ../.obj/QmlAV_osx_x86_64_llvm/plugin.o ../.obj/QmlAV_osx_x86_64_llvm/QQuickItemRenderer.o ../.obj/QmlAV_osx_x86_64_llvm/SGVideoNode.o ../.obj/QmlAV_osx_x86_64_llvm/QmlAVPlayer.o ../.obj/QmlAV_osx_x86_64_llvm/QuickFilter.o ../.obj/QmlAV_osx_x86_64_llvm/QuickSubtitle.o ../.obj/QmlAV_osx_x86_64_llvm/MediaMetaData.o ../.obj/QmlAV_osx_x86_64_llvm/QuickSubtitleItem.o ../.obj/QmlAV_osx_x86_64_llvm/QuickVideoPreview.o ../.obj/QmlAV_osx_x86_64_llvm/QuickFBORenderer.o ../.obj/QmlAV_osx_x86_64_llvm/moc_QuickSubtitle.o ../.obj/QmlAV_osx_x86_64_llvm/moc_QuickSubtitleItem.o ../.obj/QmlAV_osx_x86_64_llvm/moc_QuickVideoPreview.o ../.obj/QmlAV_osx_x86_64_llvm/moc_MediaMetaData.o ../.obj/QmlAV_osx_x86_64_llvm/moc_QQuickItemRenderer.o ../.obj/QmlAV_osx_x86_64_llvm/moc_QuickFilter.o ../.obj/QmlAV_osx_x86_64_llvm/moc_QmlAVPlayer.o ../.obj/QmlAV_osx_x86_64_llvm/moc_QuickFBORenderer.o  -F/Users/cynny/Qt/5.9.1/clang_64/lib -L/Users/cynny/progetti/pathwithffmpeg/deps/ffmpeg-3.3.2/ffmpeg-install/lib -F/Users/cynny/progetti/pathwithffmpeg/deps/QtAV/build/lib_osx_x86_64_llvm -framework QtAV -lavutil -lavdevice -lswresample -lavresample -lavfilter -framework AudioToolbox -Wl,-unexported_symbols_list,/Users/cynny/progetti/pathwithffmpeg/deps/QtAV/src/unexport.list -framework IOSurface -framework CoreVideo -framework CoreFoundation -framework VideoDecodeAcceleration -framework CoreMedia -framework VideoToolbox -L/Users/cynny/Qt/5.9.1/clang_64/lib -lavcodec -lavformat -lswscale -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL -framework QtQuick -framework QtQml -framework QtNetwork  
Undefined symbols for architecture x86_64:
  "QtAV::AVPlayer::internalVideoTracks() const", referenced from:
      QmlAVPlayer::internalVideoTracks() const in QmlAVPlayer.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../lib_osx_x86_64_llvm/libQmlAV.dylib] Error 1
make: *** [sub-qml-libQmlAV-pro-make_first] Error

**Comment by wang-bin** [comment]
run sdk_uninstall.sh before building new QtAV code
