### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by leezu** [wang-bin/QtAV#892]
To package QtAV on gentoo it would be nice to have a release with working cmake build system. As far as I see, the cmake issue (https://github.com/wang-bin/QtAV/issues/795) was closed end of last month. Is there already a schedule for the next release?

https://bugs.gentoo.org/show_bug.cgi?id=613146

**Comment by wang-bin** [comment]
it's coming

**Comment by leezu** [comment]
Great to hear that. And thanks for your work on this project!
