### ISSUE TITLE
android player 

### ISSUE THREAD

**Issue by cloria** [wang-bin/QtAV#895]
我想编译一个android player。
我下载了qt-opensource-linux-x64-android-5.6.2.run
我用的系统是centos 7 。 
按照您说的方法，我把ffmpeg的目录放到了QtAV下面，并且在.qmake.conf 里面加了这两行
INCLUDEPATH += $$PWD/ffmpeg/include
LIBS += -L$$PWD/ffmpeg/lib
qmake之后报错
Project ERROR: avutil is required, but compiler can not find it
config.log 如下： 
/home/gloria/git/QtAV/ffmpeg/include/libavutil/common.h:33:19: fatal error: errno.h: No such file or directory
 #include <errno.h>
                   ^
compilation terminated.
make: *** [main.o] Error 1
test avutil FAILED
还希望大神能够帮助我。

**Comment by wang-bin** [comment]
android 环境不对
