### ISSUE TITLE
无法定位程序输入点

### ISSUE THREAD

**Issue by nicksun011** [wang-bin/QtAV#898]
我使用的Qt Creator 3.6.1，基于Qt 5.6.0(MSVC 2013,32bit)。在下载了QtAV-Qt5.8-VS2015x86-release-845df52，进行sdk_deploy.bat后，编译程序，运行时直接崩溃，弹出提示无法定位程序输入点，下图所示：
是否我需要自己重新编译对应的dll？
![7nw8wiiwarhp7ms2grr2wj](https://user-images.githubusercontent.com/3025042/27369132-22a7ac16-5689-11e7-9e9c-c057045cb185.png)

**Comment by wang-bin** [comment]
qt版本不一致，你下载的qtav是用5.8的

**Comment by nicksun011** [comment]
了解了，多谢
