### ISSUE TITLE
编译后无法正常运行，提示"Failed to load QtAVWidgets module"

### ISSUE THREAD

**Issue by nicksun011** [wang-bin/QtAV#901]
我用QtCreator + vs2013进行编译，编译后运行程序，提示“can not create video renderer”，输出"Failed to load QtAVWidgets module"。我已经将QtAVWidgetsd1和QtAVd1都拷贝到执行程序所在目录。
![qq 20170622101732](https://user-images.githubusercontent.com/3025042/27415582-49f68e7a-573a-11e7-9106-bcd93edbc554.png)

**Comment by wang-bin** [comment]
release版就行。debug版加载dll时名字不一样，后面我改下

**Comment by nicksun011** [comment]
好的，多谢了。

**Comment by wang-bin** [comment]
试试最新的
