### ISSUE TITLE
我想设置超低延时应该怎么设置，有接口吗？

### ISSUE THREAD

**Issue by jhkwei** [wang-bin/QtAV#903]
udp　ts 流我想设置低延时应该怎么设置．

**Comment by wang-bin** [comment]
issue里搜delay

**Comment by lwj4126380** [comment]
QVariantHash hash;
    hash.insert("analyzeduration", 100000);
    avplayer->setOptionsForFormat(hash);

**Comment by lwj4126380** [comment]
QVariantHash hash;
    hash.insert("analyzeduration", 100000);
    avplayer->setOptionsForFormat(hash);
