### ISSUE TITLE
how to get an android apk ? 

### ISSUE THREAD

**Issue by cloria** [wang-bin/QtAV#904]
我编译android版本的成功了。 但是我却找不到apk，编译完之后的目录如下： 

bin  config.log  config.tests  examples  lib_android_arm  Makefile  qml  sdk_install.sh  sdk_uninstall.sh  src  tests  tools  widgets

There is no errors during the make process. 
能告诉我哪里错了吗？

**Comment by wang-bin** [comment]
No apk. It's a library. If you want to try an example, use QMLPlayer_sdk.pro
