### ISSUE TITLE
Broken build in android

### ISSUE THREAD

**Issue by manang** [wang-bin/QtAV#908]
Hi,
I'm trying to compile QtAV in android and from the 24th of June I have the following error:
`
/Users/angelomantellini/hicn_distillery/qt/QtAV/src/codec/video/VideoDecoderMediaCodec.cpp:33:35: fatal error: libavcodec/mediacodec.h: No such file or directory
 #include <libavcodec/mediacodec.h>
`

I'm using ffmpeg 3.1.4 for android (https://downloads.sourceforge.net/project/qtav/depends/FFmpeg/android/ffmpeg-3.1.4-android.7z)
thanks
Angelo

**Comment by wang-bin** [comment]
#909
