### ISSUE TITLE
Android Build issue

### ISSUE THREAD

**Issue by manang** [wang-bin/QtAV#909]
Hi,
I'm trying to compile QtAV in android and from the 24th of June I have the following error:
`
/Users/angelomantellini/hicn_distillery/qt/QtAV/src/codec/video/VideoDecoderMediaCodec.cpp:33:35: fatal error: libavcodec/mediacodec.h: No such file or directory
 #include <libavcodec/mediacodec.h>
`

I'm using ffmpeg 3.1.4 for android (https://downloads.sourceforge.net/project/qtav/depends/FFmpeg/android/ffmpeg-3.1.4-android.7z)
thanks
Angelo

**Comment by cloria** [comment]
I also need an android apk, but still don't know how to get one. So if you build && get a QTAV  android apk , please tell me . Thanks

**Comment by wang-bin** [comment]
The latest ffmpeg is here: https://sourceforge.net/projects/avbuild/files/

@cloria install QMLPlayer from google play, or https://sourceforge.net/projects/qtav/files/release/1.12.0/QtAV1.12.1-QMLPlayer-android-armv7a-signed.apk/download
