### ISSUE TITLE
QtAV::VideoPreviewPreviewWidget generates Qt warning on moveToThread

### ISSUE THREAD

**Issue by cculianu** [wang-bin/QtAV#917]
Hi,

As you may remember I am using QtAV in my Viking Recorder application.  It works great, and the video preview feature is a lifesaver.  It works most of the time but sometimes the preview breaks and no new frames are extracted (I'm still in the process of troubleshooting this).  

However, in my debugging I noticed the following error message from Qt:

```
QObject::moveToThread; Cannot move objects with a parent
```

I did a little troubleshooting and it boils down to this in VideoFrameExtractor.cpp starting at line 373:

```
VideoFrameExtractor::VideoFrameExtractor(QObject *parent) :
    QObject(parent)
{
    DPTR_D(VideoFrameExtractor);
    moveToThread(&d.thread);
    d.thread.start();
    connect(this, SIGNAL(aboutToExtract(qint64)), SLOT(extractInternal(qint64)));
}

```
The 'moveToThread' call fails because in line 32 of VideoPreviewWidget.cpp (in constructor init) we have:

```
   , m_extractor(new VideoFrameExtractor(this))
``` 
So the extractor has a parent, thus it cannot be moved to a thread.

However -- I was wondering -- that entire 'moveToThread' call seems spurious (is it?).  What is its purpose?  To avoid race conditions should someone connect a signal to one of VideoFrameExtractor's slots?  (I guess that would be a good reason for it living in a thread!).

Anyway I'd like to fix this warning and submit a PR.  Any ideas which way to go?  Should I make VideoFrameExtractor not have a parent and thus force the moveToThread() call to always succeed?

Should I get rid of the call altogether?

Also, I noticed you have some other code in the file you were playing with -- namely ASYNC_EVENT, ASYNC_TASK, and ASYNC_SIGNAL.  I noticed in the comments you complain some of them don't work.

Do you want me to take a stab at getting all of them working ok (it may be related to the moveToThread stuff, after all..)?  

By the way I think if we *DO* end up making moveToThread() work, we need the ExtractThread::run() method to process Qt events during its normal operation (so that VideoFrameExtractor can receive SLOTs -- perhaps that's related to why the other ASYNC_* modes didn't work?).

I feel if I spend time refining this class, it may somehow give me a "Eureka" moment and I can perhaps find the reason why VideoPreviewWidget sometimes fails for me in my app.

Let me know what thoughts you have and how you think I should proceed.. if you're too busy to respond, that's ok too (although do let me know!).

Best regards and thanks again,

-Calin

**Comment by wang-bin** [comment]
We don't need QThread::run(). If a QObject is in a QThread, the signals connected(Queued connection) to the object's slots will be executed in QThread's thread, because signal/slot is implemented by event, and processed in QThread's own event loop in it's thread.

`, m_extractor(new VideoFrameExtractor(this))` 

This line is wrong, parent is not allowed and should be removed from it's constructor. You can do some tests and create a PR.

There is another class `FrameReader`, which use QThread without `run` now. It was designed to replace VideoFrameExtractor, and it should have more features. Actually in one of my private project, `FrameReader` is the most important class of the whole framework. I will bring the changes from my private project to QtAV 2.0. It will be a better and brand new archietecture.

**Comment by cculianu** [comment]
> We don't need QThread::run(). If a QObject is in a QThread, the signals connected(Queued connection) to the object's slots will be executed in QThread's thread, because signal/slot is implemented by event, and processed in QThread's own event loop in it's thread.

Yes that's true... *if* the thread in question is in the exec() method (default implementation of run() calls exec(), of course).  

exec() method basically has its own QEventLoop internally...

However in VideoFrameExtractor, the ExtractThread has its own run() implementation and it does not use a QEventLoop, so qApp->processEvents() must be called... (this is in the default ASYNC_TASK=1 setup...).

But yes, if you use VideoFrameExtractor with ASYNC_TASK=0, then yes, the run() method calls exec() in your code.

Anyway.. besides that.. that FrameReader class sounds excellent but at this point replacing VideoFrameExtractor with it seems onerous... hmm.

I am working on a patch now to fix up VideoFrameExtractor and make it more reliable.  I also am implementing your recommendation and making sure VideoFrameExtractor doesn't have a parent so it can live in a thread.  Of course, then, code that creates it must delete the extractor on delete (I am changing VideoPreviewWidget to do this)...

Another quetion:  Shall I go ahead and kill the other ASYNC_SIGNAL and ASYNC_EVENT conditionals?  Or leave them in?

Does the above sound ok?  Or would you like me to see about using FrameReader and throwing out VideoFrameExtractor altogether?  Is FrameReader very good? Is it reliable?

Your thoughts are appreciated...

**Comment by cculianu** [comment]
I got ASYNC_SIGNAL and ASYNC_EVENT working.

Not sure which one to use.  I like ASYNC_TASK because it kills repeated requests for a frame and only processes the latest one....

**Comment by cculianu** [comment]
One more update: I found some race conditions/hang bugs in VideoFrameExtractor and fixed them.

I got rid of ASYNC_SIGNAL and ASYNC_EVENT.

I fixed some bugs in VideoPreviewWidget..

I'll review my code tomorrow and send you a PR.

**Comment by wang-bin** [comment]
> Not sure which one to use. I like ASYNC_TASK because it kills repeated requests for a frame and only processes the latest one

Yes, that's why it exists.
