### ISSUE TITLE
Change playback speed

### ISSUE THREAD

**Issue by KolyanVM** [wang-bin/QtAV#918]
Hello!
Is there a function to increase the playback speed?
I try to call AvPlayer.setSpeed(real), but not found.

**Comment by wang-bin** [comment]
What's wrong with `AVPlayer.setSpeed` ?

**Comment by KolyanVM** [comment]
_TypeError: Property 'setSpeed' of object QmlAVPlayer_QML_180(0x6355a220, "player") is not a function_

Maybe, because I'm calling a function for the Qml object  AVPlayer

**Comment by wang-bin** [comment]
qml api is `Video/MediaPlayer.playbackRate`, like qtmultimedia
