### ISSUE TITLE
Windows Nvidia CUDA Zero Copy Fails

### ISSUE THREAD

**Issue by emantec** [wang-bin/QtAV#920]
Attempting to use the Nvidia Cuda decoder on windows with Zero Copy enabled results in the following repeated errors and  image displayed

"CUDA error SurfaceInteropCUDA.cpp@357. cuD3D9CtxCreate(&ctx, &dev, CU_CTX_SCHED_BLOCKING_SYNC, device9): 999 CUDA_ERROR_UNKNOWN - unknown error" 
"map hw surface error" VideoShader.cpp: 638

![cuda](https://user-images.githubusercontent.com/29915564/27857545-0489d6be-616a-11e7-9b98-aa30d3ef758d.PNG)

With zero copy disabled decoding works ok.

Reproduction steps
1. Launch QMLPlayer example app
2. Set Nvidia Cuda decoder and Zero Copy (if zero copy already enabled uncheck and check, appears to be a separate bug here where zero copy is only set on change, instead of on launch).
3. Play any video file.

**Comment by wang-bin** [comment]
Did you run it with nvidia gpu instead of intel gpu?

**Comment by emantec** [comment]
Tested on Nvidia 1080ti, it's a Nvidia decoder, surely it should work on Nvidia cards?

**Comment by wang-bin** [comment]
I need your complete log

**Comment by emantec** [comment]
[log-QMLPlayer.txt](https://github.com/wang-bin/QtAV/files/1124757/log-QMLPlayer.txt)

**Comment by emantec** [comment]
@wang-bin Were you able to identify the issue?

**Comment by wang-bin** [comment]
No. What about using desktop opengl instead of ANGLE?

**Comment by emantec** [comment]
Using desktop fixes the CUDA problem but then totally breaks ZeroCopy decoding on DXVA and completely breaks D3D11 decoding with a crash.

D3d11 log and stack trace
[log-QMLPlayer.txt](https://github.com/wang-bin/QtAV/files/1131050/log-QMLPlayer.txt)

[d3d11_stacktrace.txt](https://github.com/wang-bin/QtAV/files/1131053/d3d11_stacktrace.txt)

At this point identifying and fixing the issue with the openGL implementation of CUDA Zero Copy might be the best option? Happy to help investigate further if you can point me in the right direction.

**Comment by wang-bin** [comment]
What happens with dxva zero copy? The log show 0-copy It's not enabled.

cuda direct copy is also a good choice.

**Comment by emantec** [comment]
Didn't include it as both causing errors/crash I want to concentrate on getting the CUDA Zero copy working.

But if you need it - seems to occur when changing the zerocopy mode when running
[log-QMLPlayer.txt](https://github.com/wang-bin/QtAV/files/1131243/log-QMLPlayer.txt)
[dxva_stacktrace.txt](https://github.com/wang-bin/QtAV/files/1131245/dxva_stacktrace.txt)

As you'll probably see in the logs there's lot of decoder errors, this is other issue I'm encountering where Hardware FFMPEG decoding (DXVA/D3D11) fails to decode H264 properly, the software FFMPEG decoder and CUDA decode it fine.

**Comment by wang-bin** [comment]
Fixed in the latest code
