### ISSUE TITLE
DXVA/D3D11 & H264 smeared/corrupted frame   [$100]

### ISSUE THREAD

**Issue by emantec** [wang-bin/QtAV#923]
Using DXVA/D3D11 hardware accelerated output with RAW H264 input results in corrupted video output on the lower section of the video.

The software FFMPEG decoder and the CUDA decoder present perfect video with no artifacts/corruption which suggest there is nothing wrong with the data and this is a decoder issue. 

![corrupted_output](https://user-images.githubusercontent.com/29915564/27986295-779301ac-63f5-11e7-960e-0f52e25e520f.png)

Similar issues that I have found suggested it was due to incorrect cropping parameters (https://trac.kodi.tv/ticket/11499) but appears to have been fixed several years ago. 

Example video

[example.zip](https://github.com/wang-bin/QtAV/files/1132086/example.zip)

Log of failing DXVA decoder with ffmpeg debug output
[log-dxva.txt](https://github.com/wang-bin/QtAV/files/1133021/log-dxva.txt)

Log of successful software FFMPEG decoder with ffmpeg debug output
[log-software.txt](https://github.com/wang-bin/QtAV/files/1133025/log-software.txt)

NOTE: to avoid any potential threading issues I changed the following code

	@@ -114,7 +114,7 @@ bool VideoDecoderFFmpegHWPrivate::prepare()
	 {
		 //// From vlc begin
		 codec_ctx->thread_safe_callbacks = true; //?
	-    codec_ctx->thread_count = threads;
	+    codec_ctx->thread_count = 1;
	 #ifdef _MSC_VER
	 #pragma warning(disable:4065) //vc: switch has default but no case
	 #endif //_MSC_VER

	@@ -198,7 +198,7 @@ public:
		   , strict(VideoDecoderFFmpeg::Normal)
		   , skip_frame(VideoDecoderFFmpeg::Default)
		   , thread_type(VideoDecoderFFmpeg::DefaultType)
	-      , threads(0)
	+      , threads(1)
		   , debug_mv(VideoDecoderFFmpeg::No)
		   , bug(VideoDecoderFFmpeg::autodetect)
		 {}

**Comment by wang-bin** [comment]
It's not because of cropping. cropping happens when the coded_witdh/coded_height and width/height are not the same. This video has the same value.

I tested QtAV1.12.0, looks better than yours. Kodi 17.3 is worse.

![qtav-dxva-923](https://user-images.githubusercontent.com/785206/28001813-55391f7e-6562-11e7-81fc-3175afff38ff.jpg)

![kodi-923](https://user-images.githubusercontent.com/785206/28001827-6cd5b552-6562-11e7-8703-b2a8ce0bed2f.jpg)

**Comment by emantec** [comment]
Check out mpc-hc, currently looking through code to see what they do differently as it plays the video perfectly on DXVA.

**Comment by wang-bin** [comment]
it use lavfilters, which is based on it's own ffmpeg fork with a lot of modifications

**Comment by wang-bin** [comment]
btw, which qtav and ffmpeg version do you use?

**Comment by wang-bin** [comment]
I just built lavfilters ffmpeg and tested it. It works perfectly. You can download from here: [x86](https://sourceforge.net/projects/avbuild/files/windows-desktop/ffmpeg-lavfilters-desktop-MINGW32-lite.7z/download) [x64](https://sourceforge.net/projects/avbuild/files/windows-desktop/ffmpeg-lavfilters-desktop-MINGW32-lite.7z/download)

**Comment by wang-bin** [comment]
Since there are too many changes in lavfilters ffmpeg, it's really hard to find out how it solves the problem.

**Comment by wang-bin** [comment]
Close it because lavfilters ffmpeg works

**Comment by wang-bin** [comment]
https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/h264dec.h#L68

Change this line to a larger value can fix this issue, for example 64, 128. The value in lavfilters is 256.

**Comment by ValZapod** [comment]
Issue upstream https://trac.ffmpeg.org/ticket/628#comment:7
