### ISSUE TITLE
Android - hardware decoding, x86 build

### ISSUE THREAD

**Issue by t-artikov** [wang-bin/QtAV#924]
As I understand it, the only way to use hardware decoding on Android is to extract pre-built libraries from QMLPlayer.apk. In that case, could you provide an x86 version of the apk?

**Comment by wang-bin** [comment]
https://sourceforge.net/projects/qtav/files/depends/mediacodec-x86/libqtav-mediacodec.so/download

**Comment by t-artikov** [comment]
Thanks
