### ISSUE TITLE
Android, HW decoding, color distortion

### ISSUE THREAD

**Issue by t-artikov** [wang-bin/QtAV#927]
### QtAV, Qt version and platform
QtAV version - 51f9e8f73872d51c6cfd44bbd6fa87028fbe5256, Qt5.9.1, Android armv7 (LG nexus 5X, Galaxy S6 Edge, Xiaomi Redmi 3S)
ffmpeg - https://sourceforge.net/projects/avbuild/files/android/ffmpeg-3.3.2-android-gcc-lite.tar.xz, 
libavcodec.so from https://sourceforge.net/projects/qtav/files/release/1.12.0/QtAV1.12.1-QMLPlayer-android-armv7a-signed.apk

### Reproduction steps
Run a QML application with the QML file:
```
import QtQuick 2.0
import QtQuick.Window 2.2
import QtAV 1.7

Window {
    id: root
    width: 1280
    height: 720
    visible: true
    Video {
        anchors.fill: parent
        source: "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"
        videoCodecPriority: ["MediaCodec"]
        autoPlay: true
    }
}
```

### Expected behavior
The video is played correctly.

### Actual behavior
The colors are distorted.
![qtav_hw_decoding](https://user-images.githubusercontent.com/1927992/28571230-1ade7ffc-716c-11e7-8825-25b5a309db77.png)

### Log file
[QtAV_hw_decoding_log.txt](https://github.com/wang-bin/QtAV/files/1173067/QtAV_hw_decoding_log.txt)

**Comment by wang-bin** [comment]
hw rendering plugin `libqtav-mediacodec.so` is not free. If the performance boost is noticeable for you, you can consider buy a key to let it render correctly.

**Comment by t-artikov** [comment]
Clear. I believe it should be explicitly stated in the documentation.
Can I use a demo version to measure performance, or will the unlocked version perform better?

**Comment by wang-bin** [comment]
There is no performance difference, only the color

**Comment by t-artikov** [comment]
OK, thank you.
