### ISSUE TITLE
sdk_deploy.bat does not deploy qml types

### ISSUE THREAD

**Issue by ThatOdieGuy** [wang-bin/QtAV#928]
In the [latest build](https://sourceforge.net/projects/qtav/files/ci/QtAV-Qt5.9-VS2015x86-release-b85c69a.7z/download), the command to deploy the qml types files is pointing to the wrong location. I'm not sure if the .bat file is wrong or the location of the files in the archive is wrong.

I believe the files that it should be copying are in bin\QtAV not qml\QtAV. qml\QtAV does not exist.

`xcopy /syi  qml\QtAV %QTDIR%\qml\QtAV`

**Comment by wang-bin** [comment]
right

**Comment by ThatOdieGuy** [comment]
👍
