### ISSUE TITLE
LNK2001	unresolved external symbol VideoFrameExtractor::event

### ISSUE THREAD

**Issue by ThatOdieGuy** [wang-bin/QtAV#930]
I'm building QtAV with a fresh clone from today with Qt 5.9.1 msvc2015 and getting this linker error. 

LNK2001	unresolved external symbol "public: virtual bool __thiscall QtAV::VideoFrameExtractor::event(class QEvent *)" (?event@VideoFrameExtractor@QtAV@@UAE_NPAVQEvent@@@Z)	QtAVWidgets	C:\Development\video\QtAV\widgets\VideoPreviewWidget.obj

If I revert the event code from #922 from @cculianu and put back the `virtual bool event(QEvent *e);` code, it also builds fine. But I'm new to the project and don't know the real fix.

**Comment by wang-bin** [comment]
run sdk_uninstall.bat before building new QtAV code

**Comment by ThatOdieGuy** [comment]
Oh, the old headers were in the Qt dir. Ok, thank you. That worked.
