### ISSUE TITLE
建议添加一个函数

### ISSUE THREAD

**Issue by 32ns** [wang-bin/QtAV#935]
有时候我们用QML只是做显示和动画用,做数据处理还是C++比较方便,所以VPlayer我是注册在C++中,只把VideoOut2放到QML中做显示,我想其它朋友可能也有这种需求,所以在此提交申请;
还有一个问题想请教您,我在Android中无法开启硬件加速,是不是开启硬件加速要另付费去购买您的插件呀?如果是的话请您联系我,我愿意付费购买(微信:860988600)

QuickFbORenderer.h
Q_PROPERTY(QObject* source READ source WRITE setCSource NOTIFY sourceChanged)

void setCSource(QObject *source);

QuickFbORenderer.cpp
void QuickFBORenderer::setCSource(QObject *source)
{
    DPTR_D(QuickFBORenderer);
    if (d.source == source)
        return;
    d.source = source;
    Q_EMIT sourceChanged();
    if (!source)
        return;
    ((AVPlayer*)source)->addVideoRenderer(this);
}

**Comment by wang-bin** [comment]
这个属性看上去不错，周末加下。 
是的

**Comment by 32ns** [comment]
那我怎么联系您购买呢?

**Comment by wang-bin** [comment]
我的邮箱

**Comment by wang-bin** [comment]
The property is still `source`
