### ISSUE TITLE
视频怎么旋转？

### ISSUE THREAD

**Issue by zyb920** [wang-bin/QtAV#951]
手机录制的视频大多数都带有旋转参数。用QtAV播放 ，视频总是倒着、横着，没旋转过来。

**Comment by zyb920** [comment]
还有个问题就是 ：
QtAV.Player.QML 好像能单独开起cuda硬件加速。
QtAV.Player 开启了cuda没反应。

**Comment by zyb920** [comment]
刚刚发现1.12 已经加了qsv。
QtAV.Player 开启了cuda也解决了。

还剩下旋转了。。。

**Comment by wangwenx190** [comment]
我记得Player项目里好像有旋转画面的代码，你好好看看源码。再说了，QtAV只是个框架，不可能什么功能都替你实现了，画面旋转这种你自己实现就可以了，Player中就是自己实现的，QtAV并没有提供接口。
而且，播放器又不知道你视频是不是倒了，它怎么会自动旋转？手机上自动旋转是根据重力来的，也不是播放器知道视频倒了。
有QtAV没有实现的需求，你就自己写啊，你把GitHub当什么了？纯白嫖？

**Comment by zyb920** [comment]
视频文件 里面有个旋转标志：
好像是 rotate标志。
vlc 播放文件的时候 就会去读这个标志 然后把旋转回来，播放起来就是正确的了。

QtAV也没有 反交错。有些视频播放起来就是一杠一杠的。

**Comment by zyb920** [comment]
看到了  快捷键R旋转 [尴尬]

**Comment by wang-bin** [comment]
这次提交后会自动识别并旋转 00f5d13
