### ISSUE TITLE
function entry point not found in QtAv1.dll 

### ISSUE THREAD

**Issue by xy-lin** [wang-bin/QtAV#957]
### QtAV, Qt version and platform
QtAv - V1.12.0
Qt - V5.6
or commit id if not using release version

### Reproduction steps
1. Use Qt Creator config and build the release configuration
2. double click any example executable, e.g. play.exe

### Expected behavior
player launched.

### Actual behavior
cannot launched executable, complain about the dll entry point
### Sample files (optional)
![qtav](https://user-images.githubusercontent.com/19847273/31154315-2fdf200a-a89e-11e7-8b0a-72c35f47571b.png)

**Comment by xy-lin** [comment]
In debug configuration, the executable can be launched without any problem.

**Comment by wang-bin** [comment]
wrong ffmpeg dll

**Comment by xy-lin** [comment]
Solved, thanks.
