### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: av Project ERROR: Unknown module(s) in QT: avwidgets

### ISSUE THREAD

**Issue by princethetyagi** [wang-bin/QtAV#961]
### QtAV, Qt version and platform

or commit id if not using release version

### Log file

set environment var `QTAV_LOG=all` or C++ api `QtAV::setLogLevel(All)` to enable log.

For Player and QMLPlayer example app, choose log level `all` in config page.

**Comment by princethetyagi** [comment]
Project ERROR: Unknown module(s) in QT: av 
Project ERROR: Unknown module(s) in QT: avwidgets
getting this error , successfully install qtav, add all library but still same error are occuring.

**Comment by wang-bin** [comment]
How do you install qtav? what platform?

**Comment by princethetyagi** [comment]
I am using window 10 pro.. qt5 and qtav

**Comment by princethetyagi** [comment]
I have install the qt from it's site and I am using free version. I
downloaded the qtav from Github.

**Comment by shbobur** [comment]
Same error: win7, qt 5.9.1 and QtAV-Qt5.9-VS2015x86-release-b17b3f6.7z
If I leave just "CONFIG += avwidgets" in the project file, build finishes with a bunch of undefined reference errors. Any thoughts?

**Comment by princethetyagi** [comment]
no, problem is that avwidgets is not evening including, it is showing error
as i add that into project as QT+=avwidgets or QT+=av, i have downloaded
qtav also also successfully add the path of qtav but project didn't finding
this module.

**Comment by shbobur** [comment]
I downloaded QtAV archive (https://sourceforge.net/projects/qtav/files/ci/QtAV-Qt5.9-VS2015x86-release-b17b3f6.7z/download) and run sdk_deploy.bat. Now I can include without any problem. But I am having errors in referencing. Trying to fix...

**Comment by wang-bin** [comment]
Did you run sdk_deploy.bat?

**Comment by shbobur** [comment]
Yes. After that, I could add "QT += av avwidgets" without any problem. But still I can not build my app. It is requiring QtAVd.dll and QtAVWidgetsd.dll (development libraries). Now I am trying to build QtAV myself (hope it helps).

**Comment by wang-bin** [comment]
Only release build is supported

**Comment by princethetyagi** [comment]
I have run sdk_deploy but still I am getting problem.. let me try once
again and I'll let you know.. hope this time it work fine

**Comment by shbobur** [comment]
Maybe my question is for another thread, but please take a look. I am getting this error while trying to build simpleplayer_sdk (release build):
 undefined reference to `_imp___ZN4QtAV8AVPlayer4playERK7QString'
release/playerwindow.o:playerwindow.cpp:(.text+0x27b): undefined reference to `_imp___ZNK4QtAV8AVPlayer9isPlayingEv'
release/playerwindow.o:playerwindow.cpp:(.text+0x2df): undefined reference to `_imp___ZN4QtAV8AVPlayer4seekEx'
release/playerwindow.o:playerwindow.cpp:(.text+0x36b): undefined reference to `_imp___ZNK4QtAV8AVPlayer9isPlayingEv'
release/playerwindow.o:playerwindow.cpp:(.text+0x378): undefined reference to `_imp___ZNK4QtAV8AVPlayer8isPausedEv'
release/playerwindow.o:playerwindow.cpp:(.text+0x38a): undefined reference to `_imp___ZN4QtAV8AVPlayer5pauseEb'
release/playerwindow.o:playerwindow.cpp:(.text+0x3a6): undefined reference to `_imp___ZN4QtAV8AVPlayer4playEv'
release/playerwindow.o:playerwindow.cpp:(.text+0x3c6): undefined reference to `_imp___ZNK4QtAV8AVPlayer8durationEv'
release/playerwindow.o:playerwindow.cpp:(.text+0x44b): undefined reference to `_imp___ZNK4QtAV8AVPlayer8positionEv'
release/playerwindow.o:playerwindow.cpp:(.text+0x47b): undefined reference to `_imp___ZNK4QtAV8AVPlayer14notifyIntervalEv'
release/playerwindow.o:playerwindow.cpp:(.text+0x524): undefined reference to `_imp___ZN4QtAV8AVPlayerC1EP7QObject'
release/playerwindow.o:playerwindow.cpp:(.text+0x56a): undefined reference to `_imp___ZN4QtAV8AVPlayer23setVideoDecoderPriorityERK11QStringList'
release/playerwindow.o:playerwindow.cpp:(.text+0x5ce): undefined reference to `_imp___ZN4QtAV11VideoOutputC1EP7QObject'
release/playerwindow.o:playerwindow.cpp:(.text+0x5dc): undefined reference to `_imp___ZN4QtAV11VideoOutput6widgetEv'
release/playerwindow.o:playerwindow.cpp:(.text+0x602): undefined reference to `_imp___ZN4QtAV8AVPlayer11setRendererEPNS_13VideoRendererE'

**Comment by shbobur** [comment]
BTW, QtAV releases are built with VisualStudio and I am using mingw. Could it be the reason for "undefined reference" error? Do I need to build on mingw myself?

**Comment by princethetyagi** [comment]
i got  undefined reference error when i did not add av or avwidget module
in project and if i add then project got undefine module

**Comment by wang-bin** [comment]
@princethetyagi how did you install qtav sdk?

**Comment by wang-bin** [comment]
https://sourceforge.net/projects/qtav/files/ci/QtAV-Qt5.9-VS2017x64-release-45fb210.7z/download
