### ISSUE TITLE
Errors when trying to install SDK

### ISSUE THREAD

**Issue by dohisev** [wang-bin/QtAV#975]
I downloaded the `QtAV-Qt5.9-VS2015x86-release-b17b3f6.7z` from sourceforge and executed `sdk_deplay.bat` I get a few errors:

```
bin\*portaudio*.dll
The system cannot find the file specified.
lib\*Qt*AV*.a
The system cannot find the file specified.
```

And the same happens if I try to uninstall...

Also when I try to compile the simple example I get this error:

`:-1: error: LNK1181: cannot open input file 'Qt5AVWidgets.lib'`

I renamed the libraries myself (although I don't think that this is a fine way to solve)

Is this how it works or I'm doing something wrong?

**Comment by wang-bin** [comment]
the file name is wrong. you have to manually rename the file, or use the latest package
