### ISSUE TITLE
Undefine Symbols Mac Os X 10.13

### ISSUE THREAD

**Issue by manang** [wang-bin/QtAV#978]
### QtAV, Qt version and platform
QtAV version = 1416eedb26aec89261676afeebeac98b5f80f8c9
Qt version =5.9.2
OS = Mac Os X 10.13, High Sierra
ffmpeg version = 3.4
### Reproduction steps
I'm trying to install compile QtAV in a virgin environment.
I have this output:
`Undefined symbols for architecture x86_64:
  "_av_vda_alloc_context", referenced from:
      QtAV::VideoDecoderVDAPrivate::setup(AVCodecContext*) in VideoDecoderVDA.o
  "_av_vda_default_free", referenced from:
      QtAV::VideoDecoderVDAPrivate::setup(AVCodecContext*) in VideoDecoderVDA.o
      QtAV::VideoDecoderVDAPrivate::close() in VideoDecoderVDA.o
  "_av_vda_default_init2", referenced from:
      QtAV::VideoDecoderVDAPrivate::setup(AVCodecContext*) in VideoDecoderVDA.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../lib_osx_x86_64_llvm/QtAV.framework/QtAV] Error 1
make: *** [sub-src-libQtAV-pro-make_first] Error 2`

**Comment by wang-bin** [comment]
vda is deprecated. it's disabled in the latest code. so please update your code
