### ISSUE TITLE
iOS 11, IOSurface.h not found

### ISSUE THREAD

**Issue by manang** [wang-bin/QtAV#986]
### QtAV, Qt version and platform
QtAV version: master, commit 428cb595b2db9a4a79574697527a1dc0bbe3a3af
Qt version: 5.9.2
Platform: iOS 11
I'm trying to compile QtAV for iOS 11,
I have the following error:
`
~/QtAV/src/codec/video/SurfaceInteropIOSurface.mm:37:10: fatal error: 'IOSurface/IOSurface.h' file not found
#include <IOSurface/IOSurface.h>
`

Thank you
Angelo

**Comment by wang-bin** [comment]
should be fixed
