### ISSUE TITLE
compile only for ios arm64

### ISSUE THREAD

**Issue by manang** [wang-bin/QtAV#987]
Is it possible to compile the library only for ios arm64?
Thank you very much
Angelo

**Comment by wang-bin** [comment]
it's a question about qt, not qtav. I believe you can't

**Comment by manang** [comment]
The problem is that I can't compile ffmpeg for arm32 because it is not supported with xcode 9 and ios 11.

**Comment by wang-bin** [comment]
It's not true. You can compile for any cpu target, and any ios version. You can download my precompiled ffmpeg for all platforms from here: https://sourceforge.net/projects/avbuild/files/

my build script: https://github.com/wang-bin/avbuild

**Comment by manang** [comment]
Sorry If I insist,
I receive this error if I compile my personal project (cmake + xcodebuild)
`xcodebuild ENABLE_BITCODE=NO -configuration Release -target install -sdk iphoneos -arch armv7 -miphoneos-version-min=5.0`
`clang: error: invalid iOS deployment version '-miphoneos-version-min=11.1', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]`

**Comment by wang-bin** [comment]
Of cause you can not use 11 as target version for 32bit. You have to find out why 11.1 is used in your command. I'm not familiar with xcodebuild. btw, 5.0 target requires some files not included in xcode8+. 6.0 is ok.

**Comment by manang** [comment]
Ok, I solved my error.
with the new sdk I have to specify a lower sdk target inside my cmake file, as a cflag.
Thank you very much.
Angelo
