### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by yoer** [wang-bin/QtAV#990]
+++ b/examples/player/EventFilter.cpp
@@ -298,7 +298,7 @@ bool EventFilter::eventFilter(QObject *watched, QEvent *event)
     }
         break;

-    case QEvent:: QEvent::MouseButtonDblClick: {
+    case QEvent::MouseButtonDblClick: {    //  here, compile error
           QMouseEvent *me = static_cast<QMouseEvent*>(event);
           Qt::MouseButton mbt = me->button();
           QWidget *mpWindow =  static_cast<QWidget*>(player->parent());

**Comment by wang-bin** [comment]
fixed
