### ISSUE TITLE
Crash on video playback when building from source

### ISSUE THREAD

**Issue by nigelgrange** [wang-bin/QtAV#992]
I've built a working demo project using the QML Video widget against the pre-built download of QtAV. However, when building QtAV from source and installing, the same demo project crashes whenever a video played.

Does anyone have experience with resolving this, or pointing out where to start. I'm building against the latest FFMPeg on OSX. Will it help building FFMPeg from source also?
Thanks

### QtAV, Qt version and platform

QTAV: 1.12.0
Qt: 5.9.2

or commit id if not using release version

### Reproduction steps

Create Video QML element. Play video.

### Expected behavior

App doesn't crash

### Actual behavior

App crashes.

### Log file

QtAV 1.12.0(Nov 10 2017, 15:13:44)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin->PPTV, Shanghai, China Copyright (C) 2012-2017 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
VideoRenderer::Register(..., QQuickItem)
VideoRenderer::Register(..., QuickFBO)
QtAV 1.12.0(Nov 10 2017, 15:13:44)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin->PPTV, Shanghai, China Copyright (C) 2012-2017 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
"Build with Qt-5.9.2"
"FFmpeg/Libav configuration: --prefix=/usr/local/Cellar/ffmpeg/3.4 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-ffplay --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma"
"Build with avutil-55.78.100"
"Build with avcodec-57.107.100"
"Build with avformat-57.83.100"
"Build with swscale-4.8.100"
Registered audio backends:  ("AudioToolbox", "OpenAL", "null")
AudioOutputBackend::id("AudioToolbox")
engine: "LibASS"
SubtitleProcessor::id("LibASS")
Not found
Unknown id engine: "FFmpeg"
SubtitleProcessor::id("FFmpeg")
"OpenGL version: 2.1  hasGLSL: 1"
"GL_VERSION: 2.1 APPLE-12.1.0"
"GL_VENDOR: Apple Inc."
"GL_RENDERER: Apple Software Renderer"
"GL_SHADING_LANGUAGE_VERSION: 1.20"
"Is OpenGLES: 0"
"Is EGL: 0"
"GLSL version: 120"
"Has PBO: 1"
"16 bit texture depth: 16.\n"
"using gl_param_3r16"
"Has 16bit texture: 1"
"check gl3 rg: 0x822B"
"Has RG texture: 1"
QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 32, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
"AudioQueue is not created. skip close"
AudioOutputBackend::id("AudioToolbox")
Loading  QVariant(QString, "qrc:/60secs.mp4")  ...
"all closed and reseted"
"avformat_open_input: d->format_ctx:'0x7f9cc489f800'..., MediaIO('QFile'): 0x7f9cc3df9180"
"avformat_open_input: (with MediaIO) ret:0"
"avfmtctx.flags: 2097281, iformat.flags"
"invalid index 0 (valid is 0~0) for stream type 2."
"notify_interval: 500"
"stream: 1, duration=2850227 (64630 ms), time_base=0.000023"
"codec: aac(AAC (Advanced Audio Coding))"
"stream: 0, duration=825344 (64480 ms), time_base=0.000078"
"codec: h264(H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)"
"has audio"
AudioDecoder::id("FFmpeg")
Singleton 0x7f9cc3e89880 created...
Unknown id Unknown id "QtAV::AudioDecoderFFmpeg thread type: Single, count: 1"
"AudioQueue is not created. skip close"
AudioOutput format:  QtAV::AudioFormat(44100Hz, 4Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "flt") ; requested:  QtAV::AudioFormat(44100Hz, 4Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "fltp")
The program has unexpectedly finished.
The process was ended forcefully.

set environment var `QTAV_LOG=all` or C++ api `QtAV::setLogLevel(All)` to enable log.

For Player and QMLPlayer example app, choose log level `all` in config page.

### Sample files (optional)

**Comment by wang-bin** [comment]
can you run lldb and see where it crashes?

**Comment by nigelgrange** [comment]
I've been trying a few different things, but still haven't solved the issue.
I've build 1.11.0 from source, and the example apps work fine (I didn't get this far with 1.12.0).
However, after running sdk_install.sh from the build folder, I can't get an app built against the installed libs to run correctly.

I've isolated the crash to an issue in bool AVPlayer::Private::setupAudioThread(AVPlayer *player)
 at the following line:
    adec->resampler()->setOutAudioFormat(ao->audioFormat());

The crash is because the resampler() call returns null. I can't figure out why the audio decoder would have a null resampler. The same file plays fine in the QmlPlayer app (and other example apps) built using the same source.

**Comment by nigelgrange** [comment]
Ok, this can be closed now, I've managed to build everything cleanly on a new OS X install.

I think it came down to a couple of issues:
1. I was building from the tagged releases (1.11.0, 1.12.0) but these weren't compatible with the ffmpeg version I had. Using the latest source and latest ffmpeg built correctly.
2. I had an older build that had been installed to the Qt/lib folder, which was being linked to in preference to the libs build built.
