### ISSUE TITLE
Crash when using AA_UseDesktopOpenGL and on Remote Desktop (RDP) or a virtual machine.

### ISSUE THREAD

**Issue by ThatOdieGuy** [wang-bin/QtAV#993]
This is an odd use case but it blocked me for a while and I'm mostly filing this for anybody else who might run into this issue. My workaround is to just not set AA_UseDesktopOpenGL and let the system decide. Or maybe detect OpenGL support before trying to set this.

### QtAV, Qt version and platform
QtAV cda61b264b7154006f3fb475bcbda7d9d5118d25
Qt 5.9.2 MSVC 2015 x86

### Reproduction steps
1. Set the sampleplayer app to use Desktop OpenGL by adding line to the top of main(): QApplication::setAttribute(Qt::AA_UseDesktopOpenGL);
2. Build the app.
3. Run the app on Windows via Remote Desktop Connection or inside a virtual machine. I used VirtualBox and Windows 10.

### Expected behavior
App launches, or at least errors and says there's an unsupported GL version.

### Actual behavior
Launch of app throws an exception:
Exception thrown at 0x593EE426 (ucrtbased.dll) in simpleplayer.exe: 0xC0000005: Access violation reading location 0x00000000.
I tracked this error down to OpenGLHelper.cpp:135 GLSLVersion() -> glGetString(GL_SHADING_LANGUAGE_VERSION)
This value is returning null and causing the exception to be thrown. I added some null checks for this value, and that fixes the problem here...

But then this error pops up:
Program: C:\Development\player\debug\Qt5Cored.dll
Module: 5.9.2
File: c:\users\qt\work\qt\qtbase\include\qtcore\../../src/corelib/tools/qvector.h
Line: 426
ASSERT failure in QVector<T>::operator[]: "index out of range", file c:\users\qt\work\qt\qtbase\include\qtcore\../../src/corelib/tools/qvector.h,

I couldn't see where the problem was in QtAV. But the actual problem was from the earlier OpenGL setting so I didn't bother debugging further.

### Log file
[openGLbug.log](https://github.com/wang-bin/QtAV/files/1462616/openGLbug.log)

**Comment by wang-bin** [comment]
opengl 1.1 is used. qtav requires 2.0+

**Comment by ThatOdieGuy** [comment]
Thanks!
