### ISSUE TITLE
Error compiling for iOS 11

### ISSUE THREAD

**Issue by manang** [wang-bin/QtAV#995]
### QtAV, Qt version and platform
Qt version = 5.9.2
QtAV commit = c00bd1a0af84ca56d2b2d06e8154d0dd3d850234

### Log file

When I try to compile I have the following error:

/Users/angelomantellini/QtAV/src/codec/video/SurfaceInteropIOSurface.mm:147:67: error: use of undeclared identifier 'i'
         qWarning("error creating IOSurface texture at plane %d", i);

**Comment by manang** [comment]
I think that you can correct like this"
`qWarning("error creating IOSurface texture at plane %d", plane);`

**Comment by wang-bin** [comment]
thanks. I don't have qt ios environment, so the code is not tested. but the code should work
