### ISSUE TITLE
QtAV module not found in iOS

### ISSUE THREAD

**Issue by manang** [wang-bin/QtAV#997]
### QtAV, Qt version and platform
QtAV commit ae41a034ddb01669323a35f087bd8cb993a0df7a
Qt 5.9.2

When I compile QMLPlayer_sdk for iOS the compiling part is ok, but when the application is launched inside the tablet I have the following error:
`Warning: qrc:///qml/QMLPlayer/main.qml:33:1: module "QtAV" is not installed`

I built and installed the qtav staff with sdk_install.sh
in Qt creator if I try to insert "import QtAV" the module is not autocompleted, so maybe I have to set some variable.
Thanks
Angelo

**Comment by manang** [comment]
I tried with Qt 5.7.1 and I don't have the error.
I had the same error with Qt 5.8
I don't know how I have to tell to the project that it has to include all the modules.
Thank you very much

Angelo

**Comment by GitHubKsti** [comment]
I have the same problem under Qt 5.9.2 and the 5.10 beta.

**Comment by manang** [comment]
I think that the installation of the qtav framework is changed in the newest version of Qt.

**Comment by GitHubKsti** [comment]
I have the same problem since Qt 5.8.0 and i was not able to get rid of it.
With Qt 5.10 RC the problem already exists.

**Comment by cbdg** [comment]
I have the same problem when i use myself qml plugin on ios, when run my app on device, there always show: module "myselfqmlpluginmodel" is not installed, i use Qt5.9.2 for ios

**Comment by wang-bin** [comment]
Sorry I don't have ios development environment. you may compare qtav result binaries with standard qml modules

**Comment by toannguyen-v** [comment]
run into this issue recently.
Env: QT5.13, XCode 11.0.
module: QMLPlayer for iOS 12.4

Resolution: add QMLPATHS += [QT_PATH]/ios/qml/QtAV in to .pro file. (yeah that is the place that sdk_install.sh installs the QtAV module).
this will help packaging QML custom module to ipa.
reference: https://forum.qt.io/topic/75452/problem-with-custom-plugin-for-qtquick-on-ios/6
