### ISSUE TITLE
Would you please tell me what's the 'chapter' means in AVPlayer? Is it means 'frame'?

### ISSUE THREAD

**Issue by zmy235** [wang-bin/QtAV#999]
`
void AVPlayer::seekChapter(int incr)
{
    if (!chapters())
        return;

    qint64 pos = masterClock()->value() * AV_TIME_BASE;
    int i = 0;

    AVFormatContext *ic = d->demuxer.formatContext();

    AVRational av_time_base_q;
    av_time_base_q.num = 1;
    av_time_base_q.den = AV_TIME_BASE;

    /* find the current chapter */
    for (i = 0; i < chapters(); ++i) {
        AVChapter *ch = ic->chapters[i];
        if (av_compare_ts(pos, av_time_base_q, ch->start, ch->time_base) < 0) {
            --i;
            break;
        }
    }

    i += incr;
    //i = FFMAX(i, 0);
    if (i <= 0)
        i = 0;
    if (i >= chapters())
        return;

    //av_log(NULL, AV_LOG_VERBOSE, "Seeking to chapter %d.\n", i);
    qDebug() << QString::fromLatin1("Seeking to chapter : ") << QString::number(i);
    setPosition(av_rescale_q(ic->chapters[i]->start, ic->chapters[i]->time_base,
                             av_time_base_q) / 1000);
}
`

**Comment by wang-bin** [comment]
Time points. For example episode1 episode2

**Comment by javlada** [comment]
By calling `av_player->chapters()` I get the number of chapters. Is it possible to get the names and start times of the chapters?
